### ISSUE TITLE
Feature Request: Extended ListView Component (Thunkable X)

### ISSUE THREAD

**Issue by UserEightyOne** [thunkable/thunkable-issues#1]
Take any popular app (ios or android) - it will have a rich Listview with icons and varios text sizes and fonts

For thunkable android, ColinTree developed an awesome Listview.

The Listview for thunkable X may be developed in distinct steps. I recommend these steps, sorted by priority:

1. customize textsize and textcolor of the first textrow
2. second textrow under the first
3. add Image Icon on the left
4. make image icon clickable
5. option to show text above or instead the image on the left
6. make rounded corners or circle crop to the image Icon
7. set element height
8. add button on the right (or make the arrow on the right customizable and individually clickable)
9. option to add third textrow
10. individual backgroundcolor for each listitem
11. load images asychonious
12. cache images in cache
13. cache images in cache and/or memory
14. option to wrap text and make multiline (textbreak only ofter words or in words)
15. consider alternative listviews like cardview or list that scrolls horizonally

cheers, 
User81

**Comment by weihuali0509** [comment]
@UserEightyOne Thanks for the suggestion. We will add this awesome list to our to-do list and prioritize it :)

**Comment by UserEightyOne** [comment]
The common list view in many iOS apps (whatsapp for example) is like in my app...
![screenshot_2018-05-01-08-13-20](https://user-images.githubusercontent.com/40308030/42258513-6de2d6e0-7f5c-11e8-9f75-163bc810c6b5.png)

**Comment by UserEightyOne** [comment]
Functionality is in iOS via "..."-button on the right instead of the arrow (first picture)

or via swapping the list to a view, where there is a button on the left and a extrabutton on the right

or via swiping the row in the list to the right or left

![image3](https://user-images.githubusercontent.com/40308030/42258630-0634b0c6-7f5d-11e8-8f04-aab49d9f543b.PNG)

![image2](https://user-images.githubusercontent.com/40308030/42258634-0c55b64e-7f5d-11e8-9a67-36dbe4b675ab.PNG)

![image4](https://user-images.githubusercontent.com/40308030/42258650-1b0afabe-7f5d-11e8-8df7-ebe479d2be43.PNG)

**Comment by tijender7** [comment]
Hi do you know by when we can have a better list viewers.. m waiting for this since long and many things are pending just because in list viewer there is no chance of modifications

**Comment by tijender7** [comment]
Is there a way we can create elements by using block

**Comment by mark-friedman** [comment]
> Hi do you know by when we can have a better list viewers..

@tijender7, this is very high on our list of enhancements.

**Comment by mark-friedman** [comment]
> Is there a way we can create elements by using block

@tijender7 This is also high on our list of planned enhancements.

**Comment by nicbyron** [comment]
I know this is already in development, but preferably it would be great to have a cell function, which you can customize as you would a row/column, but is used to populate the rows of a listview. I know this is likely significantly more complex, but would allow the flexibility to no longer need to significantly update this functionality again IMO.

Thanks for all the hard work guys—I know you're doing the best you can!

**Comment by mark-friedman** [comment]
>I know this is already in development, but preferably it would be great to have a cell function, which you can customize as you would a row/column, but is used to populate the rows of a listview.

@nicbyron Sometime near the beginning of 2020 we should have a customizable data viewer.  It won't be a completely customizable as, say, a row/column but will be significantly more customizable than the current List Viewer.  Also in 2020, we should be rolling out support for templates, which would provide a completely customizable solution.

**Comment by nicbyron** [comment]
> > I know this is already in development, but preferably it would be great to have a cell function, which you can customize as you would a row/column, but is used to populate the rows of a listview.
> 
> @nicbyron Sometime near the beginning of 2020 we should have a customizable data viewer. It won't be a completely customizable as, say, a row/column but will be significantly more customizable than the current List Viewer. Also in 2020, we should be rolling out support for templates, which would provide a completely customizable solution.

@mark-friedman both of these things sound very exciting! I'm looking forward to seeing and implementing them! Thanks for the update!

**Comment by MrTwoCanes** [comment]
Please consider list viewer font color/size/bold/italic changes.  Having only black letters makes it impossible to see on a black background; even just white font color would be a great help.

**Comment by MrMazzone** [comment]
@MrTwoCanes +1 I agree.  Font color/size/bold/italic would be useful in the List Viewer.

Maybe we should submit a new request for this?  This thread seems very busy and most of the request here is met with the new Data Viewer components https://docs.thunkable.com/data-viewer-list 

Also, as a helpful aside.  You can set the Background Color of the List Viewer in the "Advanced" properties. 
![image](https://user-images.githubusercontent.com/40954645/86538484-493fb200-bec4-11ea-924b-3382671db22c.png)

I know this is not ideal, but it does let you keep a black background for your app and still use the List Viewer. https://x.thunkable.com/copy/6e717c577069e0226715d49f03f4d595

**Comment by kezb765** [comment]
I would like to have some enhancements to the good old "list viewer". I worked with the new "data viewer list/grid" in combination with "local data sources" for several months now and got many new grey hairs. Sorry for that, but in some apps a slightly enhanced list viewer could be sufficient.

Here are my two (!) wishes for an update of the list viewer component:
- styling options for background-/foreground-/text-color
- multiline support plus automatically first line in bold (like the text that appears when clicking on a marker on a map).

**Comment by domhnallohanlon** [comment]
Hey @UserEightyOne @AcrobatEpee @tijender7 @nicbyron @realmisterfish @MrTwoCanes @MrMazzone @tatiang @kezb765 

The Data Viewer, and in particular the custom data viewer layouts can be used to achieve pretty much everything you've mentioned in your posts above. 

Have you tried using custom layouts in your project:
https://www.youtube.com/watch?v=UIZtLgELGyk

See more about this component in the Community here:
https://community.thunkable.com/t/latest-thunkable-release-new-components-data-viewer-list-and-data-viewer-grid-2020-05-05/564204?u=domhnallohanlon

**Comment by jane-d-alt** [comment]
Since Domhnall's previous comment explains how to implement this functionality in Thunkable X, we will close this issue now. Thanks to all who commented!
