### ISSUE TITLE
Vibration built-in procedure under non-visible Sound component

### ISSUE THREAD

**Issue by wongmk59** [thunkable/thunkable-issues#100]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I hope to have a vibration built-in procedure which can be called by the non-visible component, Sound, just like what Thunkable Classic (or AI2 [managed by MIT ]) for Android can do.  When the sound component called such procedure, the argument to be provided is the number of milliseconds, same as what Thunkable Classic (or AI2 [managed by MIT ]) for Android can do.

**Describe alternatives you've considered**
Although I can find extension written by someone else, I don't know if it's reliable to use it for the security reason and I won't take the risk to download such extension and install it.

**Which platform are you asking for?**
 Thunkable ✕ (x.thunkable.com)

**Additional context**
N/A

**Comment by josmas** [comment]
Vibrate exists in the Device drawer. Thanks!
