### ISSUE TITLE
Google sheets issue

### ISSUE THREAD

**Issue by baquang2910** [thunkable/thunkable-issues#1004]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
Thunkable X
### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
When use the Thunkable platform to create App.
### Steps to Reproduce
1. My account is unable to link Google sheet.
2. 
3.

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.
Please refer issue as link below

https://drive.google.com/file/d/1dKYY5n-mHXHk2_pTluJ51k_216_qc2CS/view?usp=sharing
### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jane-d-alt** [comment]
Hi there,

What happens when you try to connect a Google Sheet to your project?
Can you send an email to support@thunkable.com? We may need to reset your Google Sheets connection.

**Comment by fabform** [comment]
handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by jane-d-alt** [comment]
Hi again,

Did you email support@thunkable.com with your issue?
Has it been resolved?

**Comment by jane-d-alt** [comment]
As there has been no follow up on this issue, we are going to close it. Please let us know if you continue to experience this issue.
