### ISSUE TITLE
No Blocks in X

### ISSUE THREAD

**Issue by codetantra** [thunkable/thunkable-issues#101]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
X
### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
on site
### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?
To see the blocks - there are one to select from
### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by codetantra** [comment]
Won't let me edit - I meant - there are NONE to select from

**Comment by mrching** [comment]
Do you have a screenshot that you could add here?

**Comment by codetantra** [comment]
This apparently is a browser issue. This is happening in Chrome. It show alright in Firefox.
