### ISSUE TITLE
Date Modified for copied projects is original creation date

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1014]
### Platform
Thunkable X

### Steps to Reproduce
1. Make a copy of a project.
2. The date modified listed on the https://x.thunkable.com/projects page is the original creation date (as far as I can tell) for the source project. 

### Community Link
https://community.thunkable.com/t/my-actual-version-of-app-is-not-the-right-version-when-i-duplicate-it/1843873

### Expected Behavior
The date modified value should be the latest date modified value for the source project, not its creation date.

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jane-d-alt** [comment]
Hey Tatian,

I remember you reporting this behavior before. I was able to replicate it at the time. 

I tried to replicate this behavior in Google Chrome and I couldn't - the new project appears at the top of my projects list.

What browser are you using? How do you sign in to Thunkable? I can try to replicate the behavior in conditions as similar to yours as possible.

Thanks,
Jane

**Comment by tatiang** [comment]
Here's a video that shows the problem:

https://drive.google.com/file/d/1_GW4XSowAbglF6wyrQF9mbCWdHegjzmj/view

You'll notice at the start, I don't have the hover menu options available for duplicating a project so I had to open it and Make a Copy. At that point, I'm just waiting because there's no confirmation message. Eventually, I go back to the projects list and see that a copy has been made. The original file has a modification date of September 6, **2021**. But the new copy has a modification date of September 23, **2020**.

![image](https://user-images.githubusercontent.com/10355498/132254420-92c1d9f7-6fff-443e-b6d8-83b6ce45355f.png)

I'm using Chrome Version 93.0.4577.63 (Official Build) (x86_64) on an iMac running OS X 10.15.7. I sign in to Thunkable using a personal Gmail account.

**Comment by tatiang** [comment]
It's so silly to have to wade through copies that all have the same Date Modified value, especially when making a copy/duplicate of a project doesn't always display a notification. So then it's easy to accidentally make two or three copies of the same project. And then each copy has an identical name but there's no way to tell them apart from copies made earlier.

These copies were all made on different days:

![image](https://user-images.githubusercontent.com/10355498/135387638-b8f8d5b5-28fd-4e15-9bc9-db4e0d87974d.png)

**Comment by tatiang** [comment]
This is still an issue. These copies were made today:

![image](https://user-images.githubusercontent.com/10355498/146056397-6dfa2fe7-d3f2-4d14-b381-b2aefa0eb7c6.png)

**Comment by tatiang** [comment]
This continues to be a problem. It's preventing me from using Thunkable in any sort of systematic way in terms of updating projects and keeping backup copies. I'm really nervous I'm going to lose work or update the wrong project.

![image](https://user-images.githubusercontent.com/10355498/147868512-ca698969-39a0-4132-a5ae-2a5819cee576.png)

**Comment by tatiang** [comment]
This issue is preventing me from making useable backups/versions of my projects. I have no idea which project is which now.

**Comment by tatiang** [comment]
Unfortunately, this continues to malfunction and be a big problem.

**Comment by tatiang** [comment]
This continues to be a problem.

See also https://community.thunkable.com/t/bugs-copying-duplicating-projects-fails/1744947

**Comment by tatiang** [comment]
Still a major issue. It's nearly impossible to figure out which copy is the newest one!

**Comment by tatiang** [comment]
It's been 7 months and this issue remains. I can't trust the copies I make to be accurate. It's very hard to organize backups and I fear that I will choose the wrong one thinking it's the most up to date or worse, delete the wrong one thinking it's an old version.

**Comment by tatiang** [comment]
_Added new community link to original post._

**Comment by Ealalin02** [comment]
I have the same problem with my app "Work Plan"   , App Bundel ID  com.gmail.ealalin1.eventsmembers
I have make a duplicaat of my new  version of app from 22/04/2022 02:03 PM
Who had the version Admin V00.18
![image](https://user-images.githubusercontent.com/104272738/165928931-974f1df8-196e-4a98-8be9-84fe23ed3340.png)

![image](https://user-images.githubusercontent.com/104272738/165928465-186d4450-d1bd-4a3e-b0fa-46fba68210b0.png)
and I have received a duplicata with the date :from december 28 2020 6:59 PM I don’t trust the date and time received !!!!!!!   and the version is also a old one ( Admin V00.17 ) !!!!!!!

![image](https://user-images.githubusercontent.com/104272738/165929316-0d0ea5cf-071b-4be4-91ef-b1a507764292.png)

It's a serious problem ; it's mean that I have no backup of my last version of App .

**Comment by weihuali0509** [comment]
Sorry for the long wait. I will take a look at it early next week.

Wei

**Comment by weihuali0509** [comment]
The issue should be fixed by now. Please let me know if you have any questions.
