### ISSUE TITLE
Camera will not initiate

### ISSUE THREAD

**Issue by Chantel3474** [thunkable/thunkable-issues#1021]
Hi there,

I'm having an issue that I see has caused problems in the past, but all other threads have been closed (https://github.com/thunkable/thunkable-issues/issues/382) so I thought it appropriate to start a new one. I am using the new drag and drop interface. My issue is with Thunkable live (latest version 284-5, on iPhone 11 and iOS 14). I cannot get the camera to initiate using the 'photo from camera' block.

### Platform
✕ iOS companion (Thunkable live)

### Issue/Request Origin
Community

### Steps to Reproduce
1. Create button and photo from camera block
2. 
3.

### Expected Behavior
The camera should activate to take a photo

### Actual Behavior
Nothing happens - the camera does not activate. When I create the app in the old interface (not the new drag and drop one) then it works. The 'image from photo library' block also works.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![Screenshot 2021-09-22 at 16 02 11](https://user-images.githubusercontent.com/70948575/134358373-5358c557-8c56-45c9-972b-d07e807f7efd.png)

**Comment by josmas** [comment]
Hi @Chantel3474 did you allow the camera to be used for the live app? If the app has no permissions, then the block will not work.

You can check by right clicking the camera block and choosing to see the `advanced` version of the block, as:
<img width="367" alt="cam_1" src="https://user-images.githubusercontent.com/194925/134385953-cad37f1e-2f19-4a25-9728-b7ba4ab5cc37.png">

You can use the block as follows to see if there is an actual error (note a label is needed for debugging):
<img width="416" alt="cam_2" src="https://user-images.githubusercontent.com/194925/134386006-bdadca3b-e451-4f19-ae0e-90ec91ba30a0.png">

**Comment by Chantel3474** [comment]
Hi @josmas - thanks very much for sending through that tip and the screenshot, I used the if, do, else block to either show an error or open the camera and it's working now!
