### ISSUE TITLE
Google Maps Component Does Not Work in Published App

### ISSUE THREAD

**Issue by amazingwx** [thunkable/thunkable-issues#1040]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Verified on iOS through TestFlight
Have not tested with Android

### Steps to Reproduce
1. Open Live Test in Thunkable X and maps work on Thunkable Live iOS app
2. Open published app from TestFlight in iOS and maps do not work

I was using an unrestricted Google Maps API key which works with all of the other web viewer maps in my app. Thinking this was the problem, I created API keys for both iOS and Android apps, loaded them into my app settings, and the result is the same. I just get a blank Google map.

### Expected Behavior
When the screen opens, the app should show a map in the box to allow a user to select their location if they would like to change it. 

### Actual Behavior
The map shows the user's current location (blue dot on a white background), but no map is displayed. It should display the default Google map.

### Project Link
This is a private project.

###Community Link
https://community.thunkable.com/t/google-map-is-not-loading-correctly/1388656/10

```
  STACK TRACE AND/OR SCREENSHOTS
```
Expected Behavior:
![IMG_1761](https://user-images.githubusercontent.com/92692549/137682855-1f7fb9c9-f511-46d8-a1ca-a5f8940e62b4.jpeg)

Actual Behavior:
![IMG_1760](https://user-images.githubusercontent.com/92692549/137683102-8f6fba19-eb34-45ec-825b-13751e66f1c0.jpeg)

**Comment by amazingwx** [comment]
> @amazingwx is this still an issue?

So, it's still definitely an issue, but a whole new one now. I tried loading into Android and now I am getting a whole slew of errors:
![Image 10-29-21 at 11 31 PM](https://user-images.githubusercontent.com/92692549/139524646-dd4e940a-799c-40f6-ae3c-9342ce6b69b3.jpg)
![Image 10-29-21 at 11 32 PM](https://user-images.githubusercontent.com/92692549/139524643-8a68b9bd-75ba-4eae-9af0-8dc0f9d78eab.jpg)
![Image 10-29-21 at 11 33 PM](https://user-images.githubusercontent.com/92692549/139524644-fefbefbd-b7ef-4239-ae74-64c90a4019cc.jpg)
![Image 10-29-21 at 11 33 PM (1)](https://user-images.githubusercontent.com/92692549/139524647-3d00c4ee-5854-4362-af43-1459876b7d43.jpg)

**Comment by amazingwx** [comment]
I was just able to install from TestFlight on iOS and, yes, still an issue there too:
![IMG_1825](https://user-images.githubusercontent.com/92692549/139525123-0e819c40-eaad-4609-9500-653b96999228.PNG)

**Comment by josmas** [comment]
hey @amazingwx I just downloaded a basic map app on Android and it works fine. It uses a button and location to mark the user's location with a marker; it all works as expected.

Can this be an issue with your API keys or similar?

**Comment by amazingwx** [comment]
> Can this be an issue with your API keys or similar?

@josmas I don’t think so. I tried three API keys: unrestricted, iOS, and Android. None of them work in the maps component. Yet, when I put the same unrestricted API key in a web viewer, it works fine. I think my keys are fine. Plus, they work in the web app and Thunkable Live previews but display no maps when published.

**Comment by josmas** [comment]
This should be resolved; please let us know if that is not the case. Thanks!
