### ISSUE TITLE
iOS downloaded app mp4 not playing

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#1041]
Hi there,

I cannot play mp4 videos in the downloaded iOS app if I include them with the download package. I can get them to play with the video component when live testing for iOS, for Android (even with the downloaded app), and also for iOS with the downloaded app if I host them somewhere online and play them by url. But indeed, if I include the mp4 videos with the iOS app, and I download the app, then they won't play, the video player component is just blank.

I have tried everything I could think of and could find any discussion about, for example using a simple name for the file such as video.mp4. The same file, by the way, works when I host it somewhere and designated it by url for the video component to play with the downloaded iOS app.

Would be nice if you could help me out here. Thank you!

**Comment by josmas** [comment]
This should be resolved; if there are still issues please feel free to re-open. Thanks!
