### ISSUE TITLE
Apple blocking publishing because of the webviewer doesn't have AppTrackingTransparency framework

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#1044]
Dear Thunkable Team,

I have challenges getting my app published on the App Store because I utilize a webviewer and the page I'm displaying uses cookies (and a GDPR style prompt for them) -- and the app doesn't have the AppTrackingTransparency framework implemented. See the response from Apple below:

_Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing

We noticed your app accesses web content you own where you collect cookies. However, you do not use App Tracking Transparency to request the user's permission before collecting data used to track.

Collecting cookies is a form of tracking. Starting with iOS 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them.

Next Steps

Follow these steps to resolve this issue:

1. If you haven't already, update your app privacy information in App Store Connect to disclose that you track users. You must have the Account Holder or Admin role to update app privacy information.
2. Implement App Tracking Transparency.
3. Request permission using App Tracking Transparency before collecting data used to track the user. When you resubmit, indicate in the Review Notes where the permission request is located.
4. If the user does not allow tracking, do not collect cookies for tracking purposes.

You may also choose to remove the tracking functionality from your app, including tracking that occurs when accessing web content.

Resources

- Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about tracking.
- See Frequently Asked Questions about the new requirements for apps that track users.
- Learn more about designing appropriate permission requests.

Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing

We noticed your app includes a GDPR prompt, informing the user that your app tracks. However, you do not use App Tracking Transparency to request the user's permission before collecting data used to track.

Starting with iOS 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them.

Next Steps

Follow these steps to resolve this issue:

1. If you haven't already, update your app privacy information in App Store Connect to disclose that you track users. You must have the Account Holder or Admin role to update app privacy information.
2. Implement App Tracking Transparency.
3. Request permission using App Tracking Transparency before collecting data used to track the user. When you resubmit, indicate in the Review Notes where the permission request is located.

You may also choose to remove the tracking functionality from your app.

Resources

- Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about tracking.
- See Frequently Asked Questions about the new requirements for apps that track users.
- Learn more about designing appropriate permission requests.

Please see attached screenshot for details._

Would be nice if you could help to implement this framework into Thunkable, otherwise it will become somewhat hard for people to publish for iOS with the webviewer.

Thank you!

**Comment by jaredgibb** [comment]
Hi @Heikkiss, it sounds like this issue has been resolved. Can you try publishing again?

**Comment by Heikkiss** [comment]
Hi, thanks for helping out with this. I could indeed publish now. But as mentioned on the forums, for the future, it would also be good to think of how to enable the tracking prompt if needed. But for now this works. :)
