### ISSUE TITLE
In the drag and drop version of Thunkable the sensors does not work, when you click the PLUS it just goes white.

### ISSUE THREAD

**Issue by 72drenton** [thunkable/thunkable-issues#1045]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Does this affect:
Drag and Drop UI - web?
Drag and Drop UI - Android?
Drag and Drop UI - iOS?

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

###Community Link
If there's an ongoing discussion about this behavior in the Community, please link to it here

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by tatiang** [comment]
Working for me, too. Thank you!

**Comment by jane-d-alt** [comment]
Thank you both for replying and confirming! I'll close this issue now.
