### ISSUE TITLE
Math block REFORMAT missing in X

### ISSUE THREAD

**Issue by SeeTryFly** [thunkable/thunkable-issues#105]
I have a project in Classic that cannot be translated to X because the math block Reformat Number is missing.

**Comment by AlexITMan** [comment]
There is no ready block, but instead it is possible to make the necessary functions from the available blocks.

**Comment by jane-d-alt** [comment]
Thunkable X has a block to round a given number to a given amount of decimal places.
To convert degrees to radians: multiply [degrees] by π/180
To convert radians to degrees: multiply [radians] by 180π
