### ISSUE TITLE
Time does not work in Drag n Drop Web Preview

### ISSUE THREAD

**Issue by TechTeacherK** [thunkable/thunkable-issues#1053]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Does this affect:
Drag and Drop UI - web?  YES - I am a middle school teacher and without the timer working in web preview the students can't use the timer functionality (they don't have phones/aren't allowed to download onto them/have lost privileges, etc.)
Drag and Drop UI - Android?
Drag and Drop UI - iOS?

### Steps to Reproduce
1.  Add Timer
2. Create code with timer (see attached screenshot) 
3. Press web preview

### Expected Behavior
What did you expect to happen?  
Countdown should begin when button is pressed

### Actual Behavior
What actually happens? 
Nothing

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

https://x.thunkable.com/copy/e42c49df6b245e0e390462950b4cf96f

###Community Link
If there's an ongoing discussion about this behavior in the Community, please link to it here

https://community.thunkable.com/t/timer-webpreview/1529237
```
  STACK TRACE AND/OR SCREENSHOTS
``
![Timer CodeBlocks](https://user-images.githubusercontent.com/93870567/140648728-bbaf8d2f-8702-42dd-9064-a0dfec47c139.PNG)
`

**Comment by josmas** [comment]
Hey @TechTeacherK Timers should be working again in preview mode.
Closing this for now, please let us know if you are still having issues. Thanks!
