### ISSUE TITLE
Ability to change the font colour and font style of all text on a page in Thunkable Cross Over X

### ISSUE THREAD

**Issue by licon4812** [thunkable/thunkable-issues#106]
**Is your feature request related to a problem? Please describe.**
The ability to change the font colour and font style of all labels on a page in one simple block of code will make it easier to make adjustments to pages that have 100+ labels on them

**Describe the solution you'd like**
a simple block of code that makes the above possible

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by AlexITMan** [comment]
Sorry, can you explain to me why there are so many (100) labels on the page?  If you need complex markup, you can use WebViewer and HTML for this.

**Comment by licon4812** [comment]
HTML isn't a feature in thunkable though. And I wanted to make everything self contained in the app without having some external page embeded

**Comment by mark-friedman** [comment]
@licon4812 Thanks for suggesting this feature.  It's on our general roadmap, although perhaps not in the near future.

@AlexITMan We certainly hope to be able support reasonably complex layouts in Thunkable.  Resorting to a Web Viewer and HTML just forces the user to do the sort of textual programming that Thunkable is trying to help users avoid.  Not to mention that it's difficult to communicate between a Web Viewer and the rest of the app.  I understand that right now there might be reasons to use a Web Viewer as a workaround, but I hope that over time we can greatly reduce the need for it.

**Comment by AlexITMan** [comment]
@licon4812 You don't need to use a external page. But as correctly noted by Mark you need to be able to program in order to do a little more that can be done only with the help of blocks.

@mark-friedman, management and developers of Thunkable X fundamentally do not want and do not plan to create a local data exchange mechanism between WebViewer and the app or work in this direction is underway, but is such an exchange extremely difficult to implement using existing technologies or is it forbidden by Apple to make it?

**Comment by licon4812** [comment]
@AlexITMan  I thought the block code was the only way of using code within thunkable. How do I use other coding languages within the thunkable interface.

**Comment by AlexITMan** [comment]
There are examples of using html in Thunkable X on the scrHtml screen.

https://x.thunkable.com/projects/5be41fffe4baa4f06bb4f907/project/properties/designer/

**Comment by jane-d-alt** [comment]
This can now be done with any component blocks: https://docs.thunkable.com/any-component-blocks
We'll close this issue; apologies for not following up when these blocks were originally added.
