### ISSUE TITLE
Racing league app

### ISSUE THREAD

**Issue by BekotheBigG** [thunkable/thunkable-issues#1067]
Greetings to all,
For about 2 months , I have been designing a mobile application for our league organized over the formula 1 2021 game on thunkable .
I would like to tell you about a problem that I noticed a little late.

The place where I am having trouble in my application is in the Yarışlar(races) tab. Normally, when the user selects a race from there, I would write the name of the race in my selection tab in my google sheet and read the data with vlookup. But I noticed that this system only works for 1 person. And because I didn't want to add 21 hidden screens for each race, I set up such a system (thanks to the Thunkable community).

 Since I'm trying to make an application that more than 300 people can use, my system needs to be renewed, fixed and if possible without adding 21 hidden screens :D .
my app link :
https://x.thunkable.com/copy/d00f8406bd4aed8b8640dc6a8a453ac3
my sheet link:
https://docs.google.com/spreadsheets/d/1MRyCT4tfyUA0UQOimdK-Y32I9lauv6fmqeuaMoFlpBo/edit?usp=sharing

I'm waiting for your ideas. (not just about Yarışlar tab, I'm waiting for any ideas that will take my application one step further).

Kind regards . 
Beko

**Comment by tatiang** [comment]
I think you should post this question on the Thunkable Forums. This isn't a bug report or a feature request which is what is expected here.

**Comment by jaredgibb** [comment]
Hey @BekotheBigG 

We love to see the excitement here! The forum is a much better place, however, for these types of discussions! Please do take it over there and it'll surely fire up some conversation! 

Best,

Jared Gibb
