### ISSUE TITLE
Some Project Settings are not saved between sessions

### ISSUE THREAD

**Issue by jaredgibb** [thunkable/thunkable-issues#1069]
Issue detailed in title. 

**How to reproduce.**
open a new drag and drop project
assign an admob API key
assign a google map API key
navigate to the main projects page
return to the newly created app
check the api keys

**Here is a video that outlines the issue** 
https://vimeo.com/650311364

**Comment by Muneeralshaikh** [comment]
It is worth mentioning that this **BUG** is not limited to Drag and Drop but also affects Snap to Place.

**Comment by josmas** [comment]
Thanks @jaredgibb and @Muneeralshaikh 
I can reproduce locally. We had a similar issue with iOS perms recently, so will check if it is the same thing.
