### ISSUE TITLE
Please add IAP to the basic editing interface

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#1072]
Hi there,

As a long-time PRO user I was really pleased to notice that you added IAP support recently to Thunkable. I've really been waiting for this. However, I also quickly discovered that you can use IAP only with the new interface, which I haven't quite understandably yet used for my projects that I've been building and publishing to the App Store / Play Store for a while. So I can't add IAP without switching to the new interface, which is quite a hassle, particularly as I hear that not all the features from the old interface are yet available in the new one (quite understandably as the new interface is still in beta, it seems).

So, simply put, could I please ask you to add the same IAP support to the old interface? I imagine this wouldn't probably be too big a work to do as you have the underlying mechanics in place already. For me and for many others though, struggling to monetize our apps, this would be big leap forward. Also, to be honest, it feels simply unfair that IAP is available only for those PRO users who use the new interface as I can imagine many are still sticking with the traditional one. I do get it that for example some options regarding layout would be available only with the new interface, but a feature as central as IAP is, and one that has nothing to do with the interface/layout side of development, I just can't see why IAP is not there with the old interface.

The reason I might sound a bit disappointed here is that besides the issue itself, I in fact raised the issue on the forums a while ago, without any response. I really love Thunkable, but this just doesn't feel right. Hoping you could fix this soon.

Thank you!

Best,

Heikki

**Comment by tatiang** [comment]
Link to forum topic: https://community.thunkable.com/t/in-app-purchase-component-not-there/1629857

**Comment by jaredgibb** [comment]
Check it out guys! 
<img width="259" alt="Screen Shot 2021-12-10 at 7 24 37 AM" src="https://user-images.githubusercontent.com/70493366/145573774-ee2f0230-127e-4f4e-b3a3-766a37307a08.png">

**Comment by Heikkiss** [comment]
Many, many thanks for this! So great to hear this! 👍 👍
