### ISSUE TITLE
Submenu of Data Viewer List component has ID values and creates errors

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1073]
### Platform
Snap to Place - web

### Steps to Reproduce
1. Add a Data Viewer List (DVL) component to a screen in the Snap to Place interface.
2. Assign a custom DVL layout to the DVL
3. Open the submenu (see https://community.thunkable.com/t/unable-to-access-data-viewer-list-sub-items/1619383) and notice that instead of the component name appearing in each block, the normally-hidden ID is displayed.
4. Adding one of these blocks results in an error.

### Expected Behavior
See above.

### Actual Behavior
See above.

### Project Link

###Community Link
[(https://community.thunkable.com/t/unable-to-access-data-viewer-list-sub-items/1619383)
](https://community.thunkable.com/t/unable-to-access-data-viewer-list-sub-items/1619383)
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jaredgibb** [comment]
@tatiang Thank you for reporting this! I’ll investigate at 9AM EST! Would you mind sharing a link to a simple project with this issue? Is this issue persistent for you?

**Comment by Muneeralshaikh** [comment]
The error is in DnD only. StP seems to work fine.

The BUG appears even when using any of the default layouts.

**Comment by tatiang** [comment]
> @tatiang Thank you for reporting this! I’ll investigate at 9AM EST! Would you mind sharing a link to a simple project with this issue? Is this issue persistent for you?

The link I just sent you with the project where I'm having problems with the DVL appearing too narrow also has this issue. If you open a submenu of the DVL on the Blocks tab, you'll see ID numbers instead of component names.

**Comment by jaredgibb** [comment]
Hey @josmas, I am experiencing the same thing when I use a DVL in a DnD project. 

I am building in Chrome on a MacBook (early 2015) with Catalina 10.15.7

When I add a DVL to a DnD project, I am unable to reference any specific element via the rowID block for an onClick/onSlide event as there is no spot to place the rowID block in the individual elements that comprise the DVL. Although they can be used to display data no problem, you _**can't**_ access the individual elements.  

This is what I see when i try to access the relevant blocks 
<img width="1128" alt="Screen Shot 2021-12-02 at 3 34 27 PM" src="https://user-images.githubusercontent.com/70493366/144498767-8b913122-2c26-4c1f-bff8-9c8d337d16b4.png">

**Comment by tatiang** [comment]
@jaredgibb It's really helpful to have this kind of confirmation posted on a GitHub topic. Thanks for looking into this! I have a project stalled until I can update DVL "fields" (subcomponents) dynamically. I do have a workaround in mind but would love to see this fixed.

**Comment by jaredgibb** [comment]
Hey @tatiang 

Please check your apps again. This issue has been fixed!
