### ISSUE TITLE
Buttons should have font properties

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1077]
**Is your feature request related to a problem? Please describe.**
There should be a way to specify a font on a button just like there is for labels.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable X, Snap to Place Interface

**Additional context**
Here's how it looks for a label:

<img src="https://user-images.githubusercontent.com/10355498/145634401-57414396-c05a-4427-90b7-956eeb15bbaa.png" width=250>

**Comment by jaredgibb** [comment]
We agreed. We have added this feature back in! 
<img width="877" alt="Screen Shot 2021-12-29 at 1 55 24 PM" src="https://user-images.githubusercontent.com/70493366/147694537-aeb7b4d9-1d34-4985-a3b4-c9a967777e9b.png">
