### ISSUE TITLE
Sound (and Video?) filenames cannot contain spaces

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1078]
### Platform
Snap to Place UI - web

### Steps to Reproduce
1. Import a sound (or a video, I think) with a space in the name such as "test sound.mp3"
2. Play the sound
3. An error message appears (from the green block) "Error loading Source..."
4. Import the same sound file but renamed without a space such as "test_sound.mp3"
5. The sound plays correctly.

### Expected Behavior
The sound should play even with a space in the filename. 

The documentation for the Sound (and Video?) component should mentioned to avoid using filenames with spaces until this bug is fixed.

### Actual Behavior
See above.

### Project Link

###Community Link
It's been mentioned before but I don't have links.
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img src="https://user-images.githubusercontent.com/10355498/145700288-e1041d63-e6c3-410c-af4f-860d6631bd74.png" width=350>

**Comment by jaredgibb** [comment]
waiting to merge the docs on assets now! 
<img width="847" alt="Screen Shot 2021-12-14 at 11 05 20 AM" src="https://user-images.githubusercontent.com/70493366/146034936-8855cfe4-772b-4803-817b-0654f7708225.png">
