### ISSUE TITLE
Copy & paste blocks not working

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1079]
### Platform
Drag and Drop UI - web

### Steps to Reproduce

1. Click on when PDF Viewer Opens block in screen 1.
2. Press cmd+c (Mac) to copy
3. Click on screen 2
4. Press cmd+v (Mac) to paste
5. Duplicate blocks do not appear in screen 2.
6. Duplicate blocks appear in screen 1 and are formatted oddly.

### Expected Behavior
The copied blocks should appear in screen 2.

### Actual Behavior
See above.

### Project Link

###Community Link
https://community.thunkable.com/t/copy-paste-blocks/1652223
```
  STACK TRACE AND/OR SCREENSHOTS
```
Screencast of the problem:

https://watch.screencastify.com/v/OgycAkYtVHC3F4BRJNXm

**Comment by jaredgibb** [comment]
Thanks for reporting this issue. I have escalated this with our team and will followup!

**Comment by OrangesII** [comment]
Hey is there any update on this? This bug makes duplicating screens/blocks a lot of work.

**Comment by tatiang** [comment]
This is still a problem. If I try to copy a set of blocks on one Drag & Drop screen and then paste it on a different screen, it appears incorrectly formatted and on the same screen that I copied it from.

**Comment by OrangesII** [comment]
Hey @tatiang have you tried recently? I just tried to copy and paste something, and it pasted across screens. Are you seeing this behaviour>

**Comment by tatiang** [comment]
Yes, it worked for me yesterday. Hopefully that means it’s fixed.
