### ISSUE TITLE
Objects have a appendix

### ISSUE THREAD

**Issue by lisztomania1** [thunkable/thunkable-issues#108]
![image](https://user-images.githubusercontent.com/34504909/47616178-9a758c80-dab9-11e8-9d5c-50fdc69cedd3.png)

Every object created has a appendix which is called _scopeVariableInfo.

This appendix is stored on firebase after uploading the object.

**Comment by domhnallohanlon** [comment]
Linking back to Community questions about this:

- https://community.thunkable.com/t/scopevariable-in-rt-database/1042074?u=domhnallohanlon
- https://community.thunkable.com/t/there-is-a-random-array-called-scopedvariablearray-appearing-in-my-app/1042776?u=domhnallohanlon
- https://community.thunkable.com/t/firebase-scopevariableinfo-cloud-variable-error-notification/235341?u=domhnallohanlon (with work-arounds from Mark and ACTech)
- https://community.thunkable.com/t/problem-with-reading-the-scopevariableinfo/388381?u=domhnallohanlon
- https://community.thunkable.com/t/convert-value-of-firebase-to-list/706489/8?u=domhnallohanlon (another interesting work-around)

**Comment by jane-d-alt** [comment]
Hi there, this behavior has been resolved. Apologies for not following up when this behavior was originally resolved. Please reach out if you experience similar behavior in the future. Thanks!
