### ISSUE TITLE
Problems editing and saving custom data viewer layouts

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1080]
### Platform
Snap to Place UI - web

### Steps to Reproduce
1. Go to https://x.thunkable.com/projects and click on **My Data Viewer Layouts** tab.
2. Click **edit** next to a layout name.
3. Make changes to the layout.
4. Click **Save as Data Viewer Layout**.
5. Type in a name and click **OK**.
6. The dialog box does not disappear. I have to then click the **close (x)** or **cancel** button.
7. The new layout does **not** get saved to the list of custom data viewer layouts.

### Expected Behavior
The new layout should save.

### Actual Behavior
See above.

### Project Link
https://x.thunkable.com/modules/61b1b34c0e35a5007763dd15/c5e4fbe2-5a1c-4cc7-a5e3-61f2418d67d0/designer

###Community Link

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jaredgibb** [comment]
Hey @tatiang 👋 ,

I am seeing the same thing on my end. I have touched base with the team and will return with a response hopefully later today as to whether it's intended or not. 👍

**Comment by tatiang** [comment]
@jaredgibb Any word on this? I'd like to know if I should be attempting to edit custom layouts that way. It seems like the intended method but it's not working for me.

**Comment by pmwthunkable** [comment]
You can edit an existing custom data viewer layout by following the first three steps you listed.

1. Go to https://x.thunkable.com/projects and click on My Data Viewer Layouts tab.
2. Click edit next to a layout name.
3. Make changes to the layout.

The layouts auto-save (just like projects).

You CANNOT create a new data viewer layout from inside an existing data viewer layout. If you want to make a new one, go to the original project. We need to remove the "Save as Data Viewer Layout" button inside of layouts - it's a bug.
