### ISSUE TITLE
Drag and Drop: Label background Bleeds over border

### ISSUE THREAD

**Issue by OrangesII** [thunkable/thunkable-issues#1083]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Does this affect:
Drag and Drop UI - iOS?

### Steps to Reproduce
1. Open app on iPhone
2. Click any of the boxes
3. Observe the bug

### Expected Behavior
What did you expect to happen?
When filling in the background of a label on Android or the Web it works perfectly and fills in the background as expected

### Actual Behavior
What actually happens?
For the iPhone it fills in the border, but it doesn't respect the radius lines and fills in the whole box.

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.
https://x.thunkable.com/copy/926b925de5f9c8b42088e4b1f01647a8

###Community Link
https://community.thunkable.com/t/drag-and-drop-label-background-bleeds-over-border/1653761/2

```
  STACK TRACE AND/OR SCREENSHOTS
```
Andriod:
![image](https://user-images.githubusercontent.com/96126523/146071081-97a76e26-678b-482f-b62d-de084bb2acef.png)
Web:
![image](https://user-images.githubusercontent.com/96126523/146071100-44c724da-b6f6-4f2c-8134-343d3efb6d12.png)

Issue with iPhone:
![image](https://user-images.githubusercontent.com/96126523/146071155-32920117-3ce0-4876-9338-d35bd88622b8.png)

**Comment by jaredgibb** [comment]
HI @OrangesII , are you seeing this same behavior on your downloaded app? Are you on the latest version of the companion app?

**Comment by jaredgibb** [comment]
I see this too. One potential workaround while we get this sorted out would be to place the label in a group and give the group the color and rounded edges. Obviously not ideal but may work for now while we get this fixed.

**Comment by jaredgibb** [comment]
Please check this again @OrangesII This issue should be fixed now!

**Comment by OrangesII** [comment]
> Please check this again @OrangesII This issue should be fixed now!

I just checked it is fixed!! Thanks @jaredgibb and thunkable team for the quick turnaround!

**Comment by OrangesII** [comment]
@jaredgibb Something must have happened, the edge bleeding is happening again :(
