### ISSUE TITLE
Button heights are rendered incorrectly in downloaded iOS apps

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1089]
### Platform
Drag and Drop UI - iOS?

### Steps to Reproduce
1. Create a button with equal height and width (e.g. height 70, width 70)
2. Download project for iOS

### Expected Behavior
I expect to see a round (circular) button. 

### Actual Behavior
The button is elongated so that the height is about 50% more than it should be and the button is oval in shape. This does not happen when previewed in a browser or Live Tested in Thunkable Live. I'm using an iPhone 11.

### Project Link

###Community Link
https://community.thunkable.com/t/circular-buttons-are-getting-stretched/1660460
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jaredgibb** [comment]
Thanks, I have escalated this to the team. I will follow up when we have more info.

**Comment by schnaars** [comment]
@tatiang thanks for sharing this.  I'm also seeing this same bug and you and I have discussed in the Thunkable community - https://community.thunkable.com/t/buttons-look-normal-in-test-but-bad-in-app/1711895/4

**Comment by jaredgibb** [comment]
Hi all,  

We have released a new property for visual components to address this. Check it out in the layout section of any visual component, it's called "resize". Set your button to "float in place" and see how they look then!
