### ISSUE TITLE
Back button on Webview

### ISSUE THREAD

**Issue by MattUnsworthUK** [thunkable/thunkable-issues#109]
**Is your feature request related to a problem? Please describe.**
I create apps which convert websites in to app form and would love for the cross platform to offer a back and forward button if possible. 

**Describe the solution you'd like**
A back and forward button for webview.

**Describe alternatives you've considered**
None, I currently use classic for this. 

**Which platform are you asking for?**
Thunkable X

**Additional context**
Nothing else to add currently.

**Comment by jane-d-alt** [comment]
The Web Viewer now has 'back' and 'forward' buttons. We'll close this request; apologies for not following up when the feature was originally added.
