### ISSUE TITLE
FireBase Authentication Not Working in iOS

### ISSUE THREAD

**Issue by jpandare** [thunkable/thunkable-issues#1093]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Does this affect:
Drag and Drop UI - web? No
Drag and Drop UI - Android? No
Drag and Drop UI - iOS? Yes

### Steps to Reproduce
1. Login to Firebase when starting Home page
2. Try to access data on same user
3. Access denied by firebase due security rules (rules are the same for web, android and iOS)

### Expected Behavior
What did you expect to happen?
Access user data in RealTime dabase in firebase

### Actual Behavior
What actually happens?

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.
https://x.thunkable.com/projects/612e2fa7fd15c300115a7863/9ad40c3a-98d8-40ca-ac8a-0ba72db9c429/blocks

###Community Link
If there's an ongoing discussion about this behavior in the Community, please link to it here

```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/92627899/147942905-2f888438-7eab-496e-b119-5b4883441309.png)

This issue started few days ago. Very low occurrence in web and android. iOS just not working.

**Message got from firebase: permission_denied at /Users/[user-id-here]/PostsToView Cliente doesn't have permission to access the desired data.****

**Comment by jaredgibb** [comment]
Hi @jpandare . Can you share a minimal example of this issue? I am unable to reproduce this on my side. I believe you are having issues, but I was just able to set up what you are describing without issue using DnD and am only testing on iOS.

**Comment by jpandare** [comment]
I have changed cloud var operation after sign-in block and now is working fine. Thanks...
