### ISSUE TITLE
API calls on web-view and responsive web-app are https:// even though API URL puts http://

### ISSUE THREAD

**Issue by gobassky** [thunkable/thunkable-issues#1099]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Does this affect: 
Thunkable X - web
Drag and Drop UI - web

### Steps to Reproduce
1. Make a web-api GET call to a http:// source that only serves http://  
2. Test it using web-view or responsive web-app using any browser, eg chrome  

### Expected Behavior
The api calls should return JSON data. It works for mobiles.    

### Actual Behavior
1) For testing on live app on android or iOS it works. But for web-app it returned "failed to fetch data"
2) On browser (chrome) inspecting the out going traffic of the web-app using developer tools, the api calls are https://, which the api server is unable to process. 

### Project Link
Http IP address is private.

###Community Link
https://community.thunkable.com/t/api-json-tutorial-video/1140575/39?u=gobassky

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
This is a limitation of the web and not Thunkable's. Calls to http from a https resource will get upgraded to https by the browser. We talk about it in more depth here: https://blog.thunkable.com/integration-security-how-to-safely-integrate-your-apps-4cae27470f11 and propose certain ways around it.

**Comment by gobassky** [comment]
Thanks Very useful information. 

> This is a limitation of the web and not Thunkable's. Calls to http from a https resource will get upgraded to https by the browser. We talk about it in more depth here: https://blog.thunkable.com/integration-security-how-to-safely-integrate-your-apps-4cae27470f11 and propose certain ways around it.

**Comment by gobassky** [comment]
Thanks. Very useful information, and pardon me that I have missed the blog.
So to put things simply, new secure browsers such as Chrome running the web-app will automatically upgrade HTTP to HTTPS requests. And if the server only serves HTTP and not HTTPS, it will understandably not work. 

Thanks. I will look at making a work around, since I have control over the server side. Thanks again.

**Comment by josmas** [comment]
hey @gobassky no worries at all. Yeah, that is how it works with modern browsers. We can bypass on devices to accept http request, but not on web.

If you have control over the server you can look into https://letsencrypt.org/ for free certs. If you are not hosting directly on a cloud provider, or even during development, you can check out https://ngrok.com/ to create a https tunnel to whatever machine you are working on, even if it is not publicly reachable.
