### ISSUE TITLE
Feature Request: Option to duplicate screens (ThunkableX)

### ISSUE THREAD

**Issue by rschoem** [thunkable/thunkable-issues#11]
I am building an app containing several screens. I want the screens to look the same, with standard header, footer, background, etc. 
At the moment, I have to repeat the design for each of these screens. It would be helpful if I could duplicate screens so that I only have to design a screen only once.

Obviously, it would even be nicer if it were possible to define a sort of "templates" for screens, and that a template can be assigned to a screen. This way, if the design changes in the future, only the template(s) needs to be changed. But I guess this will be much more difficult to implement than just a "screen duplicate" option ;-)

Thanks!

**Comment by AmigoDeluxe** [comment]
How can we upvote feature requests? This one is a MUST!

**Comment by mark-friedman** [comment]
We are actively working on a template feature similar to this.   We don't have an estimate yet for when this will be finished.

**Comment by nicbyron** [comment]
Excited for templating/reusability to come to thunkable!

**Comment by josmas** [comment]
Screens can now be saved and reused in latest release. Thanks.

**Comment by nicbyron** [comment]
💥 Yay! thank you all!!
