### ISSUE TITLE
Unable to use live test for drag and drop screen

### ISSUE THREAD

**Issue by Saranbcc** [thunkable/thunkable-issues#1109]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Drag and Drop UI - Android
Drag and Drop UI - iOS

### Expected Behavior
The live test on at least 1 device work

### Actual Behavior
When I use the live test feature on both of my devices (Android and Ipad), the screen went white blank. When I go view the code, it is not there for me to check. It is like I only create the project and do nothing else, no screens and no codes. In conclusion (I do not know that this only happens to me or not), my live test for the new drag and drop screen won't work for some reason. 

### Project Link
https://x.thunkable.com/copy/11b2ef9489d7a33adca7480fa94cad6a
(This is my first ever project)

```
![image](https://user-images.githubusercontent.com/98821005/151976523-d3384336-e6e9-4388-b096-8ac4b0fb9e24.png)
![image](https://user-images.githubusercontent.com/98821005/151976543-aef6d616-bc93-413a-a3ef-660ca70e23b9.png)
![image](https://user-images.githubusercontent.com/98821005/151976581-95d1f873-4c4e-4323-bbf6-57f74f73ed07.png)
```

I hope this gets fixed as soon as possible. Thank you!

**Comment by tatiang** [comment]
You have a drawer navigator with nothing in it. This is causing the blank white screen when testing on devices.

![image](https://user-images.githubusercontent.com/10355498/152068045-6a2a0629-61f8-4770-9d6b-3395a13a8f20.png)

You either need to delete the navigator or you need to drag some screens onto it to add them to the navigator.

I hope you'll consider re-wording some of the screens. You're equating gender with sex and they are not the same thing. On the first screen, for example, you could ask for the person's biological sex if that's what you're wanting to know.

**Comment by josmas** [comment]
thanks @tatiang closing this for now. Thanks!

**Comment by Saranbcc** [comment]
Ohh, Thanks @tatiang!. I didn't know that was causing the problem. The live test work now
