### ISSUE TITLE
Set Time- and Date picker from block code.

### ISSUE THREAD

**Issue by bytepot** [thunkable/thunkable-issues#1113]
The feature would be great to solve time- and date issues.

Pfatform for this feature request is thunkableX.

**Comment by jaredgibb** [comment]
Hi @bytepot 

We no longer support Thunkable Classic. As far as i can tell, this works in the drag and drop interface. try this block combo, for example 
<img width="593" alt="Screen Shot 2022-02-09 at 2 35 43 PM" src="https://user-images.githubusercontent.com/70493366/153276890-9d6ae930-f68e-4d05-8358-ee872895c75b.png">

**Comment by bytepot** [comment]
Sorry Jared, i was meaning thunkable X.
🙈
________________________________
