### ISSUE TITLE
Crash caused by an error in AndroidManifest.xml

### ISSUE THREAD

**Issue by dani1913** [thunkable/thunkable-issues#1114]
### Severity
**BLOCKING ISSUE**

Since today the Thunkable platform encode the ~ symbol with %7E in Android Manifest in the meta-data com.google.android.gms.ad.APPLICATION_ID

This causes a crash anytime I open my app.

It is a very urgent issue because I cannot deliver the app to my customers.

### Platform
Does this affect:
Drag and Drop UI - Android

### Steps to Reproduce
1. Insert Android Admob App ID in project settings (app id normally contains symbol ~)
2. Build and download the APK
3. Open the app

### Expected Behavior
No crash expected

### Actual Behavior
What actually happens?
The App crashes immediately every time

### Project Link
https://x.thunkable.com/projects/61ae31cc17ca440442439781

```
  STACK TRACE AND/OR SCREENSHOTS
```
The issue is located in the android manifest

ADB debugger shows this
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
02-09 12:36:18.362 28630 28630 E AndroidRuntime: 
02-09 12:36:18.362 28630 28630 E AndroidRuntime: ******************************************************************************
02-09 12:36:18.362 28630 28630 E AndroidRuntime: * Invalid application ID. Follow instructions here:                          *
02-09 12:36:18.362 28630 28630 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
02-09 12:36:18.362 28630 28630 E AndroidRuntime: * to find your app ID.                                                       *
02-09 12:36:18.362 28630 28630 E AndroidRuntime: ******************************************************************************

**Comment by jaredgibb** [comment]
How many times has this error occurred for you?

**Comment by dani1913** [comment]
@jaredgibb every time I open the app there is a crash.
This started to happen since today.
Last friday everything worked fine.

**Comment by dani1913** [comment]
@jaredgibb you can try yourself by puttin a ~ in admob settings app id, build the apk and read the manifest. You will see that ~ become %7E

**Comment by weihuali0509** [comment]
@dani1913 we are looking into it now.
