### ISSUE TITLE
Add Circle block for google maps

### ISSUE THREAD

**Issue by werd-abbas** [thunkable/thunkable-issues#1122]
Hi, I am working on tracking app, where if person goes outside the geo-fence(Circle) the admin gets notified. But there is no "add circle" block in the maps. I wasn't able to finish the app due to this issue. I think its a pretty basic feature and should have been there.

A simple solution would be just to add "Add Circle" block in maps, with draggable property as well for editing purposes, means if some one wants to edits the circle it can be draggable.

I tried to make circular fence by using polygon method but that didn't work quite well. It was more of a ellipse rather than circle and at some areas ellipse is just so stretched out that its just a line.
Here are the Links of what i have tried so far;
In this one he showed to make circle with the Polygon.
[https://stackoverflow.com/questions/14664685/google-maps-circle-to-polyline-coordinate-array](url)
here is an-other one;
[https://community.thunkable.com/t/polygon-in-the-form-of-a-circle/1642580/3](url)

I want this feature in thunkable X because the classic already had this feature.

**Comment by jaredgibb** [comment]
I've added this as a feature request and also created a decent project that displays circles up to 500km pretty dang well! 

https://community.thunkable.com/t/fun-share-circle-on-map/1760218
