### ISSUE TITLE
Horizontal scrolling in Data Viewer Grid also scrolls vertically

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1128]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Drag and Drop UI - iOS

### Steps to Reproduce
1. Add data to a local data source
2. Add a Data Viewer Grid (DVG) and sync it to the data source
3. Enable horizontal scrolling for the DVG
4. Test in Thunkable Live on an iPhone 11
5. Swipe left or right

### Expected Behavior
The DVG contents should scroll horizontally.

### Actual Behavior
The DVG contents scroll horizontally but also vertically. I believe this is related to the pull-to-refresh feature of DVGs. This does not occur on Android phones.

### Project Link
https://x.thunkable.com/copy/2541d5c0967fa6a4040dc679d139beea

###Community Link
https://community.thunkable.com/t/horizontal-scrolling-in-data-viewer-grid-also-scrolls-vertically/1759856
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jaredgibb** [comment]
Sorry for the delay getting to this! I have reported this with the team. We appreciate your diligence in reporting these things with such detail!

**Comment by jaredgibb** [comment]
This has been resolved!

Please be sure to update your app and do a hard refreshing the browser in your notice the updates!
