### ISSUE TITLE
My actual version of app is not the right version when I duplicate it!

### ISSUE THREAD

**Issue by Ealalin02** [thunkable/thunkable-issues#1139]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Does this affect:
Drag and Drop UI - web?
Drag and Drop UI - Android?
Drag and Drop UI - iOS?

### Steps to Reproduce
1.When I want to duplicate my laast version of my App from 22/04/2022 02:03 PM

2. I receive well a duplicaat but not from the last version. The version received is from december 28 2020 6:59 PM I don’t trust the date and time received
3.
Actual version is the version Admin V00.18 ,The second version received after the duplicate is the version Admin V00.17
### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens? The duplicate version is not the last version edited , so i m running without backup

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

###Community Link
If there's an ongoing discussion about this behavior in the Community, please link to it here
https://community.thunkable.com/t/my-actual-version-of-app-is-not-the-right-version-when-i-duplicate-it/1843873

```
  STACK TRACE AND/OR SCREENSHOTS
```https://aws1.discourse-cdn.com/business4/uploads/thunkable/original/3X/e/b/eb1d54ab9c504912bd520f882afaa6eac7f3dda9.png
https://aws1.discourse-cdn.com/business4/uploads/thunkable/original/3X/1/e/1ef6152143dfb0359dc3e30de5afa852a30a509c.png

**Comment by Ealalin02** [comment]
It's a serious problem , this mean that i don't have backup file for my latest App version !!!!!

**Comment by jaredgibb** [comment]
Hi @Ealalin02 

I' was unable to reproduce this. Are you still experiencing this issue?

**Comment by tatiang** [comment]
Are you experiencing this?

https://github.com/thunkable/thunkable-issues/issues/1014

**Comment by Ealalin02** [comment]
This issue is résolves

Op za 14 mei 2022 om 04:49 schreef tatiang ***@***.***>
