### ISSUE TITLE
 (for Thunkable X) Methods for opening and closing the panel DrawerNavigator

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#114]
Many applications have a menu button, when clicked, opens the sidebar DrawerNavigator.  We do not have a method for opening this panel because of what many users tell me that the application is unfriendly, because they cannot understand if there is a menu and how to open it.

**Comment by jane-d-alt** [comment]
Thunkable X now has a block that can [toggle the Drawer Navigator.](https://docs.thunkable.com/release-notes#jun-24-2019)
