### ISSUE TITLE
"Any Component" Create block causes app crash

### ISSUE THREAD

**Issue by jrshelby** [thunkable/thunkable-issues#1141]
Check this Thunkable message board thread for additional details:
https://community.thunkable.com/t/any-component-create-block-suddenly-bugged/1853795

### Platform
Running on Live preview or Thunkable iOS.

### Steps to Reproduce
See this app example: https://x.thunkable.com/copy/07a207e1eea97bbb3f76995e3c6b0e24

Any creating of "any component" components.

### Expected Behavior
Components are made!

### Actual Behavior
An app crash.

### Project Link
https://x.thunkable.com/copy/07a207e1eea97bbb3f76995e3c6b0e24
https://x.thunkable.com/projects/626986451eaf5c0012d5a2cd/87f96793-23e5-4692-b550-4550e100df59/designer

###Community Link
https://community.thunkable.com/t/any-component-create-block-suddenly-bugged/1853795

**Comment by jaredgibb** [comment]
This has been resolved! :)
