### ISSUE TITLE
Disable visual group click effect

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#1142]
**Is your feature request related to a problem? Please describe.**
Groups are useful for organizing components on a screen. But they have a default click/tap effect where the group flashes. This doesn't always look that good and it can be confusing to the user to see a click effect where there is no obvious action to take (and no programmed action either in many cases).

**Describe the solution you'd like**
It should be possible to disable the visual click effect for a group.

**Describe alternatives you've considered**
I haven't figured out any way to remove or hide that effect.

**Which platform are you asking for?**
Thunkable X

**Additional context**

**Comment by jaredgibb** [comment]
We have identified this as an issue and I have escalated this internally.

I will update as I learn more.
