### ISSUE TITLE
(Thunkable X) Background images are not displayed when BackgroundPictureResizeMode = Center

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#115]
In a app by reference, open the "Check bugs" screen on iOS 12.0.1.  Under the label "No images in the elements below" there is a button and a column in which the background image should be displayed, but nothing is shown (empty frames). On iOS 10.3  and Android 7 background images are displayed.

https://x.thunkable.com/projects/5be813b36245ad2916513266/project/properties/designer/

**Comment by mark-friedman** [comment]
FWIW, it works fine on iOS 12.1, so perhaps this will just fix itself over time as phones update.

**Comment by AlexITMan** [comment]
I updated the iPhone6 to iOS 12.1, but the background images did not appear.

**Comment by jane-d-alt** [comment]
This behavior is resolved on iOS 14 devices. Please re-open if seen again.
