### ISSUE TITLE
(Thunkable X) The app variable is not initialized.

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#116]
On the scrTitle screen, the global variable app.listPicker is initialized.  Run the project and go to the Pickers screen.  When you open this screen, this variable is assigned to the middle button.Text, but instead of "List picker (universal)", the button does not display anything (iOS) or any service symbol (Android).

https://x.thunkable.com/projects/5be813b36245ad2916513266/project/properties/designer/

**Comment by mark-friedman** [comment]
At the end of your `'when scrTitle Starts'` block you are setting `app.listPicker`:
![screen shot 2018-11-16 at 4 34 41 pm](https://user-images.githubusercontent.com/1743690/48653948-a7511600-e9bd-11e8-9c8c-e597fca8a054.png)

That is overwriting your initialization of `app.listPicker`.

-Mark
