### ISSUE TITLE
Refresh Block of Data List Viewer crashes the app

### ISSUE THREAD

**Issue by JiGentick** [thunkable/thunkable-issues#1161]
### Platform
Refresh Block of the Data List Viewer - crashes on Android

### Steps to Reproduce
1. Local DB
2. Data List Viewer showing the values of the table.
3. Call Refresh Block to refresh the list viewed on the app when creating, updating and or deleting a row in the Local DB

### Expected Behavior
Refresh the list viewed on the app when creating, updating and or deleting a row in the Local DB.

### Actual Behavior
Crashes the app in Live test.

### Project Link
https://x.thunkable.com/copy/99fb292e691d3949a96e371545585f55

```
![image](https://user-images.githubusercontent.com/106071274/184600412-7a2afd57-854d-49cf-969b-10458b896afe.png)
![WhatsApp Image 2022-08-15 at 10 12 34 AM (1)](https://user-images.githubusercontent.com/106071274/184600529-7ea8b5fb-2418-4187-96c4-95ea3e9189e7.jpeg)

```

**Comment by jaredgibb** [comment]
Thanks for the info. I have filed this as a bug and you can follow along here
https://community.thunkable.com/t/data-viewer-crashes-app-when-refreshed-aug-2022/1996700/29
