### ISSUE TITLE
Web View with an upload button failed

### ISSUE THREAD

**Issue by bdbais** [thunkable/thunkable-issues#117]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
X but all with same problem

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
My test

### Steps to Reproduce
1. Create webview
2. Use webview with a site where you must to send a file/image
3. push upload button (no explorer / sharing windows appears)

### Expected Behavior
What did you expect to happen?
Open file / images selection to send a file / image to site.

### Actual Behavior
What actually happens?
```
Button change color (so it's clicked event caught) but upload explorer file doesn't appear.
```

**Comment by AlexITMan** [comment]
View file selection screen of File viewer project 

https://x.thunkable.com/projects/5be813b36245ad2916513266/project/properties/designer/

Perhaps this example will help you in some way.

**Comment by jane-d-alt** [comment]
It is now possible to upload files to a website shown in a Web Viewer.
