### ISSUE TITLE
Error generating block and unconfiguration of the project

### ISSUE THREAD

**Issue by orobbson** [thunkable/thunkable-issues#118]
Olá, estou tentando criar meu projeto, já estou quase finalizando, na plataforma cruzada, contudo aparece a seguinte mensagem: “Erro interno ao gerar código para blocos
Por favor, notifique o suporte ao Thunkable. Você pode desfazer sua última alteração para evitar esse erro.”
Ao emular no celular, aparece o projeto todo desconfigurado agora.
Por favor, alguém poderia me ajudar. Agradeço desde já!

Hello, I’m trying to create my project, I’m almost finished, on the cross platform, however the following message appears: "Internal error generating code for blocks
Please notify Thunkable support. You can undo your last change to avoid this error. "
When emulating on the cell phone, the whole project appears unconfigured now.
Please, could anyone help me. Thanks in advance!

**Comment by mark-friedman** [comment]
@orobbson 

Sorry for the problem!

Could you please send us a share link to your project? [Here's how](https://docs.thunkable.com/thunkable-cross-platform/share).

Also, do you remember what the last block was that you tried to add?

And finally, have you tried "undo-ing" your last change as suggested by the error message?  If you still have your browser tab open for the project, are in the Blocks editor and haven't made any other changes to the blocks since the error message appeared, you can undo that last change by right-clicking in the Blocks editor and selecting undo.  If you have made some changes since the error message appeared you might still be able to get back to the state that you were in before the error by doing multiple undo's.

**Comment by orobbson** [comment]
I already undo the last action, but still the error continues. I can even build the code again, but the contents of the designer when emulated deconfigure. If there is no solution I believe I will have to start all over again.

**Comment by mark-friedman** [comment]
@orobbson 

Could you please send us a share link to your project? [Here's how](https://docs.thunkable.com/thunkable-cross-platform/share).

Also, do you remember what the block was that you added that led to the error message?

It might be too late but you could try additional undos until you get to a safe state of your blocks.

**Comment by orobbson** [comment]
The field of blocks was all broken and did not solve, I believe there is no way. Thank you anyway. Could you tell me what causes the Layout configuration error when emulating on the device?

**Comment by mark-friedman** [comment]
@orobbson 

What about my requests?  They could help up figure out what the problem is:

>Could you please send us a share link to your project? [Here's how](https://docs.thunkable.com/thunkable-cross-platform/share).
>
>Also, do you remember what the block was that you added that led to the error message?

**Comment by orobbson** [comment]
Thanks for the help, but it is because I tried to insert a block of stop when clicking the button, it was at that moment that gave the problem, I already undid the action, but it did not solve. Actually I pressed the undo button several times, when updating the page vi that ended deleting all the blocks created, I will try to do them again. I just hope you do not misconfigure the dimensions in the Layout by emulating Live on the device.

**Comment by mark-friedman** [comment]
@orobbson 

> I tried to insert a block of stop when clicking the button

What do you mean by "a block of stop"?  Can you attach a screenshot of that block?

> I just hope you do not misconfigure the dimensions in the Layout by emulating Live on the device.

I'm not sure what you mean by the above.

**Comment by orobbson** [comment]
When I mentioned stopping, it would be an Exit application button.
When I mentioned to unconfigure the Layout, I wanted to inform that the desing built in the platform is no longer the same one that appears on the device, the dimensions of the images and texts were not changed, but when I emulated after the error in the block, the dimensions of the Desing elements were all changed only on the device when emulated, but on the platform the location and sizes are correct because I have not changed them.When I mentioned stopping, it would be an Exit application button.
When I mentioned to unconfigure the Layout, I wanted to inform that the desing built in the platform is no longer the same one that appears on the device, the dimensions of the images and texts were not changed, but when I emulated after the error in the block, the dimensions of the Desing elements were all changed only on the device when emulated, but on the platform the location and sizes are correct because I have not changed them.

**Comment by mark-friedman** [comment]
@orobbson 

As far as I know we don't have an "Exit application" block.  Can you attach a screenshot of the block that you were adding when you received the error?

Also, could you please send us a share link to your project? [Here's how](https://docs.thunkable.com/thunkable-cross-platform/share).

**Comment by orobbson** [comment]
Actually I noticed that I was looking for the "close application" functionality that is in the Thunkable Classic, there is really no cross platform. It must have been some block I inserted wrong. Unfortunately, I will not be able to send a photo or share the project, I've deleted it and I'm creating another one again.
Thank you in advance for your commitment to help me. I hope there will be no further problems.
Taking advantage of the chat space, is there something like Close Application on the cross platform?

**Comment by mark-friedman** [comment]
> is there something like Close Application on the cross platform?

There is no such block.  It seems like most modern apps just let the user close apps using their devices' general exit and kill gestures rather than having a "quit" button or menu item within the app itself.

**Comment by orobbson** [comment]
Thank you!

**Comment by jane-d-alt** [comment]
Hi @orobbson,

Since this is an older GitHub entry, I am going to delete it. There have been several updates to Thunkable blocks since November 2018!
Please get in touch with us or post in the Thunkable Community if you experience any future issues with blocks.
