### ISSUE TITLE
Tab Navigators

### ISSUE THREAD

**Issue by rojoredrouge12** [thunkable/thunkable-issues#119]
### Steps to Reproduce

1. Added bottom tab navigator
2. Disabled visibility of the navigator
3. I didn´t obtain the result that I wanted, so I deleted the tab navigator component
4. Added a Top tab navigator
5. Live app on android crashed
6. Reinstall the app
7. The navigator didn´t showed up neither on android nor iOS live app. And I didn´t find any visibility option for the top navigator.
8. Deleted top navigator
9. Added the bottom navigator
10. Noticed that the visibility option was still disabled, so I enabled it
11. Deleted the bottom navigator
12. Added once again the top navigator
13. Everything was ok, the navgator dis show up this time.

### Expected Behavior
I expected that even though I disabled visibility on the bottom navigator, that wouldn´t be a problem or it wouldn´t remain disabled in the top navigator, or at least I´d have the option to re-enable visibility in the top navigator properties

### Actual Behavior
Visibility options of the bottom navigator also apply to the top navigator even though the bottom navigator component was already deleted.

**Comment by jane-d-alt** [comment]
Thunkable X now has a block to [toggle the Drawer Navigator.](https://docs.thunkable.com/release-notes#jun-24-2019)
