### ISSUE TITLE
Landscape or portrait mode (ThunkableX)

### ISSUE THREAD

**Issue by dbantonio** [thunkable/thunkable-issues#12]
In the classic version of Thunkable there is the Landscape or portrait option. In the X version it is not present. Can this option be added?

I think it's an option that serves many people.

Thanks.

**Comment by ytknows** [comment]
Would love to see this option in an upcoming release; several of my app designs are not flexible enough to accommodate both landscape and portrait.

**Comment by jane-d-alt** [comment]
Support for setting screens to portrait, landscape and 'auto' orientation was introduced in July 2020. You can find this option at the bottom of your Screen's settings panel. https://docs.thunkable.com/screen#set-orientation
