### ISSUE TITLE
Support for push notifications

### ISSUE THREAD

**Issue by git-naren** [thunkable/thunkable-issues#120]
**Is your feature request related to a problem? Please describe.**
As a pro feature, thunkable x should support the push notifications, this will be very much useful to develop full fledged mobile apps

**Describe the solution you'd like**
Looking for push notifications 

**Describe alternatives you've considered**
Go for native app development

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by jane-d-alt** [comment]
Thunkable X now supports [Push Notifications.](https://docs.thunkable.com/push-notifications-by-one-signal)
