### ISSUE TITLE
naming a button with a hash character bugs out the editor

### ISSUE THREAD

**Issue by grahampcharles** [thunkable/thunkable-issues#121]
If you rename a button with a # character (mine was btn#), you'll confuse the URL scheme such that you'll jump into the blocks panel and not be able to do anything there. The only recourse is to browser-back and delete the button.

The # character should be disallowed from object names.

**Comment by jane-d-alt** [comment]
This behavior has been resolved. URLs now refer to UUIDs of components, not names.
