### ISSUE TITLE
Updating/Getting Current URL Address from Webviewer in Thunkable X while webviewer address is changing

### ISSUE THREAD

**Issue by khaledmustafa2018** [thunkable/thunkable-issues#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by khaledmustafa2018** [comment]
In thunkable X when we request get address of a webviewer it just giving the initial assigned address not the current opened ,
I think it could be done but thunkable developer since it is existing in thunkable classic version

**Comment by jane-d-alt** [comment]
This is now how the 'get current URL' block works. We'll close this issue now; apologies for not following up when this feature was first added to the platform.
