### ISSUE TITLE
APK Installation not working

### ISSUE THREAD

**Issue by autunwahid** [thunkable/thunkable-issues#123]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for ✕ Android companion?

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. I downloaded but couldn't install on my android 9 & 8.1 mobiles.
2. Then, I edited again and next versions also can't be installed.
3. it shows when try to install: 'there was a problem parsing the package'.

### Expected Behavior
What did you expect to happen?
I thought it would install instantly.

### Actual Behavior
What actually happens?
But it doesn't.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jane-d-alt** [comment]
Probably due to package name; this type of error is best reported to the Creator Success team or in the community
