### ISSUE TITLE
App Download Error: Not Found

### ISSUE THREAD

**Issue by navneetsinghal1** [thunkable/thunkable-issues#126]
Unable to delete 1 sound file.

https://x.thunkable.com/projectPage/5c0d34397cf5ca4c6b0042b0 

Due to this I think the project is unable to download, build iOS, copy and share link. Nothing is working.

### Platform
✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
My own project

### Steps to Reproduce
1. Just click download
2. Click copy
3.

### Expected Behavior
I expect it to download APK

### Actual Behavior
Not found error
```
  STACK TRACE AND/OR SCREENSHOTS
```
![1](https://user-images.githubusercontent.com/46914865/51517738-c5197c00-1e41-11e9-8272-4d3ce6f1ff39.png)

**Comment by jane-d-alt** [comment]
Hi @navneetsinghal1, it seems that the issue with this project is that it has an invalid Android Version Name. Try entering a value into this field in the App Settings menu.
I am going to close this GitHub entry. Please email me at jane@thunkable.com if you have further questions about this issue.
