### ISSUE TITLE
support landscape on iOS (Thunkable X)

### ISSUE THREAD

**Issue by grahampcharles** [thunkable/thunkable-issues#127]
Applications do not go into landscape mode when an iOS device is rotated.

They should, as this is a feature of mobile devices that users expect. 

Using a "Rotate" transform on a Screen object is not a reasonable solution, as the device will still have its system icons (and the time, etc.) in the correct position for portrait mode. In addition, this approach would require some component to "detect" the device orientation and then apply the Rotate transform.

Thunkable ✕ (x.thunkable.com)

Here is a simple app; it will not rotate on an iOS device:

https://x.thunkable.com/copy/ea05c3f4d5337d3a32b0b940d77734c3

**Comment by jane-d-alt** [comment]
landscape is now supported on iOS. We'll close this issue; apologies for not following up when this feature was originally added to the platform.
