### ISSUE TITLE
Strange behavior of list indices

### ISSUE THREAD

**Issue by guidolang** [thunkable/thunkable-issues#128]
There appears to be a bug in the “in list get #” block when used in combination with a list viewer. I’ve created a simple app to demo the bug at [https://x.thunkable.com/copy/aeb9a9da63b58cffe82a2b4a9464fde5](https://x.thunkable.com/copy/aeb9a9da63b58cffe82a2b4a9464fde5)

### Platform
✕

### Steps to Reproduce
1. Make a copy of the demo app.
2. Open Screen2 in the block view.
3. Live test the app. Notice that whichever list item you select on Screen1, the corresponding list item is displayed on Screen2.
4. Open Screen1 in the block view.
5. Live test the app. Notice that whichever list item you select on Screen1, the incorrect list item is displayed on Screen2 (shifted by index + 1).

**Comment by mark-friedman** [comment]
@guidolang Thanks for the bug report and the simple, easy to reproduce test project!  We'll look into the issue.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved.
