### ISSUE TITLE
Web API headers

### ISSUE THREAD

**Issue by lflfm** [thunkable/thunkable-issues#131]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to set headers via block code, this is absolutely required for many REST servers that take API keys and authentication tokens via headers.

**Describe the solution you'd like**
We need a block to set the WebAPI headers. The tricky thing about this is that it can raise some concerns like:
1. Should the block take a single string that the user will have to format himself or a list of user-formatted strings or a list of lists with the value pairs?
-> I would recommend that a second block type be created "key-value pair" block and then the WebAPI set header block will take a list of key-value pairs
2. When setting the headers via blocks, will they replace the component's properties or be appended?
-> I would recommend that they replace them

**Describe alternatives you've considered**
There aren't really any alternatives; if the user doesn't have control over the target server, then there's nothing they can do. If they have control, then they could change the server code to take the values via body or query params, but this is a dirty workaround to something that's a clear fault of Thunkable.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
This proposed key-value pair block would be generic and would probably be useful in many other places...

**Comment by jane-d-alt** [comment]
Thunkable X now supports adding [headers and query parameters](https://docs.thunkable.com/web-api) via blocks.
