### ISSUE TITLE
Admob Ads (Interstitial, Banner and Native) in Thunkable X

### ISSUE THREAD

**Issue by gulwaseem35** [thunkable/thunkable-issues#134]
I am working on a Project but there is no way to monetize it (Other than direct sales) So I want Thunkable team to bring Admob Ads feature in Thunkable X.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
Thunkable X supports AdMob now.
