### ISSUE TITLE
Changes to LocalDB using SetCell method are not persistent

### ISSUE THREAD

**Issue by bhontz** [thunkable/thunkable-issues#135]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thunkable X

### Issue/Request Origin
Posted this to the community on Feb07, a community member validated (replicated) on Android (I'm using iOS) and asked that I post the bug.

### Steps to Reproduce
1. Add a LocalDB to a project, and using the "Edit" link exposed within the Design mode for the LocalDB, enter a number (say 10) of placeholder records.  I used two fields but I suspect this doesn't matter.
2. Create an app that will use the SetCell method to change the values of the these 10 records, and additionally be sure that your app can view (i.e. expose through a Label control for example) the values that you're changing.  Operationally verify that you can change the LocaDB records using the SetCell method and see them within your app's session.
3. Quit completely out of the Thunkable X phone app, then relaunch the app.

### Expected Behavior
Expected the data changed in step 2 above using the SetCell method to remain (i.e. be persistent) between usages of the phone app.  

### Actual Behavior
Any changes made to the LocalDB using method SetCell appear only within the current session of the phone app and are not persistent between phone app sessions.

**Comment by mark-friedman** [comment]
Thanks, @bhontz!  We are planning to add persistency (and a bunch of other enhancements) to the LocalDB component in the future.

**Comment by mark-friedman** [comment]
As far as I know this issue is still there.

**Comment by bhontz** [comment]
apologies for closing, I was just adding another issue and noted this one
was still open.

**Comment by jane-d-alt** [comment]
Data saved to a local DB is not persistent.

To save data persistently you can:
use stored variables https://docs.thunkable.com/variables#stored-variables
use a local table as a Data Source: https://docs.thunkable.com/data-sources
