### ISSUE TITLE
Realtime db DataChange block KEY parameter is uneditable

### ISSUE THREAD

**Issue by bhontz** [thunkable/thunkable-issues#137]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by bhontz** [comment]
Platform: Thunkable X

Experienced this myself, reported to the community

Steps to Reproduce:
1) Open a new Thunkable X project
2) Add the Realtime DB invisible component
3) Drag the Realtime DB's DataChange block onto your screen
4) Try to replace the Key parameter of this block with a text block (i.e. to identify the key)

Expected behavior:
I would expect the ability to add a key value.  If you have more than one listener on a screen they need to have separate key values (right?)

Actual behavior:
The UI starts flashing and will not accept the text block drug over top of the key parameter.  A number of disabled blocks are left on the screen, and deleting any of these blocks just seems to propogate another one.

**Comment by mark-friedman** [comment]
@bhontz I'm sorry that our [documentation for the RealtimeDB component](https://docs.thunkable.com/thunkable-cross-platform/create/components/data/realtime-db) is unclear.  The way to listen for changes to more than one key is to add more `AddListener` blocks (see [here](https://docs.thunkable.com/thunkable-cross-platform/create/components/data/realtime-db#update-data-in-real-time)).  The  `key` block attached to the `DataChanged` block is to identify which key has been changed.  The idea is that you have a single `DataChanged` block and within that block you check the `key` value (e.g. by dragging it out and putting it into an `if` block) and do whatever logic you need to do for each key change.
