### ISSUE TITLE
Thunkable X android's webview is NOT letting images/videos/files upload to the sites just like any other web browser

### ISSUE THREAD

**Issue by hskit** [thunkable/thunkable-issues#138]
### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

✕ Android companion, but **I am pretty sure it's going be in all the android platforms**

### Steps to Reproduce

**Please check my shared link to access the test app at the bottom of this request.** 

1. Login to your facebook account through the app.
2. Try to upload your image/video using the app like you normally do on the facebook. 
3. Now you will notice that the upload button on the facebook, isn't opening the android's local phone storage. 

### Expected Behavior
Must allow the user to upload files through the thunkable webview, **just like any other web browser.** 

### Actual Behavior
When you click on the upload button on the facebook page to upload, the click event happens, but action doesn't complete as it should ( Open the the android's gallery to select image/video  )

### My Opinion and thoughts on the issue

I am assuming, thunkable webview is missing any of the below permissions to open the local storage of the android phones. 

uses-permission android:name="android.permission.INTERNET" 
uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" 
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" 
uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 

It used to work, but maybe now it's conflicting with all these new updates or **the android has updated some core webview features, which needs to be updated in the thunkable platform**.  

```
  STACK TRACE AND/OR SCREENSHOTS
```
Extremely simple testing app. Just open and follow the normal procedure to upload your image on Facebook using the app. If you like you can even change the URL to any other site such as instagram or anything you like where you can find an upload option. 

https://x.thunkable.com/copy/ebd11b3dd60689eceb4b23c91d9ba701

This is a **very important thing for any thunkable  webview app** where user has to upload some sort of file/image/video using the app. I am sure it will be a very easy fix for the thunkable developers from the backend.  Please do let me know if you have any questions.

Thanks in advanced and happy thunking :)
hskit

**Comment by hskit** [comment]
Hello any updates on the above errors ???

After doing an extensive research, I have found out that errors are in the react-native framework, which is the core language of thunkable. React-native has updated core webview files, which also needs to be updated in thunkable. Please have a look at the link below. 

https://github.com/react-native-community/react-native-webview

https://github.com/andreipfeiffer/react-native-webview-android-file-upload

Please let me know as this issue is very important and should be fix. 

Thanks in advanced and happy thunking
hskit.

**Comment by mark-friedman** [comment]
We certainly are planning to incorporate react-native-webview.  However, I'm not entirely convinced that that will be sufficient to enable file uploads in a way that it useful within Thunkable ✕.  We'll see.

**Comment by hskit** [comment]
Hi mark, 

If I understood you correct, then thunkable currently doesn't use react-native-webview, instead it has its own custom webview component, right ? 

If that's the case, then bug is in the thunkable's webview because **I have made an app few months ago on thunkable X, which also uses the webview. That app perfectly works fine and is able to upload files via the webview.** 

I am little bit confused with your word "Enable". Are you saying that "File upload via Webview" has been **disabled by thunkable** purposely and it's not the bug ? Please elaborate that part. 

Thanks in advanced and happy thunking
hskit.

**Comment by mark-friedman** [comment]
@hskit I think you misunderstood me.  We import the standard WebView component of React Native, which has been pulled out into the separate react-native-webview package.  What we haven't yet done is move toward importing WebView from that react-native-webview package rather than the standard react-native package.

**Comment by mark-friedman** [comment]
@hskit By "enable" above, I am just saying that in addition to whatever standard file upload behavior is provided by react-native-webview, we might want/need to do additional work to make that support maximally useful to Thunkable ✕ users.  For example, we would want to make sure that photos uploaded via a WebView were available to be be used as the `Picture` property in our Image component.

**Comment by jane-d-alt** [comment]
It is now possible to upload files to a website shown in a Web Viewer.
