### ISSUE TITLE
Can't remix a specific project (link included within)

### ISSUE THREAD

**Issue by bhontz** [thunkable/thunkable-issues#140]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thunkable X  (I'm working on a MacOSX / Safari laptop and using an iPhone 7)

### Issue/Request Origin
I am a mentor for a [Technovation Challenge](https://technovationchallenge.org) team.   

The team has asked me to assist with a coding challenge and I am unable to remix their app; I'm receiving a "Save remix error" dialog with additional text Problem communicating with the server.  HTTP status: 500, server message:

(there is no further message beyond the above).  The dialog has a "X" to dismiss it in the upper right corner.

Within a few weeks the team will need to submit their app for judging.  I am concerned that judges will not be able to interact with the app if it can not be saved.   

I have submitted this issue to the Thunkable X community a few days ago; I had one reply from a community member indicating that they could replicate the problem.

### Steps to Reproduce
Try to remix this project:
https://x.thunkable.com/projects/5bcd159416e056ddc91447a3/Screen1/designer

### Expected Behavior
I would expect the ability to save (remix) the project.  

### Actual Behavior
The project opens in my browser, I can view the design and blocks, I can live test it on my phone, but I can't make changes to anything or see it within the list of my other (9) projects.

Thank you in advance for assisting!  

One potential "clue" I will offer.  This project has a large number of HTML files saved within it; part of the app is a recipe viewer and the team is using the web viewer component and saved HTML files to accomplish their design.  This is the only thing I can think of that might make this specific project out of the ordinary.

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
@bhontz This was due to internal error that we believe we have fixed.  Please reload that app and try again.  If you still have a problem please re-open this issue.

**Comment by bhontz** [comment]
Thanks so much!!!
