### ISSUE TITLE
A voice/sound recorder on Thunkable X

### ISSUE THREAD

**Issue by kindafree** [thunkable/thunkable-issues#141]
A voice/sound recorder on Thunkable X that can save the recorded audio file to local storage; something very identical to iPhone's "Voice Memos" app. Would be nice to have an immediate playback option so that unwanted recordings that can be thrown out as well.

**Comment by jane-d-alt** [comment]
Thunkable now has an Audio Recorder component: https://docs.thunkable.com/audio-recorder
