### ISSUE TITLE
Handler for exiting the app

### ISSUE THREAD

**Issue by ritvik0611** [thunkable/thunkable-issues#144]
A feature that enables the app to delete cache data stored locally or within the app is required in Thunkable X. This may be achieved through the use of a handler for when the app is voluntarily or involuntarily quit or the phone dies down. This is essential for ensuring that the data records inputted by the user are deleted as soon as a session ends. Hope this is considered seriously. Thank you!

**Comment by jane-d-alt** [comment]
Hi there,

If you want data to not be saved between app sessions, you can use app variables or the Local DB component. These components do not save data outside of the app session. Thanks!
