### ISSUE TITLE
Adds the option: when you click to the lottie

### ISSUE THREAD

**Issue by tomer2526** [thunkable/thunkable-issues#148]
I will be happy if you can add the option when you click to lotie component

**Comment by AlexITMan** [comment]
You can click on the lotie to do this: place the full width of the Column lottie and the transparent button above it using absolute positioning. After that, add the necessary blocks to the button event handler.

**Comment by tomer2526** [comment]
Thanks for the advice 😃, (the truth is I've already done it😅), but you still have to add that option.

**Comment by jane-d-alt** [comment]
Thunkable now has a 'when Animation Click' block. We'll close this request; apologies for not following up when this feature was originally added.
