### ISSUE TITLE
app crash when set  visible column true or false

### ISSUE THREAD

**Issue by ygorbittencourt** [thunkable/thunkable-issues#149]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
 ✕ Android companion And ✕ iOS companion?

### Issue/Request Origin
In my App

### Steps to Reproduce
Dear Sirs, I need a lot of help.

Until yesterday my application was working very well.Today in the morning when opening the application it is locking in loop. I made a debug and found that just setting up visible column or not breaking the application. I think it's a bug. Can you help me please ? This application is very important to me.

The application link is: https://x.thunkable.com/copy/7245a0b45b0f279d0907730433b6d00e

The configuration code requested in the application is: FAB01

### Expected Behavior
What did you expect to happen?

### Actual Behavior
start working normally again.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
@ygorbittencourt What exactly do you mean by: 

> I made a debug and found that just setting up visible column or not breaking the application

**Comment by ygorbittencourt** [comment]
If you verify the copy that I sent in the link will verify that the
application breaks when I configure the property of the column. It's just
you see in the project that I sent. This is just a part of the project that
I uploaded to you, with only 1 screen to show the behavior of the app, I
can not miss this project, originally with several screens and is already
finished.
I do not know why this is happening, everything was normal until yesterday
The application link is:
https://x.thunkable.com/copy/7245a0b45b0f279d0907730433b6d00e

Em qua, 10 de abr de 2019 às 13:39, mark-friedman <notifications@github.com>
escreveu:

**Comment by ygorbittencourt** [comment]
the application continues with the same problem reported

**Comment by ygorbittencourt** [comment]
@mark-friedman , 
Did you take a look at the project? Did you see the screen breaking?
I need every possible help, the original project has several screens and is at the end

**Comment by mark-friedman** [comment]
@ygorbittencourt, We're looking at it.

**Comment by ygorbittencourt** [comment]
ohh God, thanks friend for the help.

If you need to, I can send the full application link, I noticed that
several screens are breaking, when I use local_db as well. Thank you.

Em qua, 10 de abr de 2019 às 15:12, mark-friedman <notifications@github.com>
escreveu:

**Comment by mark-friedman** [comment]
@ygorbittencourt I think we know the general causes of the problem and are working on figuring out the details and coming up with a fix.

**Comment by ygorbittencourt** [comment]
Friend when you fix this, will you correct it on the platform or just in
that application of the link that I sent as an example? If it is only in
the link I need to send the link of the original application, which has
many more screens than the one there that sends the link.

I hope in the future to be able to contribute more with you, thunkable is a
formidable platform.

Many, many thanks for your help.

Em qua, 10 de abr de 2019 às 15:26, mark-friedman <notifications@github.com>
escreveu:

**Comment by mark-friedman** [comment]
@ygorbittencourt It will be fixed on the platform.  A bunch of other users have discovered similar issues.

**Comment by ygorbittencourt** [comment]
Hello @mark-friedman , good morning to you and your entire team!

I saw that IDE's look changed for the better, I loved it.
Sorry for bothering my friend, do you have any news, or any timeframe for the platform to work normally again? I am eager to program my application again.

I need to present this application "which is a prototype" to a prospective investor in 2 weeks. I spent my last 4 weeks working on this application. Is there any way I can make the application work again by making changes to my code? Any kind of adaptation?

Thank you very much for your attention and help.

**Comment by mark-friedman** [comment]
@ygorbittencourt I believe that we have fixed the problem on the platform.  To get it to take effect, you should make a trivial change to your blocks (e.g. just move one), force quit your Thunkable Live app and then restart it.

**Comment by ygorbittencourt** [comment]
@mark-friedman , Thank you very much for fix the problem, you and your team work hard and are incredible.

I do not know if it has a connection with the resolution of the problem but a new problem has arisen. The line break has stopped working, I've always done using firebase, and it's not working at all.
Do I need to open another issue here in the GIT or is the line break problem linked to this fix?

**Comment by mark-friedman** [comment]
@ygorbittencourt Is the line break working in `label15` or is it failing in both `label15` and `label14`?  Also can you try setting another pair of labels to the value of the `error` block from the call to `Realtime_DB1.Get`.

**Comment by mark-friedman** [comment]
Also, I might suggest bringing up these sorts of errors in the Thunkable Community or via the chatbox (in the lower right corner of our web app). This GitHub issues list is generally for less urgent matters.

**Comment by ygorbittencourt** [comment]
> @ygorbittencourt Is the line break working in `label15` or is it failing in both `label15` and `label14`? Also can you try setting another pair of labels to the value of the `error` block from the call to `Realtime_DB1.Get`.

About Labels, Until Tuesday everything was working, the fourth began to break. Now this problem of the label, as I sent in the image, the label is not breaking in any way. I did what you said and the error output is "undefined", I noticed that the firebase data change function also is not working as it should. a lot right now.

**Comment by mark-friedman** [comment]
@ygorbittencourt May I ask again: Is the line break working in `label15` or is it failing in both `label15` and `label14`?  Also, is the `error` value "undefined" for both `Realtime_DB1.Get` blocks?

**Comment by ygorbittencourt** [comment]
@mark-friedman  failing in both label15 and label14. 
The label is not breaking in any way.

**Comment by mark-friedman** [comment]
@ygorbittencourt, Thanks for the clarification.  Do other attempts to get data from Realtime_DB1 work for you?  Also, can you send me a link to your project?

**Comment by ygorbittencourt** [comment]
> @ygorbittencourt, Thanks for the clarification. Do other attempts to get data from Realtime_DB1 work for you? Also, can you send me a link to your project?

Yes @mark-friedman  I can help more but now it's time to go home.
Tomorrow we continue, it will be a pleasure to contribute with you. I'll map all the errors and inform you tomorrow morning ok. Is there another way I can send you the project link? I would not want to make it public in GIT.  thank you very much.

**Comment by mark-friedman** [comment]
>Is there another way I can send you the project link?

You can DM me in the [community site](https://community.thunkable.com/c/thunkable-cross), where I am simply 'Mark'.

**Comment by ygorbittencourt** [comment]
@mark-friedman , my apologies, a lot apologies, there was a big mistake. When you upgraded the platform all access data from the firebase API has been cleared from the properties palette. So for this reason nothing was working connected to the firebase, including the line break. The tiredness may have fooled my eyes initially, but now I found it more calmly. A lot of people can report problems and this could be the cause. Either way is learning. Thank you again for all your attention. I will sign the annual plan of the tool, if in any other way I can contribute with you in the future please do not hesitate to contact. My root skills are in infrastructure and data security.

**Comment by mark-friedman** [comment]
@ygorbittencourt No need to apologize.

**Comment by mark-friedman** [comment]
By the way, is it possible that the project that didn't contain the Firebase API settings was actually a copy of a project that did contain them?  We currently don't copy those setting over when we make a copy (although perhaps we should).  We haven't heard from anyone else (yet) having any issues with the settings disappearing after the recent upgrade, so I'm not sure that that was the issue.  We'll keep on the lookout, though, just in case.
