### ISSUE TITLE
Issue #140 (remix error) seems to be broken once again

### ISSUE THREAD

**Issue by bhontz** [thunkable/thunkable-issues#150]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thunkable X

### Issue/Request Origin
Reported on the community initially 20 days back.  Then I posted here as a bug (issue #140).  I had a reply that it was fixed and the issue was closed.  (It did work after the fix).  I have since need to remix a similar (updated version of the project from the team I'm mentoring) and I am experience the identical problem (remix error) that is explained in closed issue #140.

### Steps to Reproduce
1. try to remix this project:  https://x.thunkable.com/projects/5bcd159416e056ddc91447a3/Screen1/designer 
2. 
3.

### Expected Behavior
I would like to be able to save this project which has been shared to me by the team I'm mentoring.

### Actual Behavior
I get a "Save remix error" dialog
```
  STACK TRACE AND/OR SCREENSHOTS
Please see closed issue #140 for a screenshot of the error dialog

**Comment by mark-friedman** [comment]
@bhontz Once again, sorry for the problem.  I believe that we've fixed this for your project.  Could you please try again?

Also, I might suggest bringing up these sorts of errors in the Thunkable Community or via the chatbox (in the lower right corner of our web app).  This GitHub issues list is generally for less urgent matters.

**Comment by bhontz** [comment]
Yep, all fixed!  Thank you Mark!
