### ISSUE TITLE
RTL support does not work on IOS (it works only on Android)

### ISSUE THREAD

**Issue by tomer2526** [thunkable/thunkable-issues#151]
RTL support does not work on IOS (it works only on Android)
Here are some examples of RTL tests: https://x.thunkable.com/copy/b76783391d4035339dd92f64d9a1ab2b

**Comment by mark-friedman** [comment]
@tomer2526 As a workaround, at least for Label components, set the `WritingDirection` property under the 'Text Style' section of the Advanced properties.

**Comment by tomer2526** [comment]
It works. But if the English text is also will be from right to left (even if it is on auto mode)

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved. @tomer2526, please get in contact if you experience further issues relating to this.
