### ISSUE TITLE
New obfuscated text block in Thunkable X

### ISSUE THREAD

**Issue by 10MINT** [thunkable/thunkable-issues#153]
**Is your feature request related to a problem? Please describe.**
If I want to make an application with the Web API component and I set my project to public, my secret keys might get abused

**Describe the solution you'd like**
The block should work like the obfuscated text block from Thunkable Classic, plus the text in the block will be emptied if you share your project. 

**Describe alternatives you've considered**
I am aware that this can be abused to make a non-pro user's project unusable for others, but I can't think of another solution

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
None

**Comment by mark-friedman** [comment]
This sounds reasonable.  Thanks!

**Comment by jane-d-alt** [comment]
Thunkable X now allows you to [obscure](https://docs.thunkable.com/text-input#set-up-for-passwords) the input typed into a Text Input.
