### ISSUE TITLE
IOS Vibration, and text speech events do not work when the application is in backgroud. Only works on Android.

### ISSUE THREAD

**Issue by ygorbittencourt** [thunkable/thunkable-issues#155]
### Platform
IOS, or ✕ iOS companion.

### Issue/Request Origin
My project

### Steps to Reproduce

![Erro1](https://user-images.githubusercontent.com/5061466/56805025-10a34380-67fe-11e9-967f-6e20cb5d432f.jpg)

### Expected Behavior
Vibration, and text speech when the application is in backgroud

### Actual Behavior
IOS Vibration, and text speech events do not work when the application is in backgroud. Only works on Android.
```
  STACK TRACE AND/OR SCREENSHOTS
```
Attached.

**Comment by ygorbittencourt** [comment]
PS:  Added correct image
![Erro2](https://user-images.githubusercontent.com/5061466/56805196-a2ab4c00-67fe-11e9-8cf6-10b11393b038.jpg)

**Comment by mark-friedman** [comment]
FWIW, I think that that fact that it works in the background at all is accidental.  We've not done the work yet to generally support background operation.

**Comment by ygorbittencourt** [comment]
Hi @mark-friedman.

Look on the good side, on Android is already working. Not work to do!
I understand, I will eagerly await the implementation on IOS in the Future, developers uses real-time features will lose advantage, after all, no App is in the foreground for long.

my friend, taking advantage of the opportunity to talking with you, how much time is left for a qrcode reader ? All projects needs It too.
