### ISSUE TITLE
Thunkable X Android DrawerNavigator's drawer titles/labels are truncated

### ISSUE THREAD

**Issue by andychin62** [thunkable/thunkable-issues#156]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thunkable X Android Live Test and downloaded .apk file.

### Issue/Request Origin
The Drawer Navigator's drawer titles/labels are truncated in Android (but not in iOS).
I experienced it myself while creating my app.

### Steps to Reproduce
Please see this app (Public) that I created to illustrate the issue.
https://x.thunkable.com/copy/21d538fe19adc56372e4990dbeef645d

### Expected Behavior
The drawer titles/labels must not be truncated. To work like in iOS.
(It's OK if need to set a limit e.g. 20 or 25 characters on the title/label length.)

### Actual Behavior
The drawer titles/labels are truncated.
```
  STACK TRACE AND/OR SCREENSHOTS
```
1) Thunkable X Live Test Android
![Screenshot_2019-04-19-12-48-21-50](https://user-images.githubusercontent.com/50279739/57186878-38d72480-6f19-11e9-960d-7ccce6675f55.png)

2) Thunkable X downloaded .apk file
![Screenshot_2019-04-19-12-54-12-15](https://user-images.githubusercontent.com/50279739/57186879-48ef0400-6f19-11e9-8eef-dd54357c0fa7.png)

3) Thunkable X iOS (No problems)
![IMG_0012](https://user-images.githubusercontent.com/50279739/57186897-953a4400-6f19-11e9-917a-f3b48ec4d9a2.PNG)

**Comment by mark-friedman** [comment]
Thanks, @andychin62.  We'll look into this.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved.
