### ISSUE TITLE
X WebViewer contents cannot scroll when Column is longer than physical screen on Android

### ISSUE THREAD

**Issue by andychin62** [thunkable/thunkable-issues#157]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
X Live Test Android and X downloaded .apk file.

### Issue/Request Origin
I experienced it myself while creating my app.

### Steps to Reproduce
Try/see Screen2 of this example app on Android ... and then try it on iOS.
https://x.thunkable.com/copy/31bf266a01ccae746fff5b5f8cf76e7d

(Please also see my post in the Thunkable Community https://community.thunkable.com/t/anomaly-between-live-test-android-and-live-test-ios/74864/6?u=andrew_chin )

### Expected Behavior
I expect the contents of the WebViewer to scroll on Android just like on iOS.

### Actual Behavior
The WebViewer cannot scroll.

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
Thanks for filing the bug report, @andychin62.  We'll check it out.

**Comment by jane-d-alt** [comment]
Hi there, apologies for not following up on this at the time, but the Web Viewer can now scroll as normal on Android. Thanks for reporting!
