### ISSUE TITLE
Uncaught Error: folly::toJson: JSON object value was a Nan or INF

### ISSUE THREAD

**Issue by CFjamesg** [thunkable/thunkable-issues#158]
### Platform
✕, completed APK (fine on iOS)

### Issue/Request Origin
Android app running on Galaxy Tab, running Android 5.1.1

### Steps to Reproduce
1. Download and install app on Android (https://x.thunkable.com/copy/ef1fbd3707c71830ea7cbb4d055efbb4)
2. Open app

### Expected Behavior
App to open on PIN Entry screen and allow PIN input

### Actual Behavior
App opens on PIN entry screen and then immediately crashes. This does not happen on iOS, where it works fine.

Error logs show 2 issues:
1. Uncaught Error: folly::toJson: JSON object value was a NaN or INF
2. Uncaught Error: Error calling RCTEventEmitter.receiveEvent

**Comment by mark-friedman** [comment]
@CFjamesg I replied to you via Intercom.  If you didn't get that message, let me know.

-Mark
