### ISSUE TITLE
Notifier

### ISSUE THREAD

**Issue by GOTFire** [thunkable/thunkable-issues#16]
We need Notifier for Thunkable X platform.

Multichoice notifier
Alert notifier
textinput notifier
Notifier with image
Notifier with progres bar

**Comment by mrching** [comment]
We have an Alert notifier that is almost ready for testing and should be available soon!

**Comment by mrching** [comment]
Our new Alert component is now available -- it supports the multichoice and alert notifier as specified above

More details here:
https://community.thunkable.com/t/thunkable-release-jul-20-alert-notifier-component/36804
