### ISSUE TITLE
App Crashes on Android (but not iOS) when coordinates added to map

### ISSUE THREAD

**Issue by KaneoheKid** [thunkable/thunkable-issues#161]
![Screenshot_ofErrorLog](https://user-images.githubusercontent.com/42430475/57965949-309ec200-78e7-11e9-8b9b-727d6a0fe1a6.png)

### Platform
 crash occurs with the  ✕ Android companion but NOT the    ✕ iOS companion?

### Issue/Request Origin
Identified while trying to develop an app.

### Steps to Reproduce
1.  for the project below, run in the iOS companion.  No problem, it starts and executes correctly.
2. try the same using an android companion, it crashes

https://x.thunkable.com/copy/42941d146565038a94fc233341469a0f
### Expected Behavior
clean execution, as with the iOS companion.

### Actual Behavior
crashes while trying to execute the "in Map1 call addMarker" block (android only).  However, if number blocks are used instead of "in list... get..." the marker is placed correctly with no crash in the android companion.

The crash in android occurs whether the map provider is google or left blank (Apple Maps).
```
  STACK TRACE AND/OR SCREENSHOTS
Screenshot of the error log is attached for reference.
```

**Comment by jane-d-alt** [comment]
Hi there,

Apologies for not following up when this behavior was originally resolved, but it has been resolved. See this demo app for an example of an app that can create a marker on a map using co-ordinates from a list: https://x.thunkable.com/projectPage/609d3cc9731ded0011def656/
