### ISSUE TITLE
Don`t download without pro version

### ISSUE THREAD

**Issue by zifirplay** [thunkable/thunkable-issues#164]
### Issue/Request Origin

i using the Thunkable and find this issue.
In code i don`t use a push notification
you can check it: https://x.thunkable.com/projects/5cf8dd613dbaa29f6cc7edfa/3963b3bc-b7c5-4477-94c9-eadfbb09a440/designer

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
Please fix this issue. 

### Actual Behavior
What actually happens?

I aded push notification and delete it. And i don`t can download my app because it requires pro versoin for push notification. I DON`T USE a push notification, it DELETED.

  STACK TRACE AND/OR SCREENSHOTS

  you can check it:     https://x.thunkable.com/projects/5cf8dd613dbaa29f6cc7edfa/3963b3bc-b7c5-4477-94c9-eadfbb09a440/designer

**Comment by mark-friedman** [comment]
@zifirplay, can you please verify that link to your project.  It doesn't appear to be a valid link.

**Comment by jane-d-alt** [comment]
@zifirplay as the project can't be accessed, this issue is being closed. Please contact the customer success team if you still experience this issue.

**Comment by zifirplay** [comment]
thank you


ср, 19 февр. 2020 г. в 18:04, jane-d-alt <notifications@github.com>:
