### ISSUE TITLE
after compiling and installing apk the application is slow

### ISSUE THREAD

**Issue by ExtremusDPS** [thunkable/thunkable-issues#165]
### Platform
 ✕, ✕ Android companion (APK compile only)

### Issue/Request Origin
I have a project that until yesterday was all ok.
Yesterday at the end of the afternoon I noticed that when I compile the app and install the APK the application gets slow. Image changes or webapi return are too slow the screen gets slow. inside the companion everything is ok, the application is fast, the problem only occurs when compiling and install the APK. The IOs version is OK too, the problem only shows up on android when the APK is installed.  I am PRO member, my application uses Ondesignal, firebase db, local db.  I tested it on another device and it continues to cause problems.
I removed the push notification function and the problem continued, I do not know what else to do.

### Steps to Reproduce
Entire app slow

### Expected Behavior
Run normally

### Actual Behavior
application is slow

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by ExtremusDPS** [comment]
update info: 
maybe it's some bug, other people are already commenting on this -> [https://community.thunkable.com/t/app-hanging-and-slowing-a-lot-after-apk-urgent/120323/3](https://community.thunkable.com/t/app-hanging-and-slowing-a-lot-after-apk-urgent/120323/3)

**Comment by jane-d-alt** [comment]
Issue was resolved at the time, further info available by following Community link. We'll close this issue; apologies for not following up when this behavior was originally resolved.
