### ISSUE TITLE
Lottie Bug

### ISSUE THREAD

**Issue by jane-d-alt** [thunkable/thunkable-issues#167]
[Thunkable X]

User reported an issue with Lottie, referencing a specific animation: https://community.thunkable.com/t/feature-requests/64316/5?u=jane

I tried making a minimal app with this animation and experienced the same behavior (app crashed).

I tried displaying a different random animation from Lottie in my app: https://lottiefiles.com/7192-404 and now the project can't be accessed - grey screen.

App link: https://x.thunkable.com/projects/5d16127d2300351ad2994dca/ef0a6f21-8d9a-43e4-9f7e-f42d295bd486/designer

**Comment by MrMazzone** [comment]
I am getting crashes on Android for projects with Lottie animation.  Immediately crashes on open.  The iOS Live app does not seem to have the issue.  Wondering if the issue above is the same I have been experiencing.

**Comment by mark-friedman** [comment]
Sorry to hear that, Joe. There is a known issue with certain Lottie animations on Android devices.  We're looking into potential solutions.

-Mark

**Comment by jane-d-alt** [comment]
This behavior was resolved shortly after reporting. We'll close this issue; apologies for not following up when this behavior was originally resolved.
