### ISSUE TITLE
Feature Request for Thunkable X

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#168]
I would love to have some of these features in thunkable x.

1. Access more devices security sensors, such as fingerprint or facial recognition, if applicable.
2. Video player. Be able to play files from a stream link, and is native to the app, so things like full screen work.
3. This is kind of the same as number 2, but I would like to be able to have full screen videos in web viewer, and to be able to actively monitor its current link, so if i click out of its set link onto a different web page, it will know that, and track it.
4. Animations for buttons and photos when a screen opens. Example. When i navigate to a new screen, the button will float up from the bottom, or fade in, etc. Same goes for photos.
5. Audio input, not just for text to speech, and get output.

6. This one is only an idea, and isn't something that we will probably see, but i thought i would share with you it.

What about the ability for 3rd parties to develop extensions for thunkable x? I know that thunkable currently owns the right to its code etc and may not want to share it. But this is how it could work:

The developer(s) would create the blocks to add as extensions, and ensure they work for cross platform. They can set a price for the plugins. To add a plugin to thunkable, it would simply connect with your account. This cuts out the user having to download the file, and it means that the developer knows their work will not be pirated etc. 

This also means that thunkable can moderate every plugin, as it must go through the system. So if a plugins seems malicious or broken, it can be removed, or not allowed. 

There could be a link through thunkables website, that had a massive directory of plugins, that are compatible with android and ios.

That is only a thought from me :)

I would really like for some of the items I mentioned in the first 5 points to be added though, that would be great!

Thank you for creating thunkable, I really enjoy it.

**Comment by mark-friedman** [comment]
@eoinparkinson Sorry to make more work for you 🤷‍♂  but could you please post each of these as separate feature request GitHub issues?  That would make them much easier to prioritize and track!

**Comment by eoinparkinson** [comment]
> @eoinparkinson Sorry to make more work for you 🤷‍♂ but could you please post each of these as separate feature request GitHub issues? That would make them much easier to prioritize and track!

Yeah sure, sorry about that.

**Comment by mark-friedman** [comment]
Closing this, since @eoinparkinson created individual issues!
