### ISSUE TITLE
Full screen videos in web viewer

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#171]
I would love to have this feature in thunkable x.
 
Be able to have full screen videos in web viewer, and to be able to actively monitor its current link, so if i click out of its set link onto a different web page, it will know that, and track it.

**Comment by jane-d-alt** [comment]
It is now possible to view a video in full screen with the Web Viewer component. We'll close this issue; apologies for not following up when this feature was originally added.
