### ISSUE TITLE
Audio input

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#173]
I would love to have this feature in thunkable x.

Audio input, not just for text to speech, and get output. This way users can do things like record audio. This would be great for making a music app. You could play instrument's over others or have the 1 vocalist harmonise their voice by making multiple recordings. Also to add to that, maybe have some way of adjust the audio output, like bass, treble? Although that wouldn't be a major concern. Just the ability to record audio and save it in a variable or stored variable would be cool.

**Comment by jane-d-alt** [comment]
Thunkable now has an audio recorder component: https://docs.thunkable.com/audio-recorder

We'll close this issue; apologies for not following up when this feature was originally added.
