### ISSUE TITLE
Platform speed

### ISSUE THREAD

**Issue by HayderAlLami** [thunkable/thunkable-issues#179]
Thunkable Cross platform has been too slow in Blocks area because the amount of blocks and components.
This leads Thunkers to leave their apps as they are because they cannot work on them smoothly and fast. To move or add blocks we must wait more than 10 seconds each time and that is too much.
The platform freezes for 10 seconds each time we want to update a single block.
I hope you can fix this so very big issue.
My regards!
Hayder

**Comment by AlexITMan** [comment]
This is indeed one of the major problems.

**Comment by eoinparkinson** [comment]
Yes this is a huge problem.

**Comment by kartik142857** [comment]
I think major of us face that problem...

**Comment by mark-friedman** [comment]
We feel your pain and believe we know the largest source of the slowdown.  There's no ETA on a fix yet but we want to get to it soon.

**Comment by bobjohn1212** [comment]
Hello @mark-friedman, have you solved this problem yet? I too am having this problem. My app has slow to a stand still and I have a long way to go. At this pace. my app will be complete in about a year. Does any of the other platforms have the same problem? Perhaps one like Appybuilder would be better for me.

**Comment by mark-friedman** [comment]
We're still ironing out some issues but our latest release had some significant improvements in this area.  Let us know how it's working for you and feel free to provide feedback at https://community.thunkable.com/t/thunkable-x-blocks-update-your-feedback/425809

**Comment by jane-d-alt** [comment]
Issue was resolved; further info at community link.
