### ISSUE TITLE
Feature Request: iOS Push Notifications - Thunakable X

### ISSUE THREAD

**Issue by jade13cat** [thunkable/thunkable-issues#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by jane-d-alt** [comment]
Thunkable X now has [push notifications](https://docs.thunkable.com/push-notifications-by-one-signal) for iOS.
