### ISSUE TITLE
Issues in how blocks are compiled (ie they sometimes just dont work)

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#180]
The most recent event of this occurred in my latest project, a private messaging app with firebase. Everything was working great, but any time i go to tweak something like design or a couple blocks here and there for some extra buttons etc, the main home screen page (the page you see first) has an issue where when i go to select an item from list, it does nothing.

I can assure you what I am doing is the correct way about it. The short term fix for this is going to that screen after doing all my adjustments on other screens, and simply moving the error causing block about on the canvas, to ultimately call a reload in the app (which i believe compiles it again).

This does somewhat fix the issue. This also goes for making a copy of the app, and compiling it for both android and ios, I have checked.

This is also not the first time it has happened. I made an app to search for new films, watch there trailers and see information about it. This apps search feature, which also on the first screen loaded in had a search issue, that when the search button was clicked and a search was called, it would sit loading, in an endless loop with no answer. And what i was searching for was definitely there. Then, upon moving the error causing blocks around on the canvas after doing all my editing, it reloaded and compiled again and all of a sudden it wants to work??

The first time I couldn't really say what was happening. But for the second time now its become frustrating. Both of the apps had their errors when dealing with lists. I cannot say it is the cause of lists, but my guess based on two apps, is that it may very well be.

If you would like more insight into the problem, maybe screen shots, a link to the project I would be more than happy to share with you, for the benefit of a better thunkable experience.

**Comment by mark-friedman** [comment]
@eoinparkinson A link to the project, along with specific steps to reliably reproduce the issue, would certainly be useful.  If you can create a really simple project which shows the issue, that would be super useful!

**Comment by eoinparkinson** [comment]
@mark-friedman 

If I were to try and re create the issue it simply would not happen. I am unsure on how that actually works.

Here is a link to my project: To test it fully you might want to link it your firebase and enable email auth in it.

To test it make two tags in firebase with an empty value.

**USER DATA**

**allchats**

everything should recreate itself.

Here is the project link:

https://x.thunkable.com/copy/eb3cc4e489e6eb43e9ef6072f7e3e6fd

Thanks

**Comment by eoinparkinson** [comment]
I forgot to add, the issue is on the Home screen. it is the list viewer that shows all chats. 
also alternatively could i private message you the firebase details? If that is best way to recreate the issue?

**Comment by mark-friedman** [comment]
@eoinparkinson, Is this issue still happening?  We recently fixed a longstanding problem with list indexing which might have fixed this.

**Comment by jane-d-alt** [comment]
Presumed resolved due to substantial block updates since this issue was filed and no duplicate reports.
