### ISSUE TITLE
Custom font file usage

### ISSUE THREAD

**Issue by cray0866** [thunkable/thunkable-issues#181]
**_Problem:_**
In the old Thunkable Classic you had the ability to upload your own Font Typeface and use it to style text such as in labels and buttons. Thunkable X lacks this important feature as app designers would really like to use their own custom fonts to make their apps unique so as to avoid using a set list of fonts which everyone else is using.

**_Feature to be added:_**
A feature should be added to some of the components to allow .ttf files to be uploaded and applied to the Font Typeface of the component.

**_Solutions I have attempted:_**
I have tried many ways to get around this including using HTML and a webviewer and even making custom images which contain pretyped text in the font of my choice but with these workarounds come a whole set of problems such as flickering images and slow webview response times.

**This feature request is for the Thunkable X platform.**

**Comment by mark-friedman** [comment]
Thanks for the feature request, @cray0866!  It turns out that this is a pretty difficult technical challenge, especially if we want it to be cross-platform.  That said, we will keep it on our list and if the demand for the feature is great enough or the technical challenge becomes easier we will consider implementing it.

**Comment by cray0866** [comment]
> Thanks for the feature request, @cray0866! It turns out that this is a pretty difficult technical challenge, especially if we want it to be cross-platform. That said, we will keep it on our list and if the demand for the feature is great enough or the technical challenge becomes easier we will consider implementing it.

Thanks Mark. It's more of ease of design kind of feature so its not too important. Thanks for the update.

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. We are happy to announce that we are working on the ability to upload font files to Labels and Buttons right now!

**Comment by SkulaMesterHU** [comment]
Hi @jane-d-alt!

I am looking forward to see this feature in Thunkable. I am wondering about a release date? Like days, weeks or months? It would be very important in my app.

Keep up the good work!

**Comment by jane-d-alt** [comment]
Hi all,

This is now available for Business and Enterprise thunkable accounts. You can read more at https://docs.thunkable.com/v/drag-and-drop/label#label and https://docs.thunkable.com/v/drag-and-drop/button#button
