### ISSUE TITLE
"Back" button no longer works in compiled APK (though it works in the Companion app for the same project)

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#184]
### Platform
✕

### Description
Since recently, the "Back" Android button won't take me to the previous screen in a compiled APK file though it does work in the Thunkable Companion app.

### Steps to Reproduce
1. Create button on the main screen to take you to a second screen when clicked
2. Click the button
3. Tap the "Back" button when taken to the second screen

### Expected Behavior
Clicking the "Back" button should take you back to the main screen

### Actual Behavior
Nothing happens

**Comment by mark-friedman** [comment]
Thanks for reporting this @AmigoDeluxe!  We're looking into it.

**Comment by AmigoDeluxe** [comment]
Ok not sure what just happened but the "Back" button no longer working in the Companion app either!!!

**Comment by AmigoDeluxe** [comment]
Looks like it has been fixed in the latest release. Thanks!
