### ISSUE TITLE
(for Thunkable X) Blocks must return current property values.

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#185]
If the button has a width of 100px and then adds a lot of text to its Text property, it will stretch, but the width block of the button will return 100px, which is incorrect. This is the case for most units.

Imagine the situation. The driver agreed to take the passenger from San Francisco to Los Angeles on the condition that the passenger pays the cost of gas for the road on the meter and they will not stop anywhere. Initially, there were 500 liters in the tank, which was returned by the Label.getWidth block. After arriving in Los Angeles, the driver asks to pay for the cost of passenger gasoline. The passenger looks at the value of the Label.getWidth block - 500 liters - and says, why should I pay for gas, if before the trip and after the trip the program shows 500 liters, and that means we didn’t spend it at all?

**Comment by mark-friedman** [comment]
@AlexITMan I see that you closed this issue.  Just curious why.  Did the problem not actually exist?

**Comment by AlexITMan** [comment]
Mark, I noticed that side effects are not used in Thunkable X blocks and getter blocks return to their default values, or those that were set using setters. For example, if I set the Button.SetWidth = "fit content" property, then when using the Button.GetWidth block I will always get "fit content" instead of the really changed width when changing the label on the button. It turns out that with the help of property blocks I cannot find out the current state of the object. That’s what I’ve been talking about in my proposal - to add functionality to the blocks so that they reflect the current value of the properties of the components.

**Comment by mark-friedman** [comment]
@AlexITMan I get what you are asking for.  I think it would be valuable to be able to get the actual, computed, height and width of components, in addition to their more abstract values (e.g. "fit contents").  I think that both sets of values are useful.

**Comment by AlexITMan** [comment]
You're right, Mark, that's what I wanted to say. A similar situation occurs, for example, using Map. I scale the map with my fingers, but the Zoom block does not show the new value and moreover, after the map is redrawn, its position and scale are reset to their original values, and not new ones. But out of this trouble, I found a way out.

**Comment by jane-d-alt** [comment]
Hi there, apologies for not following up when this block was originally implemented. You can see a demonstration of the Computer Width (vs. regular Width) block here: https://x.thunkable.com/projectPage/609d41b1497320001183eea2/
We will close this issue now. Thanks for the request!
