### ISSUE TITLE
Array of elements

### ISSUE THREAD

**Issue by gepponline** [thunkable/thunkable-issues#192]
It would be nice to have the possibility to create an array of controls/indicators to create dynamic interface.
So If I have to place on screen a number of object that depend from a programmatic aspect, it can be done easily.
For example, if i need a Button for every bluetooth device available, I can create a growable array of button that will show me the same number of button as the bluetooth devices.
This type of control should return a value based on the type of control/indicator inside the array and/or the index of clicked object.

**Comment by AlexITMan** [comment]
Please see the new blocks in the Any Components category that allow you to do this.

**Comment by gepponline** [comment]
wow! Perfect! I didn't know it exist.
I'll teake a look at it ;)

**Comment by mark-friedman** [comment]
I'm going to close this for now.  If it turns out that the the new any/generic blocks are not what you need, please feel free to re-open this issue and comment on what else you need.
