### ISSUE TITLE
Can not see all text in label

### ISSUE THREAD

**Issue by tomer2526** [thunkable/thunkable-issues#200]
When there is a long text you can not see the end of the text even if there is a scrolling (the problem is mostly called Android)

**Comment by mark-friedman** [comment]
@tomer2526, have you tried increasing the height of your label component so that the text will all fit?

**Comment by tomer2526** [comment]
Yes.  I tried many other things that did not fix the problem

**Comment by mark-friedman** [comment]
@tomer2526 Can you create a small project showing the issue and post a link to it here?

**Comment by tomer2526** [comment]
here:https://x.thunkable.com/copy/f44834144b0c60a8e026fbb5e7f4322a
Sorry about the delay😅

**Comment by yuexi2009** [comment]
Hi @tomer2526, set your Column1 height to "fit content", will solve your problem.

**Comment by tomer2526** [comment]
Problem not resolved in my application yet (watch video, note that the text was cut at the end)
 link to the video: https://drive.google.com/file/d/1AHbFz7au3Myy0XRfqgt1h05pf5y-V-a_/view?usp=sharing
![photo_2019-07-30_12-05-48](https://user-images.githubusercontent.com/32513840/62116168-60445000-b2c2-11e9-95ca-0e0c1398f687.jpg)
![photo_2019-07-30_12-05-51](https://user-images.githubusercontent.com/32513840/62116169-60445000-b2c2-11e9-8b1c-5571fc3de815.jpg)

**Comment by yuexi2009** [comment]
Hi @tomer2526, sorry about that, there are few things you can check. 
1) do you set the label component "height" to "fit content"? If not please try it.
2) this is a hacky way in case the first option doesn't work, just inset few blank lines at the end. 
Let me know if it works. Thanks.

**Comment by tomer2526** [comment]
I've already adjusted the height to fit (and it still doesn't work)

**Comment by yuexi2009** [comment]
@tomer2526  could you share your actual project? Because this project you shared with us worked well https://x.thunkable.com/copy/f44834144b0c60a8e026fbb5e7f4322a  so want to see if any other component in the project causes the issue.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved.
