### ISSUE TITLE
Variable in "get property of object" block

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#203]
Such a block is requested

![изображение](https://user-images.githubusercontent.com/20015046/61577241-544fd580-aaed-11e9-98a8-56a12ce05277.png)

Suppose you need to translate all the inscriptions on the screen into another language. In this case, you can do so

![изображение](https://user-images.githubusercontent.com/20015046/61577490-99293b80-aaf0-11e9-8f8c-2ee5501b487b.png)

**Comment by mark-friedman** [comment]
FYI, this is currently being worked on.

**Comment by AmigoDeluxe** [comment]
Yes, yes and again yes. This is going to save TONS of work by creating FOR loops instead of having to duplicate sets of blocks which is a killer. And with the availability of the new clone features this will be perfect!!!
