### ISSUE TITLE
Variables Force-renamed in app

### ISSUE THREAD

**Issue by jane-d-alt** [thunkable/thunkable-issues#204]
If an app project has a variable name 'thing', then the user creates a variable 'thing1', all instances of 'thing' in the app are renamed to 'thing1'. 
This is the case for any variables with names [name] and [name+].

Thunkable X

### Steps to Reproduce
1. Create variable [thing]
2. Create blocks which use variable [thing]
3. Create new variable [thing+], whose name is the name of [thing] plus extra characters at the end

### Expected Behavior
What did you expect to happen?
Variable [thing+] is created, nothing else

### Actual Behavior
What actually happens?
Variable [thing+] is created, all instances of [thing] in the code are replaced with [thing+]
```
  STACK TRACE AND/OR SCREENSHOTS
```
![thing-thing1](https://user-images.githubusercontent.com/51848939/61628960-90b13c00-ac7b-11e9-91df-0ab139023a41.gif)

**Comment by AmigoDeluxe** [comment]
I just got the same with a Stored variable. Super annoying!

**Comment by jane-d-alt** [comment]
issue was resolved
