### ISSUE TITLE
(Thunlable X) Maybe \n doesn’t work in Label

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#205]
I ran a test on the Android emulator and saw this image.

![изображение](https://user-images.githubusercontent.com/20015046/61697482-0383eb00-ad40-11e9-826c-c4d7b379c792.png)

![изображение](https://user-images.githubusercontent.com/20015046/61697606-434ad280-ad40-11e9-84b1-9cd8b7b91bd8.png)

**Comment by mark-friedman** [comment]
We are in the middle of adding support for using `\n` in a label to create a new line.  Sorry that it is in an inconsistent state.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved.
