### ISSUE TITLE
Refresh of image files not working

### ISSUE THREAD

**Issue by peat26** [thunkable/thunkable-issues#208]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
thunkable X

### Issue/Request Origin
In testing

### Steps to Reproduce
1.upload a image file (png), labelled image1.png
2. add image block and point to file image1.png
3.Delete from file system in thinkable image1.png (or rename)
4. upload image1.png (new version)

### Expected Behavior
See new image file

### Actual Behavior
Shows old version
```

If I add a image file renamed as newimage1.png and recode block to point to this it works.
It seems to cache the original file, also you cannot simply update the trailer of filename, (eg imagex1.png), this suggests some indexing on first letters of file name internally.
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
Thanks for the bug report, @peat26!  We'll look into the issue.

**Comment by jane-d-alt** [comment]
This behavior has been resolved. We'll close this issue now; apologies for not following up when the behavior was originally resolved.
