### ISSUE TITLE
Essential features missing... like tab navigator color

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#21]
Hi,

I am really irritated that Thunkable X just launched out of Beta without essential functions like changing tab navigators colors and adding icons... I also don't get why the icon feature should only become available to iOS since menus with icons are part of Material Design as well... I think that's a poor decision and there is no good reason for that...

Too me currently Thunkable X feels much more like an early Alpha than a finished product...

cheers, Chris

**Comment by jane-d-alt** [comment]
This is now available in Thunkable X.
