### ISSUE TITLE
The "coordinate" property of a Map works only once in the same "do" section

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#210]
Ok so this is simple to explain. On Thunkable X companion for Android, when I do this:

![image](https://user-images.githubusercontent.com/7762893/61909104-f3376000-af39-11e9-814c-8ccd7b89bfa0.png)

...the two labels are getting populated properly. But when I do this:

![image](https://user-images.githubusercontent.com/7762893/61909184-1cf08700-af3a-11e9-9f8a-463062e2fda7.png)

...only the first label in the "do" section gets the value while the second gets nothing. Interestingly enough, this does work but it is not a viable solution:

![image](https://user-images.githubusercontent.com/7762893/61909242-48737180-af3a-11e9-9dc6-a3c1c7fccec8.png)

**Comment by mark-friedman** [comment]
@AmigoDeluxe Nice catch!  That is a very strange bug.  We'll investigate.

**Comment by AmigoDeluxe** [comment]
Just tested on iOS too, same issue

**Comment by jane-d-alt** [comment]
This behavior does not effect the new 'event' output block of the 'onMarkerPress' event block. We'll close this issue now; apologies for not responding here when this behavior was originally resolved.
