### ISSUE TITLE
(Thunkable X) Label does not change Text value

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#211]
On the Adroid emulator, this block does not work - the Text on the Label does not change to an empty value, but shows the previous one.

![изображение](https://user-images.githubusercontent.com/20015046/61991929-09d7d700-b060-11e9-8266-ea606892e9f9.png)

https://x.thunkable.com/projects/5d26212512df12a72fd0565f/project/properties/designer/

**Comment by AmigoDeluxe** [comment]
Wow. True.

**Comment by mark-friedman** [comment]
@AlexITMan Thanks, we'll look into it.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved.
