### ISSUE TITLE
(Thunkable X) The global variable does not work with the list of objects.

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#213]
In this block, the value of the image property does not change.

![изображение](https://user-images.githubusercontent.com/20015046/62011031-90cda200-b17b-11e9-8ec5-449dca05b414.png)

**Comment by mark-friedman** [comment]
Yeah, that's an interesting bug!  

We're working on it.

**Comment by jane-d-alt** [comment]
This behavior has been resolved. We'll close this issue now; apologies for not responding here when this behavior was originally resolved.
