### ISSUE TITLE
(Thunkable X) Bottom navigation bar is not displayed.

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#214]
iPhone6 (iOS 12.3.1)

![изображение](https://user-images.githubusercontent.com/20015046/62011100-9ecff280-b17c-11e9-8e4f-6f3a0a8c635f.png)

**Comment by weihuali0509** [comment]
Thanks for reporting. I identified the issue and working on a fix. It should be released within 48 hours.
