### ISSUE TITLE
Slow label text assign in Android

### ISSUE THREAD

**Issue by MrSco** [thunkable/thunkable-issues#216]
### Platform
Thunkable X - Android only (works fast/correctly on iOS)

### Issue/Request Origin
My testing

### Steps to Reproduce
1. create a label
2.  assign it text value from a app/stored/cloud/local storage variable
3. the text takes way too long to render on screen
4. create label
5. assign it text value using string value and/or for loop local variable
6. the text instantly is rendered on screen

### Expected Behavior
text instantly is rendered on screen

### Actual Behavior
text takes way too long to render on screen

forum post:  https://community.thunkable.com/t/slow-label-text-assign-in-android/163791
sample test project: https://x.thunkable.com/copy/bd1fd30ebab40d1bdabbbf975506b3c7
gif example: 

![fGaGmCu 1](https://user-images.githubusercontent.com/11297411/62240792-be962f00-b3a5-11e9-8c59-466ec6ba254d.gif)

**Comment by AmigoDeluxe** [comment]
Yup... seeing the same.

**Comment by mark-friedman** [comment]
Thanks, @MrSco.   We are currently in the midst of some work that should help this issue.

**Comment by MrSco** [comment]
Thanks, @mark-friedman. Any ETA?

**Comment by mark-friedman** [comment]
>Thanks, @mark-friedman. Any ETA?

@MrSco Not yet.

**Comment by jane-d-alt** [comment]
@MrSco is this behavior still affecting your projects?

**Comment by MrSco** [comment]
@jane-d-alt yes. still slow on android when filling text labels from variables

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved when testing the above app on an Android device. @MrSco could you confirm?

**Comment by MrSco** [comment]
@jane-d-alt i'm not using thunkable any more. I rewrote my app in react native.

**Comment by jane-d-alt** [comment]
Thanks for replying. I'll close the issue since the behavior appears resolved.
