### ISSUE TITLE
(Thunkable X) Crash app when using atypical values in blocks

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#217]
Crashing applications in Live on launch in BlueStackes4

![изображение](https://user-images.githubusercontent.com/20015046/62365867-e6b09a00-b52d-11e9-8b83-1bd5e50809f8.png)

**Comment by mark-friedman** [comment]
Thanks, @AlexITMan.

**Comment by jane-d-alt** [comment]
These fontstyle and alignment blocks now do nothing, while the justification blocks now successfully set the justification of the row component.

We will now close this issue. Apologies for not following up when this behavior was originally resolved.
