### ISSUE TITLE
Feature Request - Tab Images/icons iOS - Thunkable X

### ISSUE THREAD

**Issue by jade13cat** [thunkable/thunkable-issues#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by jane-d-alt** [comment]
Thunkable X now allows you to add icons to [bottom tab navigators](https://docs.thunkable.com/bottom-tab-navigator#adding-labels-and-icons-to-your-tab) and [top tab navigators](https://docs.thunkable.com/top-tab-navigator#adding-labels-and-icons-to-your-tabs).
