### ISSUE TITLE
(Thunkable X) Confusion with Justification and Alignment block properties

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#221]
Using blocks of Justification and Alignment blocks is confusing, which is clearly visible in the project.

https://x.thunkable.com/projects/5d468e52e644813a7d4ea398/project/properties/designer/

You can say that the string "false" and logical false are values ​​of different types and are not equal, but then the question arises as to why the property "bottom" is set in the example shown, and some strange "flex-end" is returned?

The user wants to set the Justification property using blocks. He uses a text block with the text "bottom", and can not understand why everything is aligned on the top edge?

**Comment by MrMazzone** [comment]
There is a dropdown menu of options that you can select from. No need to add a boolean or string block to set the property. 
![image](https://user-images.githubusercontent.com/40954645/62422577-c7775100-b682-11e9-93b2-922e635f7d1e.png)

The real issue is Justification and Alignment property blocks need to be renamed to match their designer counterparts, Vertical Alignment and Horizontal Alignment. Not sure if this is a reported issue elsewhere.

**Comment by AlexITMan** [comment]
Thanks for your clarification.

Suppose I create an application for learning programming using Thunkable X and want to show what happens when using Justification with different values ​​depending on the user's choice. How would you solve this problem and how many blocks are needed for this?

**Comment by MrMazzone** [comment]
Maybe something like this: https://x.thunkable.com/copy/aaf338a6a887f8caf37f002ef1dd34eb

Buttons that trigger each property change
![image](https://user-images.githubusercontent.com/40954645/62464197-edbbf000-b759-11e9-83af-5b84c9ba541a.png)

As a recommendation, this Github page is for reporting bugs and requesting features. If you need help figuring out how to do something or have a question about Thunkable, please visit the forum and post there. https://community.thunkable.com

**Comment by MrMazzone** [comment]
I also suggest that you edit this issue title to "(Thunkable X) Change 'set Justification' block to 'set Vertical Alignment' and 'set Alignment' block to 'set Horizontal Alignment'"

**Comment by AlexITMan** [comment]
Sorry for misleading you. Actually, I wanted to show that using static blocks is much more complicated, as you can see. If you need to change 100 properties, then you have to use 100 blocks of property changes.

I can solve this problem with just two blocks, but the problem is that using a text string as the value of these blocks not only leads to confusion, but also crashes the application on the Android emulator (for which I created another topic).

**Comment by MrMazzone** [comment]
I am still really confused about what you want to do, but you do not need 100 blocks to change 100 properties. You could use a list of the components and a generic 'any component' block to change a property of many components. 
![image](https://user-images.githubusercontent.com/40954645/62468960-3f1dac80-b765-11e9-807d-dfd2528db0c7.png)

And you can do this with Screens or Columns or whatever you are trying to do this with.
![image](https://user-images.githubusercontent.com/40954645/62469090-8dcb4680-b765-11e9-9825-6e7b0c26ef81.png)

**Comment by mark-friedman** [comment]
I'm going to close this for now, since it's not really clear what the bug or feature request is here.  If that can be figured out, feel free to edit this issue's title and description or create a new issue.
