### ISSUE TITLE
(Thunkable X) Crash of an empty project in Memu play when adding the Map component to it

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#223]
I don’t know if this is a Thunkable X error and whether it is similar to devices with Android 5.1.1, but I decided to report it just in case.

When I launch an empty application with the Map component in the Android Memu play emulator, the application crashes.

Stack contents

![изображение](https://user-images.githubusercontent.com/20015046/62560728-599b7700-b886-11e9-9616-80150b2567ca.png)

**Comment by mark-friedman** [comment]
Thanks, @AlexITMan.  It would be nice to know whether this is a problem on a real Android 5 device or just the Android Memu play emulator.  We'll investigate.

**Comment by josmas** [comment]
I have tested this with an actual Nexus 5 running 5.1.1 and it works as expected. Closing it now. Thanks!
