### ISSUE TITLE
(Thunkable X) Picture resize before uploading to MediaDB

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#224]
Taking pictures and uploading them to MediaDB takes time since the average picture size taken on modern smartphones is 4MB (or so). Having to upload just a few pictures can take ages due to the total size which needs to be uploaded to MediaDB.

It would be nice to have an option to resize the images before uploading them as seen in some email clients. In many cases, the full-quality picture is not really needed so being able to upload a smaller version would be great!

**Comment by AmigoDeluxe** [comment]
That would really be useful! Thanks @AmigoDeluxe for bringing this up! :-D

**Comment by josmas** [comment]
How would you expect the UI for this to look like? I mean, we can resize under the hood but then some users will complain that they want the full blown pic, so does this look like an extra block, or a property, or something else?

**Comment by AmigoDeluxe** [comment]
Hey @josmas . Doing this through a dedicated block could be useful if down the road, Thunkable offers the option to upload media files to other destinations than MediaDB. The properties I see making sense to include for a start are:

- **Width**: Should accept percentage or absolute value
- **Height**: Should accept percentage or absolute value
- **Resize mode**: Fit or Fill
- **Enlarge/Reduce**: Always, Enlarge only or Reduce only
- **Maintain aspect ratio**: Yes or No

Then you can take your time to introduce more options down the road. Like, maybe considering the same for videos with additional options such as target size and others we can think of together. But the image resize capability is what's important for now. Implementing this would be massively appreciated!

Thanks
K

**Comment by MrMazzone** [comment]
@AmigoDeluxe @josmas 
I haven't tried this,  but does this not work?
![image](https://user-images.githubusercontent.com/40954645/86487565-68a3d700-bd2c-11ea-81d4-f090bfa578db.png)

In other languages (Python) I have simply done something like this.  Does the "Picture" property just point to the source image thus why this doesn't work?

**Comment by AmigoDeluxe** [comment]
Hey! Tried it, doesn't work. In your example, all you do is change the **display** size of the image component, not the size of the source picture file. The Image1 > Get Picture block does not return the picture but rather the path to the picture in the device's filesystem which is text. I tried your example and also the one below and in both cases, the size of the image on Cloudinary is 3456 x 4608.

![image](https://user-images.githubusercontent.com/7762893/86488905-3d8ca800-bd6b-11ea-9faa-763176879027.png)

If you have a working sample project, I am more than happy to look at it!

Thanks
K

**Comment by AmigoDeluxe** [comment]
![image](https://user-images.githubusercontent.com/7762893/92313791-45b9cb80-efd8-11ea-81a9-20108e3e3fe8.png)

**Comment by AmigoDeluxe** [comment]
Any update on this?

**Comment by sy-per** [comment]
Please add this feature

**Comment by tatiang** [comment]
+1 For this feature request. I'm making a photo journal app and the upload time for photos is pretty long. It can take 5-10 seconds to upload each one to the Media DB. It would be great to resize on the fly before uploading each one.

**Comment by tatiang** [comment]
When I upload a photo from my iPhone 11 to Cloudinary, about once in every five tries, the Media DB upload fails because the image size is too large. I could maybe get around this by using High Efficiency (HEIF/HEVC) format but that's a pain because then I have to convert everything.

**Comment by josmas** [comment]
Apologies for the slow response to this; I am moving it to internal tracker to prioritize. Please note that we are swamped with more pressing things such as iOS app tracking, android 11 and android bundles (hard deadline in August) and a few other operational things, but we can hopefully squeeze this in when that work is done. Thanks!

**Comment by alanglade** [comment]
I am also strongly interested in this feature

**Comment by tatiang** [comment]
What is the status of this issue? It’s still a problem with the media DB block and it’s only getting worse as new phones’ camera quality improves.

**Comment by josmas** [comment]
hey @tatiang we've had a DnD resize block for quite a while: https://docs.thunkable.com/v/drag-and-drop/camera#resize-image

No plans to have this available on legacy projects though.

**Comment by tatiang** [comment]
That's a disappointment. There are so many limitations with the drag and drag interface. It's so promising but I can't use it for serious app development yet. Having the resize block in the Snap to Place interface would be a huge improvement as far as Cloudinary is concerned. I have several apps -- most of my apps, actually -- that are stalled because of the delay it takes to upload photos to Cloudinary.
