### ISSUE TITLE
Is device iPad boolean

### ISSUE THREAD

**Issue by ruymello** [thunkable/thunkable-issues#228]
**Is your feature request related to a problem? Please describe.**
Using a scrolling screen/column makes it difficult to size items with percentages and, consequently, makes proper resizing to larger screens, such as the iPad, more difficult.

**Describe the solution you'd like**
Should there be a block “is device iPad/iPhone?” (Much like the current “is device iOS/Android), we could set different absolute sizes for objects/buttons, or even set different columns/screens for each device.

**Describe alternatives you've considered**
None so far.

**Which platform are you asking for?**
 Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by mark-friedman** [comment]
Somewhat more general, at least for the purposes you describe, might be the ability to get the screen size of the device.

**Comment by jane-d-alt** [comment]
This can be achieved using the blocks to get screen height/width from the Device drawer of blocks.
