### ISSUE TITLE
Feature Request: Ability to Delete and Rename Created Variables - Thunkable x

### ISSUE THREAD

**Issue by jade13cat** [thunkable/thunkable-issues#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by 10MINT** [comment]
You didn't answer the questions, so I have to make an assumption. When you click the name of a variable, you can rename and delete it
![grafik](https://user-images.githubusercontent.com/10596945/42726392-e6de7768-8793-11e8-8e44-f80e84516938.png)

**Comment by mrching** [comment]
You can now rename variables in our latest release
https://docs.thunkable.com/thunkable-cross-platform/create/blocks/variables
