### ISSUE TITLE
Can't cascade new "object" tiles after the August 19th update

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#231]
### Platform
✕

### Issue/Request Origin
After the August 19th update I can no longer cascade a “get property abc of object” > “get property xyz of object”; the two blocks just won’t snap to each other like they used to:

### Steps to Reproduce
https://community.thunkable.com/uploads/default/original/3X/2/6/2607b727a77a3b814d2bd7c5e2072e3f0efbc318.png

### Expected Behavior
https://community.thunkable.com/uploads/default/original/3X/e/9/e9bd0c48861ba58a2699ca198c27a508b2b04831.png

### Actual Behavior
The "of object" will not snap to the "get property" of the next tile

**Comment by mark-friedman** [comment]
This has been fixed in the latest release.
