### ISSUE TITLE
App start up speed

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#232]
Any major app now days, starts up within a second. At most, 2. Take Snapchat or Spotify as a great example, on iOS and Android, both apps start up, for me anyway, within a second. 

My device is a Samsung Galaxy S8 running Android 9. 

Thunkable apps take, on average, 4-6, sometimes 7 seconds (I based this off of 10 start ups of the app)

This is a long time, for an app starting up.

Is this a limitation of cross platform? I know that Android app builders like Thunkable Classics has startup time of 1 second, same as Spotify or Snapchat. 

Would be great to reduce the start up time!

Thanks.

**Comment by mark-friedman** [comment]
Thanks, Eoin.  To be honest we simply haven't spent much time optimizing app startup time.  We've been more focused on simplifying app development, adding features and fixing bugs.  That said, your point is well taken and I appreciate your comparisons to other apps.

**Comment by tomer2526** [comment]
I mentioned the same problem here:
https://community.thunkable.com/t/my-applications-are-slowly-working/223533/4

**Comment by jane-d-alt** [comment]
Hi there,

App speed is something we are always keeping an eye on, but I'll report that at time of writing, a downloaded Android app from Thunkable has a startup speed (time between clicking the app and seeing the home screen) of 2-3 seconds, which puts it on a par with Reddit, Slack and Spotify, faster than the Netflix app, and slightly slower than Google Photos. So from our perspective, our app startup times are par for the course. We'll close this issue for now, but we are always interested in hearing about people's experience with startup times and runtime speeds!
