### ISSUE TITLE
(Thunkable X) Live Test with Code

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#233]
**Is your feature request related to a problem? Please describe.**
Logging into the Thunkable Live app with the Google account and having it display all of your projects to test is fantastic.  My issue relates to classrooms and shared devices for testing.  I have a classroom set of Android tablets for students to use in class.  The Google sign-in options signs the student into Google across the device (Gmail, Calendar, Drive, etc.).  Students must remove their Google account from the device in device settings at the end of each class in order to prevent other students from accessing their Thunkable account, Gmail, Google Drive, etc.  Students easily forget to do this step, creating a vulnerability for their account. 
<br>

**Describe the solution you'd like**
When a user selects "live test" generate a code to type into the Thunkable Live app to connect the one app for one session. Or vice-versa generate on Thunkable Live and type in "live test" area of Thunkable X UI.  (similar to Thunkable Classic and App Inventor)

The solution may be as simple as allowing the non-Google account way of testing for Google accounts, where they select "Need a code? Click here" and connect that way. (I have limited knowledge of how this works exactly as I have never used it myself)
<br>

**Describe alternatives you've considered**
- Shared accounts per tablet - But students will have each other's projects.

- BYOD, Students use their own devices - But I prefer they do not use them as their devices have other distracting apps.
  
<br>
  
**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by mark-friedman** [comment]
@MrMazzone In the short and medium term I think that using email sign-in (with the "Need a code? Click here" mechanism) is probably the way to go.  We're working on some more documentation on how to use it (esp. with Live companion) and will post a link to that asap.

**Comment by MrMazzone** [comment]
@mark-friedman Excellent! Much appreciation. 

Joe

**Comment by MrMazzone** [comment]
**Update:** Have been using the login via email for students to connect to classroom Android tablets.  It is working, but sometimes it logs them in through Google after clicking on the email link (I think this might be because they log into Gmail to click on the link) causing them to have to log out and reclick the email link in order to live test with the code. 

It would be incredibly convenient if the Google sign-in accounts could just type in a code also.

**Comment by MrMazzone** [comment]
Just commenting to see if the team could revisit this idea.  Doesn't seem to difficult to implement. 

Would love for Google sign ins to be able to use code to live test.  Again, this is helpful for shared devices where it is not ideal to log into your Google account on the device to test.

**Comment by MrMazzone** [comment]
@josmas I have been doing workshops with students again.  It would be incredibly helpful if the team could revisit this idea.

Again, I have a set of tablets for the group to use.  I do not want them to login with their Google account on the tablet as it will persist their and people could access their Gmail, etc.  So, I ask students to login with email option instead of login with Google.  Every time there is a student that logs in with Google because they think they are smarter than me and say to themselves, I have a Google email. Students always complain too that the sign in with email is so many extra steps. 

Why can't the connect with code option just be present when a user logs on with Google in the web browser?

**Comment by weihuali0509** [comment]
@MrMazzone We will talk about it internally in the coming week. We will let you know soon.

cc @TingC

**Comment by weihuali0509** [comment]
@MrMazzone The option is enabled now, please check it out :)

<img width="445" alt="Screen Shot 2020-10-27 at 11 14 24 AM" src="https://user-images.githubusercontent.com/1775235/97344145-9b2a9000-1845-11eb-902b-108a4e238ce1.png">

**Comment by MrMazzone** [comment]
WOOOHOOOOOOOO!!! 🎉🎊🥳

Thank you so much!
