### ISSUE TITLE
Top Tab Navigator Tool-Bar

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#240]
Here is the design I am looking for

https://lh3.googleusercontent.com/LAOxT4-h0ZfpaphiJfKC4dVQyWJL4oi2a3fWxamDd6tGHCj2nNKiUuwrnsm_GUGqlA=w1920-h975-rw

It would then be great to have buttons at the top like shown that performed actions based on the screen you are on. 

The buttons could work like any component. So you add the buttons you want to the background screen (the screen that is not in top tab navigator, but functions as a tools panel as such, as shown in the photo linked above). Then in each specific screen (screens that are in top tab navigator) you would get an option on the left panel of blocks for the buttons/components in this background screen. This means all the load from the blocks would be separated out between screens to reduce blocks per screen lag.

**I am sure something like this though is to do with the actual top tab navigator. So to be able to add some buttons into it and perform functions would be pretty cool.**

I am unsure if this is a big ask, but if it is not, it would be pretty cool!

**Comment by jane-d-alt** [comment]
Hi Eoin, we're going to close this issue since it seems to be the same as your issue #174. Thanks for the request!
