### ISSUE TITLE
Background Image Resize Issue with Column

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#243]
### Platform
Thunkable X

### Issue/Request Origin
When column or row is set to Relative Size, the Background Image does not properly fit in the container. Resize mode does affect the way it looks but still does not allow the image to fill the entire column. After playing around for a bit, It seems the image uses the Relative Size percentage to determine its size in the column. 

### Steps to Reproduce
1.  Add Column component to project. 
2.  Set Width and Height properties (or just Width or Height) to relative sizes. Example: Width = 90% and Height = 50%
3. Upload a background image or use Camera component to take picture and set background image.
4. Change Resize Mode property, testing each option.
5. Image will not display properly.

### Expected Behavior
The background image should fill container as it does on Screen or Image components. 

### Actual Behavior
The background image is only displayed partially in the container, seemingly using the relative size values. 

Shared Project Link with Issue:
https://x.thunkable.com/copy/5b3261315fa9891429f9530b9cb303a4

**Comment by AlexITMan** [comment]
Yes, there is a problem

**Comment by jane-d-alt** [comment]
Hi there, it seems like this behavior has been resolved. See [this demo project](https://x.thunkable.com/projectPage/60a37931aed6ad0012a5d0e7/) as an example. Apologies for not following up when this behavior was originally resolved. We will close this issue now. Thanks for reporting!
