### ISSUE TITLE
Background Picture Oversize Issue with Column

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#244]
### Platform
Thunkable X

### Issue/Request Origin
The Background Picture is oversized and extends beyond the bottom border of the Column.

### Steps to Reproduce
1. Add a Column component. 
2. Set the Column's border width property.
3. Set the Column's Background Picture property.

### Expected Behavior
The background image should stay within the borders of the Column component. 

### Actual Behavior
The background image stretches past the bottom border of the Column component. (See image)

https://x.thunkable.com/copy/cb6b625f479511edef48620335126d70
![SmartSelect_20190908-173811_Thunkable](https://user-images.githubusercontent.com/40954645/64494831-954ba700-d25f-11e9-934b-58e67bf09105.jpg)

**Comment by AlexITMan** [comment]
Hi,

Set overflow = hidden for Column

**Comment by jane-d-alt** [comment]
Hi there,

This behavior appears to be resolved. See [this demo app](https://x.thunkable.com/projects/60a37931aed6ad0012a5d0e7/a822aaf5-8187-40ef-8625-945cf12cc9b3/designer) for an example. Apologies for not following up here when this behavior was originally resolved. We will close this issue now. Thanks for reporting!
