### ISSUE TITLE
New type of “Get Object” suddenly broken for JSON arrays

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#245]
### Platform
Is this for ✕, ✕ Android companion, can't test ✕ iOS companion

### Steps to Reproduce
https://community.thunkable.com/uploads/default/optimized/3X/8/1/816361df368e3cb8eb69b6582455215a7562466e_2_1380x590.png

### Expected Behavior
Both labels get populated properly

### Actual Behavior
What actually happens?
Only the "Old" label gets populated properly

Ongoing discussion here: https://community.thunkable.com/t/new-type-of-get-object-suddenly-broken-for-json-arrays/216655

**Comment by mark-friedman** [comment]
We'll take a look.

-Mark

**Comment by AmigoDeluxe** [comment]
Looks like it is now resolved. Thanks!
