### ISSUE TITLE
Feature request: access to device clock (ThunkableX)

### ISSUE THREAD

**Issue by rschoem** [thunkable/thunkable-issues#25]
**Is your feature request related to a problem? Please describe.**
For an app I am building, I need to keep track of time. At present it is not possible to access the device clock on Thunkable X.
I tried a number of workarounds (also with help of some forum members on the ThunkableX forum), but all of them are cumbersome and unnecessary complicated for just keeping time.
See https://community.thunkable.com/t/help-feature-request-access-to-device-clock-enhanced-timer/33396 for a detailed description/discussion.

**Describe the solution you'd like**
Please provide a block that allows to get the system time from the device. For my personal needs something like JavaScripts Date.now() would be fine, but I can imagine that others might be more interested in a formatted date (maybe it is an option to return multiple values like some other blocks do, so that the developer can decide which format he/she wants to use)

**Describe alternatives you've considered**
See https://community.thunkable.com/t/help-feature-request-access-to-device-clock-enhanced-timer/33396

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
Thunkable X apps can now [get the current device date/time](https://docs.thunkable.com/device#get-current-time-and-date).
