### ISSUE TITLE
X  Date and Time Picker Text Block

### ISSUE THREAD

**Issue by KaneoheKid** [thunkable/thunkable-issues#250]
The new Thunkable X Date and Time pickers are VERY much appreciated, THANKS!  

Two additional features will make them a lot more useful.  First, it would be the ability to turn off the default, which automatically displays the current Date or Time.  There are times when one wants the field to be empty.  

Second would be to add Text blocks (as attached, from Classic).   
![ClassicTimePickBlocks](https://user-images.githubusercontent.com/42430475/64913141-5e014e00-d6d6-11e9-9e05-7ab7ae7784ca.png)  
There are times when one needs to set the date or time to some other value than the current one.  For example, if I have a screen which displays 4 preset milestones, I need to have the ability to use the text block to enter the preset dates into the four date pickers.  Then, as I reach each milestone, i could use the date picker to record the Actual milestone and then store that value.  

Thanks, KK

**Comment by mark-friedman** [comment]
Thanks, @KaneoheKid, we'll look into this.

**Comment by weihuali0509** [comment]
@KaneoheKid You can set the Visible of Date Input/Time Input to **false**, and you can drag a button and use the following block. Please let us know if that fits your need - 

<img width="443" alt="Screen Shot 2019-09-16 at 9 51 17 AM" src="https://user-images.githubusercontent.com/1775235/64977073-8c626300-d867-11e9-9d18-12e8c4b0c387.png">

cc @mark-friedman

**Comment by KaneoheKid** [comment]
That works very well, thanks for the simple solution.
