### ISSUE TITLE
The "Remove" and "All <component> in <component>" blocks don't work as expected

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#251]
### Platform
✕, ✕ Android companion, ✕ iOS companion?

### Steps to Reproduce
1. Create a column (i.e. Column A) and within that column create another column (i.e. Column B)
2. Create the following blocks when opening the screen: Remove > All Columns in "Column A"

### Expected Behavior
Only "Column B" should be deleted since this is what is contained **in** "Column A"

### Actual Behavior
**Both** "Column A" **and** "Column B" are deleted.

**Comment by jane-d-alt** [comment]
This behavior has been resolved.
