### ISSUE TITLE
Android font Weight in label is either "Bold" or "Not Bold" no matter which Weight value is set

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#252]
### Platform
✕ Android companion

### Steps to Reproduce
This: https://x.thunkable.com/copy/c3db32e69bfc5d2068c16a81f02337c9

### Expected Behavior
Fonts on Android to show according to the weight value set in the designer like they do on iOS

### Actual Behavior
Fonts appear as normal for weight values from 100 to 400 and as **bold** from values 500 to 900.

### Screenshots
![Font weight bug - Android](https://user-images.githubusercontent.com/7762893/64918341-8efc8400-d7a5-11e9-898c-a2da1780ffb5.jpg)
![Font weight bug - iOS](https://user-images.githubusercontent.com/7762893/64918342-8efc8400-d7a5-11e9-813b-b047f42e54a4.png)

**Comment by mark-friedman** [comment]
@AmigoDeluxe  The values 'normal' and 'bold' are supported for most fonts. Not all fonts on all platforms have a variant for each of the numeric values, in that case the closest one is chosen.

**Comment by AmigoDeluxe** [comment]
So this applies to the default fonts too? By default I mean not setting a font name and just using the generic one which is the case in my example. 

And does this also mean that there is at least one font on Android which does support all font weights? If so, which one?

Thanks
K

**Comment by mark-friedman** [comment]
>So this applies to the default fonts too? By default I mean not setting a font name and just using the generic one which is the case in my example.

Apparently.

>And does this also mean that there is at least one font on Android which does support all font weights? If so, which one?

I'm not sure.

**Comment by AmigoDeluxe** [comment]
Hi @mark-friedman 

So I read the [official documentation](https://docs.thunkable.com/fonts#android-fonts) listing the Android fonts supported by Thunkable and updated my [test app](https://x.thunkable.com/copy/c3db32e69bfc5d2068c16a81f02337c9) to show each of them progressing from 100 to 500 weight. It turns out none of them respects the weight setting, at least on my Android 9 device. So there are two cases:

1. There is indeed a bug
2. Your statement "Not all fonts on all platforms have a variant for each of the numeric values" should be "None of the supported fonts on Android respect the weight value and they are either bold or not bold (normal)"

Should we close this as not a bug or would you prefer to forward this to the development team to investigate?

Thanks
K

**Comment by mark-friedman** [comment]
Thanks, @AmigoDeluxe, we'll update the documentation to reflect what your research.

**Comment by AmigoDeluxe** [comment]
Duh... I assumed that it was a bug but I am sure Thunkable's developers know better. Perhaps it works as expected on a future release of Android.
