### ISSUE TITLE
Background Picture Doesn't Display when Screen is Scrollable

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#253]
### Platform
Thunkable X (only tested on Android Live test app and apk install, NOT iOS)

### Steps to Reproduce
1. Set app Screen's Scrollable property to True 
2. Set the Screen's Background Picture property to an image file.

### Expected Behavior
Background picture displays on the screen. 

### Actual Behavior
Background picture only displays on the designer preview and not in the live test app or installed app.

See project as an example: https://x.thunkable.com/copy/e90fb33cec0a927bd24853f83ef0a95d

**Comment by mark-friedman** [comment]
Thanks, @MrMazzone!  We're taking a look.

**Comment by MrMazzone** [comment]
This seems to be resolved in the most recent update (September 19th, 2019).
