### ISSUE TITLE
Share Image with Share Component on Android

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#254]
### Platform
Thunkable ✕ (Android ONLY)

### Issue/Request Origin
https://community.thunkable.com/t/sharing-a-photo-issue/136438 

### Steps to Reproduce
1. Have a project with Share component
2. Use the ShareImage method
3. When ShareImage method runs, nothing happens. 

### Expected Behavior
Open share menu to share an image with other apps.

### Actual Behavior
ShareImage method of the Share component gives “undefined” error message and doesn't share an image.

![image](https://user-images.githubusercontent.com/40954645/64923815-bf472100-d7ab-11e9-97cb-a797a9caee4b.png)

**Comment by mark-friedman** [comment]
Thanks, @MrMazzone.  We'll look into the issue.

**Comment by MrMazzone** [comment]
Tested this on Android today.  Issue seems resolved.  Thank you Thunkable team!
