### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist 

### ISSUE THREAD

**Issue by orderrex** [thunkable/thunkable-issues#258]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
x
### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
community
### Steps to Reproduce
1.publish
2. 
3.

### Expected Behavior
What did you expect to happen?
send too appstore
### Actual Behavior
What actually happens?
```email with this info ITMS-90683: Missing Purpose String in Info.plist 
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by orderrex** [comment]
@mark-friedman

**Comment by mark-friedman** [comment]
@orderrex Can you please provide more information such as the full contents of the message that you received as well as a link to your project.

**Comment by orderrex** [comment]
https://x.thunkable.com/projects/5d82542e1f80bbd15feac214/4ae07e69-7b56-4b4a-a3ad-f9ca1b16b354/designer

**Comment by orderrex** [comment]
@mark-friedman <img width="904" alt="Screenshot 2019-09-19 18 13 09" src="https://user-images.githubusercontent.com/55457819/65265591-3280c800-db09-11e9-86a4-0840bf3e6be5.png">

https://x.thunkable.com/projects/5d82542e1f80bbd15feac214/4ae07e69-7b56-4b4a-a3ad-f9ca1b16b354/designer

**Comment by weihuali0509** [comment]
We are working on a quick fix. It should be out within 24 hours. Thanks for reporting the issue. @orderrex 

Best,
Wei

**Comment by weihuali0509** [comment]
We deployed a new release and the issue should resolved now. Can you confirm?

Best,
wei

**Comment by orderrex** [comment]
it worked fr me after thanks
