### ISSUE TITLE
iOS App Publishing guide links are broken links, and lack of information for iOS publishing

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#264]
The app publishing to apple app store works fine but the thunkable doc links associated with it are broken links.

The links are:

`https://docs.thunkable.com/thunkable-cross-platform/publish/publish-to-app-store-ios#generate-and-upload-an-app-provisioning-profile`

`https://docs.thunkable.com/thunkable-cross-platform/publish/publish-to-app-store-ios#generate-and-upload-an-account-certificate`

Have the posts been removed or are they moved? I could see users getting frustrated by this and potentially end up not uploading their apps.

Also I believe Thunkable Pro members have access to obtain screenshots of their app on iOS devices with dimensions that Apple requests? If this is the case, maybe you could make a form for it and advertise it as such on the publishing screen, as I myself being a Pro member have heard nothing about this until I asked the question.

Apologies if I came across rude with this, I don't mean to be!

Thanks.

**Comment by mark-friedman** [comment]
Thanks for the heads-up @eoinparkinson

**Comment by jane-d-alt** [comment]
Links in iOS publish portal have been updated.
