### ISSUE TITLE
Shutter/Glitch When Changing Slider Value (Slider project with Image Component)

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#265]
### Platform
Thunkable X

### Steps to Reproduce
1. Add image component(s) to project.
2. Add slider component(s) to project below images on screen.
3. Move sliders and notice screen shutter as images refresh/appear disappear.

### Expected Behavior
When image(s) are placed above a slider, the slider value should be able to change without any visual disruption. Should work as if there are no images in app or images below slider(s).
Example:
![SliderGlitch2](https://user-images.githubusercontent.com/40954645/65364361-48f95300-dbdf-11e9-898e-3d55c041aed2.gif)

### Actual Behavior
When image(s) are placed above a slider and the user changes the slider value the screen shutters and the images refresh. The larger the distance between the sliders and the image or the size of the image, the worse the shutter is. 
Example:
![SliderGlitch1](https://user-images.githubusercontent.com/40954645/65364354-44349f00-dbdf-11e9-8cf9-99fa36cd1ebf.gif)

**Possible issue with Image component and not Slider???**

When you have a large image and distance between image and slider the app is rendered unusable with tremendous screen disruption. 
Example:
![PizzaPlanet2](https://user-images.githubusercontent.com/40954645/65364570-9cb86c00-dbe0-11e9-8972-f423d088928a.gif)

Simple project displaying issue while testing: https://x.thunkable.com/copy/a13fef76fd95cf4e791f027050d7fd8e 

Project I created with students where I discovered issue: https://x.thunkable.com/copy/2ddb7eee48b0848179f90ebf06414f12

**Comment by mark-friedman** [comment]
Joe,  Thanks for reporting the issue, as well as the excellent demonstration gifs and example projects!

The general problem has to do with optimizing the refresh of the screen based on UI changes.

**Comment by nicbyron** [comment]
Big +1 here, this does a great job of demonstrating the kinds of issues I am facing! 

@mark-friedman do you have any sort of ballpark on the priority/timeline of fixing this UI changes bug? I know y'all are working as hard you can, just want to have an idea of when it might be

**Comment by jane-d-alt** [comment]
This behavior has been resolved.

**Comment by nicbyron** [comment]
@jane-d-alt WOOT!!! Thank you guys!!!!!! (cc @mark-friedman )

**Comment by MrMazzone** [comment]
Woot woot indeed!!!  This is great.  Performance in many apps seem to be improved.
