### ISSUE TITLE
Support HTML Source for Web Viewer

### ISSUE THREAD

**Issue by tijender7** [thunkable/thunkable-issues#266]
when using live test its working fine, 

when apps are published on both android and IOS they are not working fine, 

![image](https://user-images.githubusercontent.com/23029135/65376931-5f1e1680-dca6-11e9-84fa-05b4e6f231e4.png)

got his reply can you please help me 
![image](https://user-images.githubusercontent.com/23029135/65376935-70ffb980-dca6-11e9-9d5f-a6081c4bde7b.png)

https://community.thunkable.com/t/web-viewer-not-working-properly-when-apps-are-published/233991

**Comment by mark-friedman** [comment]
Thanks for the feature request, @tijender7.

**Comment by jane-d-alt** [comment]
The Thunkable X web viewer does now support HTML sources, so we will close this issue for now. Please reach out if you have any more issues with this. Thanks!
