### ISSUE TITLE
(for Thunkable X) Label with support for basic HTML-tags

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#267]
In some tools to develop applications for Android it is possible to use the following tags:

![изображение](https://user-images.githubusercontent.com/20015046/65499413-3d9b7580-dec6-11e9-8526-26ffe14b0f53.png)

I think that it would be useful and for Thunkable X

**Comment by mark-friedman** [comment]
Thanks, @AlexITMan.  We'll consider this feature.

**Comment by Ubilab-PUCRS** [comment]
Yes some kind of text formating could be very useful!!

**Comment by jane-d-alt** [comment]
We're going to close this request as it overlaps with #29. We recognize the community interest in such a feature and I will see if we can implement it in the near future. Thank you for the request!
