### ISSUE TITLE
(for Thunkable X) Web_view

### ISSUE THREAD

**Issue by amatuzzo** [thunkable/thunkable-issues#269]
There are mainly three features that I need:

1) send username and password from app to web page loaded into Webview with the method POST;
2) keep track of the current url of the web pages opened in webview;
3) intercept scene error when the web page loaded in the webview is not available.

The most important for me is the 1). In the thunkable classic  use the functioon figure shown in the annex

It is possible?
![Immagine](https://user-images.githubusercontent.com/36345186/65516407-43eb1b00-dee1-11e9-8410-9c54bfd13d3a.png)

**Comment by mark-friedman** [comment]
Thanks, @amatuzzo.  We'll look into providing those capabilities.

**Comment by jane-d-alt** [comment]
Thunkable now has post message and receive message blocks for the Web Viewer component. You can read about them [here](https://docs.thunkable.com/web-viewer#post-message-receive-message). We'll close this issue now; apologies for not following up when these blocks were originally added to the platform.
