### ISSUE TITLE
Text-Input + Image : When typing, screen flashes

### ISSUE THREAD

**Issue by rhythmehta** [thunkable/thunkable-issues#27]
### Platform
Thunkable X Android (haven't tested on iOS yet)

### Steps to Reproduce
1. Create a new screen
2. Upload & add any image on the screen.
3. Add text input, anywhere on the screen.

### Actual Behavior
Now whenever user types anything onto the input the images on the screen flashes quickly

```

**Comment by mrching** [comment]
Is it possible for you to share your project link so that we can replicate on our side?

**Comment by ytknows** [comment]
Experiencing the same issue in iOS. Example in this thread: https://community.thunkable.com/t/remember-me-switch-disabled-when-fields-are-empty/31317/2

actech provided a workaround (using other element, such as button, with background image) but the bug still exists when placing an image.

**Comment by lirongreenwald** [comment]
Hi, for me images also flush when playing a sound
kind regards

**Comment by jane-d-alt** [comment]
This behavior was resolved shortly after it was reported. We'll close this issue; apologies for not following up here when this was originally resolved!
