### ISSUE TITLE
Test crashes

### ISSUE THREAD

**Issue by IanOstrom** [thunkable/thunkable-issues#270]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

X iOS companion

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

What does this question mean? The issue came from using the software.

### Steps to Reproduce
1. [Follow this link to an app with the issue](https://x.thunkable.com/projects/5d8a6841d568219854a08f4c/b0094363-9a2a-4cd5-abda-ba7f269f12bd/blocks)
2. Live test
3. Enter text in one of the text inputs
4. Click the button

### Expected Behavior
What did you expect to happen?

Screen switches to screen 2 and shows the mad lib in the label.

### Actual Behavior
What actually happens?

The companion app app exits from the live test. The live test restarts immediately with all inputs blank.

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by IanOstrom** [comment]
Another example of the same isssue. I've tested on student devices and on mine. It seems to be device independent.

**Comment by mark-friedman** [comment]
Thanks, @IanOstrom.  We'll look into it.  Hopefully we can recreate the crash.  If you get any insight into which devices (or other variable) cause it to fail, that will help.

**Comment by AlexITMan** [comment]
I have Android 8.1 on the specified application after clicking on the Button causes freezing.

**Comment by IanOstrom** [comment]
I'm using an iPhone X with iOS 12.4.1

**Comment by IanOstrom** [comment]
I found the source of the issue. It restarts when setting a variable equal to the text of an input that is blank. If all of the inputs have text entered by the user it is fine. One would expect it to save it as "undefined" if blank.

**Comment by mark-friedman** [comment]
@IanOstrom, do you mean setting a variable to the `Text` property of an `Text Input` component in which the user hasn't entered anything?

**Comment by mark-friedman** [comment]
I've verified that setting a variable to the Text property of an Text Input component in which the user hasn't entered anything crashes my iOS Live Test app.

**Comment by IanOstrom** [comment]
Yes, that was the issue I was having.

**Comment by jane-d-alt** [comment]
The issue of "setting a variable to the Text property of a Text Input component in which the user hasn't entered anything crashes the Live Test app" has been resolved. We'll close this issue now; apologies for not following up when this fix was originally deployed.

**Comment by IanOstrom** [comment]
Thanks for letting me know. I love the work you all do. Our CS Club has
just started using it for ongoing project development at club meetings.
