### ISSUE TITLE
(Thunkable X) Crash when using Canvas

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#273]
![изображение](https://user-images.githubusercontent.com/20015046/65671429-e2958a00-e04f-11e9-891d-a10222107ae8.png)

**Comment by mark-friedman** [comment]
@AlexITMan Can we get any more details than this?  Perhaps a link to a project that demonstrates the issue, along with some reproducible steps?

FWIW, the stack trace suggests an issue with a sensor.  Are you using a gyroscope or some other sensor in your app?

**Comment by AlexITMan** [comment]
I'll try to check carefully the project. I was very surprised that uses gyroscope event, although only event handlers used the Canvas, a gyroscope has been removed from the project.

Once again, I'll check the project and try to give an explanation, because noted instability Canvas work in Live.
