### ISSUE TITLE
addRow does not work under IOS (specifically 12.4.1)

### ISSUE THREAD

**Issue by brucemortland** [thunkable/thunkable-issues#275]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
x ios companion

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
I reported it to the community and the problem was replicated by other IOS 12.4.1 users

### Steps to Reproduce
1. Link to my project: https://x.thunkable.com/copy/fcaa6e4829517ee1f4c44a7bb2dd0ecb
2. I originally used row **numbers**, but it was suggested my problem was that I should use column **titles**, but that did not work either.
3.

### Expected Behavior
What did you expect to happen?
that a row would be added to my LocalDB table using the addRow function

### Actual Behavior
What actually happens?
no row was added to my LocalDB table

  STACK TRACE AND/OR SCREENSHOTS
here is a link to my project (very small and distilled to problem)

https://x.thunkable.com/copy/fcaa6e4829517ee1f4c44a7bb2dd0ecb

Thanks, Bruce Mortland 
email: brucemortland@gmail.com
username:  brucemortland7e6c

**Comment by mark-friedman** [comment]
Thanks, @brucemortland!  We'll take a look.

**Comment by domhnallohanlon** [comment]
Hi @brucemortland , 

Are you still facing this issue on iOS 12.4? I retested your sample app on a newer iOS version and it seems to work fine for me now. 

Wondering if we can close this issue?

**Comment by brucemortland** [comment]
Dom,

Let me check.

Bruce

*Bruce Mortland*
<https://mail.google.com/>work: 614-365-2283 x317
cell: 614-327-6300

<http://themortlandminute.weebly.com/>

**Comment by brucemortland** [comment]
Dom,

Sorry about the slow response! Yes, it appears to work now. Close it!

Thanks again,
Bruce Mortland

*Bruce Mortland*
<https://mail.google.com/>work: 614-365-2283 x317
cell: 614-327-6300

<http://themortlandminute.weebly.com/>
