### ISSUE TITLE
OnUserLocationChange block is not reliable

### ISSUE THREAD

**Issue by jonathanvalgar** [thunkable/thunkable-issues#278]
Hello,

As it is known since a long time, the blocks of the Google Map are not properly working. Nowadays there are some problems:

- Not possible to show the data from the markers.
- The map is not updating dinamically (the new coordinates can not be taken when the user moves the map to another location).
- The map is restarted to it´s original coordinates everytime that an event is happening (f.e. when a timer is fired or when yo press a button...).

I am close to end my project, but to publish it i need at least those functionalities to be working.

Regards.

**Comment by mark-friedman** [comment]
@jonathanvalgar Thanks for the bug report.

I'm not sure exactly what you mean in the first bullet point.  Can you expand on that a bit?

**Comment by jonathanvalgar** [comment]
Hello,

I mean that the methods "onMarkerPress" and "onCalloutPress" don´t work. In the same way the methods "get latitude/longitude" don´t give you the current coordinates because the map is not dinamically updated.

![Methods](https://user-images.githubusercontent.com/56083282/66071613-10c80d80-e519-11e9-8ea7-48dc5e95fee3.PNG)

![coordinates](https://user-images.githubusercontent.com/56083282/66071910-a06dbc00-e519-11e9-9531-1f48b6fa84b9.png)

Regards.

**Comment by mark-friedman** [comment]
@jonathanvalgar There's a known issue with `onCalloutPress` but `onMarkerPress` should work.  Please take a look at these two community posts and let us know if they help or not: [this](https://community.thunkable.com/t/map-component-event-block/73742/3?u=mark) and [this](https://community.thunkable.com/t/onmarkerpress-feature/115344/4?u=mark).

Hope this helps.

**Comment by AmigoDeluxe** [comment]
> * The map is restarted to it´s original coordinates everytime that an event is happening (f.e. when a timer is fired or when yo press a button...).

+1 for this issue

**Comment by gre4twh1te** [comment]
Yes, the map is always jumping back to last coordinates set when adding a marker / clicking on an item. That is pretty annoying.

**Comment by bymahoapp** [comment]
as @jonathanvalgar expressed, the map component has a priority of my app as well. 
For example, I need to change marker color or choose an icon instead of a color.

**Comment by gepponline** [comment]
I'm Still waiting for someone to solve the map reset issue.
Every time I place a marker, the Map get back to it's original Position and Zoom factor And I don't want it to.

**Comment by nicbyron** [comment]
> The map is restarted to it´s original coordinates everytime that an event is happening (f.e. when a timer is fired or when yo press a button...).

+ 1

**Comment by jonathanvalgar** [comment]
@mark-friedman Hello

I was following with the project, however i am in a point wher I need to know if those bugs are going to be fixed soon. I am reffering to:

- The map is not updating dinamically (the new coordinates can not be taken when the user moves the map to another location).

- The map is restarted to it´s original coordinates everytime that an event is happening (f.e. when a timer is fired or when yo press a button...).

Without those bugs fixed making an app based on maps becomes almost impossible.

Thanks for your help.

**Comment by jaredgib** [comment]
+1  

I wonder if mapBox or mapquest have a better sdk that the Thunkable devs could consider using?

**Comment by jane-d-alt** [comment]
Hi there,

Addressing the issues in this original report:
You can click a marker and view its details in the callout
The map does not reset when an action such as a Button click takes place

We will follow up on the onUserLocationChange behavior. I will change this issue's title to reflect this.
