### ISSUE TITLE
(Thunkable X) Crash when trying to open a PDF in WebViewer

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#279]
https://x.thunkable.com/projects/5d9e2137d2b95aa5d863ecc2/project/properties/designer/

1) Tap Let`s Begin to Read Book on start screen
2) Click on first item Pipe Layout

![изображение](https://user-images.githubusercontent.com/20015046/66509128-10acac80-eadb-11e9-9ecc-91e74135f698.png)

The same error on Android 8.1

**Comment by mark-friedman** [comment]
@AlexITMan, I believe that what is going on here is that the Android web viewer doesn't know how to handle PDF files, so it is handing this off to the Android download manager which can only handle HTTP/HTTPS URIs.  Have you thought about using the PDF Reader component instead of a Web Viewer?

**Comment by AlexITMan** [comment]
You're right, I was not able to show any PDF file in a Web Viewer on Android. It turns out that PDF Reader - is the only way.
