### ISSUE TITLE
List view width scroll

### ISSUE THREAD

**Issue by Hindawi91** [thunkable/thunkable-issues#28]

**Comment by Hindawi91** [comment]
When list view elements are longer than the screen width, the screen does not become scrollable!

**Comment by domhnallohanlon** [comment]
@Hindawi91 make sure you Screen has the "scrollable" property set to `True`

![screen_scrollable](https://user-images.githubusercontent.com/3117345/104028501-b1978500-51c0-11eb-932f-bd268e520223.png)

Does that work for you?

**Comment by jane-d-alt** [comment]
Hi there,
Since we believe Domhnall's response to have been the solution to this report, we will close this issue for now. You are welcome to re-open if this solution does not work for you. Thanks!
