### ISSUE TITLE
A Subscription feature in thunkable X

### ISSUE THREAD

**Issue by Stolengalaxy** [thunkable/thunkable-issues#280]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to see a subscription feature added to thunkable X where users can pay a monthly price to access the app or a certain page on the app, it would be a free feature and instead of having to buy thunkable pro to access thunkable could just take a percentage of the money. Please Please Please Make this a thing!

**Describe alternatives you've considered**
If this can't be done then please make an in-app purchases feature

**Which platform are you asking for?**
Thunkable X

**Additional context**
Please make it a free feature but thunkable can just take a percentage of the money earned as it would be so good

**Comment by jane-d-alt** [comment]
Our future in-app purchases component will have a subscription option. Since this request overlaps with #227 , we're going to close this issue. Thank you for making this request!
