### ISSUE TITLE
Airtable Crash App

### ISSUE THREAD

**Issue by mastertechisme** [thunkable/thunkable-issues#281]
#150 
# Platform
Thunkable X

### Issue/Request Origin
Me

### Steps to Reproduce
Use a airtable object, and while in the app turn on Airplane mode, to simulate spotty network connectivity.  Press the button or action to use the airtable, the app crashes.

and What did you expect to happen?
An error code is returned so you know why the retrieve or update did not work, no app crash.

### Actual Behavior
What actually happens?
App crashes.

  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
Thanks, @mastertechisme, we'll take a look.

**Comment by mastertechisme** [comment]
Just wondering, do we have an ETA on this.  This seems like a critical bug.

Thanks,
Ed

**Comment by mark-friedman** [comment]
@mastertechisme, we don't have an ETA yet, but in the meantime, as a workaround you could use the [online/offline status block](https://docs.thunkable.com/device#get-online-offline-status) to control whether you call out to Airtable.  You could even display a message to the user in the case that they are offline!

**Comment by mastertechisme** [comment]
Thanks for the prompt reply Mark.  We have already done that, but what we still see is that when the network drops, it takes some time for the the phone to recognize that it is offline, and that check will not work at all times, and the app will still crash.

**Comment by mark-friedman** [comment]
@mastertechisme, got it.  Thanks.

**Comment by mastertechisme** [comment]
![image](https://user-images.githubusercontent.com/56603362/67948092-5ed53d00-fbbb-11e9-881f-1d7acc610d08.png)

**Comment by mastertechisme** [comment]
Any update on this?

**Comment by mark-friedman** [comment]
We haven't forgotten this, but we haven't gotten around to fixing it yet and we don't have an ETA.  Sorry I don't have better news for you :-(

**Comment by domhnallohanlon** [comment]
Hey @mastertechisme, 

Just gone through the read and write blocks for Airtable with my device in Airplane more. In relation to your original question, if you add some error handling like this then it will return an error message when your device is offline and the app does not crash:

<img width="624" alt="Screenshot 2021-01-15 at 15 28 41" src="https://user-images.githubusercontent.com/3117345/104745987-9986af00-5746-11eb-9f63-b1172347bb97.png">

If you encounter any further problems, please open a new issue.
