### ISSUE TITLE
(Thunkable X) Errors using any blocks in Live

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#285]
The link is a test project, through which you can find errors in any components.

For example, if in a Row is a Label, the Label color is not the screen turns red.

Similarly, do not work for properties Igeescht if there Row with embedded therein Button.

If the type select Row, is not working BackgroundColor property to Row, which were originally painted in any color.

https://x.thunkable.com/projects/5daea90289a58c8591c2cc18/project/properties/designer/

**Comment by mark-friedman** [comment]
@AlexITMan Just curious why this was closed.  Did you realize that there was not actually an issue?

**Comment by AlexITMan** [comment]
I closed the topic, because it was my fault.

I can see a situation where the properties have the same name, but they work differently for different components. For example, if you specify the type of Button Background Color property value will change only the background for the button. If you specify the type of Label, change the background and other components. I'm used to the fact that the methods of the same name work the same way, but in this case it is not fundamentally.
