### ISSUE TITLE
Unable to run thunkable live app in ios

### ISSUE THREAD

**Issue by victoriachin84** [thunkable/thunkable-issues#286]
### Platform
Thunkable live on IOS

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. Install thunkable on brand new iphone that already have ios version 13.x
2. Open thunkable app

### Expected Behavior
The app should open and show the screen to login

### Actual Behavior
It crashes.

If the thunkable app haven been installed on phone before the update to ios version 13.x, then it is still workable after the update to version 13.x. However if it is a new install on iphone with version 13.x, it crashes whenevere there are attempts to open up the app.

**Comment by gre4twh1te** [comment]
Please download Testflight and install the pre-release of Thunkable via this link: https://testflight.apple.com/join/7rBLpV07

**Comment by victoriachin84** [comment]
> Please download Testflight and install the pre-release of Thunkable via this link: https://testflight.apple.com/join/7rBLpV07

Yes I have tried and it is working. When will this update be available in the app store? Thanks!

**Comment by ChristoDeluxe** [comment]
The update in TestFlight seems to be stable for me, doesn't crash, was able to sign in and run apps from the web to the phone as expected -- any update on when this might get pushed up to the app store?

**Comment by mark-friedman** [comment]
@ChristoDeluxe Glad the TestFlight version is working well for you!  The app store version update is currently in Apple's hands for review.  There's no telling right now how long that review might take.

**Comment by mark-friedman** [comment]
The app store version has finally been updated.  Some users have had some issues, so if it fails for you please file (or add you comments to) a new bug describing the problem and adding what phone and iOS version you are testing with.
