### ISSUE TITLE
(Thunkable X) Crash in Live app on Android when trying to set a error type or value property using an simple and "any" block

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#288]
These blocks cause crash in Live on Android. In Live on iOS сrash no - wrong values ​​are ignored.

![изображение](https://user-images.githubusercontent.com/20015046/67859998-f12eff80-fb2d-11e9-9d90-95939c64bffb.png)

**Comment by jane-d-alt** [comment]
Such a block now fails silently on Android. Apologies for not following up when this behavior was originally resolved. Thanks for reporting!
