### ISSUE TITLE
(Thunkable X) Mismatch line height dimensions with components height

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#289]
Column Height and Label line height are set to 500 px. On iOS 12.4 height components are the same, but on Android 8.1 and Live on Android is not the same as seen in the screenshot.

![изображение](https://user-images.githubusercontent.com/20015046/68014361-63275600-fca0-11e9-856d-a4a31e7a6dc9.png)

In Bluestackes 4 height equal

![изображение](https://user-images.githubusercontent.com/20015046/68016469-b64fd780-fca5-11e9-91bc-10c6716e0ce6.png)

**Comment by domhnallohanlon** [comment]
Hey @AlexITMan , 

You should use the `height` property to set the height of your label rather than `line height`

The line height is a different property entirely. See more here:
https://stackoverflow.com/questions/23247467/how-css-line-height-is-measured
