### ISSUE TITLE
Button visible false via blocks not working on Android

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#291]
### Platform
X

### Issue/Request Origin
Thunkable live & built app (Android only)

### Steps to Reproduce
1. try to set a buttons visibility to false via blocks
2. wont work at all in Android

### Expected Behavior
Button to be hidden

### Actual Behavior
nothing happens on Android, works as expected on iOS

**Comment by domhnallohanlon** [comment]
MWE:
https://x.thunkable.com/copy/36d7b476763462c24787fbcd54c47937

Origin:
https://community.thunkable.com/t/button-visible-false-not-working-for-android/300903?u=domhnall

**Comment by domhnallohanlon** [comment]
@gre4twh1te following up/closing this now. 

Just retesting with the following blocks and the visibility is toggling as expected:
![Screenshot 2021-01-15 at 15 39 45](https://user-images.githubusercontent.com/3117345/104748217-5f6adc80-5749-11eb-8f35-16ac75f8692e.png)
