### ISSUE TITLE
Google Maps not showing "ShowsMyLocationButton" and other maps components

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#292]
### Platform
X

### Issue/Request Origin
Google Maps component on Android

### Steps to Reproduce
1. Add Google Maps component to Thunkable X
2. enable "show user location icon"

### Expected Behavior
show user location icon

### Actual Behavior
does not show on Android.

Also several other on screen components do not show properly like ShowsCompass, ShowsScale - these do also not work on iOS.

**Comment by domhnallohanlon** [comment]
Community post:
https://community.thunkable.com/t/google-maps-bug-on-android/296509?u=domhnall

**Comment by jane-d-alt** [comment]
This behavior has been resolved. Make sure that you have granted location permission to your built APK or to the Thunkable Live app (screenshot of permissions page included). We'll close this issue now; apologies for not following up when this behavior was originally resolved.
![Screenshot_20210115-154859](https://user-images.githubusercontent.com/51848939/104748209-5da11900-5749-11eb-82e5-6cb485452a08.jpg)
