### ISSUE TITLE
Made with Thunkable branding not being removed with PRO account (iOS)

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#293]
### Platform
X

### Issue/Request Origin
built App for iOS

### Steps to Reproduce
1. building app with PRO account
2. installing on iOS device

### Expected Behavior
removed "made with Thunkable" branding

### Actual Behavior
"made with Thunkable" branding appears and shortly after the app icon launch screen appears In the gif below it is quite short but it also happens to show longer:

![ezgif-1-c423323bc05c](https://user-images.githubusercontent.com/37402054/68140318-e9a39800-ff2b-11e9-87a8-c346f091cf41.gif)

**Comment by domhnallohanlon** [comment]
Origin:
https://community.thunkable.com/t/made-with-thunkable-not-disappearing-in-pro-ios/301275?u=domhnall

**Comment by jane-d-alt** [comment]
The linked community post is marked as Solved, so we'll close this issue as well. Please reach out if similar behavior is seen with future apps!
