### ISSUE TITLE
Feature request: "Copy block to other screen" option

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#294]
**Is your feature request related to a problem? Please describe.**
This is a feature request

**Describe the solution you'd like**
We would like to be able to copy blocks from one screen to another. This would be super useful for duplicating functionality across screens such as functions and other extremely complex blocks. It could look something like this:

![image](https://user-images.githubusercontent.com/7762893/68189841-8a399c80-ffac-11e9-8b47-c0c1020bec5f.png)

**Describe alternatives you've considered**
Spending time on re-creating complex blocks in new screens. Not an option really...

**Which platform are you asking for?**
Thunkable X

**Additional context**
Check screenshot above

**Comment by kezb765** [comment]
Hi @AmigoDeluxe,
this feature exists in ThunkableX: select a block in screen A, press "Cmd-c" (=copy), change to screen B and press "Cmd-v" (=paste). Then your block gets copied!

**Comment by AmigoDeluxe** [comment]
I would swear I've tried this already and it did not work. Does now. Respect!
