### ISSUE TITLE
Get index of clicked buttons created with "clone"

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#295]
I generated buttons with "Any component -> clone". Let's say I have created 4 buttons. When I click on one of them, the "When any button click" event gets fired.

**Describe the solution you'd like**
I want to know **which button** was clicked. I could test the buttontext from the result, but maybe the text is the same in all 4 buttons. So I want to have some sort of **index** as a result. Maybe this helps also for other components, _button_ is just an example.

Thunkable ✕ (x.thunkable.com)

**Additional context**
I really love to work with "Any component", it is of GREAT help! Sorry for this request if this feature exists, please let me know.

**Comment by AlexITMan** [comment]
![изображение](https://user-images.githubusercontent.com/20015046/68317719-a9c7e680-00cc-11ea-8b6a-1e0abb081c78.png)

**Comment by AmigoDeluxe** [comment]
Hey @AlexITMan, I know you are super-knowledgable but I just fail to see how the above example helps. There must be a way to tag the buttons in a unique way so you can refer to them, like tagging them somehow. I do have something evil in mind which I will share later on but I would like to understand your solution first. 

Konstantinos

**Comment by AlexITMan** [comment]
Hey Konstantinos, 

On the top block, as you can see, I create 5 buttons. After creating these buttons, I assign each button a unique name indexN, where N is the counter of cycle i.

For convenience, I save this unique name in the Message property of the button. The button does not have such a block, for this reason I chose the Alert type, which has it. Simply put, I added the Message property to the button and assigned it a string with the name of the component. Now do you get the idea?

Why did I choose the Message property to store the button name? Because it seems to me that this is a suitable property. You can save the name of the button in any other property that can store the string - URL, Title, BackgroundPicture, Hint, etc. But for this you must choose the type that has this property.

Alex

**Comment by AmigoDeluxe** [comment]
VERY smart and interesting!!! Wow! Here is my approach ([sample app](https://x.thunkable.com/copy/d562cb5b52b34d767d8e844edc3e9596)):

**Basic concepts**
1. Each element has its own identifier (a random string)
2. It is important to understand in which order the elements get created when cloned
3. If you know the order the elements get cloned then you know how to refer to them (i.e. 1st button in 2nd column, 3rd button in 1st column)

**The setup**
So let’s start with a basic example. We create a prototype we will be cloning, a simple column which contains 2 buttons. We will be cloning the prototype 3 times which will result to 3 columns and 6 buttons as each cloned column will contain 2 buttons.

![image](https://user-images.githubusercontent.com/7762893/68757402-8fce5c80-0614-11ea-8f04-a68a7dcbdaf0.png)

**The challenge**
How to change the background color of any of the two buttons in any of the cloned columns.

**The answer**
We need to identify in which order the columns and buttons within them get created. In this example it is top to bottom and I assume that it is also left to right, if designed as such:

![image](https://user-images.githubusercontent.com/7762893/68757451-a1afff80-0614-11ea-8310-d34325aaba80.png)

We now need to get the identifiers of the cloned elements, 3 columns and 2 buttons per column. This is where we use the “all (element) in (element)” block. This basically returns a list which we can store in a list variable. So if we are aiming at the 2nd cloned column, it will be the 2nd list item which contains the unique identifier of that column. Having that, we can apply the same logic for the elements of that column meaning, the buttons and aim at either the 1st or the 2nd button in that cloned column and then change any of its properties. So here is what my block logic looks like to change the background color of the 2nd button in the 1st column:

![image](https://user-images.githubusercontent.com/7762893/68757484-ac6a9480-0614-11ea-9cd5-bbc2dff09ba3.png)

Which results to this:

![image](https://user-images.githubusercontent.com/7762893/68757519-be4c3780-0614-11ea-9d98-de7eb9fe2daa.png)

So the secret sauce to this is the use of the “all (element) in (element)” block which returns the identifiers of the elements we are creating by cloning. If you master this block, you can do crazy things...

Happy to hear back from you.

Konstantinos

**Comment by AlexITMan** [comment]
More universal solution. Here we find the indices of all the components on the screen.

![изображение](https://user-images.githubusercontent.com/20015046/68764738-50ac0580-062c-11ea-85da-a221781cab3a.png)

**Comment by AmigoDeluxe** [comment]
This is awesome! The “all (element) in (element)” block rocks!

**Comment by kezb765** [comment]
Hey all, thank you for the great reply!

I implemented a sample (see screenshot), it works perfect:
- it works, even when the texts of the buttons are in different order or the texts are used more than once (my first thought was to analyse the text: "when anyButton->Click: look at the text...").

One more question: 
- is it possible to change the whole list? The buttons can be deleted with "remove (all button in Row1)", but how gets the list in Alert1 refreshed?

![grafik](https://user-images.githubusercontent.com/7669660/69040459-207ab300-09ee-11ea-9b99-90fc905386b0.png)

And ... for me, the section "Any component" is the greatest invention ever!

**Comment by kezb765** [comment]
Hi @AmigoDeluxe , @AlexITMan and others, I just found an easier solution: I read today, that it is possible to assign a text / number to button "background", like so:

![grafik](https://user-images.githubusercontent.com/7669660/69052542-93dcee80-0a07-11ea-89c2-741f963cc652.png)

That way there is no need to use a second component like "Alert1", all values are store inside of "button".

If you need to set the background to a color, you can use this technique also. Just set the background to a string that contains the color plus the index separated with i.e. a ";". In the "AnyButton-Click" block you have to search for the ";" in the "background"-value of the selected block. I tested it, it really works.

**Comment by mark-friedman** [comment]
I'll just point out that we will, hopefully soon, support custom properties on components. That will allow you to create your own property (e.g. "index") on the clone so that you won't have to re-use an existing property.

**Comment by kezb765** [comment]
Hi @mark-friedman , thank you for this information. That sounds good to me!

**Comment by coiddaa355** [comment]
![32F6FCF8-CC07-4B72-B20B-B6857E5A7F93](https://user-images.githubusercontent.com/58005036/69265911-6e4c1280-0bca-11ea-9615-7457464789d8.png)

I do it like that and than on screen start execute function

**Comment by mark-friedman** [comment]
@coiddaa355 How does your comment relate to the topic of this GitHub issue?  If it doesn't, please file a separate GitHub issue, explain your problem and provide a link to a simple project which demonstrates the problem.

**Comment by coiddaa355** [comment]
> @coiddaa355 How does your comment relate to the topic of this GitHub issue? If it doesn't, please file a separate GitHub issue, explain your problem and provide a link to a simple project which demonstrates the problem.

Because it works it shows the index !!??

**Comment by MaxBushido** [comment]
Thank you guys,
in my app I have to clone a set of 3 different buttons and 3 different labels and this helped me giving me the idea to use lists and now the app works well enough, thanks!
