### ISSUE TITLE
Date/Time Components Format Unchangeable at Runtime

### ISSUE THREAD

**Issue by lisa-itmgr** [thunkable/thunkable-issues#298]
### Platform
✕

### Issue/Request Origin
I found it

### Steps to Reproduce
1. Create new project and add Date Input component to Screen1
2. Add blocks as in screenshot
3. Observe displayed date

(The same steps can be followed to reproduce the same issue with the Time Input component.)

### Expected Behavior
Expected displayed date to change format to 'YYYY-MM-DD'

### Actual Behavior
Date format does not change but remains in default format

  STACK TRACE AND/OR SCREENSHOTS
<img width="532" alt="Screen Shot 2019-11-10 at 19 33 15" src="https://user-images.githubusercontent.com/48545464/68561722-06b5fa80-0447-11ea-84e4-37db8d42154f.png">
(note: label is not necessary)

**Comment by mark-friedman** [comment]
Thanks for the bug report, @lisa-itmgr!  We'll look into it.

**Comment by AmigoDeluxe** [comment]
It would be nice to be able to define custom formats too...

**Comment by jane-d-alt** [comment]
Mark's linked issue is closed, so we'll close this issue as well. Apologies for not following up when the linked issue was originally resolved.
