### ISSUE TITLE
Native ads

### ISSUE THREAD

**Issue by Kiranmadde** [thunkable/thunkable-issues#3]
**Is your feature request related to a problem? Please describe.**
If native ads are available in Thunkable then it will be awesome!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by weihuali0509** [comment]
Thanks for the suggestion. Do you want to see Native Ads on app.thunkable.com or x.thunkable.com?

**Comment by Kiranmadde** [comment]
I want native ads in Thunkable classic android
