### ISSUE TITLE
Canvas - Transparent Background Color or Background Image Support

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#300]
**Is your feature request related to a problem? Please describe.**
Canvas does not support Transparent background colors.

**Describe the solution you'd like**
Allow Canvas to have a transparent background color so you can see the background image.

**Describe alternatives you've considered**
Provide a background image property to the Canvas. 

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by mark-friedman** [comment]
Thanks for the feature request, Joe!

**Comment by MrMazzone** [comment]
Background image support has been added to the Canvas 🎉
