### ISSUE TITLE
Buttons placed above Maps component not working on Android OS

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#301]
### Platform
Thunkable X, Android

### Issue/Request Origin
-

### Steps to Reproduce
1. add a button
2. position absolute and higher z-index 
3. place above a map component
4. press button

### Expected Behavior
Should trigger ButtonPressed event

### Actual Behavior
Will work as expected on iOS but not call buttons events on Android instead will trigger "map touched" event

**Comment by AlexITMan** [comment]
In Live on Android 8.1, everything works fine for me. The event from the button passes.

**Comment by domhnallohanlon** [comment]
@AlexITMan what blocks are you using? Does this work when Live Testing and Installing?

@gre4twh1te ditto!

**Comment by domhnallohanlon** [comment]
@AlexITMan @gre4twh1te I'm going to close this now as the behaviour seems to be fixed. 

Screenshot below of the simple test I ran. (the button worked at the default size too!)

![button_on_map](https://user-images.githubusercontent.com/3117345/104750412-f9338900-574b-11eb-847b-243a8caf5740.png)
