### ISSUE TITLE
Need at least one event for Text Input

### ISSUE THREAD

**Issue by itdir** [thunkable/thunkable-issues#303]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to perform context-sensitive logic related to Text Input components. For example it is not possible to enable a Button or change its caption based on the state of a Text Input.

**Describe the solution you'd like**
Please implement at least one event for the Text Input such as When TextInput... Focus() or Click() or Change().  Something... anything.

**Describe alternatives you've considered**
With no events for most components, there really isn't much that can be tried.  I was even hoping there would be a "When Any Text Input" event, but there isn't.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
This request is related to issues #111 and #92, but is not the same.

**Comment by AlexITMan** [comment]
You can implement the onChange event for Text Input using the Timer component.

**Comment by nicbyron** [comment]
+1 on this. Would be nice to trigger logic based off of a user hitting the return key as well as if the keyboard is in focus or not.

**Comment by mark-friedman** [comment]
Thanks for the requests @itdir, @AlexITMan and @nicbyron!

**Comment by jane-d-alt** [comment]
Text Input now has the following events:
When Text Input Click
When Text Input Changes
When Text Input Unfocus
When Text Input Submit

We'll close this issue now; apologies for not following up when these blocks were originally added.
