### ISSUE TITLE
(Thunkable X) Strange interaction of cloning with recursive function

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#304]
Press Button 2. After this, the creation of 10 buttons should occur.

https://x.thunkable.com/projects/5db93ebab8e0fc9c685b3477/project/properties/designer/

But this does not happen.

![изображение](https://user-images.githubusercontent.com/20015046/69239954-76955500-0bac-11ea-864f-aa28b83ca505.png)

Remove Column1 set Visible block - buttons will start to be created. The second problem is that the block must create 10 buttons. But when you reopen the application, a different number can be created - 4, 9, etc. This will be clearly visible if you remove the wait block in the function.

**Comment by mark-friedman** [comment]
Interesting.  I have a theory, but first let me ask you a question @AlexITMan.  Does the behavior change if you remove the `'change x by -1'` block and replace the recursive call to `'bagFunction with: x'` by `'bagFunction with: x - 1'`?

**Comment by coiddaa355** [comment]
There is also the bug when you clone objects that get data from airtable it doesn't show to cloned blocks only if you touch or scroll the screen

**Comment by mark-friedman** [comment]
@coiddaa355 That seems like a different problem than the one that Alex is talking about.  Could you please file a separate GitHub issue for your problem and include a link to a simple app which demonstrates your issue?

Thanks in advance.

-Mark

**Comment by coiddaa355** [comment]
I have done that 
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Wed, Nov 20, 2019 at 7:17 PM +0100, "mark-friedman" <notifications@github.com> wrote:












@coiddaa355 That seems like a different problem than the one that Alex is talking about.  Could you please file a separate GitHub issue for your problem and include a link to a simple app which demonstrates your issue?


Thanks in advance.


-Mark

**Comment by coiddaa355** [comment]
https://github.com/thunkable/thunkable-issues/issues/305    	    	
    	 Holen Sie sich Outlook für iOS      



On Wed, Nov 20, 2019 at 7:17 PM +0100, "mark-friedman" <notifications@github.com> wrote:












@coiddaa355 That seems like a different problem than the one that Alex is talking about.  Could you please file a separate GitHub issue for your problem and include a link to a simple app which demonstrates your issue?


Thanks in advance.


-Mark

**Comment by coiddaa355** [comment]
https://github.com/thunkable/thunkable-issues/issues/305

**Comment by coiddaa355** [comment]
I have done it

**Comment by coiddaa355** [comment]
> @coiddaa355 That seems like a different problem than the one that Alex is talking about. Could you please file a separate GitHub issue for your problem and include a link to a simple app which demonstrates your issue?
> 
> Thanks in advance.
> 
> -Mark

I have that

**Comment by AlexITMan** [comment]
`Interesting. I have a theory, but first let me ask you a question @AlexITMan. Does the behavior change if you remove the 'change x by -1' block and replace the recursive call to 'bagFunction with: x' by 'bagFunction with: x - 1'?`

@Mark, Nothing changed after I deleted the block and replaced the function call as you wrote

**Comment by mark-friedman** [comment]
Thanks, @AlexITMan!

**Comment by mark-friedman** [comment]
I have been able to reproduce this behavior described by Alex on both iOS and Android live companion apps with the current production versions of those companion apps.

**Comment by mark-friedman** [comment]
Interestingly I don't see the problem is I replace the recursive function call with a simple `repeat` block.  Consequently, I revised the issue title.

**Comment by mark-friedman** [comment]
@AlexITMan Do you know if this is new behavior (i.e. the last 3 days or so) or if you were seeing this behavior before that?

**Comment by AlexITMan** [comment]
This happened after Live was updated to version 120. Before that, I had never seen a situation where using a block would cause the block below it to fail. Also up to Live ver. 120 I cloned the components using a recursive function and did not see the situation that instead of the specified number of blocks, the wrong number was displayed on the screen.

**Comment by AlexITMan** [comment]
I see that the problem is resolved. I close the question.
