### ISSUE TITLE
Thunkable X Cloned blocks only show on scroll or tap

### ISSUE THREAD

**Issue by coiddaa355** [thunkable/thunkable-issues#305]
Hello, 
So my app worked great until yesterday. 
https://share.icloud.com/photos/0223cgrZd6QpYDrBaxmYgBRkQ#Luxemburg
So what you see is on scroll the first time and on the second time i open the app is on tap one block shows up. .. 
My blocks ( on the screen shot we don't see the on screen start ( execute function ) 
![0E60A3AD-8B33-43F3-9F45-C433776BD3BB](https://user-images.githubusercontent.com/58005036/69265713-039ad700-0bca-11ea-8fda-589efb842740.png)

**Comment by mark-friedman** [comment]
@coiddaa355 Instead of a screenshot, could you please provide either a direct browser link to your project or a copy/share link (see [here](http://docs.thunkable.com/share-1) for how)?  Also, is there any chance that you could create a simpler example that shows the problem?

Also, can you tell me what device and iOS version you testing with?

Thanks.

-Mark

**Comment by coiddaa355** [comment]
> @coiddaa355 Instead of a screenshot, could you please provide either a direct browser link to your project or a copy/share link (see [here](http://docs.thunkable.com/share-1) for how)? Also, is there any chance that you could create a simpler example that shows the problem?
> 
> Also, can you tell me what device and iOS version you testing with?
> 
> Thanks.
> 
> -Mark

I think is the simplest way to share a record from a apple phone. 
I have a iphone 11 pro max ios 13.3 beta 2 
Here is the link, you want the api key to ? 
https://x.thunkable.com/copy/c68570225aba348d0cc569ae3a4a4fc5

**Comment by mark-friedman** [comment]
Thanks @coiddaa355!  Videos and screenshots are useful for showing us the problems or issues you are having look like and act like.  Browser links and copy/share links help us to more replicate that behavior, since we can then access you actual design and blocks.  Simpler, test projects allow us to isolate the possible causes to a smaller set of components and blocks.

I hope this all makes sense.

-Mark

**Comment by coiddaa355** [comment]
api key keyDqBSzj6y77spxg

**Comment by mark-friedman** [comment]
@coiddaa355, I am the one redacting your API keys, so that other people don't get them :-)

**Comment by coiddaa355** [comment]
ahh okay thx but it's only a test api but thx for pay attention for this details 
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Thu, Nov 21, 2019 at 1:07 AM +0100, "mark-friedman" <notifications@github.com> wrote:












@coiddaa355, I am the one redacting your API keys, so that other people don't get them :-)

**Comment by mark-friedman** [comment]
>it's only a test api but thx for pay attention for this details

Just being careful!

-Mark

**Comment by mark-friedman** [comment]
@coiddaa355 Unfortunately, we don't see the same behavior when testing your app (in either live mode or downloaded) as you describe and show in your video.  So far we've only tested it on an older iPhone.  Maybe it's an issue with that's affected by the phone model, so we'll try it on a newer phone and see if we see any difference.

**Comment by coiddaa355** [comment]
> @coiddaa355 Unfortunately, we don't see the same behavior when testing your app (in either live mode or downloaded) as you describe and show in your video. So far we've only tested it on an older iPhone. Maybe it's an issue with that's affected by the phone model, so we'll try it on a newer phone and see if we see any difference.


Okay thanks, I'm not the only one in the community with this

**Comment by coiddaa355** [comment]
Are my blocks good like that or is there a better to do that ?

**Comment by coiddaa355** [comment]
The strange thing is that everthing was perfect before the update two days ago ...

**Comment by coiddaa355** [comment]
> @coiddaa355 Unfortunately, we don't see the same behavior when testing your app (in either live mode or downloaded) as you describe and show in your video. So far we've only tested it on an older iPhone. Maybe it's an issue with that's affected by the phone model, so we'll try it on a newer phone and see if we see any difference.

Anything new ? People continue complaining on the community with this problem

**Comment by mark-friedman** [comment]
We're working on it.  Unfortunately, we haven't been able to reproduce the problem so far, so it has been hard to diagnose.

**Comment by coiddaa355** [comment]
I tried it mon ipad on ios 13 no beta and it does the same, and like I said in the community are a lot of others with that problem 
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Thu, Nov 21, 2019 at 7:04 PM +0100, "mark-friedman" <notifications@github.com> wrote:












We're working on it.  Unfortunately, we haven't been able to reproduce the problem so far, so it has been hard to diagnose.

**Comment by coiddaa355** [comment]
But thanks :) waiting for good news
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Thu, Nov 21, 2019 at 7:04 PM +0100, "mark-friedman" <notifications@github.com> wrote:












We're working on it.  Unfortunately, we haven't been able to reproduce the problem so far, so it has been hard to diagnose.

**Comment by coiddaa355** [comment]
It’s working have you done something  ?

 

dany coimbra

 

T :   +352 266 360 604

M :  +352 621 724 401

leitmotif I 11, rue des Capucins I L-1313 Luxembourg

www.leitmotif.lu

 

 

Von: mark-friedman <notifications@github.com>
Antworten an: thunkable/thunkable-issues <reply@reply.github.com>
Datum: Donnerstag, 21. November 2019 um 19:04
An: thunkable/thunkable-issues <thunkable-issues@noreply.github.com>
Cc: coiddaa355 <d.coimbra@leitmotif.lu>, Mention <mention@noreply.github.com>
Betreff: Re: [thunkable/thunkable-issues] Thunkable X Cloned blocks only show on scroll or tap (#305)

 

We're working on it. Unfortunately, we haven't been able to reproduce the problem so far, so it has been hard to diagnose.

**Comment by mark-friedman** [comment]
>It’s working have you done something  ?

Yes!  We discovered and (hopefully) fixed the issue.

**Comment by coiddaa355** [comment]
It's working for me :D thx
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Fri, Nov 22, 2019 at 6:41 PM +0100, "mark-friedman" <notifications@github.com> wrote:














It’s working have you done something  ?





Yes!  We discovered and (hopefully) fixed the issue.
