### ISSUE TITLE
Animation / Fade out & in

### ISSUE THREAD

**Issue by coiddaa355** [thunkable/thunkable-issues#307]
Hello, 
It could nice if we could add animations to the blocks like fade out fade in / slow,fast or time settings. 
Or bounce, fly in.. because it would bring thunkable to a new level !

**Comment by AlexITMan** [comment]
This can be done by changing the transparency of the component by timer.

**Comment by coiddaa355** [comment]
I know this to but expo the framework they use have it ! So they can implement it to thunkable ? Why always propose to work around if the things exist natively 
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Thu, Nov 21, 2019 at 3:01 PM +0100, "AlexITMan" <notifications@github.com> wrote:












This can be done by changing the transparency of the component by timer.

**Comment by AlexITMan** [comment]
Why do I offer workarounds and crutches for the functionality that exists in expo? Because there are only 2 possible answers:

1) are you ready to wait for the developers to add the necessary functionality
2) you are not ready to wait for the developers to add the necessary functionality

You yourself choose the answer.

**Comment by coiddaa355** [comment]
I ready to have a good working nice looking app so I will wait 
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Thu, Nov 21, 2019 at 9:11 PM +0100, "AlexITMan" <notifications@github.com> wrote:












Why do I offer workarounds and crutches for the functionality that exists in expo? Because there are only 2 possible answers:

are you ready to wait for the developers to add the necessary functionality
you are not ready to wait for the developers to add the necessary functionality



You yourself choose the answer.

**Comment by gre4twh1te** [comment]
> This can be done by changing the transparency of the component by timer.

not really because this is likely to not be smooth at all especially on Android devices and a not so powerful processor... also there seems to be a real issue with the timer component on Android - when you set short timeframes it becomes really buggy...

**Comment by jane-d-alt** [comment]
Closing as this issue overlaps with #172.
