### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by coiddaa355** [thunkable/thunkable-issues#309]
Hello, 
It would nice to have a pull to refresh, to update a page where data is please

**Comment by gre4twh1te** [comment]
I think this feature could be useful with several components like webview, listview, reseting forms... 👍

**Comment by mark-friedman** [comment]
I agree that this would be a generally useful feature!

**Comment by coiddaa355** [comment]
So let's build it lol

**Comment by domhnallohanlon** [comment]
@coiddaa355 @gre4twh1te closing this as pull to refresh is available for both the data viewer and the web viewer now:

https://community.thunkable.com/t/solved-how-do-i-increment-values-in-the-data-viewer-list/590659/7?u=domhnallohanlon

Thanks again!
