### ISSUE TITLE
Textbox content editable despite not being enabled (Thunkable X)

### ISSUE THREAD

**Issue by Hrist0S** [thunkable/thunkable-issues#31]
### Platform
Thunkable X

### Issue/Request Origin
User contacted support staff with this issue through Intercom. 

### Steps to Reproduce
1. Open the public app project at the following link: 
https://x.thunkable.com/projects/5b3732b9a6a98a07bd1759e1/Aconite%20Info/designer

2. Open the app using the Thunkable Live App.

3. Tap 'Explore' on the first screen.

4. Tap 'Herbs' on the second screen.

5. Tap 'Aconite' on the third screen.

6. Tap the 'Family Name' textbox, or any other on the page.

### Expected Behavior
The keyboard should not be opened, and the user should not be able to type into any Textbox, as they all have their 'Editable' property set to 'false'.

### Actual Behavior
The keyboard is opened, and the user is able to type into all of the Textboxes on the screen.

  STACK TRACE AND/OR SCREENSHOTS

![firstscreen](https://user-images.githubusercontent.com/41082935/42539495-29232410-8493-11e8-9e10-08759d87aea3.jpg)

![secondscreen](https://user-images.githubusercontent.com/41082935/42539521-39f1a730-8493-11e8-8224-2e4b87e9bc30.jpg)

![thirdscreen](https://user-images.githubusercontent.com/41082935/42539529-3c288370-8493-11e8-8d9e-1e8f42b9d9ed.jpg)

![fourthscreen](https://user-images.githubusercontent.com/41082935/42539534-41afb1d8-8493-11e8-923e-3eef39584499.jpg)

**Comment by jane-d-alt** [comment]
This issue was resolved shortly after being reported. We'll close this issue; apologies for not following up when this issue was originally resolved.
