### ISSUE TITLE
Gallery block

### ISSUE THREAD

**Issue by coiddaa355** [thunkable/thunkable-issues#310]
Hello, it would be nice to have a gallery block where you can add pictures, for the best use it would be if you have a lot of images in airtable or other database that you can show them all in one gallery

**Comment by AlexITMan** [comment]
This can be done using Any blocks. Such a component will work slowly, but that is another matter.

**Comment by coiddaa355** [comment]
Tell me more about it please I allready us ant block but how you want to do a gallery with that

**Comment by AlexITMan** [comment]
See example https://x.thunkable.com/projects/5d90cb81aab4c26ef753f324/project/properties/designer/

**Comment by jane-d-alt** [comment]
This can now be done with the [Data Viewer ](https://docs.thunkable.com/data-viewers)components, as you can select a layout that displays images.
