### ISSUE TITLE
(For Thunkable X) Crash in Live on Android device and emulators

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#311]
https://x.thunkable.com/projects/5dd646080e08f22d5dabf831/project/properties/designer/

Click on the Start button in the project at the link. Crash in Bluestackes with a log (If we remove the Text change blocks for the Button and Label from the loop, then there is no crash)

11-21 11:49:31.572  4001  4034 I PlayCommon: [234] ajkk.c(29): Preparing logs for uploading
11-21 11:49:31.574  4001  4034 I PlayCommon: [234] ajkk.c(149): Connecting to server for timestamp: https://play.googleapis.com/play/log/timestamp
11-21 11:49:31.712  2016  2016 W ChimeraUtils: Non Chimera context
11-21 11:49:31.728  4001  4034 I PlayCommon: [234] ajkk.c(185): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
11-21 11:49:31.817  4001  4034 I PlayCommon: [234] ajkk.c(214): Successfully uploaded logs.
11-21 11:49:49.430  1534  1564 I audio_hw_primary: choose pcmC0D0p for 0
11-21 11:49:49.486  1534  1564 D AudioFlinger: mixer(0xb6d3b010) throttle end: throttle time(30)
11-21 11:49:50.794  3744  3744 D SoLoader: init exiting
11-21 11:49:50.796  1787  2072 I ActivityManager: START u0 {flg=0xc080000 cmp=com.thunkable.live/host.exp.exponent.MainActivity} from uid 10078 on display 0
11-21 11:49:50.797  1787  2072 D ActivityManager: TopActivityInfo, pkgName: com.thunkable.live activityName: host.exp.exponent.MainActivity callingPackage: com.thunkable.live  bstSpecialAppKeyboardHandlingEnabled = false
11-21 11:49:50.797  1787  2072 D ActivityManager: Sending app launch intent for appName: Thunkable pkgName: com.thunkable.live
11-21 11:49:50.798  1787  2072 I ActivityManager: Ignoring FLAG_ACTIVITY_NEW_DOCUMENT, launchMode is "singleInstance" or "singleTask"
11-21 11:49:50.798  1787  4379 D ActivityManager: Sending TopActivity Info
11-21 11:49:50.819  3744  4318 W FPStaticServerModule: Stopped Server
11-21 11:49:50.820  3744  3744 E unknown:ReactNative: Tried to remove non-existent frame callback
11-21 11:49:50.820  3744  3744 W unknown:ReactNative: Not flushing pending UI operations because of previously thrown Exception
11-21 11:49:50.825  1787  1799 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10078/3744 clientId=android.media.AudioManager@9ec988cexpo.modules.av.AVManager@8304af5
11-21 11:49:50.839  1787  3205 D ActivityManager: TopActivityInfo, pkgName: com.thunkable.live activityName: com.thunkable.live/host.exp.exponent.MainActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
11-21 11:49:50.848  1787  4382 D ActivityManager: Sending TopActivity Info
11-21 11:49:50.849  1787  3205 D ActivityManager: Sending app launch intent for appName: Thunkable pkgName: com.thunkable.live
11-21 11:49:50.850  1787  3205 D WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true
11-21 11:49:50.874  1787  3205 I PGA     : PgaSocketInit: opened /dev/bstpgaipc: fd = 271
11-21 11:49:50.874  1787  3205 I PGA     : Attempting to create new SOCKET connection pid = 1787, tid = 3205
11-21 11:49:50.876  1787  3205 I PGA     : PgaSocketInitClientPgaIpc: data mapped to 0x90c00000
11-21 11:49:50.876  1787  3205 I PGA     : New SOCKET connection: system_server (pid 1787, tid 3205)
11-21 11:49:50.950  1787  3205 V WindowManager: isVisibleLw false for win : Window{675b8dc u0 com.thunkable.live/host.exp.exponent.MainActivity}
11-21 11:49:50.954  3744  3744 W unknown:ReactNative: Not flushing pending UI operations because of previously thrown Exception
11-21 11:49:50.956  1787  1813 W art     : Long monitor contention with owner Binder:1787_C (3205) at void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder)(ActivityManagerService.java:7079) waiters=2 in void com.android.server.am.ActivityManagerService$3.handleMessage(android.os.Message) for 121ms
11-21 11:49:51.005  3744  3744 W a       : Could not find listener for key: openOptimisticExperienceActivity
11-21 11:49:51.005  3744  3744 W a       : Could not find listener for key: openExperienceActivity
11-21 11:49:51.005  3744  3744 D SoLoader: init exiting
11-21 11:49:51.052  3744  3865 E GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
11-21 11:49:51.109  3744  4387 W a       : Could not find listener for key: devicePushToken
11-21 11:49:51.114  1787  2188 D InputMethodManagerService: packageName=com.thunkable.live, activityName=host.exp.exponent.MainActivity
11-21 11:49:51.114  1787  2188 D InputMethodManagerService: ime_enabled = false is same as last value, no change
11-21 11:49:51.121  3744  4386 D b       : Using cached or embedded response.
11-21 11:49:51.122  3744  4386 D b       : Got cached OkHttp response for https://d1wp6m56sqw74a.cloudfront.net/%40thunkable%2FthunkableCompanion%2F1.0.0%2Fd3ee03488f2250837eacb1a6e78192ba-34.0.0-android.js
11-21 11:49:51.124  3744  4386 D b       : Have cached source file for https://d1wp6m56sqw74a.cloudfront.net/%40thunkable%2FthunkableCompanion%2F1.0.0%2Fd3ee03488f2250837eacb1a6e78192ba-34.0.0-android.js
11-21 11:49:51.125  1787  1821 I ActivityManager: Displayed com.thunkable.live/host.exp.exponent.MainActivity: +276ms
11-21 11:49:51.128  3744  3744 D SoLoader: init exiting
11-21 11:49:51.130  1787  1944 D WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true
11-21 11:49:51.131  3744  3744 W a       : Could not find listener for key: readyForBundle
11-21 11:49:51.132  3744  3744 E c       : java.lang.RuntimeException: A TaskDescription's primary color should be opaque
11-21 11:49:51.140  3744  3744 D ReactNative: ReactInstanceManager.ctor()
11-21 11:49:51.140  3744  3744 D SoLoader: init exiting
11-21 11:49:51.145  3744  3744 D ReactNative: ReactInstanceManager.createReactContextInBackground()
11-21 11:49:51.145  3744  3744 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
11-21 11:49:51.145  3744  3744 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
11-21 11:49:51.145  3744  3744 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-21 11:49:51.145  3744  3744 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-21 11:49:51.146  3744  4388 D ReactNative: ReactInstanceManager.createReactContext()
11-21 11:49:51.171  3744  4388 I TextToSpeech: Sucessfully bound to com.svox.pico
11-21 11:49:51.173  3744  4388 D ReactNative: Initializing React Xplat Bridge.
11-21 11:49:51.182  3744  4388 D ReactNative: Initializing React Xplat Bridge before initializeBridge
11-21 11:49:51.185  3744  4388 D ReactNative: Initializing React Xplat Bridge after initializeBridge
11-21 11:49:51.185  3744  4388 D ReactNative: CatalystInstanceImpl.runJSBundle()
11-21 11:49:51.185  3744  4388 D CatalystInstanceImpl: Loading script from file
11-21 11:49:51.187  3744  3744 I TextToSpeech: Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
11-21 11:49:51.201  3744  4392 D ReactNative: ReactInstanceManager.setupReactContext()
11-21 11:49:51.202  3744  4392 D ReactNative: CatalystInstanceImpl.initialize()
11-21 11:49:51.204  3744  4393 I TextToSpeech: Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
11-21 11:49:51.205  3744  4392 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
11-21 11:49:51.213  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
11-21 11:49:51.214  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
11-21 11:49:51.215  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
11-21 11:49:51.215  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
11-21 11:49:51.216  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
11-21 11:49:51.216  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
11-21 11:49:51.216  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
11-21 11:49:51.217  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
11-21 11:49:51.217  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
11-21 11:49:51.218  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
11-21 11:49:51.218  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
11-21 11:49:51.221  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
11-21 11:49:51.222  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
11-21 11:49:51.222  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
11-21 11:49:51.223  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
11-21 11:49:51.224  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
11-21 11:49:51.226  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
11-21 11:49:51.228  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
11-21 11:49:51.228  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
11-21 11:49:51.229  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
11-21 11:49:51.231  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
11-21 11:49:51.231  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
11-21 11:49:51.233  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
11-21 11:49:51.233  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
11-21 11:49:51.234  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
11-21 11:49:51.235  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
11-21 11:49:51.236  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
11-21 11:49:51.236  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
11-21 11:49:51.240  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
11-21 11:49:51.240  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
11-21 11:49:51.241  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$GroupViewManager
11-21 11:49:51.243  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$RenderableShadowNode
11-21 11:49:51.244  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$PathViewManager
11-21 11:49:51.244  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$CircleViewManager
11-21 11:49:51.245  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$EllipseViewManager
11-21 11:49:51.245  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$LineViewManager
11-21 11:49:51.246  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$RectViewManager
11-21 11:49:51.247  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$TextViewManager
11-21 11:49:51.248  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$TSpanViewManager
11-21 11:49:51.251  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$TextPathViewManager
11-21 11:49:51.252  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$ImageViewManager
11-21 11:49:51.252  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$ClipPathViewManager
11-21 11:49:51.253  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$DefsViewManager
11-21 11:49:51.253  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$UseViewManager
11-21 11:49:51.254  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$SymbolManager
11-21 11:49:51.255  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$LinearGradientManager
11-21 11:49:51.257  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$RadialGradientManager
11-21 11:49:51.259  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$PatternManager
11-21 11:49:51.260  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.RenderableViewManager$MaskManager
11-21 11:49:51.261  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.svg.SvgViewManager
11-21 11:49:51.263  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapCalloutManager
11-21 11:49:51.263  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapMarkerManager
11-21 11:49:51.265  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapPolylineManager
11-21 11:49:51.266  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapPolygonManager
11-21 11:49:51.267  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapCircleManager
11-21 11:49:51.269  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapUrlTileManager
11-21 11:49:51.270  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapWMSTileManager
11-21 11:49:51.278  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapLocalTileManager
11-21 11:49:51.279  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.maps.AirMapOverlayManager
11-21 11:49:51.280  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.lottie.LottieAnimationViewManager
11-21 11:49:51.281  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerRootViewManager
11-21 11:49:51.281  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerButtonViewManager
11-21 11:49:51.282  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.screens.ScreenContainerViewManager
11-21 11:49:51.282  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.screens.ScreenViewManager
11-21 11:49:51.283  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class versioned.host.exp.exponent.modules.api.components.webview.RNCWebViewManager
11-21 11:49:51.286  3744  4392 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class co.apptailor.googlesignin.RNGoogleSigninButtonViewManager
11-21 11:49:51.291  1787  1944 D ConnectivityService: requestNetwork for uid/pid:10078/3744 NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
11-21 11:49:51.291  1787  1852 D WIFI_UT : got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 70
11-21 11:49:51.292  2034  2034 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 70
11-21 11:49:51.292  1787  1852 D WIFI    : got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 70
11-21 11:49:51.292  1787  1870 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 70
11-21 11:49:51.322  3744  3941 D i       : WARNING: getPackageName called on ScopedContext
11-21 11:49:51.676  3744  4395 D b       : Using cached or embedded response.
11-21 11:49:51.676  3744  4395 D b       : Got cached OkHttp response for https://d1wp6m56sqw74a.cloudfront.net/%40thunkable%2FthunkableCompanion%2F1.0.0%2Fd3ee03488f2250837eacb1a6e78192ba-34.0.0-android.js
11-21 11:49:51.676  3744  4395 D b       : Have cached source file for https://d1wp6m56sqw74a.cloudfront.net/%40thunkable%2FthunkableCompanion%2F1.0.0%2Fd3ee03488f2250837eacb1a6e78192ba-34.0.0-android.js
11-21 11:49:51.705  1787  3198 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10078/3744 clientId=android.media.AudioManager@9ec988cexpo.modules.av.AVManager@8304af5
11-21 11:49:51.706  3744  3744 D ReactNative: CatalystInstanceImpl.destroy() start
11-21 11:49:51.706  3744  3744 W unknown:Fresco: Fresco has already been initialized! `Fresco.initialize(...)` should only be called 1 single time to avoid memory leaks!
11-21 11:49:51.706  3744  4318 I ReactNative: [GESTURE HANDLER] Tearing down gesture handler registered for root view versioned.host.exp.exponent.ReactUnthemedRootView{a7e4e58 V.E...... .......D 0,0-720,1280 #15}
11-21 11:49:51.707  3744  3744 D SoLoader: init exiting
11-21 11:49:51.707  1787  1858 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=14, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
11-21 11:49:51.708  3744  3744 W unknown:ImagePipelineFactory: ImagePipelineFactory has already been initialized! `ImagePipelineFactory.initialize(...)` should only be called once to avoid unexpected behavior.
11-21 11:49:51.776  3744  4393 D ReactNative: CatalystInstanceImpl.destroy() end
11-21 11:49:51.945  3744  4391 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
11-21 11:49:51.946  3744  4391 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
11-21 11:49:52.340  3744  4391 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class org.unimodules.adapters.react.views.ViewGroupManagerAdapter
11-21 11:49:52.341  3744  4391 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode

**Comment by mark-friedman** [comment]
Thanks, @AlexITMan!  We are able to reproduce the crash on Android.

**Comment by mark-friedman** [comment]
@AlexITMan Did the new release on Friday fix this?

**Comment by AlexITMan** [comment]
Yes
