### ISSUE TITLE
(Thunkable X Live) Blocks are not executed

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#312]
After clicking on the button, Label1.Text = 20, and the block for changing the text on the button does not work at all.

![изображение](https://user-images.githubusercontent.com/20015046/69343818-5b474a00-0c7f-11ea-9c92-47c8c4519369.png)

**Comment by mark-friedman** [comment]
@AlexITMan I'm not seeing the behavior that you are describing.  Are you seeing it on live test, downloaded app or both?  Also, what device(s) and OS versions are you seeing the behavior on?  Finally, is this on a new project or an older one?

-Mark

**Comment by AlexITMan** [comment]
This is a new project. I see this behavior in Live (on Android 8.1, iOS 12.4, Bluestackes 4) after the release of the latest Live 120 update.

**Comment by mark-friedman** [comment]
@AlexITMan This should be working now.  Note that you might have to do a "hard refresh" in your browser to get the latest version of Thunkable ✕ loaded and then move a block to force a regeneration of your app's code.  Sorry for the issue.
