### ISSUE TITLE
Functions do not return objects under certain conditions

### ISSUE THREAD

**Issue by itdir** [thunkable/thunkable-issues#313]
### Platform
✕

### Issue/Request Origin
self... https://community.thunkable.com/t/returning-objects-lists-from-functions/337096

### Steps to Reproduce
1. Create a function which attempts to return an object
2. Observe object is not returned by function

### Expected Behavior
I expected the (reference to the) object to be returned from the function.

### Actual Behavior
The function does not return the object.
 
```
  STACK TRACE AND/OR SCREENSHOTS
```
Demonstration:
https://x.thunkable.com/copy/2d4bd61f771a1bef5e3b9dce187058f6

**Comment by mark-friedman** [comment]
Thanks for bug report, @itdir!  

BTW, The bug looks to be slightly more complicated than just returning an object from a function.  For example, in your repro app if you just have your function return `'get object from JSON [from Text_Input1 get Text]'`, then it will work correctly.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved, based on [this sample project](https://x.thunkable.com/projectPage/6001be0f9a55110012ccb75a/). We'll close this issue now; apologies for not following up when it was originally resolved.
