### ISSUE TITLE
Canvas Component - Sprites and Drawing 'Z' property

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#316]
**Is your feature request related to a problem? Please describe.**
Currently, the Z position of sprites and drawings are set when the object instantiates on the canvas.  This is frustrating when you are managing multiple instances and expect certain sprites and drawings to pass in front of one another.  For example, an app that draws on a sprite or sprites that belong in the background while others are in the foreground. 

**Describe the solution you'd like**
All for Sprites (and drawings) to have Z property.

**Describe alternatives you've considered**
A possible alternative would be to allow developers to set instantiation order on Canvas. It seems more complicated though. 

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by mark-friedman** [comment]
Thanks for the heads-up, Joe.  The canvas/sprite features are still under active development.

**Comment by MrMazzone** [comment]
Awesome, Mark!  I figured that just making sure this one makes it to the backlog.  Thank you.

**Comment by MrMazzone** [comment]
This feature was implemented recently.  Great job Thunkable team!
