### ISSUE TITLE
Feature Request: Deep Linking (or Branch.io integration)

### ISSUE THREAD

**Issue by nicbyron** [thunkable/thunkable-issues#317]
**Is your feature request related to a problem? Please describe.**

Need users to be able to transition from a web browser on their phone or from a native QR reader (i.e. in the camera app) to the app more easily. 

**Describe the solution you'd like**

I want users to be able to start the app by clicking on a URL that opens up the app. Additionally, it would be really powerful to be able to parse out start data/values from the URL so that the user could be taken to a place in the app that is contextually relevant.

Specifically, I would like Thunkable to be able to support the following two use cases:
```
Given I am a user with a Thunkable app downloaded
When I tap on a specific link  (either in a web browser or through a QR reader, e.g. native camera app)
Then the Thunkable app will be opened

And if there were contextual information/parameters in the link
Then the user will be displayed information or navigated to a particular place given those parameters
```

``` 
Given I am a user without the Thunkable app downloaded
When I click on a specific link
Then I will be taken to the App Store to download the app
```

The best option would probably just to have a branch.io integration (https://branch.io/what-is-deep-linking/).

If a custom solution was implemented it would be great if it could be done using Universal Links rather than URL Scheme (https://medium.com/wolox-driving-innovation/ios-deep-linking-url-scheme-vs-universal-links-50abd3802f97)

**Describe alternatives you've considered**

After seeing this post (https://community.thunkable.com/t/solved-universal-link-to-open-native-app/255040/3?u=nicnok) I stopped looking for a solution as it appeared there is none.

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

Thunkable X

**Additional context**

Very related to this post, but wanted to give a bit more details/an extra bump: https://github.com/thunkable/thunkable-issues/issues/53

**Comment by mark-friedman** [comment]
@nicbyron It's better to have just a single issue relating to this.  Please add your details as a new comment on #53.

**Comment by nicbyron** [comment]
@mark-friedman that is fair. I will leave a comment on #53
