### ISSUE TITLE
Switch and slider inside column/row not visible are visible on the top left of the screen

### ISSUE THREAD

**Issue by grfr58** [thunkable/thunkable-issues#318]
if I have inside a column/row a slider or a switch and I set not visible the container I see on the top left of the screen a small piece of the object.

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

x

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
look the app
https://x.thunkable.com/copy/d85cc648ad4b6307f79385f405a06da7
click the button Aggiungi on the bottom of the first screen and you will see on the second screen the problem on the top of the page
![Screenshot_20191211-155615](https://user-images.githubusercontent.com/56504218/70635189-ca3b1180-1c33-11ea-9cce-da73980594b4.png)

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
Thanks for the report, @grfr58.

**Comment by domhnallohanlon** [comment]
Hey @grfr58  we updated the platform since this was reported - is it displaying properly for you now?

**Comment by jane-d-alt** [comment]
As there was no report of this behavior enduring in response to Domhnall's question above, we will close this issue for now. Please reach out if you have any further questions about layouts in your project. Thanks!
