### ISSUE TITLE
Sound Component Refuses to Play Icecast Streams

### ISSUE THREAD

**Issue by jkrueger2020** [thunkable/thunkable-issues#319]
I've confirmed that the Sound Component can play a Shoutcast sample URL that I found online, but it is not working with my Icecast stream. No sound comes out when I use Icecast. I've tried with a 5 second wait before trying to play the stream and a 35 second wait - no difference. I just get "Sound file is not loaded yet." Which makes sense - kind of. I mean it is a non-stop stream. But if Shoutcast works, why not Icecast?
![2019-12-12 00_57_28-Thunkable](https://user-images.githubusercontent.com/29052544/70686480-76075000-1c7a-11ea-954e-ba3920ce8a92.png)

Here is an Icecast URL you can test with:
http://s4.yesstreaming.net:7060/mobile

I've tried with HTTPS too and that doesn't work either:
https://s4.yesstreaming.net/proxy/calvary1?mp=/mobile

Can you please help me?

**Comment by mark-friedman** [comment]
I'm afraid that Audio support can be tricky.  The key issue is not so much the streaming platform (e.g. Shoutcast or Icecast) but the codec that the audio stream is encoded as.  AFAICT, Shoutcast and Icecast support a different, but overlapping, set of audio codecs (see, for example, [here](https://www.rocketbroadcaster.com/help/icecast-vs-shoutcast), or for more details [here](https://en.wikipedia.org/wiki/SHOUTcast#Supported_file_formats) and [here](https://en.wikipedia.org/wiki/Icecast#Supported_file_formats)).

Furthermore, the set of supported codecs differs between Android and iOS.  You can see those [here](https://developer.android.com/guide/topics/media/media-formats.html) and [here](https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW47).  From those lists, the most likely codec/format to work for both platforms is mp3, with AAC and maybe WAV also possibly working.

Hope this helps.

**Comment by jkrueger2020** [comment]
I'm afraid that doesn't help. I've tried it with both an MP3 stream and an AAC+ stream. Neither work

**Comment by mark-friedman** [comment]
>I'm afraid that doesn't help. I've tried it with both an MP3 stream and an AAC+ stream. Neither work

Sorry to hear that.  If you haven't already, it might be worth posting a message to [our community forum](https://community.thunkable.com/c/thunkable-cross/).  Maybe someone there has come across this problem and can help you.

**Comment by domhnallohanlon** [comment]
@jkrueger2020 does it make a difference if you use https:// instead of just http://?

**Comment by jane-d-alt** [comment]
Hi there, the Sound component Source can be set with a URL, but this URL must end in a file extension much as .mp3 .wav etc. Since there was no follow up to Domhnall's question, we will close this issue for now. Thanks!
