### ISSUE TITLE
Web Viewer issues with "data:" URI on iOS. 

### ISSUE THREAD

**Issue by ghost** [thunkable/thunkable-issues#320]
I experience this issue on iOS only specifically when I try to view charts using Google chart service through the web viewer. one Thunker has stated this is because i am not trying to view a URL but instead URI and that URI does not work with the web viewer on iOS devices. Are you guys aware of this and if so, is there any fix in sight?

I just tested this after downloading Thunkable Live (114) from Testflight moments ago

specifically, I am trying to graph from the localDB. apps on Android work with this feature and when i try them on IOS, this does not work at all. 

i have included a link of one such app. 
https://x.thunkable.com/projects/5d70f93f8a62b4079eedaff2/project/properties/designer/

**Comment by mark-friedman** [comment]
>i have included a link of one such app.
https://x.thunkable.com/projects/5d70f93f8a62b4079eedaff2/project/properties/designer/

@jaredgib That project link appears to point to someone else's project.  Also, I don't see any Web Viewer components on that screen.  Can you try creating a very simple project (perhaps with just a Web Viewer) that demonstrates the problem and posting a link to that?

-Mark

**Comment by jaredgib** [comment]
@mark-friedman 
Thank you for reaching out so quickly, Mark. 
here is an updated link
https://x.thunkable.com/copy/5ef4d7c386fa6c12a8e53ba005d8e1d4

**Comment by mark-friedman** [comment]
Thanks, @jaredgib.

Yes, there are issues with "data:" URIs on iOS.  It's not clear whether this will be fixable or not.  We rely on a 3rd-party library for our Web Viewer support and it is unclear whether they can or will support  "data:" URIs on iOS.  We'll look into it, though.

**Comment by jaredgib** [comment]
Thank you!

Do you know of any workaround to be able to display charts or specifically
a line graph using thunkable and iOS?

**Comment by mark-friedman** [comment]
@jaredgib I've not used it, but perhaps https://quickchart.io/ might be able to meet your needs.  Basically, you build up a URL which represents your graph and use it as the source of an Image component or a Web Viewer component.

**Comment by jaredgib** [comment]
Wow!!! This was the perfect fix! Thank you so much for your help!!

**Comment by mark-friedman** [comment]
>Wow!!! This was the perfect fix! Thank you so much for your help!!

@jaredgib Glad to hear it!
