### ISSUE TITLE
Block editor too small on iphone 5

### ISSUE THREAD

**Issue by AvnerHadjadj** [thunkable/thunkable-issues#321]
### Platform
 ✕ iOS companion

### Issue/Request Origin
Developer testing a tutorial 

### Steps to Reproduce
1. Use an iPhone 5
2. Open Thunkable Live
3. Start a tutorial
4. Tap on View Code button
5. Open the block editor

### Expected Behavior
Seeing the block editor completely ore almost completely, without the element list remaining opened on most of the screen.

### Actual Behavior
The block editor zone is too small and uses only the remaining space. 
```
  SCREENSHOTS
```
![IMG_2650](https://user-images.githubusercontent.com/3876288/70864776-1f419500-1f5e-11ea-8c3b-66144dc3e6c3.jpg)

![IMG_2651](https://user-images.githubusercontent.com/3876288/70864778-223c8580-1f5e-11ea-9749-8c2b3498e2e0.jpg)

**Comment by mark-friedman** [comment]
Thanks for the report @AvnerHadjadj!

**Comment by jane-d-alt** [comment]
Hi there,

You can set your project's Screen to 'landscape' or 'auto'. This will allow you to use the Thunkable Live app in landscape mode, which should help with this sizing issue.

We recommend doing the majority of your editing on a desktop or laptop computer for maximum ease of use.
