### ISSUE TITLE
Live app crashes when some properties (e.g. Image.Picture) are set to an invalid value

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#322]
This block causes crash.

![изображение](https://user-images.githubusercontent.com/20015046/70865556-f9bd8700-1f6f-11ea-8452-06fbc4806540.png)

**Comment by MrMazzone** [comment]
The picture property should be set to an empty string when not showing an image.  The picture property does not expect null, integer, or boolean value, only string.

**Comment by AlexITMan** [comment]
You are correct, but the application should not crash when using data of the wrong type or wrong operations. The Image.Picture block allows you to attach blocks of different types and even operations to it, which causes crash. I think that you understand that this is a bug of developers.

**Comment by mark-friedman** [comment]
Thanks for the report @AlexITMan!  We believe that something changed recently in our iOS Live app where these types of errors used to be ignored but now are causing crashes.  We are investigating.

**Comment by jane-d-alt** [comment]
This behavior has been resolved. We'll close this issue now; apologies for not following up when it was originally resolved.
