### ISSUE TITLE
Change the font of buttons and navigation elements

### ISSUE THREAD

**Issue by nicbyron** [thunkable/thunkable-issues#323]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I want to be able to change the font of the buttons and navigation elements. This is extremely important to make an app that looks consistent with a brand.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
```
Given I am a Thunkable X user
When I have added a button or navigation element
Then I should be able to change the font and styling of the text on these elements
```

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
Creating custom elements to replace the navigation elements and using images with text for the buttons.

**Which platform are you asking for?**
_Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)_
Thunkable X

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by mark-friedman** [comment]
Thanks for the feature request, @nicbyron!

**Comment by gre4twh1te** [comment]
This would also be extremely helpful to implement (vector) icons that are state of the art instead of using pixel graphics that don’t work well

**Comment by nicbyron** [comment]
Yeah @gre4twh1te +1 on vector graphic support 🙌 (However, as we've discussed in other threads—solving the rending issues so we can at least get stable images in our apps is the first priority 😅 )

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request! Since this overlaps with request #181 we will close this issue. We are working on the ability to upload font files to the platform!
