### ISSUE TITLE
API key, base id, table name, view name of Airtable could not be set by blocks

### ISSUE THREAD

**Issue by yuhigashi1** [thunkable/thunkable-issues#324]
I have an app which requires dynamically changing your Airtable API key, baseID or table name,View name.
Blocks setting the properties (API key,base id,table name,view name ) does not work.

### Platform
x

**Comment by mark-friedman** [comment]
@yuhigashi1 Is there any chance that you could use multiple Airtable Spreadsheet components which have different values for the API key, base id, etc?

**Comment by yuhigashi1** [comment]
Multiple Airtable Spreadsheet can not solve the problem.
I want the user to create airtable and set API key ,base id,etc.

**Comment by mark-friedman** [comment]
@yuhigashi1 I see.  Thanks for the clarification.

**Comment by jane-d-alt** [comment]
Hi there, after some testing on our end, it looks like these blocks work. Apologies for not following up as soon as these fixes were implemented. Thanks for reporting!
