### ISSUE TITLE
Map component events: MarkerPress and CallOutPress, ... error

### ISSUE THREAD

**Issue by afarago** [thunkable/thunkable-issues#325]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
✕, ✕ Android companion

### Issue/Request Origin
I have seen this issue while testing the my code via Live

### Steps to Reproduce
1. Create a map component
2. Add event handler: Map1.onMarkerPress and event handler: Map1.onCallOutPress
3. Add in each handler: from Label1.set Text to generate JSON from object event
4. Add event handler: Map1.onLongPress
5. Add in each handler: from Label1.set Text to generate JSON from object coordinate

### Expected Behavior
Adding a valid marker (separate code) and pressing, then pressing the callout, then pressing the map long will update the label with some valid data. 

### Actual Behavior
{dispatchConfig: null, _targetInst: null, ...., _dispatchInstances: null} is displayed.
Though this might be greate there is NO reference to the actual marker or position pressed.

Additional feature request: return some marker ID when adding the marker.

**Comment by mark-friedman** [comment]
@afarago Are you seeing the same text displayed for each of the various presses?  Also, what version of Android is your phone running and what make and model is it?  Finally, are you seeing the same behavior when you download and install the app?

**Comment by jane-d-alt** [comment]
Hi there, apologies for not following up when these behaviors were originally resolved, but all of these blocks perform as expected on Android. In [this project](https://x.thunkable.com/projectPage/609e036e4a9c670012c9ef15/), you can click the Button to add a marker. The onMarkerPress and onCalloutPress return the expected JSON, and the onLongPress block now returns latitude, longitude, coordinate X and coordinate Y values, which all work perfectly. Thanks for reporting!
