### ISSUE TITLE
Remove filler content from top of Thunkable Live app

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#326]
The message “Congrats! Your project is live. Check out our tutorials if you need help" was added to the bottom of Thunkable Live when previewing apps.

The significant change in screen size because of those additional elements makes Thunkable Live much less useful for testing of apps.

My preference would be to remove it from the display and instead tell your users congratulations and about tutorials in the email message that gets generated each time an app is downloaded. The less the actual app screen gets crowded with additional text and buttons, the better.

**Comment by AlexITMan** [comment]
I think that it is impossible to remove this useless information due to the fact that this is a requirement of Apple. If Apple says that half of the screen should be blacked out, then this requirement will have to be fulfilled.

**Comment by tatiang** [comment]
I didn't realize this was a requirement of Apple's. I'm curious what the exact requirement is since other live preview apps don't have that type of message.

**Comment by mark-friedman** [comment]
Apple has been a bit inconsistent on how they've been treating various live preview apps, including ours.  Technically, they require that the "live" portion take up no more than 80%  of the screen, so we have been doing that to stay compliant.

**Comment by AlexITMan** [comment]
Thanks for the information, I thought so.

**Comment by gre4twh1te** [comment]
> Apple has been a bit inconsistent on how they've been treating various live preview apps, including ours. Technically, they require that the "live" portion take up no more than 80% of the screen, so we have been doing that to stay compliant.

You could still get around this by moving the Thunkable content to only bottom instead of top AND bottom because this way we could at least make sure our head section is looking right on devices (specially devices with nodge like iPhone X and newer). Also I think Apple would not bother if you would add a fullscreen preview that removes the menus for just a few seconds.

**Comment by weihuali0509** [comment]
@gre4twh1te Are you using Android or iOS?

**Comment by gre4twh1te** [comment]
> @gre4twh1te Are you using Android or iOS?

iOS mostly but also Android for testing purposes. However what does this have to do with the request?

**Comment by AlexITMan** [comment]
gre4twh1te, have you tried the option of scaling the entire screen and reducing it to 80% at least for a more adequate display of the interface?

**Comment by gre4twh1te** [comment]
> gre4twh1te, have you tried the option of scaling the entire screen and reducing it to 80% at least for a more adequate display of the interface?

Hi @AlexITMan, unfortunately this won't work because I need to view it in real size to make sure everything looks fine with the iPhone notch and so on.

**Comment by mark-friedman** [comment]
Obviously it's not ideal, and you probably already thought about it, but you could download the app to your iPhone occasionally in order to test its full-screen UI.  This is probably advisable, regardless, for iOS or Android since there can be subtle differences in behavior between the live companion and the built app.

**Comment by gre4twh1te** [comment]
> Obviously it's not ideal, and you probably already thought about it, but you could download the app to your iPhone occasionally in order to test its full-screen UI. This is probably advisable, regardless, for iOS or Android since there can be subtle differences in behavior between the live companion and the built app.

That is true but it takes really long to built the iOS apps therefor I think the companion should be optimized. I think it should be optimized anyways to at least show relevant informations not just some text and the view code festure that doesn’t properly work and you likely mess up yout project when doing anything on the companion view.

**Comment by eoinparkinson** [comment]
Does Apple plan on changing this?

**Comment by jane-d-alt** [comment]
I have renamed this issue as the team agrees with the idea of removing the 'filler' content from the top of the Thunkable Live app. We are working on a redesign of the Thunkable Live app that we hope the community will love!

**Comment by jane-d-alt** [comment]
Hi all,

The redesigned Thunkable app is live! Thank you all for your requests, we hope you like it
There is still some 'filler' at the bottom of the screen, as required by the app stores

**Comment by ebecaf** [comment]
Filler content is now showing on Android tablets where it wasn't before (version 301) and that filler **isn't a requirement** from Google Play. Please remove it ASAP.

Community post: https://community.thunkable.com/t/why-is-there-a-big-white-bar-at-the-bottom-of-the-live-app-on-tablets/1702502/3

**Comment by ebecaf** [comment]
Also, Android appears to have 25% filler which is obviously unnecessary.
