### ISSUE TITLE
Wait block does not have a consistent delay

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#327]
### Platform
Thunkable Live with iOS 13.3 on an iPhone 8 (have not tested with Android)

### Steps to Reproduce
1. Test this "Broken Timer demo" project: https://x.thunkable.com/copy/033076d0f0e97867eb2ada3e9d44d9fe
2. I described this further in this community post: https://community.thunkable.com/t/count-up-timer/380607/7?u=tatiang
3. (I've attached a screenshot of the code below.)

### Expected Behavior
When the Wait block value is set to 1, I expect to see 0, 1, 2, 3, 4, 5, etc. 
When the Wait block value is set to 0.5, I expect to see 0, 0.5, 1, 1.5, 2, 2.5, etc.

### Actual Behavior
The results are unpredictable. The displayed value will increase, then decrease, then stay the same or even display "null." When the Wait block is set to 1, for example, it increases by 4 or 5 or 6 or even decimal amounts.
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="300" alt="Screen Shot 2020-01-04 at 8 45 24 AM" src="https://user-images.githubusercontent.com/10355498/71768802-a5eaf180-2ece-11ea-9b05-0c77775c94e8.png">

**Comment by mark-friedman** [comment]
@tatiang There are some weird (and unfortunate) interactions with the wait block when you are in the companion and are editing your app. Two things to try would be to kill and restart your companion app after each change and see if you continue to see the issue and also to download and install your app and see if the problem persists. Let us know the results of those experiments.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved, based on [this app](https://x.thunkable.com/projectpage/6001c250de720900116591a1/) which recreates the blocks above. We'll close this issue now; apologies for not following up when this behavior was originally resolved.
