### ISSUE TITLE
always on screen feature

### ISSUE THREAD

**Issue by mirageblue** [thunkable/thunkable-issues#329]
**Describe the solution you'd like**

I want prevent screen device from sleeping

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

Thunkable ✕

**Comment by mark-friedman** [comment]
Thanks for the feature request, @mirageblue!

**Comment by gre4twh1te** [comment]
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> I want prevent screen device from sleeping
> 
> **Which platform are you asking for?**
> Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)
> 
> Thunkable ✕

as a workaround you can give this a try: https://community.thunkable.com/t/keep-the-screen-active/118584/10?u=chris

**Comment by eputkonen** [comment]
Is your feature request related to a problem? Please describe.
I am creating a timer that would be used for over an hour, but when my devices "sleep" after 3 minutes...the app basically closes and the timer stops. I don't want to ask users to modify their sleep mode. It would make more sense to temporarily deactivate sleep mode while the app is running,.

Describe the solution you'd like
A user interface item or Device bock item that will disable the sleep mode while the app is running.

Describe alternatives you've considered
I have looked through the help and conversation. People have suggested changing things on the screen (which did not work for me...or I was not doing it right) or playing video to keep it from sleeping, but this could be a Device block and solve the issue for all who want their apps to continue to run until closed.

Which platform are you asking for?
Thunkable ✕ (x.thunkable.com)

**Comment by MrMazzone** [comment]
@eputkonen have you tried this?
![image](https://user-images.githubusercontent.com/40954645/82767175-87d94b80-9df3-11ea-888a-0741da2029ae.png)

I haven't but wondering if it works in this situation.  It can be found in the Device category.

**Comment by josmas** [comment]
That's the right block; it was released a couple of weeks ago so closing this now. Thanks all!
