### ISSUE TITLE
problem detaching the ITEM inner block from the container block. Thunkable X: 

### ISSUE THREAD

**Issue by lirongreenwald** [thunkable/thunkable-issues#33]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thankable X (Cross platform)

### Steps to Reproduce
1. open Lists panel
2. select: [Does list X contain "b"] and bring to "blocks" editor
3. in the "blocks" editor I'm trying to detach the item inner block (currently "b" string) and replace it with a variable but it does not come out of its container???
4. same issue with other "Lists" functions with item blocks

![image](https://user-images.githubusercontent.com/41421298/42930187-02d4673e-8b45-11e8-95f2-9c15c6f38b0c.png)

### Expected Behavior
item inner block should be detachable 

### Actual Behavior
inner item block is stuck in its container block
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
That "b" block is something called a "shadow block".  You can replace it simply by putting another block in it's slot, so you don't need to explicitly delete it.

That said, we could probably make that clearer in our documentation and perhaps via hover text.
