### ISSUE TITLE
Animation for components visibility (True or False) 

### ISSUE THREAD

**Issue by HayderAlLami** [thunkable/thunkable-issues#330]
I will be so happy if Thunkable releases this feature.
The feature is about animation, when components disappear or appear (Visible to True or False) there should be animations for them.

Please, if you hope you see this feature in Thunkable, press “Like” for this post so Thunkable developers can see it is an important feature for professional apps.

Thunkable ✕ (x.thunkable.com)
Regards,
Hayder

**Comment by jane-d-alt** [comment]
Closing as this issue overlaps with #172
