### ISSUE TITLE
All new buttons have rounded corners

### ISSUE THREAD

**Issue by DLM-thunkable** [thunkable/thunkable-issues#332]
![screen PNG](https://user-images.githubusercontent.com/59783690/72409371-6916ca00-371a-11ea-87bb-4a1980b3c032.jpg)
Thunkable X: I have a number of buttons on my app screen, all default square. The last 5 buttons I’ve added (on three different screens) are rounded at the corners as soon as they were dragged onto the screen, before I size them or give them a color, and I can’t see how to make them square like the others. They look like I have put “25” into border radius or border radii, but both are blank. And if I put 25 or 50 into border radius, nothing happens, and then when I clear that, the buttons stay round. Finally, if I duplicate a square button, it’s rounded as well. The buttons appear rounded on Android and iOS as well.

**Comment by MrMazzone** [comment]
It seems the new default button has these rounded corners.  You can make them square by setting the border radius property to 0.  It may not display properly in the preview, but will on a device.  You can make it display properly on the preview by setting each of the border properties.

**Comment by weihuali0509** [comment]
Thanks for reporting the issue. @MrMazzone is correct and there is a bug in the phone preview.
We fixed it internally and you should see the change within the next 24 ~ 48 hours. 

Thanks,
Wei

**Comment by DLM-thunkable** [comment]
Thanks!

**Comment by DLM-thunkable** [comment]
Thanks!

**Comment by josmas** [comment]
These changes are out now. Feel free to reopen if needed. Thanks!
