### ISSUE TITLE
Image blocks lose associated file name

### ISSUE THREAD

**Issue by DLM-thunkable** [thunkable/thunkable-issues#333]
My app shows a small Canadian or US flag picture in an image component on opening a screen, depending on whether the user has chosen Canadian or US settings. The Screen.OnOpen blocks are “from FlagSS set Picture to cdn.jpg” and “usa.jpg”, referring to 2 downloaded pictures in assets. Almost every day, I get two error messages per screen, there are blanks instead of the file names, and I have to re-enter them.

### Platform
X

### Issue/Request Origin
From my own app

### Steps to Reproduce
1. assign the Picture to a file in the app list
2. this works fine, the image is shown properly on the screen
3. next day, the file name is missing, I get error messages, and no image visible
4. I reassign the picture to the file, and it works again until next day.
5. re-downloading the file doesn't fix problem
![Annotation 2020-01-14 221210](https://user-images.githubusercontent.com/59783690/72409768-8dbf7180-371b-11ea-933c-d83a17866e0e.jpg)

### Expected Behavior
That the file name would be stored in the block.

### Actual Behavior
It disappears.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by kezb765** [comment]
I got the same issue. I solved it this way:
- initiate an app variable for each flag. Example "initialize app variable FlagName1 to flag1.png"
- use this variable to set the picture. Example "from FlagSS set picture to FlagName1"

Works for me.

**Comment by DLM-thunkable** [comment]
Thanks! I also later found this:

https://community.thunkable.com/t/the-image-link-keeps-dropping/413547/9

It seems it's the default green fields that aren't working. I used a regular text field and typed in the file name, and that seems to be working just fine.

**Comment by mark-friedman** [comment]
Sorry about the problem @DLM-thunkable and @kezb765.  We'll take a look.

**Comment by DLM-thunkable** [comment]
Thanks!

**Comment by jane-d-alt** [comment]
This behavior was fixed shortly after reporting. We will close this issue now; apologies for not following up when the behavior was originally fixed.
