### ISSUE TITLE
Request: colored map Markers

### ISSUE THREAD

**Issue by rem708** [thunkable/thunkable-issues#335]
**Is your feature request related to a problem? Please describe.**

A map covered with singly coloured markers makes selection confusing

**Describe the solution you'd like**

On the map/addMarker block to have a color input. Alternatively  "on map set color to" input

**Describe alternatives you've considered**

a colored polygon has been suggested as an alternative but you would  have to generate lat/lon for the points - horrid!

**Which platform are you asking for?**
 Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by nicbyron** [comment]
+1 on more marker options! What you've described in your documentation as to what you're working on is pretty much exactly what I'm looking for 👍 
![image](https://user-images.githubusercontent.com/16532623/73436084-6bb12a80-437c-11ea-8a80-7429ac53b679.png)

**Comment by marketto3000** [comment]
I would like to have the possibility to change the color of the Marker in the Google map or better still to be able to define a custom icon.
Thanks Marco

**Comment by marketto3000** [comment]
I would like to have the possibility to change the color of the Marker in the Google map or better still to be able to define a custom icon.

Thanks Marco

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. As this request overlaps with #186 we will close it for now. You are welcome to comment on the original feature request.
