### ISSUE TITLE
Assign result of Airtable.getAllRows directly to a Local_DB!

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#337]
**Is your feature request related to a problem? Please describe.**
I use airtable a lot, it would be nice to get a whole table in column-ordered way.

**Describe the solution you'd like**
- add a function to LocalDB to import the whole result of Airtable.getAllRows:
"In Airtable1 call GetAllRows: with outputs error, rows. Then do: From LocalDB1 set Cells to rows"

**Describe alternatives you've considered**
It is possible, to convert the result from Airtable.getAllRows to columns, but this is time consuming. I often use columns for example to display all locations on a map: Loop through the column "Name" and display all locations with coordinates found in column "Latitude" and column "Longitude".
Alternative: implement a function for Airtable: "getAllColumns" that gives as a result the whole table in columns.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
./.

**Comment by kezb765** [comment]
Add some more functions:
set list to (LocalDB -> get Column "xyz")
sort LocalBD by Column "xyz"

**Comment by mark-friedman** [comment]
Thanks for the feature request, @kezb765!
