### ISSUE TITLE
deleteAllMarkers: documentation error and request for enhancement

### ISSUE THREAD

**Issue by rem708** [thunkable/thunkable-issues#339]
**Is your feature request related to a problem? Please describe.**

I'm working on a large project which uses maps. I need to create overlays made of markers, polylines and polygons. At times I need to clear these and the deleteAllMarkers does just that but this is too brutal and should only delete markers as the name suggests

**Describe the solution you'd like**

In the map documentation you have listed Add Marker with description etc. Immediately below that you have the deleteAllMarkers block and description. Following this you have the Add polyline and Add polygon.
The name of the deleteAllMarkers block infers it just deletes all markers. This is supported by its position in the documentation. However, this is not the case as it also deletes all polylines and polygons.
See example
https://x.thunkable.com/projects/5e257ce9ff1a882e327f2010/d4bbceb4-9daa-4d2d-bf6e-04d170df76bb/blocks
Whilst clearing all overlays is useful it would be better if the deleteAllMarkers was enhanced to have two other options deleteAllPolyline and deleteAllPolygon

**Describe alternatives you've considered**

I may have to use web services but I'm trying to avoid that at this moment as that requires a permanent internet connection.

See above

**Which platform are you asking for?**
 Thunkable ✕ (x.thunkable.com)

**Additional context**
example given above

**Comment by mark-friedman** [comment]
Thanks for the report @rem708.   We'll take a look.

**Comment by jane-d-alt** [comment]
The 'deleteAllMarkers' block was updated to only delete markers, and the blocks 'deleteAllPolylines' and 'deleteAllPolygons' were added to the platform and documented. We'll close this issue now; apologies for not following up when these blocks and docs were first introduced.
