### ISSUE TITLE
Canvas does not load anymore

### ISSUE THREAD

**Issue by dvlbernhard** [thunkable/thunkable-issues#341]
### Platform
✕ **Android companion** and ✕ **iOS companion** (Android: version 151, unfortunately I don't have an iPhone, so I can't test it)

### Steps to Reproduce
1. Open any Thunkable project containing a **canvas** element in the browser
2. click on "Live test"
3. open the newest (Android: version 151, unfortunately I don't have an iPhone, so I can't test it) version of the Thunkable Live app on your Android phone or iPhone
4. **the canvas element does not load anymore**

### Expected Behavior
In the previous version the canvas element still worked.

### Actual Behavior
The canvas element does not load in the Thunkable Live app.

**Comment by MrMazzone** [comment]
Sadly, I am experiencing the same issue -- Canvas not loading.  It has crippled a project I have my students working on.

Hoping for a fix very soon.

**Comment by MrMazzone** [comment]
Update released today.  It seems to be working again. Thank you for the quick turnaround, Thunkable team!

**Comment by josmas** [comment]
Good to hear, thanks for the feedback. Closing the issue now.

**Comment by dvlbernhard** [comment]
Thank you so much!
