### ISSUE TITLE
Revised Design for My Projects Page

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#343]
**Is your feature request related to a problem? Please describe.**
No, simply a suggestion for an improved view of the My Projects page.

**Describe the solution you'd like**
Let me start by saying I'm not a professional designer and barely even an amateur designer. There are countless people who could make something better than what I'm suggesting with their eyes closed. That being said, I think I have some decent ideas that could be considered for moving forward with an improved visual look and feature set for the My Projects page.

This is an attempt to combine the My Projects page with the Details page. It allows for all important links/buttons to be in one place (e.g. edit project, download, preview on web or device, etc.). It also allows for sorting of projects by name, date modified, size, etc. I'm finding that the current layout is overwhelming and I tend to lose projects now that I've made so many copies (it doesn't help that launching a web preview of someone else's project now automatically remixes it into my own projects list). And it's awkward to have to click Details to see a web preview when it should really say "Web Preview" or something along those lines. And why have a Copy button with the same icon as the Remixes button? And why does the Remixes button actually open the project editor? I'm hoping my re-design below offers a bit more of an intuitive interface. 

**Describe alternatives you've considered**
Going back to school for a degree in graphic design. ;)

**Which platform are you asking for?**
Thunkable X

**Additional context**
Here's a mockup I made. The current design in shown in the top half of the image and my new design is shown in the bottom half. 

![Thunkable My Projects page mockup](https://user-images.githubusercontent.com/10355498/73036461-79a4ff80-3e00-11ea-845b-9486b2e1cd31.png)

**Comment by MrMazzone** [comment]
I absolutely agree!  The page becomes hard to navigate when you have a considerable amount of projects.  The filters would be INCREDIBLY helpful when trying to find a project.

**Comment by mark-friedman** [comment]
Thanks, @tatiang.  That looks like a reasonable approach, especially if users could switch back and forth from grid-view (like the current UI) to list-view (i.e. like yours).  Thanks for the suggestion!

**Comment by tatiang** [comment]
It's becoming overwhelming trying to navigate through and organize my projects. I doesn't help that many of the project names are limited to 12 characters. I feel like I'm stuck in a DOS OS!

**Comment by tatiang** [comment]
Hooray, the Thunkable Staff has added this as a new feature. https://community.thunkable.com/t/projects-page-redesign-list-view-search-and-filter/616561?u=tatiang
