### ISSUE TITLE
Single spaces deleted randomly in text blocks

### ISSUE THREAD

**Issue by DLM-thunkable** [thunkable/thunkable-issues#345]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Platform: ✕

### Issue/Request Origin
I see others have this issue as well
https://community.thunkable.com/t/thunkable-x-blocks-update-your-feedback/425809

### Steps to Reproduce
1. put a single space in a text block (e.g. to separate two variables Var1 and Var2 ,to get "Var1 Var1" as output)
2. works fine for a while, then the space becomes an empty field (so output becomes "Var1Var2"), sometimes after a few minutes
3. first noticed this problem last day or so

![Annotation 2020-01-25 221844](https://user-images.githubusercontent.com/59783690/73131494-bc153a80-3fc0-11ea-99bb-cd98d07b0f99.jpg)

### Expected Behavior
The single space shouldn't change with time in a text block.

### Actual Behavior
The space becomes an empty field. Have not seen this with other text fields.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
Thanks for the bug report, @DLM-thunkable .  We'll look into it.

**Comment by DLM-thunkable** [comment]
Thanks! I basically can't try to send my app to the store until it's fixed.

**Comment by josmas** [comment]
This one should be fixed as of an hour ago or so.
Note that unfortunately, if your app was modified by the previous version the spaces will be missing, but adding them again should now stick and stay.

Please reopen if that is not the case (make sure you refresh your browser to get the latest version).
