### ISSUE TITLE
Row background image not displayed

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#347]
### Platform
Thunkable X

### Issue/Request Origin
https://community.thunkable.com/t/images-not-displaying-when-in-column-or-row-as-background-image/35033/

### Steps to Reproduce
1. add row
2. set background image

### Expected Behavior
Background image should be displayed

### Actual Behavior
No image displayed no matter what position settings are chosen. Still seems to work fine for Columns. According to the post on the community this issue persists for more than 1.5 years now or maybe it re-appeared.

**Comment by mark-friedman** [comment]
Thanks for the bug report, @gre4twh1te.  We'll look into it.

**Comment by JanhaviDahihande** [comment]
@gre4twh1te Closing this issue as it seems to be working now as seen in the screenshot. Please reopen if needed.

<img src="https://user-images.githubusercontent.com/20217203/87486763-d97ea500-c5f0-11ea-8404-387440e32ea9.png" width="300" height="500">
