### ISSUE TITLE
Fullscreen preview in live companion

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#348]
Hey, 

I really would love to see a full screen support in Thunkable Live. It was working fine in earlier versions but after recent updates it is barely possible to test what your app is going to look like as a standalone. Please add a full screen toggle so we can see our changes "as is" again and without the forced content that reduces display size too. I think a full screen option would even make more sense than the possibility to view code which is not working well at all on mobile devices anyways. Also the new bottom part "congrats your app is live..." is really useless waste of space generally.

Best, Chris

**Comment by tatiang** [comment]
I agree with you but see the response to my request here: https://github.com/thunkable/thunkable-issues/issues/326#issuecomment-571369862.
