### ISSUE TITLE
Status bar does not show properly with black and white backgrounds

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#349]
I have addressed this issue many times to Thunkable support but got no update so I decided to directly rise the issue the here I’m using Thunkable x and using it ok iPhone 6s+ iOS 13.3 
Everytime I have a white or black background the two most common colours the status bar either becomes white color and blends in with white background or becomes black coloured and blends in with black which makes it very difficult to decided the background colours  and also sometimes status bar glitches in n out and disappears

The more info the faster we will be able to address it!

### Steps to Reproduce 
1. 4 screens with bottom tab navigator 
2. 1 screen with white bg one with black bg and other 2 with any other color
3.switch between screens 

### Expected Behavior
What did you expect to happen? For white background/light backgrounds I expect it to automatically be black and for dark to be automatically black to maintain contrast 

### Actual Behavior
What actually happens? Status color becomes black for dark and white for light  to in a nutshell 
Status bar color is confused it doesn’t know which color to show when 
```
  STACK TRACE AND/OR SCREENSHOTS
```
![4027D72D-358D-4FAE-8E0A-DA5B27AEC5D6](https://user-images.githubusercontent.com/58250868/73154737-28478980-40fa-11ea-9c58-f010e7be84e6.jpeg)

Easy way to solve this would be maybe just put color option for status bar color

**Comment by mark-friedman** [comment]
Thanks for the feature request, @ayocarti.

**Comment by ayocarti** [comment]
> Thanks for the feature request, @ayocarti.

I would consider this a bug it’s not a feature request it’s just simple solution in case the issue can not be found thanks 😇
