### ISSUE TITLE
Barcode/QRcode Scanner Thunkable X

### ISSUE THREAD

**Issue by compass1312** [thunkable/thunkable-issues#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Ability to scan Barcodes and/or QRcodes and be able to compare scan results with data held in local storage.

**Describe alternatives you've considered**
Similar to scanner built in AI2

**Which platform are you asking for?**
Thunkable X

**Additional context**
There are many uses for QRcode and Barcode scans. Too many to mention.

**Comment by ygorbittencourt** [comment]
I need too, need a lot. An extremely interesting feature that meets current trends. Every media type these days has a qrcode that needs to be read.

**Comment by jane-d-alt** [comment]
Thunkable X now has a [Barcode/QR code scanner.](https://docs.thunkable.com/barcode-scanner)

**Comment by ygorbittencourt** [comment]
Thanks , great news!!

Em qui, 13 de fev de 2020 às 11:49, jane-d-alt <notifications@github.com>
escreveu:
