### ISSUE TITLE
Input lag = serious damage to UX

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#350]
Wheather it be pressing a button to navigate to new screen or it would be showing a specific background color when a screen opens there is always an input lag for example the initial color of screen is supposed to be grey but once a button is pressed the grey is changed to whatever background color they want and it gets saved for next time they open but when next time they open screen first goes grey then changed to whatever color was picked and that’s so sluggish and damages the Ux seriously secondly switching between bottom navigation bar even tho I have uploaded icons to Thunkable the icons disappears and then appears when pressed it feels so slow and sluggish 
### Platform
X & ✕ iOS companion

### Steps to Reproduce
1. Open a Thunkable project with a lot of blocks/a medium to big app 

2. Try navigating to other screens if it has bottom navigation try switching in between screens 

### Expected Behavior
What did you expect to happen? For background color screen I expect it to already set the color milliseconds before it opens I want a smooth UX that feels like my app is actually able to compete with AppStore apps 

### Actual Behavior
What actually happens? Sluggish strong input lag 
```
  STACK TRACE AND/OR SCREENSHOTS
``` 
Video starts with me pressing the most right button 
![062BA52A-B0AA-4144-B39E-0FE8955C8C27](https://user-images.githubusercontent.com/58250868/73155222-cee05a00-40fb-11ea-8751-810a4729ddb6.gif)

My switching 
![042D74D0-B5B0-4E20-A575-8E217E1EB0F9](https://user-images.githubusercontent.com/58250868/73155305-1535b900-40fc-11ea-9087-cb2df04c4ea2.gif)

Vs instagrams 
![25E748BB-A90C-49E9-AFA5-F80EAA3ACF7C](https://user-images.githubusercontent.com/58250868/73155327-2aaae300-40fc-11ea-9ea3-627e5e70abba.gif)

If the ux is gonna be this bad whose gonna use the app? They are gonna delete it meaning the hours we put in to make app is useless

**Comment by mark-friedman** [comment]
Thanks, @ayocarti, we'll look into this.  We are working to make our user's apps as professional looking and acting as possible.

**Comment by ayocarti** [comment]
> Thanks, @ayocarti, we'll look into this. We are working to make our user's apps as professional looking and acting as possible.

Could you also add animations such as following?
![762A995E-9FA8-43DD-9495-52B21BFC61D0](https://user-images.githubusercontent.com/58250868/73206567-f0c1f700-4164-11ea-907e-078b68fdc007.gif)

Lastly the UX lag issue is faced by most of the Thunkable users I love Thunkable but kindly look into it I wanna launch my app in 2 months I’m done with everything just waiting for the update on lag issue thanks :)

**Comment by mark-friedman** [comment]
@ayocarti Could you create a separate feature request for the animations and describe exactly how you would want that feature to work?

**Comment by ayocarti** [comment]
I’ll do that😇 usually how long does it take to get a feature implemented?

**Comment by mark-friedman** [comment]
>usually how long does it take to get a feature implemented?

That totally depends on how useful the feature would be to other users, how many other users would be likely to use the feature, how difficult it is to implement the feature, what other features and bugs are already being worked on, etc.

**Comment by ayocarti** [comment]
> > usually how long does it take to get a feature implemented?
> 
> That totally depends on how useful the feature would be to other users, how many other users would be likely to use the feature, how difficult it is to implement the feature, what other features and bugs are already being worked on, etc.

Thank you for letting me know 🙂 but for now the top priority is the very strong lag I tried my app lil while ago and it made me wanna delete the app 😂 and I made it 😂 

Secondly if it’s possible I submitted a feature two months ago for video upload we have cloudinary to upload video just like images and put the uploaded link in airtable and now recently we have video playback component I think it will be very helpful to me if this feature was implemented and maybe for people in future thanks 😊

**Comment by MrMazzone** [comment]
@ayocarti  Not that this is the best place to discuss this, but why can't you use the existing MediaDB (Cloudinary) component to upload videos?  I haven't tried it, but I would think it would work. Have you tried? If yes, what type of error did you get?

**Comment by ayocarti** [comment]
> @ayocarti Not that this is the best place to discuss this, but why can't you use the existing MediaDB (Cloudinary) component to upload videos? I haven't tried it, but I would think it would work. Have you tried? If yes, what type of error did you get?

Even tho all components required already exist to make it but unfortunately the component to upload videos is not there to upload image you have “image library” component which when opens shows all the pictures what I need is “video library” so all the videos are shown on phone and then you select it and rest works the same way as it does for images which is upload on cloudinary and put link on airtable

**Comment by MrMazzone** [comment]
@ayocarti Oh! Now I understand what you are saying.  Yes, that would be a great new component.  Please submit a new feature request for a component like that.

**Comment by ayocarti** [comment]
> @ayocarti Oh! Now I understand what you are saying. Yes, that would be a great new component. Please submit a new feature request for a component like that.

Already have for last 2 months

**Comment by nicbyron** [comment]
+1 here for image lagging / glitching even when they are uploaded images. It, unfortunately, makes the app look very cheap :/

**Comment by ayocarti** [comment]
![B35FA6AF-1B6C-4C19-920C-F0032A350362](https://user-images.githubusercontent.com/58250868/73517473-5f30de80-441d-11ea-9728-a26ea288640f.jpeg)

**Comment by nicbyron** [comment]
@ayocarti I like the idea of having all of those updated UX navigation options, but we have to remember that things need to be prioritized, and I would say I'd rather have basic navigation that works flawlessly than the latest and greatest ux/ui options.

**Comment by ayocarti** [comment]
> @ayocarti I like the idea of having all of those updated UX navigation options, but we have to remember that things need to be prioritized, and I would say I'd rather have basic navigation that works flawlessly than the latest and greatest ux/ui options.

At this point it’s not even a feature it’s a app standard  I rather have a working Toyota then a working 1700s car

**Comment by jaredgib** [comment]
I too have some lag when React native via thunkable blocks paints new things a screen based on some conditions passed through a function following a users button press. When I repaint 30 buttons on 1 screen at the same time, it takes about 3/4 second which isn’t long, but you can watch as the flip colors. It’s not very quick.
