### ISSUE TITLE
Global variable names are being replaced with random digits

### ISSUE THREAD

**Issue by hskit** [thunkable/thunkable-issues#351]
### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

✕, ✕ Android companion, or ✕ iOS companion

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

Start getting this issue, right after the latest update
Jan 23, 2020
Platform
Speed improvements for projects with large number of blocks

### Steps to Reproduce
1. Go to test app
2. Open Blocks tab
3. Pay attention to Set and Get "Global Variable".
4. Now check Screen2 Blocks. 
5. Come back to Screen1 Blocks. This time you will see random digits as names. 

### Expected Behavior
What did you expect to happen?
Names Must not be replaced with anything at all. 

### Actual Behavior
What actually happens?
Global variable names are being replaced with random digits

  STACK TRACE AND/OR SCREENSHOTS

https://x.thunkable.com/copy/bb5d0cc02360fef07a72e05f778ddfd2

Before:
![image](https://user-images.githubusercontent.com/48337231/73200911-a1d87b00-40ec-11ea-908f-84a2fabf1101.png)

After:
![image](https://user-images.githubusercontent.com/48337231/73200957-bae12c00-40ec-11ea-87a4-4ad554b38ffb.png)

Thanks!

**Comment by mark-friedman** [comment]
Thanks @hskit, we are working on this!

**Comment by hskit** [comment]
Solved:

Jan 29, 2020
Bug fixes
Fixes bugs related to recent blocks speed improvement as detailed in the community
