### ISSUE TITLE
Thunkable Webtest vs Thunkable Live App test  - Error - Pls fix See image

### ISSUE THREAD

**Issue by StefanSladdenEng** [thunkable/thunkable-issues#355]
![thunkable1](https://user-images.githubusercontent.com/60143626/73340245-acc11600-427a-11ea-8919-089bb6dd5fe0.png)
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
@StefanSladdenEng Can you please post a share/copy link to a Thunkable ✕ project which demonstrates the issue?

**Comment by TingC** [comment]
Hi @StefanSladdenEng,

Thanks for reporting. Good news, you can fix it on your end by going to your project editing page and then you refresh the page. It should be working properly on the preview afterward.

Please let us know how it goes and happy to help further if there are more issues.

Best,
Ting
