### ISSUE TITLE
Stored variables not working properly

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#358]
I have two variables following list and block list when you make account for the first time both of these are set to empty list and when screen opens at the bottom it’s suppose to show a 0 if the following list is empty which it does when you make account for the first time then there is block screen with label “block list” which gets changed to block list is empty if the list empty but after the first time if I close app from background or log out or anything the variables don’t work again at all please check these I have been raising this issue for last 4-5 months

### Platform
 ✕, ✕ iOS companion?

### Steps to Reproduce
1. Try my project 
2. 
3.

### Expected Behavior
For it to show 0 everytime list is empty and everytime I open my app. 

### Actual Behavior
Instead of showing a 0 it shows nothing meaning it is unable to read data from variable 
```
  STACK TRACE AND/OR SCREENSHOTS 
```
![29D11702-E1B7-4F90-AA27-434A0D6CEAB7](https://user-images.githubusercontent.com/58250868/73422797-e7df4a00-434b-11ea-8d8c-30b5fced4af4.jpeg)
![28DA631C-E7D5-48D7-ACAC-79C7C3AB4B6F](https://user-images.githubusercontent.com/58250868/73422798-e877e080-434b-11ea-81b1-d017e6c4f435.jpeg)

**Comment by mark-friedman** [comment]
@ayocarti Can you create a very simple project which shows the problem and then share that project with us?

**Comment by ayocarti** [comment]
> @ayocarti Can you create a very simple project which shows the problem and then share that project with us?

A new simple project would not be able to showcase the bugs is there anyway I can PM you here or send my Thunkable project link on your email I don’t wanna share the link with others and there are few bugs that I also want you to see

**Comment by mark-friedman** [comment]
@ayocarti You can send me a link to your project via DM in the community.  However, I'll warn you that it can be difficult debugging a large, complex, project built by somebody else ;-) . Please provide very specific instructions what the problem is and exactly what steps are required to reproduce the problem.

**Comment by ayocarti** [comment]
I can’t seem to send you a dm idk how to 
But there are 4-6 bugs in total that I would like you to take action against 1) the lag when switching between screens via bottom tab navigation 

2) (also previously told) the status bar Thunkable app is so unstable first there was status bar color issue I also made a demo app and sent you the link idk if you have seen it but now on top there is another issue the status bar goes under the column  here are two pictures the picture with status bar is how it should be looking and second is what happens the status bar goes under 
![E97EDF3A-3B78-4A81-A6EA-2DB0873A1501](https://user-images.githubusercontent.com/58250868/73772789-ac58db80-47a2-11ea-86b0-99df5f812159.jpeg)
![0AF18F0A-FD5A-44B0-86B0-629BCD111012](https://user-images.githubusercontent.com/58250868/73772791-ac58db80-47a2-11ea-9e3c-9fafd61607a1.jpeg)

3rd I told you that airtable / db data recalling is very slow For example color change issue. You start with a grey color then user changes background color and then it saves and next time when you open the saved color is shown as background but instead there is a delay 
![BA539D4E-776E-438A-B416-9207436AF56C](https://user-images.githubusercontent.com/58250868/73772936-f641c180-47a2-11ea-8fe7-5f30e3d4991e.gif)

Mark kindly look into these concerns please I have been raising this issue for last few months to Thunkable support but no action has been taken kindly look into this

**Comment by mark-friedman** [comment]
@ayocarti 
To DM me in the community (not here in GitHub), just click on my name/picture there and you should see a "Message" button.  Click on that.  

Also, please don't place all your bugs in a single bug report like this.  Please put them in separate issues. Also please create simple projects showing demonstrating those issues, if at all possible.

**Comment by ayocarti** [comment]
> @ayocarti
> To DM me in the community (not here in GitHub), just click on my name/picture there and you should see a "Message" button. Click on that.
> 
> Also, please don't place all your bugs in a single bug report like this. Please put them in separate issues. Also please create simple projects showing demonstrating those issues, if at all possible.

I have sent you a PM in community check it out

**Comment by ayocarti** [comment]
> @ayocarti
> To DM me in the community (not here in GitHub), just click on my name/picture there and you should see a "Message" button. Click on that.
> 
> Also, please don't place all your bugs in a single bug report like this. Please put them in separate issues. Also please create simple projects showing demonstrating those issues, if at all possible.

And I have made several bug reports with no action that’s why I sent you all in one :(  I also made feature report with no response either

**Comment by ayocarti** [comment]
@mark-friedman i have sent you several messages on community but I haven’t recieved any response
