### ISSUE TITLE
anycomponent bug

### ISSUE THREAD

**Issue by grfr58** [thunkable/thunkable-issues#359]
I found a bug on thunkable X for iPhone
![Screenshot 2020-01-31 at 13 10 00](https://user-images.githubusercontent.com/56504218/73538675-dec5aa00-442b-11ea-8655-dab59eac18d4.png)

This block works on Android but crash on iPhone
seems i turn around the problem like this:
![Screenshot 2020-01-31 at 13 09 15](https://user-images.githubusercontent.com/56504218/73538835-4d0a6c80-442c-11ea-87c4-8a2d2fa8f93c.png)

**Comment by tatiang** [comment]
It crashes in the web preview on a Mac but it works for me on an iPhone in Thunkable Live.

**Comment by mark-friedman** [comment]
So, to be clear, it works on Android (live and downloaded app) and iOS (live) but crashes on iOS (downloaded) and web preview?  Do I have that right?

**Comment by tatiang** [comment]
I wasn't able to test it as a downloaded app. In fact, I can't download any projects right now (https://community.thunkable.com/t/app-download-error-youre-only-allowed-to-build-one-app-at-a-time/438702).

**Comment by mark-friedman** [comment]
> I wasn't able to test it as a downloaded app

Then I am a little confused because your original post said that it **crashed on iOS**, but your 2nd post said that it **worked for iOS** in Thunkable Live.  I assumed that the difference was that the in the first post you were referring to a downloaded iOS app.

**Comment by tatiang** [comment]
@mark-friedman I said above that it crashed in a web preview on a mac. I don't think I said it crashed on iOS. In the forums post about the problem, I said that I couldn't download the app, not that it crashed.

Anyway, hopefully this is less confusing:

When I attempt to download a project as an iOS App, I get an error. 

When I attempt to preview the blocks shown above in a web preview in Google Chrome, the preview quits immediately. When I attempt to preview the blocks shown above in Thunkable Live on my iPhone, it works fine.

**Comment by mark-friedman** [comment]
Sorry, @tatiang I just realized that there are two posters here.  It was the first one (@grfr58) who said it crashed for him on iOS.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved on iOS and Mac. We will close this issue now; apologies for not following up when this behavior was originally resolved.
