### ISSUE TITLE
SMS/Texting Thunkable X

### ISSUE THREAD

**Issue by compass1312** [thunkable/thunkable-issues#36]
**Is your feature request related to a problem? Please describe.**
Not a problem, just doesn't exist in Thunkable X

**Describe the solution you'd like**
Sending and receiving SMS can allow authentication of Ph. No; Passwords etc. on phones.

**Describe alternatives you've considered**
Similar to Texting built in AI2

**Which platform are you asking for?**
Thunkable X

**Additional context**
There are many uses for QRcode and Barcode scans. Too many to mention.

**Comment by jane-d-alt** [comment]
It is now possible to send SMS messages with the [Share](https://docs.thunkable.com/share#send-a-text) component.
