### ISSUE TITLE
Airtable data needs to be recieved/saved faster 

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#361]
There is a lag and delay when retrieving data such as pictures from airtable could you make it faster

**Comment by tatiang** [comment]
I have no idea what's involved with improving this but it would make a huge difference if image loading was faster. My images are 20K-50K but still a bit slow, although I think part of the speed issue is also related to how slowly objects clone.

**Comment by mark-friedman** [comment]
Our next release has some changes which should make at least some image loading faster.  I'm not sure if it will improve your cases but let's cross our fingers.  The next release should hopefully be out within the next week or so.

**Comment by ayocarti** [comment]
> I have no idea what's involved with improving this but it would make a huge difference if image loading was faster. My images are 20K-50K but still a bit slow, although I think part of the speed issue is also related to how slowly objects clone.

What kinda app is it 20-50k is ALOT

**Comment by ayocarti** [comment]
> Our next release has some changes which should make at least some image loading faster. I'm not sure if it will improve your cases but let's cross our fingers. The next release should hopefully be out within the next week or so.

If you make data recalling from database and airtable faster I’m sure his and my issue will be solved because with apps today’s everything is so fast no one has patience. Right now data recalling speed is 5 out of 10 it needs to be 9 atleast and please include fluidity and stability and some animations

**Comment by jane-d-alt** [comment]
Hi all, just following up here: we have improved our blocks speed and introduced the Data Sources blocks and Data Viewer components, which makes retrieving data from your online data sources even faster and easier. That said, if you are calling the same data every time your project opens, you can save your data as stored variables or to a Local Data Source and show that saved/cached data on startup, reducing load time even further.

Thanks for the feedback!
