### ISSUE TITLE
Loading Icon (spinner) staying visible, when position Absolute is used.

### ISSUE THREAD

**Issue by easaw** [thunkable/thunkable-issues#363]
### Platform
✕ Android companion

### Issue/Request Origin
The spinner is set to hidden on its component menu, but when "absolute" position  is used, it still shows. Clicking the button should also hide the spinner but it does not. When not absolute, it does hide.

Found it myself on X - tested live on Android (v157)

### Steps to Reproduce
1. add a loading icon to a screen on Thunk X
2. make the position Absolute  
3. turn visibility off in the component menu
4. test on Android Live

### Expected Behavior
it should stay invisible, or at least go invisible with button press (see example)

### Actual Behavior
It remains visible even when button pressed to change visibility

Red spinner is positioned absolute, green spinner has no position set. As you can see on the app, the green one disappears and the red one stays there.
[See example here](https://x.thunkable.com/copy/bab376718f12ba495497778fab2b5418)

**Comment by gre4twh1te** [comment]
seems to work on iOS tough.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved based on live testing using the Thunkable Live app on Android. We'll close this issue now; apologies for not following up when this behavior was originally resolved.
