### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by Voyaga** [thunkable/thunkable-issues#365]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thunkable X

### Issue/Request Origin
Whilst creating

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
1. Videos to play
2. Column to scroll
3. Layout background image to display

### Actual Behavior
Videos not displaying on iOS devices
Columns not scrolling
Layouts not displaying some images when set as background
Big delay in Live updating on the fly

  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
@Voyaga Could you please create separate GitHub issues for each of the bugs that you mention.  That will help us better track and prioritize them.  Also, could you please create simple projects for each of those issues and put share links (see [here](https://docs.thunkable.com/share-1)) for them in each of those GitHub items.  That will help us more easily reproduce and fix them!

Thanks in advance.

**Comment by josmas** [comment]
I am going to close this now; please follow instructions as per comment above. Many thanks!
