### ISSUE TITLE
Time Input and Date Input scrollable section not displaying

### ISSUE THREAD

**Issue by mr-mh** [thunkable/thunkable-issues#366]
### Platform
Thunkable X, Thunkable Live app

### Issue/Request Origin
Found it.

### Steps to Reproduce
1. Begin new project
2. Place Date Input or Time Input
3. In Thunkable Live app, click on input component.

Example project: https://x.thunkable.com/copy/6fd4205913873851574bee36bf29cf7a

### Expected Behavior
When pop-up menu is opened, selectable date or time spinners should display selectable text values.

### Actual Behavior
Pop-up menu opens, and is scrollable (phone can be felt vibrating as you swipe up and down on the pop-up menu), but text is not displayed. We've tried changing text and background colors.
```
  
![IMG_6673](https://user-images.githubusercontent.com/60448622/73938371-1eb9e080-48b5-11ea-8522-f174fdb8a837.PNG)

```

**Comment by mark-friedman** [comment]
@mr-mh Thanks for reporting this bug!

**Comment by josmas** [comment]
This should be fixed by now; please reopen as needed. Thanks!
