### ISSUE TITLE
Autoscroll the component tree

### ISSUE THREAD

**Issue by jaredgib** [thunkable/thunkable-issues#367]
**Is your feature request related to a problem? Please describe.**

Some of my screens are very busy. Rows nested in columns that are nested in rows within rows. ETC. within each of those, there may be many components. It can make finding the components I want to in the component tree difficult when there are also a lot of screens. This tree gets very tall. So, when i switch between the block editor and the design screen I may have to keep 'refinding' the component/s that I want to work with.

**Describe the solution you'd like**
When switching from block to design editor screen. I want the component tree associated with that active screen to automatically be displayed at the top of the list. Not necessarily moved around, but auto scrolled to so it is at th etop of the list and i dont have to find where I am working.

Also, if I click on a component in the design screen, I would like the component tree to auto-scroll and highlight that component that I have just clicked on in the design screen. 

**Describe alternatives you've considered**
I often zoom out and make the tree as tall as possible to find things. 

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)
Thnukable X

**Additional context**
It's not detrimental, just a little annoying. 

![giphy (3)](https://user-images.githubusercontent.com/58823942/73974272-0fa55380-48f2-11ea-8109-1654d9ac8416.gif)

**Comment by mark-friedman** [comment]
Thanks for the feature request, @jaredgib.  It looks very useful!

**Comment by kartiktambi** [comment]
I was also creating the very same request yesterday - but I saw this one!
We look forward for Thunkable to implement this useful feature 💯 

Thanks @jaredgib! 👍

**Comment by Lin-in-PA** [comment]
I also want this. No more scrolling through the long list to find things.

**Comment by kartiktambi** [comment]
Yes, we are on the same boat!
When you finally find your component in the viewer, it feels happy. Then we
go to blocks, and come back, we have to do the same drill.

This is a must feature...

Thanks!

**Comment by rem708** [comment]
I too find this very annoying. Slowes you down.

**Comment by rem708** [comment]
I too don't like this. Slows you down having to refind components

**Comment by easaw** [comment]
I've given this a thumbs up. 

Similar request here: https://community.thunkable.com/t/user-interface-feature-request/462821/ that would (more or less) fix my issue.

Please consider this an upvote. Thank you.

**Comment by josmas** [comment]
This was deployed a couple of days ago. Closing now.
