### ISSUE TITLE
Auto show component on double-click

### ISSUE THREAD

**Issue by sysads** [thunkable/thunkable-issues#368]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When you have lots of sub rows and columns in your project design and you click on any of the objects, on the component tree (top left), you have to scroll till you see the highlighted component which could be annoying especially if you have lots of components nested.

Can you add the feature so you simply double-click on the object in the design pane and it auto shows you the corresponding component even if its a sub of another sub object.

**Describe alternatives you've considered**
N/A

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
N/A

**Comment by mark-friedman** [comment]
I believe that this is pretty much the same feature request as #367.
