### ISSUE TITLE
List viewer not working properly with Web Preview

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#372]
Hi,

Hope this comes to the right place. It's about a bug. I just installed (Feb 11, 2020) the latest update to Thunkable Live app to Android and IOS and it seems that the live preview feature of these apps is not showing list viewer the right way. First of all, list viewer has only a white background and not the custom color I assigned to it. Secondly, list viewer now shows the full item for each one on the list, whereas previously it just showed the first line and then ... if the item didn't fit the screen. I preferred the old way as with long list items the viewer now gets pretty crowded.

I didn't download the app to try out if these changes are only related to the live preview or to the real thing as well but probably you can quickly find out how the situation is. Hope you can fix this soon, thank you!

Keep up the good work!

Best, 

Heikkki

**Comment by mark-friedman** [comment]
Thanks for the bug report @Heikkiss!  We'll look into it.

**Comment by weihuali0509** [comment]
We recently released a fix and it should resolve the issue. Please check again :)

**Comment by Heikkiss** [comment]
Hi, many many thanks, it works like a charm now again! :) Although a new issue came up, namely, with Android live preview there's a problem with showing an image. I have only one image in my app, on the Welcome screen, and with Android live preview it's shown only partially -- like top 30% of the image is shown and the rest is blank. Image works well with the browser preview as well as with IOS.

Best, Heikki

**Comment by Heikkiss** [comment]
Hmm. Okay. I had "space evenly" (vertically) with my Welcome screen and I changed it (to test) to flex-start, and the image started working properly again. I even changed it back to "space evenly" and it works now. Weird, but the problem is fixed now. Maybe this was only a weird glitch between version change.
