### ISSUE TITLE
X Android companio

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#374]
Since a couple of hours ago there's have been a couple of issue with the behavior of the companion in my Android

1. some times stay frozens on the logo when the app initializes
2. the most common issue is that the app pass throught the logo screen and then goes into a dark screen and it just stays there.
3. and it happens twices that redirects to a screen where it says a message from thunkable comunicating an error giving two options or either close the app or restore it 

Is rare when the companion reach to my project 

I had unnistall/reinstall the app or even deletes cache or restart my cellphone but nothing worked

**Comment by josmas** [comment]
Hi There, thanks for your report. Could you confirm this is still an issue, and can you please tell us if this is just happening for one particular project or all of them? Many thanks!

**Comment by danielcoglitore** [comment]
is working fine now! this was happened before I could open any project but now is working fine =D

**Comment by josmas** [comment]
Thanks for letting us know!
