### ISSUE TITLE
(Thunkable X) When you move the slider it twitches in Live on Android

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#376]
The slider should move smoothly when you move it with your finger, but instead it twitches, then one way, then the other.

**Comment by gre4twh1te** [comment]
it also does on iOS. I experienced that it also depends on the value that you put as step and min/max. some work better some are much worse.

**Comment by mrheadyhead** [comment]
Еhe same problem, when the application becomes relatively complex, the slider starts to glitch, and as I understand it, this is only visual glitches, the values are transmitted normally

**Comment by MrMazzone** [comment]
@mrheadyhead Interesting that you are seeing this.  They fixed this issue in February: https://github.com/thunkable/thunkable-issues/issues/265

I retested it now, and everything seems to be working great still (Android and iOS companion).Do you have a sample project showing this behavior?

**Comment by mrheadyhead** [comment]
@MrMazzone 
here is a relatively simple application for bluetooth, if you move the slider - you can notice the lag of the thumb
https://x.thunkable.com/copy/a0b2bfca0e09c3f6d6924c7756a81188

I also recorded a video but the effect on it is not so noticeable
https://drive.google.com/file/d/1Ss5AruGPl6Teld18baN5v-59a_31mZg_/view?usp=sharing

**Comment by MrMazzone** [comment]
@mrheadyhead Sadly, I cannot replicate the issue. The example app you provided runs smoothly on my devices, no lag with slider thumb.  But I do see it in your video. 

Can you confirm that your Android Live testing app (the Thunkable app) is up to date?  Current version I am seeing on my device is 197.  Check for updates in the Google Play Store.

**Comment by mrheadyhead** [comment]
@MrMazzone Yes, I use the latest version - 197. Perhaps on very powerful devices this is not so noticeable. I use Redmi note 5, on nexus 5 the situation with glitches is even worse. In the thunkable classic, there were no such problems even on the nexus 5

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved (now on Thunkable Live version 255-01). We'll close this issue now; apologies for not following up when this behavior was originally resolved.
