### ISSUE TITLE
Camera and photo library isn’t working 

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#377]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
 ✕ iOS companion?

### Steps to Reproduce
1.button + image library
2. 
3.

### Expected Behavior
What did you expect to happen? Photo library to open or camera 

### Actual Behavior
What actually happens? Nothing

**Comment by josmas** [comment]
thanks for the report @ayocarti We will look into it.

**Comment by ayocarti** [comment]
> thanks for the report @ayocarti We will look into it.

Please do because I get 4 hours per day just to work on my app and these 4 hours are wasted playing with these Bugs

**Comment by ayocarti** [comment]
> thanks for the report @ayocarti We will look into it.

Lmk as soon as this issue is fixed I really can’t work on my app at all it only pushes my patience

**Comment by ayocarti** [comment]
> thanks for the report @ayocarti We will look into it.
This is what I’m dealing with everyday 5-7 times daily and as you can see changes unsaved
![E005CB99-94AF-46B3-A5C3-0E3E358E4DEB](https://user-images.githubusercontent.com/58250868/74358830-f285ee80-4de3-11ea-9a88-b2274104a427.jpeg)

**Comment by weihuali0509** [comment]
Please track the update in this thread https://github.com/thunkable/thunkable-issues/issues/382
