### ISSUE TITLE
Video-Component plays no sound on iOS (Android does work)

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#378]
### Platform:
ThunkableX

### Steps to Reproduce
- Build a new app with ThunkableX
- Add the video component
- Set the video source (I set the source dynamically depending on user's choice)
- as a test I tried it with a simple app: a button (to start video playback) and the videocomponent. Same behaviour: on iOS no sound, on Android: with sound
https://x.thunkable.com/projects/5e43fdf414c464265ac2283b/project/properties/designer/

### Expected Behavior
- the video should play with sound. The ThunkableX-app plays video on Android with sound!
- under iOS it is possible to play sound (with the sound-component), so audio output is configured correctly.  My app has both sound-component and video-component installed. It is guaranteed, that only one or the other component is active at a time.
- I can also play other videos like youtube with sound under iOS
- I tested on an iPhone 6S and an iPhone 7S. 

### Actual Behavior
- no sound from video under iOS.
- negative tested with my app
-- in ThunkableX Live
-- Downloaded locally
-- in Apple Testflight
-- in App Store

**Comment by weihuali0509** [comment]
I tested your app and the video player is working fine. Can you try another source?

**Comment by kezb765** [comment]
Hi @weihuali0509 , does it play sound? Which iPhone do you use, because the problem only happens on iOS. I added a sound component on my sample app, would you mind to remix and test it again?

**Comment by gre4twh1te** [comment]
Audio plays finde on my iPhone 11 Pro and iOS 13.3.1 when it is in ring mode. It does not play any sound when my phone is muted, even if I manually adjust media volume. I experienced this earlier with several apps. Some play sound when my iPhone is muted but I adjusted the media volume, some just don't play sound at all...

**Comment by josmas** [comment]
I am going to close this down now, please feel free to reopen if the issue persists.
