### ISSUE TITLE
Bluetooth 

### ISSUE THREAD

**Issue by ryleyrandall22** [thunkable/thunkable-issues#38]
I think Bluetooth would be a fantastic feature to add to the new Thunkable X.

When trying to build modern IoT apps it seems like bluetooth (especially BLE) is necessary.

**Comment by irrintxi** [comment]
I agree. Than would be fantastic!!!!
I would like to use Thunkable X for a proyect where I communicate to an arduino BT module. Unfortunatelly I could only do it with classic Thunkable, by now.........

**Comment by Loud160** [comment]
Would also love to switch to Thunkable X but with out BT I'm suck using classic

**Comment by lemmingDev** [comment]
Yeah - really need this feature added as a priority me thinks.

IoT compatible boards are very cheap and readily available ATM, and allowing thinkable to be able to control them over BLE (including iOS) would be fantastic.

I have an Android myself, however half of the students that I would like to make apps for their phones have iOS :(

I'm sure they're working on it

**Comment by mark-friedman** [comment]
> I'm sure they're working on it

Yes, it's fairly high on our todo list.

**Comment by Loud160** [comment]
> > I'm sure they're working on it
> 
> Yes, it's fairly high on our todo list.

Any update on when this might be added?

**Comment by mark-friedman** [comment]
This is currently scheduled for sometime in the first half of 2019.  We'll get more specific as we get closer.

-Mark

**Comment by Loud160** [comment]
> This is currently scheduled for sometime in the first half of 2019. We'll get more specific as we get closer.
> 
> -Mark

I know this isn't the best place to ask questions but..... will there be support for using bluetooth in HEX or will it still treat every thing as strings(ascii)? 

One of the largest hurdles using Classic BT with any Automotive type interface has been that Classic BT treats all data as a strings and there was no way (with out custom extensions) to properly work with this type of data  when non-printable characters are involved .

**Comment by mark-friedman** [comment]
@Loud160 Thanks for the question on allowing for hex.  We'll definitely consider that in our design!

**Comment by JeremyChambers** [comment]
Would love to use BT in hackathon this week.

**Comment by mark-friedman** [comment]
@JeremyChambers While we are trying to get to this soon, I'm afraid that it won't be ready this week.  BTW, can you (and the other folks who've posted to this issue) tell us a little more about how you would have wanted to use BT support?  Different people mean different things when they ask for BT support, so the more details we have, the better we can add that support.

**Comment by measley** [comment]
Service looks cool. Agree BLE context for hooking up IoT developer boards would be very differentiated. 

Somehow to associate a button with a UUID would be helpful. example.

**Comment by lemmingDev** [comment]
Personally, for a start, I simply want to be able to send and recieve simple text data over classic BT on both iOS and Android.

Other functionality could follow later.

**Comment by jane-d-alt** [comment]
Thunkable X now has a [Bluetooth Low Energy](https://docs.thunkable.com/bluetooth-low-energy) component.
