### ISSUE TITLE
Camera does not activate for taking photos or for Image Recognizer

### ISSUE THREAD

**Issue by bitvrbit** [thunkable/thunkable-issues#382]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
 ✕ iOS companion

### Issue/Request Origin
 Community

### Steps to Reproduce
1.button + taking photos or for Image Recognizer
2. 
3.

### Expected Behavior
camera activation to take photos

### Actual Behavior
nothing
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by bitvrbit** [comment]
Hi everyone.From two days or problems with two projects. one who takes pictures and latro that uses Image Recognizer. In both projects the camera is no longer activated at my command. Yet the blocks worked a short time ago. I also tried prevew on device with Snap Gran app and the camera does not activate.

**Comment by josmas** [comment]
Hi @bitvrbit thanks for your report. We will try and reproduce the problem and get back to you. Can you please confirm this is happening on iOS Companion for X? Thanks!

**Comment by bitvrbit** [comment]
> Ciao @bitvrbit grazie per la segnalazione. Proveremo a riprodurre il problema e ti ricontatteremo. Potete per favore confermare che ciò sta accadendo su iOS Companion per X? Grazie!

**Comment by bitvrbit** [comment]
> Hi @bitvrbit thanks for your report. We will try and reproduce the problem and get back to you. Can you please confirm this is happening on iOS Companion for X? Thanks!

thanks for the answer.I tried to use the two apps on another device but the result is the camera does not activate the command takes a photo, or uploads a photo from the library, send photos for Image Recognizer does not answer.I also tried a simple button app takes a picture but it doesn't work. both apps are tested with 1) thukable live 2) installed directly on the phone, nothing

**Comment by josmas** [comment]
Hi there, thanks for confirming? Also, did you mean to close this issue? I will reopen it, but feel free to close it again. We generally leave issues open until resolution. Thanks!

**Comment by bitvrbit** [comment]
> Ciao, grazie per aver confermato? Inoltre, intendevi chiudere questo problema? Lo riaprirò, ma sentiti libero di richiuderlo. Generalmente lasciamo aperti i problemi fino alla risoluzione. Grazie!

ok
https://community.thunkable.com/t/image-library-or-camera-isn-t-working/460379

**Comment by bitvrbit** [comment]
> Hi there, thanks for confirming? Also, did you mean to close this issue? I will reopen it, but feel free to close it again. We generally leave issues open until resolution. Thanks!

ok.
He wants to tell you that another user of the thunkable community has encountered the same problem.

**Comment by weihuali0509** [comment]
We identified the issue and @josmas implemented a fix. The fix is on the way and it should be released in the next 24 ~ 48 hours or sooner

**Comment by bitvrbit** [comment]
thank you so much for your work :)



Il giorno gio 13 feb 2020 alle 06:37 WeiHua Li <notifications@github.com>
ha scritto:

**Comment by bitvrbit** [comment]
Il giorno gio 13 feb 2020 alle 07:21 Simone Ambrosi <bitvrbit@gmail.com> ha
scritto:

**Comment by bitvrbit** [comment]
Il giorno gio 13 feb 2020 alle 07:22 Simone Ambrosi <bitvrbit@gmail.com> ha
scritto:

**Comment by bitvrbit** [comment]
Hello again, I wanted to warn you that the camera and the command octine photos from the library are not activated yet.And thanks in advance for the help.

**Comment by bitvrbit** [comment]
> Abbiamo identificato il problema e @josmas ha implementato una correzione. La correzione è in arrivo e dovrebbe essere rilasciata nelle prossime 24 ~ 48 ore o prima

Hello again, I wanted to warn you that the camera and the command octine photos from the library are not activated yet.And thanks in advance for the help.

**Comment by josmas** [comment]
hey @bitvrbit have you updated the companion on your phone?

**Comment by bitvrbit** [comment]
Yes

**Comment by bitvrbit** [comment]
I try to install thunkable live.

**Comment by bitvrbit** [comment]
Yes, it works :)

**Comment by bitvrbit** [comment]
yes sorry I hadn't reinstalled thunkable live. thank you :)

**Comment by josmas** [comment]
Thanks for letting us know, enjoy!
