### ISSUE TITLE
Text Input will not allow spaces in Live Test

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#383]
### Platform
Thunkable X

### Issue/Request Origin
On the forums: https://community.thunkable.com/t/text-to-speech-problem-no-spaces/460812

### Steps to Reproduce
1. Create a new project.
2. Drag a Text Input component onto the screen.
3. Press the Live Test button.
4. Click inside the Text Input field. Press the space bar on the keyboard.

### Expected Behavior
I expected to see spaces in the on-screen Text Input field.

### Actual Behavior
No spaces are appearing.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by weihuali0509** [comment]
We are working on a fix and it should be out in x.thunkable.com in the next 24 ~ 48 hours or sooner.

**Comment by weihuali0509** [comment]
cc @TingC

**Comment by josmas** [comment]
This is now fixed. Thanks again for your report.
