### ISSUE TITLE
Option to select status info bar colours 

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#386]
**Is your feature request related to a problem? Please describe.**
This feature is a MUST for future/Current developing as iOS 13 has made dark mode a standard and how androids are having dark modes too there is an issue on Thunkable regarding the perfect contrast color if I have a white background and my dark mode is off I can see the status bar info (Provider/wifi/time/battery) because font color goes black but now if I have dark mode ON I can not see anything because font goes white so it’s very difficult to choose a contrasting color especially such as in my case where I have both black and white themes 

**Describe the solution you'd like**
A simple switch in advance options of screen we click. Which says status bar font color and gives option black or white / Option 2 either let us pick our own color like how we can with button font color and background color / Thunkable automatically detects the background color and picks contrast color either black or white 

**Describe alternatives you've considered**
Tried using non black non white colors but with already limited features And now bad designs there is no one who would wanna use our apps 

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
Dark Mode ON vs OFF
![F095A3D3-4762-4817-B8A9-2BCED51FE7CC](https://user-images.githubusercontent.com/58250868/74469413-6eed0000-4ebe-11ea-9c0a-13f0bc30475c.jpeg)
![B0A979D3-8369-4F09-8EC3-899EF71D2454](https://user-images.githubusercontent.com/58250868/74469421-714f5a00-4ebe-11ea-8fad-6ec5e317860e.jpeg)

**Comment by eoinparkinson** [comment]
Does setting the screen background to transparent have any effect? Also maybe you could use certain colours that show white and black.
