### ISSUE TITLE
Screen Folders & Non expand after viewing blocks

### ISSUE THREAD

**Issue by realmisterfish** [thunkable/thunkable-issues#388]
Hi Devs,

First of all, great job with Thunkable. You all seem to be on it with constant updates and bug fixing.

I'm creating an app right now that's at around 50 screens. Soon it will be 100+ which is making it extremely difficult to add new screens and toggle back and forth 'design' and 'blocks'.

Three requests:

1. The most important one, please allow me to place screens in folders for organizational purposes (I beg you, this one is the most important for me and I think it would benefit the community as a whole).

2. Please toggle -off- the automatic expansion of everything once I toggle from 'design' to 'blocks' and back to 'design', There's no reason that everything should expand once I go back to 'design' from 'blocks'. I'm content with it all being MINIMIZED, if anything, but ideally it would remember what you had expanded and not do it automatically.

3. 'Live Test Beta' - this is a great idea- thank you for implementing it. Are you able to add resolution customization of say, the most popular phone sizes? As an aside, it doesn't allow me to click anything, like expandable buttons, etc.

I know you have a lot going on, so please, please, please allow me to organize screens into a folder.

Thank you for the work you've done so far!

Boris

**Comment by josmas** [comment]
Hi Boris, thanks for reaching out. Your requests are very valid but, unrelated to those 3 items, I am curious about your need for 50 or 100 screens. Can you elaborate a bit to see if we can find a way to minimize that number? Probably the community forum is the best place for a discussion like that.

**Comment by realmisterfish** [comment]
Hey Jos,

Thanks for getting back to me so quickly.

Sure, I'll explain what I'm doing.

The app is going to have 2 major parts: testing and rehabilitation

The testing part will have different sections of the body: foot, knee,
hips, torso, shoulder, elbow, arm, back and neck, head.

Each section of the body has a unique logic flow the user must go through
designed by physiotherapists leading them to a result.

Through the result page, or by selecting 'rehabilitation' at the beginning,
the user can then go to the rehab portion. The rehab portion will have a
program for each 'diagnosis', and we will have many screens for each
'diagnosis' with specific text, image and videos.

Does that make sense or is there anything I should elaborate on?

**Comment by realmisterfish** [comment]
To piggy back on my last post, even with around 50 screens right now, if I
add a new screen, I have to scroll for a minute just to get it to the top
so I can see it while I'm editing it or to confirm the edits I've made. In
order to do this, I have to collapse every single screen in order to drag
it up. The process of dragging the new screen to the top from the bottom is
not quick either, it has to be done in stages because if you click and drag
the screen to the top, it is slower than moving it to the top of whatever
view is available, scrolling up, and moving it to the top again.

The folder option would be huge for organization as would not automatically
expanding screens after toggling back and forth between design/block/design
views.

**Comment by josmas** [comment]
Hi there, I can understand the issues with having so many screens but the main issue here is that you you seem to be [hardcoding](https://en.wikipedia.org/wiki/Hard_coding) all your data into separate screens and not reusing any of them. An app like the one you are describing can be programed with a much smaller number of screens if you have both your data and the logic for each of the branches in a database.

It is not a straight forward transition, and you may have to maybe compromise on some of the layouts and make each screen more uniform, but I highly recommend that you find ways to simplify your app with some programming instead of hardcoding all your data. The community forum is probably the best place to ask questions about how to do that.

**Comment by realmisterfish** [comment]
Hey Josmas, I'll definitely do that- thank you.

Given the logic flow of the app, I think it would be far more difficult to add data and logic for each branch in a DB than adding separate screens. 

That said, even if the logic was added, could you please add folders? Or some way to consolidate screens? 

I can deal with the auto expansion but I beg you for folders to help organize

**Comment by realmisterfish** [comment]
Hey, now when I move anything from one screen to another, it expands everything in the screen from which I moved it.

When I collapse a screen, it auto moves it to the top.

Can we please get rid of auto expanding? If I'm moving something from screen Y to screen X, why does screen Y expand?

**Comment by realmisterfish** [comment]
Please, I beg you to remove auto expand. I'm noticing now even when I drag a screen above another screen, it auto expands everything below it.

This has to be a bug, there's no reason for this. Why was this implemented? It's making editing take 10x as long. At least give us the option to turn it off or remove it. This can't have been requested by anyone.

**Comment by josmas** [comment]
Hi @realmisterfish, I have added the auto expand behaviour as an issue and we'll look into it. Thanks!

**Comment by jane-d-alt** [comment]
Following up on what we have implemented that addresses these requests:
1) You can now save screens to a 'Saved Screens' folder, allowing you to file screens and move them between projects
2) The behavior where content on the Design tab is auto-expanded has been resolved
3) With snap-to-position projects, you can preview your app on different sized screens by following these instructions: https://docs.thunkable.com/generate-screenshots#preview-your-app-on-different-sized-device-screens
We are planning to implement more in-platform resizing options in the new drag and drop Thunkable UI

I hope these new features satisfy your requirements! We'll close this issue for now; apologies for not following up when these features were originally implemented.
