### ISSUE TITLE
Rotate Buttons, Sliders, text, labels

### ISSUE THREAD

**Issue by makarocket45** [thunkable/thunkable-issues#39]
**Is your feature request related to a problem? Please describe.**
Want to be able to have a user interface in landscape mode

**Describe the solution you'd like**
Would like to be able to do User interface in landscape mod as well which requires rotating
basic gadgets by 90 degrees. 

**Describe alternatives you've considered**
Could use Canvas and make custom sliders, buttons, text but would be less effcient

**Which platform are you asking for?**
For both platforms, 

**Additional context**

**Comment by jane-d-alt** [comment]
It is possible to rotate components in Thunkable X. [Community post tutorial](https://community.thunkable.com/t/layout-how-to-use-transform-perspective-rotate-settings/72850/2?u=jane)
