### ISSUE TITLE
Publish on iOS: the step 4 "App info" does not display

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#390]
### Platform
ThunkableX

### Issue/Request Origin
Publishing to App Store

### Steps to Reproduce
Open a project, click on "publish -> Publish to App Store (iOS)"
Follow the steps.

### Expected Behavior
1.Register App 2.2FA 3.App store connect 4.App info
After step4, the app should be send to the Apple App Store.

### Actual Behavior
The workflow never reaches step 4. The window (right side) stays in step 3, while the timeline (at the left) tells me that we are in step 4, which is false.

![grafik](https://user-images.githubusercontent.com/7669660/74689942-6d347c80-51dd-11ea-86df-006994fac39c.png)

I have found this behavior with two different apps!

**Comment by TingC** [comment]
@kezb765 Thanks for reporting! This issue should be resolved now. Please try again when you get a chance 🙂
