### ISSUE TITLE
Date input does not work with dark mode 

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#392]
Date input does not work when phone is turned on in dark mode 
### Platform
✕ iOS companion?
### Steps to Reproduce
1.put date input / time input 
2. Turn dark mode on 
3.

### Expected Behavior
What did you expect to happen? Show black font color on white back ground of date input 

### Actual Behavior
What actually happens? Shows white font color on white background of date input 
```
  STACK TRACE AND/OR SCREENSHOTS
``` 

with dark mode on 
![068DFE51-667C-482C-82DB-BB1141FC8389](https://user-images.githubusercontent.com/58250868/74896291-c1925480-53b5-11ea-8f48-aa677f4257a1.gif)

With dark mode off
![0ADAFBD1-F1B4-4430-B50A-1260C7428D76](https://user-images.githubusercontent.com/58250868/74896329-d7077e80-53b5-11ea-9401-f22bfd45b91d.jpeg)

**Comment by josmas** [comment]
This should be fixed by now. Thanks!
