### ISSUE TITLE
Web Api "PATCH"

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#393]
**Is your feature request related to a problem? Please describe.**
I'm triying to use Firestore web api 

**Describe the solution you'd like**
PATCH method to the web API component

**Which platform are you asking for?**
Thunkable X

**Comment by amblemind** [comment]
Upvote: This is a dup of https://github.com/thunkable/thunkable-issues/issues/130 and should be merged/deleted.

**Comment by josmas** [comment]
closing as 
Duplicate of #130
