### ISSUE TITLE
A few practical feature requests

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#394]
Hi there,

First of all, let me start by thanking the whole Thunkable team and community for an awesome platform. I think Thunkable is really changing the world for the better.

I just wanted to share a few practical feature requests for Thunkable X, which are probably nothing new but I just wanted to highlight the need for them. I just spent a few weeks pretty intensively developing an app on the platform, and it turned out pretty nice but along the way a few things kept coming up. I understand that the list for potential features is endless, but what I want to highlight is the need for a few basics, which might (I hope) be also somewhat easier to develop. So here goes:

- In the blocks view, when you right click an item you get the menu where you have the options for expand/collapse the block and delete it right next to each other.  When working on a bigger project you obviously want to make use of the expand/collapse feature of blocks, but guess how many times you end up clicking the delete instead? As there really is no safeguard for accidental deletes, guess how annoying this can be. So, I'd suggest the menu would be redesigned so that expand/collapse and delete are not so close to each other. Also a prompt against accidental deletes would be needed.

- The previous point also brings me to my next one, namely, a need for the undo. I get it that an extensive undo might be too demanding but how about even an undo for the previous action. This could save a lot of sweat and tears... And not only in the case of deletes.

- Then about saving the project. I've made numerous copies and shared links to myself to the project so that nothing would happen to it. However, I've felt uneasy about the whole thing the whole time. Reading from the forums how people's projects have suddenly been corrupted (copies included) you can't help but wonder will the same happen to me. After spending so much time and effort, you'd really want to make sure the project is safe. I get it that you want to keep everything online but how about you allowed people to download some kind of a Thunkable project file to the computer. This would let me sleep better... :) After all, you must have such a file on your server already. Overall, what I want to stress is that the lack of hard copies really is an issue from the user perspective.

- In other words, currently, as everything is in the same place, on your server, you can see the potential for a catastrophe. Of course, as you develp the platform, some kind of backward compatibility might be an issue, but going forward into the future I just can't see any other reasonable way than allowing people to download Thunkable project files. So, the sooner this would be taken into account, the better. And if you want to limit sharing of these files (for some reason), you could still tie up the file to a certain account.

- Finally, about the loading screen. I might be wrong here but at least I didn't find a way to change the color of the loading screen for the app. So here I had developed my app with this particular green color as its characteristic trademark and then I find out the loading screen can only be white (correct me if I'm wrong). And, after all, the loading screen is the first thing everybody is going to see when they launch the app. I would assume that giving the user the option to at least change the color of the loading screen might be somewhat easy to do, so I'd see a nice potential for a significant tweak here.

I could go on and on about feature requests, but I just wanted to bring up the few that would really make the platform more robust and would be, I guess, somewhat reasonable to ask for. Anyway, what you have already made is purely awesome and I hope you keep up the good work!

On a side note, you might consider branding yourself even more heavily in your well chosen "no code" direction--that the no code approach is really changing the world for the better in many ways, from teaching to empowering people. As I work in branding, sort of, I'd see even more potential here. And by the way, where is the store (online) where I can buy my own Thunkable no code hoodie.... :-) Love the beaver logo, too.

Thank you,

Heikki

**Comment by jane-d-alt** [comment]
@Heikkiss  Please make separate feature requests for each individual feature you are requesting.

**Comment by josmas** [comment]
Hi @Heikkiss as @jane-d-alt mentioned, separate requests are much easier for us to track.

We have already created a separate issue for your first point though, the one about deleting blocks, and we will look into some potential solutions shortly. We'll keep you posted.

Thanks for your report and for all the logo love, we love it too!

**Comment by Heikkiss** [comment]
Hi @jane-d-alt & @josmas Thanks for your replies! I'll create separate requests then.
