### ISSUE TITLE
Thunkable is crashing

### ISSUE THREAD

**Issue by realmisterfish** [thunkable/thunkable-issues#397]
Thunkable is crashing when I try to edit an image by clicking on 'advanced'. It automatically refreshes and freezes on a white screen

### Platform
android x ios

### Issue/Request Origin
please help

### Steps to Reproduce
1. select screen
2. click image element
3. click 'advanced' on the right column settings

### Expected Behavior
seeing the advanced settings

### Actual Behavior
it crashes on a white screen

**Comment by josmas** [comment]
Hi @realmisterfish is this happening in one particular project or in all of them?
It seems to be working fine for me.

**Comment by realmisterfish** [comment]
Specifically images once they're set to contain and scale

**Comment by josmas** [comment]
Do you happen to have the latest version of the companion? I am guessing this is happening on Android only? We fixed a similar with buttons a couple of days ago, so if you haven't yet updated the Companion, can you please do so and let us know? Thanks!

**Comment by josmas** [comment]
Also, as mentioned in the previous comment, there was an issue with rotations earlier this week; one thing to try is to remove all rotations (before you connect to the Companion) and then add them again. There was a bug in the way the rotations were written down, but removing them and adding them again should do the trick. Do let us know!

**Comment by jaredgib** [comment]
Hi when you say rotations, do you mean loops?

**Comment by josmas** [comment]
I actually meant **scale** in the advanced settings for image (or button) properties, not rotations (and not loops). Apologies for the mix up. The Transform advanced properties have both _scale_ and _rotate_.

**Comment by realmisterfish** [comment]
He @josmas , the link is https://x.thunkable.com/projects/5ddd6c476f31e0431e6496a3/51bc8168-2ce9-4a3d-817f-4814d9926f0b/designer

If I click 'advanced' the entire page goes white and freezes

Can this please be resolved?

@weihuali0509 @jaredgib

**Comment by josmas** [comment]
Hi @realmisterfish 
I can see the error now, but I do not know where it is coming from. If you want to try something quick: I made a copy of your project and deleted the image component, then added it again, place the image again, and applied the advanced properties you had. It works fine in my copy. Would you mind trying that?

**Comment by realmisterfish** [comment]
Hey Jos, thanks for getting back to me.

I have 15+ screens with images and settings already in place- will it be
fixed in a few days?

**Comment by josmas** [comment]
As far as I can see, this only happens in your current first screen (shoulder flow 27) and on screen Shoulder flow 1. The other ones are fine and not crashing.
I do not have an ETA for a fix as I don't know enough about the issue, but I can let you know when I do. Thanks!

**Comment by realmisterfish** [comment]
Thanks @josmas, appreciate your response and for looking into it.

PS: Please remove auto-expanding of screens/elements. From a UI perspective, there is no need to have that toggled on (especially when switching from design/blocks). If there is a way to set it to remember what was expanded/collapsed, that is by far superior to what is happening now and a solution to what feels like a bug.

**Comment by josmas** [comment]
hi @realmisterfish we are looking into the expand/collapse behaviour, but were you able to change the two images? are you still having issues with the project?

**Comment by realmisterfish** [comment]
Hey Jos, it's working now ⚡thank you

**Comment by josmas** [comment]
Thanks @realmisterfish I'll close this now then.
In the new release you will see changes for expand/collapse. Thanks!
