### ISSUE TITLE
Unlink Community to x.thunkable.com

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#398]
I have seen people have the same issue before.

I use a seperate email for my x.thunkable.com account, but every time I try to sign into the email used with community.thunkable.com it links be back automatically to sign in with my x.thunkable.com account. 

Is there any workaround for this or can this be changed? Can't even log into my community account now as it gives an error when redirected to x.thunkable.com

**Comment by domhnallohanlon** [comment]
Hey @eoinparkinson - were we able to resolve this in another channel? 

I've done something similar to this in the past myself and it should be possible for you too?

**Comment by eoinparkinson** [comment]
@domhnallohanlon yes! i appreciate your assistance on that one. i really should have closed this topic. thanks.
