### ISSUE TITLE
An ability to customize the loading screen (color at least)

### ISSUE THREAD

**Issue by Heikkiss** [thunkable/thunkable-issues#402]
Hi there,

I have a feature request for the loading screen (for Thunkable X). I might be wrong here but at least I didn't find a way to change the color of the loading screen for an app (or any other attributes besides the logo). Recently I developed an app with a particular green color as its characteristic trademark and then I found out that the loading screen can only be white (correct me if I'm wrong). And, after all, the loading screen is the first thing everybody is going to see when they launch the app. I would assume that giving the user an option to at least change the color of the loading screen might be somewhat easy to do, so I'd see a nice potential for a significant tweak here. Even better if other characteristics of the loading screen could be tweaked too (editing the whole layout), but the color would be the most important one.

Thank you! Keep up the good work!

Best,

Heikki

**Comment by josmas** [comment]
This is being tracked at https://github.com/thunkable/thunkable-issues/issues/175
Closing as a duplicate but thanks for your request!
