### ISSUE TITLE
Screen resizing for iPad/tablet products

### ISSUE THREAD

**Issue by thunkableBob** [thunkable/thunkable-issues#403]
I need the design screen to resize to support iPad screens or other tablets, not just phone screens.
I can Live Test with my iPad device but not on the Live Screen pop-up window.

**Comment by AlexITMan** [comment]
Add style for Stylish or Greasemonkey:

    .web-companion-container{
    	width:640px !important; /* set Width + 40px */
        height:440px !important; /* set Height + 40px */
    }

    .r-v5p6jw{
    	width:600px !important; /* set Width */
    }

    .r-115ktas{
    	height:400px !important; /* set Height */
    }

**Comment by jane-d-alt** [comment]
You can follow these instructions to web preview your app on different sized screens: https://docs.thunkable.com/generate-screenshots#preview-your-app-on-different-sized-device-screens

We will also be adding more web preview resizing options to the Drag and Drop UI.
