### ISSUE TITLE
Downloaded app verification issue (iOS)

### ISSUE THREAD

**Issue by xixxiv** [thunkable/thunkable-issues#404]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
**Thunkable X iOS**

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. Download iOS app via e-mail
2. Check network online
3. Verify "iPhone Distribution: Rappidly Inc" App

### Expected Behavior
What did you expect to happen?
- Running correctly

### Actual Behavior
What actually happens?
- **I tried several times but it is not verified because of network problem.** 

I am using iPad(4th gen, 2012) under iOS 10.3.3.
It worked well until a week ago.
However, a few days ago, it did not start with the above symptoms.

```
  STACK TRACE AND/OR SCREENSHOTS
```
![IMG_0003](https://user-images.githubusercontent.com/53360246/75301690-cdcb5580-587e-11ea-89af-3ec247e5cb11.PNG)
![IMG_0004](https://user-images.githubusercontent.com/53360246/75301693-d02daf80-587e-11ea-9a3e-8def86134fab.PNG)

**Comment by weihuali0509** [comment]
Hi, please following the instruction here - 

https://docs.thunkable.com/download#to-install-trust-thunkable-on-your-device

**Comment by xixxiv** [comment]
I checked network online but the problem is that it doesn't progress anymore here. Not verified

**Comment by xixxiv** [comment]
@weihuali0509 
Thanks. But I checked network online but the problem is that it doesn't progress anymore here. Not verified.
