### ISSUE TITLE
Live test bug - all elements over lap in the center of the screen

### ISSUE THREAD

**Issue by Lin-in-PA** [thunkable/thunkable-issues#405]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
X

### Steps to Reproduce
1. make a screen with 3 rows 10%, 80% and 10% 
2.  In the top row put a label with height fit contents.
3. In the middle row put a label with height fit contents.
4. In the bottom row put a 2 buttons with height fit contents.

### Expected Behavior -- ### Actual Behavior
Live test - I expected the screen  to look like the design, but all the content was overlapping in the middle of the screen

<img width="324" alt="thnkable bug" src="https://user-images.githubusercontent.com/33335803/75354342-cf931a00-587a-11ea-86e7-83ef5eee2678.png">

**Comment by weihuali0509** [comment]
Thanks for reporting @Lin-in-PA ! Can you share a project link with us?

cc @TingC

**Comment by Lin-in-PA** [comment]
https://x.thunkable.com/copy/8c5e41d965b2d25a51989b709f67c377

Yours,

Lin Taylor
717-766-2511 Ext. 2341

________________________________

**Comment by josmas** [comment]
Thanks @Lin-in-PA We can reproduce it and we'll look into it!

**Comment by TingC** [comment]
Hi, @Lin-in-PA, the project should now work as expected on the web live test. Please let us know if you still have any issues, and we'll be more happy to look into it. Thanks!
