### ISSUE TITLE
Screen_Start not firing

### ISSUE THREAD

**Issue by thunkableBob** [thunkable/thunkable-issues#406]
I'm finding that the Screen_Starts is not firing.
The Screen_Opens seems to work.
When my project loads, or reloads after changes,  Screen_Starts should act on the blocks contained in it, but does not.
I must navigate to another screen and return to the Home screen when Screen_Opens works and acts on the blocks contained in it.
The screen I navigate to contains a Screen_Open container and works correctly.

**Comment by josmas** [comment]
Hi @thunkableBob this might be related to the lifecycle of screens. Navigating back and forth from screens does not mean that they are always killed and recreated. If you need something to run when the screen shows, you should use Screen_Open.

If you have a look at the docs, it specifies that [Screen_Start](https://docs.thunkable.com/screen#when-screen1-starts) only runs when the screen is created.

If you want to read a more detailed techinnical account of what is happening, for instance on Android, you can have a look at this: [Understanding the Activity Lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle). Figure 1 shows how Screen_Start(onStart in the figure) happens more often that Screen_Create(onCreate in the figure).

**Comment by josmas** [comment]
I guess I should add, the takeaway here is that if you want to do something that `lives` for as long as the screen is `alive`, say for instance set up some variables or any procedure call that should happen only once, then Screen_Start is the block you need.

If you need actions to happen every time the screen shows, use Screen_Open.

**Comment by thunkableBob** [comment]
Hi Jos,  I was having an issue loading information from Local_Storage into
a list variable.  Further troubleshooting showed that Screen_Starts or
Screen_Opens works fine.
It was the way I was loading the variable from the Local_Storage Get.  If I
load it from the Do of the Get it all works fine, but I if I load the
variable after the Local_Storage Get, not all of the information gets
loaded. Not sure why.
Another block of Local_Storage Get loads the variable fine.  It just acted
squirrelly!
Thanks for your help.

**Comment by josmas** [comment]
Not a problem, good to hear you are sorted out! Thanks!
