### ISSUE TITLE
Adding Airtable not working

### ISSUE THREAD

**Issue by docbobo** [thunkable/thunkable-issues#407]
### Platform
Thunkable X

### Issue/Request Origin
When trying to add an invisible component like e.g. Airtable, the browser refreshes to an empty page. I noticed that as part of the process, the URL shown is changing - the second GUID in the path updates.

### Steps to Reproduce
1. Create empty project
2. Drag Airtable to either design area or "Invisible Components" area
3. Browser refreshes to empty view

### Expected Behavior
Airtable component is successfully added to the project

### Actual Behavior
Nothing added to the project.

**Comment by josmas** [comment]
Hi @docbobo thanks for your report. I can reproduce it and we will try to get a fix out asap.

**Comment by josmas** [comment]
This should be fixed now. Thanks again for your report @docbobo 
Leaving open until we get confirmation.

**Comment by docbobo** [comment]
I can confirm that this is again working properly for me. Thanks, @josmas

**Comment by josmas** [comment]
Great stuff, thanks for confirming!
