### ISSUE TITLE
Admob SDK not working

### ISSUE THREAD

**Issue by shemxyz** [thunkable/thunkable-issues#408]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
 ✕ iOS companion?

i email AdMob they said it could be an issue with the SDK 

### Expected Behavior
supposed to show all the time 

### Actual Behavior
shows sometimes
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
Hi @shemxyz thanks for your report. Could you please be a bit more specific?

What is it that should show all the time? Are we talking about a particular ad? Or is the component that shows sometimes?

At times it is easier to communicate an issue by providing screenshots, if you have the time. Thanks!

**Comment by ayocarti** [comment]
> Hi @shemxyz thanks for your report. Could you please be a bit more specific?
> 
> What is it that should show all the time? Are we talking about a particular ad? Or is the component that shows sometimes?
> 
> At times it is easier to communicate an issue by providing screenshots, if you have the time. Thanks!

Her and I are having the same issues. Banner ad can be seen but reward ad gets hit with the following error 

![A9E3B69E-22F9-4EE6-A91C-4821D899498D](https://user-images.githubusercontent.com/58250868/75565612-172ec700-5a70-11ea-8aa2-b1f3d475f78d.jpeg)

(Try again later is not the part of error)

**Comment by josmas** [comment]
Hi there, this seems to be an issue with your admod config. Please follow instructions here for a fix: https://stackoverflow.com/questions/39108558/admob-bannerview-request-error-no-ad-to-show

Thanks!
