### ISSUE TITLE
Airtable error

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#409]
Basically I attached two data’s to same airtable table called “feed” when you sign up your picture and etc is uploaded here as a new row (this works still) and secondly I made post photos section where you put caption and put pictures then press post and the pictures are created as a new row. It was working fine for last month or so and then out of nowhere it stopped working. The pictures are being uploaded to cloudinary as wanted but it’s not being created as a new row I dont know why but when you sign up a new row is created So I figured there is any issue in “post” section but I didn’t changed anything in the blocks and I have error blocks everywhere but when the block execution reaches the create row it shows error “trouble creating row” what could be the issue?

### Platform
 ✕ iOS companion?

![4CECD3FA-227C-478E-9271-B88EE5B2F00C](https://user-images.githubusercontent.com/58250868/75567100-c5d40700-5a72-11ea-9600-45f96cff38bd.jpeg)

**Comment by josmas** [comment]
Hi there, can you please post a link to the project or screenshots of the errors? thanks!

**Comment by ayocarti** [comment]
That’s only error I get and I already put the picture for it. “Trouble creating row”

**Comment by josmas** [comment]
from your previous post:

> I didn’t changed anything in the blocks and I have error blocks everywhere

**Comment by ayocarti** [comment]
> from your previous post:
> 
> > I didn’t changed anything in the blocks and I have error blocks everywhere

I meant error blocks not in error blocks. You know when you recall data and there is a value and error block basically what I’m saying is I only get error while creating the row in airtable else I would have known what the issue was if it was caused by something else 😇

**Comment by josmas** [comment]
This sounds like an issue with your blocks, please ask for help in the community but do provide screenshots of your blocks, otherwise we cannot help.

**Comment by ayocarti** [comment]
> This sounds like an issue with your blocks, please ask for help in the community but do provide screenshots of your blocks, otherwise we cannot help.

If there was an issue with the blocks it wouldn’t have worked in first place -_- it was working before

**Comment by josmas** [comment]
If you haven't changes any of the blocks, then you've most likely changed something on the airtable side. That error will pop up if for instance column names do not match or do not exist.

As mentioned in the previous comment, please ask for help in the forums and provide enough information such as blocks and fields/structure in airtable. Thanks!

**Comment by ayocarti** [comment]
> If you haven't changed any of the blocks, then you've most likely changed something on the airtable side. That error will pop up if for instance column names do not match or do not exist.
> 
> As mentioned in the previous comment, please ask for help in the forums and provide enough information such as blocks and fields/structure in airtable. Thanks!

The issue wasn’t my blocks like I told you. The issue was airtable. My table had a column which had auto number and when I changed from row auto number to single text it worked
