### ISSUE TITLE
Airtable: CreateRow from variable failed.

### ISSUE THREAD

**Issue by docbobo** [thunkable/thunkable-issues#410]
### Platform
Thunkable X

### Issue/Request Origin
Calling Airtable CreateRow directly from a stored object fails with an error message. However, converting the object to and from JSON beforehand works:

**Not Working**
<img width="804" alt="Screen Shot 2020-02-29 at 10 38 53" src="https://user-images.githubusercontent.com/1257060/75605130-509f1b00-5ae0-11ea-939b-b68766a9792c.png">

**Working**
<img width="782" alt="Screen Shot 2020-02-29 at 10 38 38" src="https://user-images.githubusercontent.com/1257060/75605133-5563cf00-5ae0-11ea-8e51-b4c1ef696b22.png">

**Comment by josmas** [comment]
hey @docbobo
How are you storing the object? I just tried the following and it works:

<img width="564" alt="plain_object_Airtable" src="https://user-images.githubusercontent.com/194925/75610409-d040e000-5b08-11ea-8781-e9513a75c900.png">

You can see it here: https://x.thunkable.com/copy/c3d731825a82179542885a4763d3c131

**Comment by josmas** [comment]
Note: you won't be able to run as I've changed the airtable key, but just wanted to show the blocks.

**Comment by josmas** [comment]
I believe  I understand what you are saying, if you use something like the following, it will not work:

<img width="659" alt="stored_object" src="https://user-images.githubusercontent.com/194925/75612882-a810ab80-5b1f-11ea-9636-db5afebaec15.png">

Our internal representation of an object is not just plain JSON data, which is why you need the workaround here. Agree that it's not ideal! :)

**Comment by docbobo** [comment]
Yes, exactly that. I want to update an object stored in a variable, then have it persisted. Took me a while to figure out that workaround of converting it back and forth.

**Comment by josmas** [comment]
Yeah, you are right, the usage is inconsistent. In _create_ we seem to be doing the conversion automatically. We should probably either convert depending on the type, or not convert at all anywhere, so at least it is consistent.

I am going to copy the issue over. Not sure when we'll get to it, but thanks a million for your report! Leaving it open until resolution.

**Comment by jane-d-alt** [comment]
This behavior has been resolved. We'll close this issue now; apologies for not following up when this behavior was originally resolved.
