### ISSUE TITLE
Columns won't display side by side in Thunkable cross platform

### ISSUE THREAD

**Issue by dghohens** [thunkable/thunkable-issues#42]
### Platform
This issue occurs on Thunkable cross platform. I have been able to reproduce this issue on both iPhone and Android.

### Issue/Request Origin
This occurred when trying to add columns to the design page of an app.

### Steps to Reproduce
1. Create new app
2. Drag 2 or more columns onto the screen
3. Notice that the columns stack on top of each other, rather than sit next to each other as expected from the column documentation:
https://docs.thunkable.com/thunkable-cross-platform/create/components/layout/column

### Expected Behavior
I expected the columns to sit next to each other, as is displayed here:
https://docs.thunkable.com/thunkable-cross-platform/create/components/layout/column

### Actual Behavior
The columns stack on top of each other.

![image](https://user-images.githubusercontent.com/41642475/43206181-187166e8-8ff3-11e8-88ed-95a56deff87e.png)

**Comment by mark-friedman** [comment]
Perhaps the documentation is a bit misleading.  The intent of a `Column` component is to display the components inside of it in a column (i.e. vertically).  To display a set of columns side-by-side you would put them within a `Row` component, whose purpose is to display the components inside of it horizontally.

**Comment by dghohens** [comment]
Thanks Mark, the columns work as expected when placed into a row.
