### ISSUE TITLE
(Thunkable X) Multiline displays as single line web preview

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#420]
A multi-line text input field is used for entering text, but in web browsing, the text is positioned as if the input area is a single line.

![изображение](https://user-images.githubusercontent.com/20015046/75899717-f0e0a100-5e4c-11ea-84f0-d61090857935.png)

**Comment by josmas** [comment]
Thanks @AlexITMan we'll look into it.
I am going to rename the issue though, hope you don't mind.

**Comment by josmas** [comment]
This should be working now. Closing but feel free to reopen as needed. Thanks!
