### ISSUE TITLE
(Thunkable X) Confusion with shadowOffset properties in the properties panel

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#422]
The figure shows properties that are visually related to the shadowOffset header. But, first, the property header has a smaller font than Width and Height, and, second, the Elevation and Opacity properties are not related to shadowOffset.

![изображение](https://user-images.githubusercontent.com/20015046/76163656-1c1f0500-6159-11ea-8f46-559f1c0b60b4.png)

This confusion can be easily seen in the following image, where the properties are arranged in rows for more convenient operation. The figure highlights elements that have incorrect markup.

![изображение](https://user-images.githubusercontent.com/20015046/76163772-255ca180-615a-11ea-9c45-9d09ec3d9a13.png)

**Comment by jane-d-alt** [comment]
Hi there,

We checked how these property inputs present and they seem more orderly now. Apologies for not following up when this layout was originally corrected. Thanks for reporting!
