### ISSUE TITLE
Set listener path for cloud variables 

### ISSUE THREAD

**Issue by jaredgib** [thunkable/thunkable-issues#423]
**Is your feature request related to a problem? Please describe.**
The realtimeDB can be difficult to use. I have begun using cloud variables instead as they are much easier to work with. I have also gotten to the point where I am setting pathways with in the cloud variables similar to the idea of keys using the real time data base. I do this so that I can secure the users information. However, when I add a listener to listen to that variable for data changes, anytime there is a data change the variable updates. The listener “listens” for any update but this can cause a incessant data usage and app updating if for example, user A is updating things in their specific pathway but user B is not. User B wouldn’t see changes but the listener would be pinged regardless. 

**Describe the solution you'd like**
A way to set the path or multiple paths within the variable for the listener so as to avoid unnecessary data usage and app updating. Like in firebase

This is how I set paths 
![CEB90C90-6FDC-46CE-B481-7FDB5B67BEB3](https://user-images.githubusercontent.com/58823942/76256338-24914180-6226-11ea-8892-9266839d6fd7.png)

**Describe alternatives you've considered**
Any component that utilizes a variable is checked against the updated value for a change. This is not efficient. 
![D1432C68-750D-4B03-A048-A74D32D4AFA2](https://user-images.githubusercontent.com/58823942/76256481-6621ec80-6226-11ea-8824-ac7483b153b8.png)

![737798C7-D30E-4595-9B03-01ECA5F6735B](https://user-images.githubusercontent.com/58823942/76256398-412d7980-6226-11ea-8dac-731ce5b2a974.png)

**Which platform are you asking for?**
Thunkable x

**Additional context**
I just want to keep user data secure using these cloud variables like firebase.

**Comment by AlexITMan** [comment]
The number of blocks in your example can be reduced by 5 times. Try this and you will see that both Firebase and cloud variables are quite easy to work with.

**Comment by jaredgib** [comment]
> The number of blocks in your example can be reduced by 5 times. Try this and you will see that both Firebase and cloud variables are quite easy to work with.

Here is my project link. https://x.thunkable.com/copy/e2e1ca0eff77585ea0b959936aba4c31

Perhaps you could demonstrate what you mean or direct me towards some tutorial? I hear what you are saying, but telling me I need medicine doesn’t fix my sickness. It doesn’t even tell me which doctor to see or what pill might work best. 

Also, I only have 3 months programming experience and reference your examples a lot. Perhaps you can suggest one of these with specific instructions to practice?

**Comment by jaredgib** [comment]
Do firebase wnd the cloud variables share the same pathways? For example. A cloud variable named ‘Apple’ and a firebase top level key ‘Apple’.  would these be the same pathway?

**Comment by danielcoglitore** [comment]
Yes! they are the same ! when you set up your firebase settings the cloud variables and firebase components will work with your database, I recomend you to use firebase blocks is better and you will find easier to use the realtimeDB

**Comment by jaredgib** [comment]
@danielcoglitore This is great! I haven't used them before. This is a game-changer. The ability to save and recall using the cloud variable but set paths with it and to specify the path making it easy to do things like this without any (or very very little) parsing of data from Firebase. 

<img width="502" alt="Screen Shot 2020-03-10 at 12 35 43 PM" src="https://user-images.githubusercontent.com/58823942/76336038-cc147f80-62cb-11ea-8c75-0a8ae7ff1483.png">
