### ISSUE TITLE
Videos cannot be replayed / restarted / scrolled

### ISSUE THREAD

**Issue by realmisterfish** [thunkable/thunkable-issues#424]
### Platform
Android x iOS

### Steps to Reproduce
1. Upload a video from Cloudinary into the 'video' component -or- copy the video URL and input it into blocks
2.  User plays video. User cannot restart the video or scroll to any point within the video. Once it is played 1x, it cannot be restarted
3. This occurs on both iOS and Android

### Expected Behavior
The user should be able to scroll to any point in the video or replay it

### Actual Behavior
The video is essentially 'locked'

Image #1 is the proposed 'fix' from Thunkable
Image #2 and #3 show the two ways I have videos set to display, both which do not work the way the 'fix' was presented. I was told by staff that this was indeed a bug and to post on Git

https://ibb.co/nQCN4zh
https://ibb.co/yFSBgQ4
https://ibb.co/L8WFTyJ

**Comment by josmas** [comment]
thanks for your report; we are tracking some issues with the video component. We'll update when we know more. Thanks!

**Comment by realmisterfish** [comment]
Thanks Jos, they're all being hosted on Cloudinary
