### ISSUE TITLE
Date Picker for birthday input is not convenience for user

### ISSUE THREAD

**Issue by mrkmchau** [thunkable/thunkable-issues#425]
**Is your feature request related to a problem? Please describe.**
Current version of date picker is not convenience for birthday input.
1) If user > 50 years old, It take too 50 x 12 button press to reach their birthday.
2) If user already input Date Of Birth, It can set to the Birthday if the date picker launch again.

**Describe the solution you'd like**
1) Create a year navigate button for move year back and forth
2) Display the user existing input date when date picker launch

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)
Andriod

**Additional context**

**Comment by jane-d-alt** [comment]
You can now navigate to different years when using the Date Input component on a device.
We'll close this issue now; apologies for not following up here when this feature was originally implemented.
