### ISSUE TITLE
Problem in Functions

### ISSUE THREAD

**Issue by tomer2526** [thunkable/thunkable-issues#427]
I recently wanted to translate my application, so I created a translation file (in json), here's the result: 
{
   "string1": "one",
   "string2": "two"
}

To get the application translated I did the following: 
![1](https://user-images.githubusercontent.com/32513840/76682438-f2585900-6604-11ea-9f1d-a48eaab697b5.png)

And everything works.
Then I wanted to save the blocks so I did the following: 
![2](https://user-images.githubusercontent.com/32513840/76682442-f97f6700-6604-11ea-899e-5214774fe362.png)

But after testing on a live test, it shows it: "undefined" instead of the translation that should be received.
The problem happens on all platforms.
Here is a link to the test project: https://x.thunkable.com/copy/75725db609a639b86a20c943484cc359

**Comment by JanhaviDahihande** [comment]
@tomer2526  Closing this issue as it seems to be working now as seen in the screenshot along with the blocks used. Please reopen if needed.

<img src="https://user-images.githubusercontent.com/20217203/89695114-b41b4900-d8c7-11ea-8a1b-7bf72a9f4b0f.png" width="300" height="500">

<img src="https://user-images.githubusercontent.com/20217203/89695212-fc3a6b80-d8c7-11ea-9a4c-11a20dc139f7.png">
