### ISSUE TITLE
Feature request to allow copying of components in Thunkable cross platform

### ISSUE THREAD

**Issue by dghohens** [thunkable/thunkable-issues#43]
**Is your feature request related to a problem? Please describe.**
Most apps require a consistent look and feel for each component on a screen. For instance, if I want to have 5 buttons on the screen, I would like each button to be the same size and have the same text size and color. Currently, I have to create each component and edit it separately.

This is especially an issue with screens, as I have to create each screen manually, rather than copying a screen that I'm already happy with and editing it accordingly.

**Describe the solution you'd like**
I would like to be able to copy components in Thunkable and paste those components into the same app. This could be done with keyboard shortcuts, or an icon next to the delete icon for each component in the top left menu.

**Describe alternatives you've considered**
I'm not aware of any other alternatives at this time. Currently we have to create and edit each component manually, which is a tedious process.

**Which platform are you asking for?**
This is for Thunkable X (cross platform), but this feature could be applied to Thunkable Classic as well.

**Comment by jane-d-alt** [comment]
Components can be duplicated in the Design tab and with the 'any component' blocks. We'll close this issue; apologies for not following up when this feature was originally added to the platform.
