### ISSUE TITLE
Lottie animation caused my screen to permanently crash

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#432]
I have a screen which shows peoples post it was working fine but then I decided to animation so I added animation and downloaded file from lottie animation and soon after doing that my screen started going white / crashing I removed the animation I downloaded and used the animation that didn’t caused my phone to previously crash but it still crashed then I decided to delete the animation component but then it’s still crashing. Now in total my two screens are crashing making my app 60% unusable

**Comment by easaw** [comment]
@ayocarti I've noticed some of the animations from the Lottie website don't validate well.

Also, use the left hand sidebar to upload the json. Don't use the upload button on the right (i.e. not the one in the animation settings), I've had issues, and the left sidebar seems to work better, or at least more consistently for Lottie jsons.
