### ISSUE TITLE
Set status bar colour (iOS)

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#433]
I have an issue, which is really only noticeable on devices with iPhone X/11 style screen. When my screen has a white background, the status bar text stays white. This means nothing shows. I can confirm this because when charging my battery the battery icon turns green but everything else is not visible. 

Is it possible to add the option in screen settings to change status bar text colour from white to black, or is this built into the phone to decide?

Thanks.

**Comment by ayocarti** [comment]
I mentioned these issues way before but back then you told me it’s my app :p

**Comment by josmas** [comment]
This is available now, although changing color only works on Android, you can select a light/dark theme for the bar in both platforms. Thanks!

**Comment by eoinparkinson** [comment]
I noticed this and this is great. Awesome work again from your team. Thanks!
