### ISSUE TITLE
Can data recalling via airtable be fast?

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#435]
Could you do something that makes data recalling through airtable fast for example I have image links in my airtable I use that link to show pictures but the lag is so so so so much that I’m looking at my thinking -_- no one will download my app it’s that bad

**Comment by josmas** [comment]
We are always looking at improving performance, but there's only so much we can do, especially if you want to load assets through the network, there're way too many things out of out controls such as network speed, thersholds for throtling, bottlenecks and so forth.

If you want to guarantee that your images load fast and with no errors your only option is to bundle them within the app.
