### ISSUE TITLE
ANNOYED AS HECK WITH THE INPUT LAGS

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#438]
No matter what I do or how small or big my app is there is always and ALWAYS input lags. Slow as heck app I hate Thunkable I can’t believe of all the languages I could spend time on I spent last 4-5 on Thunkable and ended up with slow as hell input lag on buttons navigations everything 

Please please fix this !! PLEASE

**Comment by josmas** [comment]
Please provide enough info for us to be able to reproduce by following one of the templates. Thanks!
