### ISSUE TITLE
Screens don’t scroll

### ISSUE THREAD

**Issue by miche0010** [thunkable/thunkable-issues#44]
Screens don’t scroll anymore in thunkable cross platforms

**Comment by miche0010** [comment]
https://x.thunkable.com/copy/7ab3101a77af58a3a3a27b2716724e9b

It seem to work in ThunkableLive app but not in the downloaded app on both
OSes. I think layouts scroll is not working too.

Il giorno mar 31 lug 2018 alle ore 22:20 mark-friedman <
notifications@github.com> ha scritto:

**Comment by mark-friedman** [comment]
Thanks @miche0010!  Using your project we were able to replicate the issue.  We're working on a solution.

**Comment by mark-friedman** [comment]
The latest release has the fix for this.
