### ISSUE TITLE
Unable to recall data from airtable

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#440]
It was working then it stopped working. I have rechecked apikey. Base id. Table name.
I have used airtable many times before so I know how to use it
I have put error alerts in case there is a error
But there is no error and I can’t seem to recall the values
It keeps saying label

![9EC81B5D-96F0-4CA3-9FD8-B4F602B1EA7B](https://user-images.githubusercontent.com/58250868/77643095-91c00900-6f80-11ea-99a6-f4d02a00d895.jpeg)

**Comment by josmas** [comment]
Please provide enough info for us to be able to reproduce by following one of the templates. Thanks!
