### ISSUE TITLE
Need audio recorder functionality, please!

### ISSUE THREAD

**Issue by beonice** [thunkable/thunkable-issues#442]
**Is your feature request related to a problem? Please describe.**
I am trying to find a way to record audio in my little sound recording app. I'm hoping to be able to save sounds like bird calls, the sound of waves thundering against a cliff wall, etc.

**Describe the solution you'd like**
I'm hoping to be able to save sounds like bird calls, the sound of waves thundering against a cliff wall, etc. My app would basically be a button that says "Record", and when I press that button, it records the audio until I release the button, or press a second button "Stop Recording". Once the recording is completed, the recorded audio should be saved and available for playback. 

I'd also like to use this functionality to actually save recorded audio notes and then be able to transcribe them, but for that, I already can use the speech recognizer->text, but that also doesn't save the transcribed text for later review/reuse.

**Describe alternatives you've considered**
I've experimented with apps that do speech recognition to text, but there doesn't seem any way to actually SAVE the audio for later!

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)
ThunkableX.

This functionality was available in Thunkable Classic apparently, but that is no longer accepting new registrations, so I can't even just say I'll stick with Android! :D Help, please!

**Additional context**

**Comment by jane-d-alt** [comment]
Thunkable now has an [Audio Recorder ](https://docs.thunkable.com/audio-recorder)component.
We'll close this issue; apologies for not following up when this component was originally added to the platform.
