### ISSUE TITLE
Maps component not displayed correctly within a container

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#449]
### Platform
X, iOS published app & companion 174-1

### Steps to Reproduce
1. place a map component with fill container settings within a row that is fill container too 
2. preview app in companion or built app

### Expected Behavior
maps component should fill container

### Actual Behavior
you can only see a part of the map:
![IMG_0615](https://user-images.githubusercontent.com/37402054/78247472-35626980-74eb-11ea-9bef-2641552b1208.PNG)
This also affects apps that where perfectly fine earlier therefor I assume it is a problem caused by recent changes to the companion app...

I think this issue is quite important to fix because it also affects existing apps when you want to publish an update.

**Comment by gre4twh1te** [comment]
also changing the maps height/width to 100% will mess it up even more. Currently the only way it seems to work is when the container is set ti 100% and the maps component to "fill container"...

**Comment by JanhaviDahihande** [comment]
@gre4twh1te Closing this issue as it seems to be working now as seen in the screenshot. Please reopen if needed.

<img src="https://user-images.githubusercontent.com/20217203/88235492-d195b500-cc2f-11ea-9ef4-9810a7833da2.png" width="300">
