### ISSUE TITLE
Canvas Sprite Drag Problem

### ISSUE THREAD

**Issue by Shemantab** [thunkable/thunkable-issues#450]
**Is your feature request related to a problem? Please describe.**
Yes, I am having problem in dragging the sprite in the stage. 
**1.** I cannot drag it to the desired location only. It means i want to drag sprite only from x-100,y-100 to x-200,y-200.
**2.** I cannot drag sprite in particular axis i.e. x only or y only.
**3.** When i drag the sprite it get out off the stage sometime.
**4.** I expect the sprite to move only when i drag and stop while i drop it.

**Describe the solution you'd like**
I would love if i could drag sprite within particular area.
I could drag sprite only in x axis
Sprite would stick on the edge while i drag instead of getting of from stage.
I expect the sprite stop as soon as i drop it or stop dragging

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by josmas** [comment]
Hi there, I am not sure if this is a feature request or a programming question. Could you please ask for help in the community forum? Many thanks!
