### ISSUE TITLE
how about a comment block

### ISSUE THREAD

**Issue by manyone** [thunkable/thunkable-issues#452]
**Is your feature request related to a problem? Please describe.**
it would be nice to prepend a sequence of complicated blocks to explain what's ahead

**Describe the solution you'd like**
maybe a simple block in bright color that contain a text box wiith autoadjusting height

**Describe alternatives you've considered**
a note alert that shows up when you hover over a block - the question is how would you anchor it?

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by josmas** [comment]
Hi @manyone you can right click a block and select `add comment`. It will show up as in this image (and can also be removed in the right click menu).
<img width="519" alt="comment" src="https://user-images.githubusercontent.com/194925/78989868-bd202780-7b2c-11ea-9586-09bbe991c0f5.png">
