### ISSUE TITLE
Webview Go Back on BackButton Pressed

### ISSUE THREAD

**Issue by mohammadaarizimam** [thunkable/thunkable-issues#460]
I found a feature that is missing in this great app builder is, Webview Go Back on BackButton Pressed.

**Comment by MrMazzone** [comment]
You can build that yourself.  If you track a history of visited URLs in a list (or at least the previous URL), you can program the following event handler to do as you describe. 
![image](https://user-images.githubusercontent.com/40954645/78681170-614e6800-78ba-11ea-9ec4-4a1c0e7055e7.png)

However, I believe MIT App Inventor and Thunkable Classic's Webviewer managed the complexity of URL history and had a back method call that navigated the Webviewer to the previous page.

**Comment by mohammadaarizimam** [comment]
So, may you please give me the full code to do so...

**Comment by MrMazzone** [comment]
@mohammadaarizimam 
Something like this would have worked, **however** I did not realize that the URL property does not change when the WebViewer displays a new URL.
![image](https://user-images.githubusercontent.com/40954645/78778530-6ae2d900-7969-11ea-84cb-a91d64050eec.png)
https://x.thunkable.com/copy/903c356fba65bd9bce38b85b8f374999

I am going to put in a separate request to get the WebViewer's current page's URL.  Sad you cannot do that now.

**Comment by jane-d-alt** [comment]
The Web Viewer now has a [go back](https://docs.thunkable.com/web-viewer#go-back-forward) block. We'll close this request now; apologies for not following up when this block was originally added.
