### ISSUE TITLE
Data Viewer List

### ISSUE THREAD

**Issue by Powergithub2019** [thunkable/thunkable-issues#469]
1) i set up a new data source and now how is it possible to remove it? (in case I made a wrong)
2) once I set up a new data source, I made some table structure on airtable. when I click on "Click here to view the data" ... the structure showed the previous structure.
3) in the data binding it should be better that when a field is missing the information missing on the screen. instead if I fill just an image url it takes it for both fields.

![image](https://user-images.githubusercontent.com/50276971/79124069-d67adb00-7d9b-11ea-8532-3bbee23d0ef7.png)

**Comment by easaw** [comment]
You can remove the sources in the top left panel, I think above the image upload box? There's definitely a way to remove them from the current project.

Having said that I've noticed the live view is very **slowwwwwww** to update. 8/10 times I have to relaunch the live app to even see an update, especially with images (Android 9, latest app version)
