### ISSUE TITLE
To add a new component application - Application (App)

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#47]
This component can be used to retrieve system parameters, get and set app properties. A sample list of data field: 

OS: ios or android 
OS version
Type: phone or tablet
Screen width
Screen height
Screen density
Screen Orientation
Screen rotation angle
Country
Country code
Status bar height
Keyboard height

The data can be returned in separate blocks or in the form of JSON data with a block of getSystemInfo.

**Comment by kenbushey** [comment]
Screen height, width and orientation seems especially important to create apps with a "responsive" design with font sizes that change based on the size of the device.

**Comment by jane-d-alt** [comment]
You can accomplish most of these now with the device blocks (https://docs.thunkable.com/device):

✓ OS: ios or android
OS version
Type: phone or tablet (can be deduced from screen width/height)
✓ Screen width
✓ Screen height
Screen density
✓ Screen Orientation
Screen rotation angle - should be possible to get this with sensors
✓ Country - can be obtained with location sensor and reverse geocoding: https://community.thunkable.com/t/reverse-geocoding-app-get-location-from-latitude-longitude/82343?u=jane
✓ Country code - see above
Status bar height
Keyboard height

I'm going to close this issue. If you would like to request the outstanding features, please make individual feature requests.

**Comment by kenbushey** [comment]
Thank you! I employed these blocks after they were released. Worked beautifully for my application. Thanks again!

 

Ken
