### ISSUE TITLE
Can't scroll to bottom of long blocks screen because conversation/help icon is in the way

### ISSUE THREAD

**Issue by DLM-thunkable** [thunkable/thunkable-issues#472]
### Platform
X

### Issue/Request Origin
The start-a-conversation icon in the lower left of screen blocks the ability to pull the scroll button all the way to the bottm, which makes it very difficult to see the bottom blocks in a long screen.
![Annotation 2020-04-16 215427](https://user-images.githubusercontent.com/59783690/79533876-e0b40800-802d-11ea-9ae2-452dbcc3b973.jpg)

### Steps to Reproduce
1. Make a big app with lots of blocks.
2. The right scroll button on the Blocks screen gets very small as a result.
3. Try to pull the scroll button to the bottom, big blue-and-white smiley icon is in the way. It's hard to drag the scroll button past the icon without opening up the Start-a-Conversation screen.

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.
Can do this with a private app if needed

### Expected Behavior
That you should be able to scroll to the bottom of the Blocks screen

### Actual Behavior
The scrolling is blocked by the icon

### Suggested Solution
Move the icon to the left a bit
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by rem708** [comment]
If issue #331 was to be addressed this would no longer be an issue as you could just scroll with the mouse rather than have to resort to using dragging of side bars.

**Comment by DLM-thunkable** [comment]
I totally agree. I see that your issue is now 3 months old and no movement there either.

**Comment by jane-d-alt** [comment]
Hi there,

The Intercom icon no longer covers the scroll bar. Apologies for not following up when this behavior was originally resolved. Thanks for reporting!

**Comment by DLM-thunkable** [comment]
Thanks!
