### ISSUE TITLE
Save copy error

### ISSUE THREAD

**Issue by jordyverheye** [thunkable/thunkable-issues#477]
Hi there

I'm creating an app for an exam in school, i've been working on it regularly and as of today i can create a copy of it. My teacher requires me to hand it in this week. Whenever i try to copy the app i get the following error: 

Save copy error
No such object: thunkable-x-production/users/5e56753f0a40e49e131a39b6/projects/5e7b5436392faf8639ecf079/assets/5e7b9d72df2235c8e58379d1

I'm unable to create a link to my app. Do you have any idea what the issue might be?

Greeting
Jordy

**Comment by josmas** [comment]
Hi Jordy, it seems like you might have deleted an asset (like an uploaded picture or similar) and still use it on the app (in blocks, maybe?). Make sure there are no block issues in any of your screens.

**Comment by josmas** [comment]
Seems like an issue for more people https://github.com/thunkable/thunkable-issues/issues/475
We are going to look into it.

**Comment by jordyverheye** [comment]
I do remember making a copy about 3 weeks ago. Today i finished up the project and deleted the original copy since i didnt need that anymore. Maybe that could have caused this issue

**Comment by josmas** [comment]
Hi @jordyverheye we've reviewed the assets for the project you linked to, could you please try to copy again?

**Comment by jordyverheye** [comment]
No sorry, i still get the same results

**Comment by josmas** [comment]
@jordyverheye is your project private?

**Comment by jordyverheye** [comment]
The project is public

**Comment by josmas** [comment]
@jordyverheye thanks for confirming. Can you confirm also that the error you linked above is correct? I cannot find your project by that ID. Any chance that is the ID of the project you deleted?

**Comment by jordyverheye** [comment]
https://gyazo.com/af819b76b717457ee710a38ade6bec13 
 you can see in the gif that the error occurs when i click copy.

**Comment by josmas** [comment]
Thanks @jordyverheye any chance you can delete and asset called `af.jpg`? you can upload it again if you need it, but it seems to be corrupt.

**Comment by jordyverheye** [comment]
It seems i'm not able to delete that asset, when i click delete nothing happens

**Comment by josmas** [comment]
Hey @jordyverheye we have deleted the asset for you and we can now copy. Can you please upload again?

**Comment by jordyverheye** [comment]
yes, i can copy and share again, thank you

**Comment by josmas** [comment]
that's great, thanks for confirming. Closing this now. Thanks!
