### ISSUE TITLE
(For Thunkable X) Add offline communication between the native part and WebViewer

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#48]
It would be nice to be able to directly send data from blocks to WebViewer and get the data from WebViewer into blocks (how this feature is implemented in the Classic).

Now for data exchange we need to be online and use web services

**Comment by jane-d-alt** [comment]
It is now possible to post and receive messages between the device and the web viewer https://docs.thunkable.com/web-viewer#post-message-receive-message
We'll close this issue now; apologies for not following up when this feature was originally implemented
