### ISSUE TITLE
problem with images and screen clone

### ISSUE THREAD

**Issue by app-vrb** [thunkable/thunkable-issues#480]
Hello, I found a serious problem with images when I import screens.
The images from the imported screen are listed on the Files, but you can't use and you can't even delete

The more info, the faster we will be able to address it!

### Platform
X

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
I found in my apps

### Steps to Reproduce
1.Save from one project a screen with images
2. Create a new project
3. Import the saved screen
4. you will find the images in the files, but if try to use doesn't work and if you try to remove (delete) you are not able 

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.
https://x.thunkable.com/projects/5ea1a45bcd115f3bdc6815ba/701a9532-3266-4853-a987-057f82842b0a/designer

(I try to generate a link to share but doesn't work.... I hope the link I copied it will be useful)

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jane-d-alt** [comment]
Hi there,

I just tried to replicate this behavior but it appears to be resolved. When you create a screen, add an image, save the screen to My Screens and import this saved screen back into your project, a second image file is not added to the project, so the issues you describe do not arise. Thanks for reporting!
