### ISSUE TITLE
Clone nested components

### ISSUE THREAD

**Issue by app-vrb** [thunkable/thunkable-issues#485]
### Platform
 ✕, ✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
When you clone for example a column with rows or columns inside, the characteristic of original components, the like width or height or color are not cloned

### Steps to Reproduce
1.create column "master" with columns and rows inside and other components
2. clone "master"
3. Clone a column/row inside the 'master'

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

### Expected Behavior
a copy of the "master" with all the same characteristic suppose to be be created

### Actual Behavior
What actually happens?
the object are created but not with the same option of the master
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jaredgib** [comment]
I don’t experience this. Can you provide a sample link.
