### ISSUE TITLE
Responsive Web App -- Download Option / iFrame Support / Custom Domain

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#486]
**Is your feature request related to a problem? Please describe.**
I really like the Responsive Web App option recently added.  Great work!  And makes sense with how everything is working behind the curtain.  Currently, the RWA option generates a web URL for people to access the web app.  Would be cool to be able to host the app at our own domains. 

**Describe the solution you'd like**
Add a Responsive Web App option for "Download", which would download a zip of the site. The project can be unzipped and hosted outside Thunkable domain.

**Describe alternatives you've considered**
Thunkable could provide an interface to setup custom domain redirects or something.  Seems more complicated though.  I would assume it is easier to have users download project and provide information on setting up project to be hosted at your domain.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
Not a priority feature, but a very useful add for anyone developing with Thunkable.  Could see this being a PRO only feature.

**Comment by josmas** [comment]
@MrMazzone thanks for the request. it is a good one, but we would need to manage people's expectations of what they would be getting.

If we provide this option, most people would expect to get some kind of web project that they can open in a text editor to make changes and so forth, but in reality, they would be getting one file with html + css + Javascript all bundled up and totally minimised, making no sense whatsoever, but still rendering properly. The reason being that we generate this code automatically, it is not written for people but for machines, so it's a tricky one!

**Comment by MrMazzone** [comment]
I would be OK with an un-editable, oddly formatted file.  The expectation should be this is for hosting on your owned domain, not for jump starting a web app project.  Thunkable should be used for all changes to the web app, download is only for adding web app to your domain.

Thank you for all the hard work Thunkable team, and for considering this idea in the future.

**Comment by amblemind** [comment]
I think being able to add a custom domain would be better. And is more realistic. 

That way Thunkable handles all the hosting for you and if you need to make updates, you just update Thunkable and republish.

**Comment by eoinparkinson** [comment]
+1 to Darren here. RWA’s have been an amazing addition to Thunkable X, though having thunk.app in the url takes away from the brand. Something like setting up domains would be fantastic but if having the possibility to iframe the app would be a great start. Maybe I’ve come across too optimistic here and think iframe is much simpler than attaching a domain. Some sort of personalisation over the url would be great though.

**Comment by marioishikawa** [comment]
+1 here also. My motivation would be to choose my own host, SLA, CDN and so on, not to change the code.

**Comment by swordzorro** [comment]
+1 for custom domain and can be embed to another website using iframe, that would be great.

**Comment by chinenyeegbe** [comment]
Being able to add it using an iframe would be of tremendous help to me right now 😔  . I'd also like to be able to add a custom domain

**Comment by stanis14** [comment]
For me being able to customize URL ; integrate to Iframe or download the web app to host it would all be great options for me !

**Comment by MrMazzone** [comment]
I agree.  @josmas Has the team discussed this at all lately?  Would be super useful.

**Comment by andykiang** [comment]
Thanks for all the discussion and suggestions. We can definitely understand the benefit to all flexibility in all this. We're looking into different options and are allowing the web app to be iframed seems to allow for simplicity in implementation as well as control on your end.

As for timing though, I unfortunately don't have a clear timetable yet. We are currently focused on cleaning up a lot of things from overall performance and stability to clearing out bugs to bringing any remaining missing components to our new UI.

I'll make another note of the continuing desire for this functionality in the backlog.

**Comment by caminostudio** [comment]
Please, allow Thunkable web apps in an iframe. In the App Settings, could be created an option to allow to render the app in an iframe (X-Frame-Options). Thus, reducing the security of the app would be a decision of the developer. Please, prioritize this feature. @josmas andykiang

**Comment by weihuali0509** [comment]
In today’s release, we allow web app to be embedded in an frame. There are two limitations now (1) all the web apps (regardless as mobile web apps or responsive web app) will have the frame when rendering in an iframe. (2) It includes the power by Thunkable footer. We hope this is the baby step to improve the web app publishing and we will have more updates down in the road.

**Comment by MrMazzone** [comment]
> In today’s release, we allow web app to be embedded in an frame. There are two limitations now (1) all the web apps (regardless as mobile web apps or responsive web apps) will have the frame when rendering in an iframe. (2) It includes the power by Thunkable footer. We hope this is the baby step to improve the web app publishing and we will have more updates down in the road.

This is a step forward, as people could iFrame their prototypes for their personal websites.  However, I believe most people want to be able to use this to host their Thunkable RWAs on their own website.  The framed mobile view just doesn't work for that.

For an example because I was not sure what @weihuali0509 was saying until I tried myself. Here is my RWA with thunkable.site URL (on left) and site in iFrame (on right).  iFrame forces it into that mobile view frame seen on Thunkable.
![image](https://user-images.githubusercontent.com/40954645/117377714-e632f900-aea1-11eb-837f-6f5922dfce9e.png)

**Comment by weihuali0509** [comment]
@MrMazzone This is a baby step and there will be updates down the road. At least for now, people can iframe their apps in their blogs :)

**Comment by caminostudio** [comment]
@weihuali0509, @josmas, Thank you for that step. Unfortunately it does not solve my problem (iframe support / user domain). I hope that soon we can overcome technical and commercial barriers to take more steps until we have full iframe support for responsive web apps. I love Thunkable. I had been waiting a long time for a platform like Thunkable (a Blockly-based platform for creating commercial apps). But I don't want to put web apps on my blog. I'm trying to create a new business based on Thunkable, and make everyone profit from it. In the future, Thunkable web apps could have a business model similar to Firebase (charge according to the volume of access). Me and other developers are your business partners building commercial apps (not only educational apps). Thunkable is wonderful and can cause a revolution in software development. Count on me to achieve this mission! I will keep waiting for the next steps! Thanks! Thanks!

**Comment by artemdzyuba** [comment]
Custom domain is a very important feature. Some solutions like Bildr have this enhancement.
Is it possible to make a script for Cloudfrone workers to set a custom domain? There's a very nice solution for Notion pages doing that: https://fruitionsite.com/. Maybe it's possible with Thunkable web apps too.

**Comment by cathysarisky** [comment]
I'm looking forward to being able to embed a responsive web app.  Soon, I hope?

**Comment by playanything** [comment]
Please please please it would be so good.

**Comment by colski** [comment]
another +1. This would be super helpful & definitely could attract an extra fee based on usage / volume

**Comment by MrMazzone** [comment]
An update. I noticed that my web app can now be in an iframe.  The example I used above is actually on my site. https://joemazzone.net/ppt-to-presentation.html

Thunkable team.  I am going to close the issue now. You may want to document in your docs.
