### ISSUE TITLE
Functions which need a pause 

### ISSUE THREAD

**Issue by Bellacopia** [thunkable/thunkable-issues#488]
Platform: Thunkable X with Firebase Realtime Database

Hi everyone,
I'm trying to develop an Italian app which allows "shopkeepers" to register their shops and "users" to search for them by indicating the type of shop and the city in which they are located. Each registered "shopkeeper" can have only one store in the database.

A few days ago I finished a first prototype of my app: everything works quite well except for the final phase of the insertion / modification / cancellation of a new shop in the database. 

This phase involves updating four lists:
1) The list of all UserIDs (and their count, to find out how many stores are in the DB);
2) The list of UserIDs that refer to the same type as the new store;
3) The list of UserIDs that refer to the same type of the new shop and that are located in the same city;
4) (only in the event that the shopkeeper has changed the type of the shop) The list of UserIDs that refer to the old type.

Well, the updating of these 4 lists is performed respectively by these 4 functions:
1_Crea_TagLIST (attached below);
2_Crea_Lista_Negozio (Shops list) (attached below);
3_Crea_Lista_NEG_in_CITTà (Shops in town list);
4_Crea_Lista_NEG_PREC (Previous type of shops list).

And here's the problem: each of these functions works only if I insert a pause of at least 1/4 of a second. The problem would not be serious if, in the last three functions, this pause was not within a loop, which in fact multiplies its duration by the number of stores on the DB, thus creating embarrassing delays.

My app is in Italian but I have prepared an English demo version to allow you to check it (if you might!). If someone had the opportunity to help me I could share my app with him. Thanks in advance.

![Screenshot (283)](https://user-images.githubusercontent.com/63849566/80390299-88da9400-88ac-11ea-8987-befb513a768c.png)

![Screenshot (282)](https://user-images.githubusercontent.com/63849566/80390328-91cb6580-88ac-11ea-9f9d-e460a59561bf.png)

**Comment by josmas** [comment]
Hi @Bellacopia please ask programming questions in the [Thunkable community forum](https://community.thunkable.com/), you'll get a much faster reply there. Thanks!
