### ISSUE TITLE
Screens orientation

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#490]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Android Companion

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. have at least 1 button and many blocks, the more the blocks you have the more affects and also have a stack navigator
2. turn your phone and let them changes his screen orientation and immediately turn it again to his original position
3. try to press any button it won't let you, the buttons stop working

### Project Link
https://x.thunkable.com/copy/a1998448349e376de9e5088c6aa5743c
try it on the second screen (screens where there are blocks)

### Expected Behavior
What did you expect to happen?

### Actual Behavior
buttons stop working
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
As reported [here](https://github.com/thunkable/thunkable-issues/issues/467), we do not support orientation on Android at the moment.

Will close https://github.com/thunkable/thunkable-issues/issues/467 and keep this one open cause it has a project copy to reproduce. Thanks for the report!

**Comment by jane-d-alt** [comment]
This behavior has been resolved. We'll close this issue now; apologies for not following up when this behavior was originally resolved.
