### ISSUE TITLE
Typing detection - Text Imput - Request

### ISSUE THREAD

**Issue by jonathanvalgar** [thunkable/thunkable-issues#496]
Good day Thunkable staff,

Thunkable X, by itshelf doesn´t have a method to detect if an user is typing or not. Nowadays it can be used with timers, so they will detect every x seconds if the text has changed. However when you combine with other thing, such as with maps. The map will be restarted to its original position every x seconds (when the timer fires).

For that reason it would be great to have that option, furthermore, our codes will be reduced considerably. 

I also use this chance to kwnow if the known maps bugs will be fixed soon. https://github.com/thunkable/thunkable-issues/issues/278

Thanks and regards.

**Comment by jane-d-alt** [comment]
This can now be accomplished with the Text Input 'when Changes' block: https://docs.thunkable.com/text-input#changes
We'll close this issue now; apologies for not following up when this block was originally added to the component.
