### ISSUE TITLE
Multi-line on standard ListView not working

### ISSUE THREAD

**Issue by eoinparkinson** [thunkable/thunkable-issues#498]
### Platform
Thunkable X

### Issue/Request Origin
This feature was added after many requests, but it doesn't seem to work from my testing. Checked in with the community and was told this is an error.

### Steps to Reproduce
1. Add in a standard list viewer to your project.

2. Blocks look as follows:
![image](https://user-images.githubusercontent.com/48634511/80994619-d454eb00-8e34-11ea-8989-6ff073371072.png)

3. The list displays this:
![image](https://user-images.githubusercontent.com/48634511/80994712-f77f9a80-8e34-11ea-92c3-2d869104c31d.png)

### Project Link
Both links are the same project
https://x.thunkable.com/copy/cd0e020a48d897ce92b6abaa175235eb
https://x.thunkable.com/projects/5eb04b67fa4a0cd02f60808b/4b2a14bb-91ac-4423-a532-a254b6700200/designer

### Expected Behavior
Expected a new line, same as \n would create.

### Actual Behavior
No new line is created, but instead it cuts off all text after the new line block. \n also doesn't create a new line, but instead shows the text "\n".
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by domhnallohanlon** [comment]
Hey @eoinparkinson  - so this came out for Android this week and should hopefully be available for iOS soon. 
![Screenshot_20210205-143848](https://user-images.githubusercontent.com/3117345/107049881-8786b200-67c2-11eb-8841-d800f84de1de.jpg)

**Comment by eoinparkinson** [comment]
Thanks for the update @domhnallohanlon, much appreciated.
