### ISSUE TITLE
✕ Webviewer - No Touch/Scroll on Android

### ISSUE THREAD

**Issue by ytknows** [thunkable/thunkable-issues#50]
### Platform
Thunkable ✕ Android companion

### Issue/Request Origin
Experiencing it personally; have seen others complain but nothing on GitHub issues (unless I missed it due to bad title!)

### Steps to Reproduce
1. Place webviewer component
2. Link to any URL 
3. Attempt to touch or scroll the webviewer

### Expected Behavior
Items should behave normally, scrolling on touch, etc.

### Actual Behavior
The webviewer scrolls a small amount and then completely freezes. Application continues to function but the webviewer will not respond to touch inputs.

**Comment by MrSco** [comment]
Their own New Market Goods example app demonstrates this issue on any android device... https://goo.gl/Df56zz

**Comment by mark-friedman** [comment]
We have a fix in place and it is under review.  It should get into the next release.

**Comment by MrSco** [comment]
thats great news! I was told by Domhnall in the thunkable chat that it was fixed, but it seems the New Market Goods example app is still unresponsive on android when trying to scroll the webview... any idea when that fix will be released?

**Comment by mark-friedman** [comment]
@MrSco, The next release should be within the next week or so.

**Comment by mark-friedman** [comment]
The fix has been released.

**Comment by mark-friedman** [comment]
@MrSco, are you sure that you are running the latest Thunkable Live app (version 44) on your device?  I just tried the New Market Goods example and it seems to be scrolling just fine.  If you verify that you are running the latest Thunkable Live app on your device and it is still unresponsive, please let us know what device you are using and what Android version it is running.

Thanks in advance.

-Mark

**Comment by MrSco** [comment]
Yep that was the issue. Updated the live app and all is good. Sorry for the false alarm. 

-Rocco

**Comment by mark-friedman** [comment]
@MrSco, No problem.
