### ISSUE TITLE
Cannot update username

### ISSUE THREAD

**Issue by pezzin** [thunkable/thunkable-issues#503]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Web

### Issue/Request Origin
Settings page

### Steps to Reproduce
1. visit https://x.thunkable.com/account/settings
2. click to update username
3. save (by clicking the update button)
You will get an error:
You are not permitted to view the requested resource.

### Expected Behavior
What did you expect to happen?
The new username should be saved.

### Actual Behavior
What actually happens?
Error message.

```
  STACK TRACE AND/OR SCREENSHOTS
```
![error message](https://user-images.githubusercontent.com/45755/81267206-5e27d280-9046-11ea-839d-c2e8c7b19d19.PNG)

**Comment by josmas** [comment]
Hi @pezzin thanks for your report. We will have a look.

**Comment by TingC** [comment]
Hi @pezzin, this should be fixed, could you try again and let us know if it works for you?
