### ISSUE TITLE
Add Delete function to Data Sources block. 

### ISSUE THREAD

**Issue by domhnallohanlon** [thunkable/thunkable-issues#504]
From the [Community](https://community.thunkable.com/t/beta-testing-the-data-viewer/471535/270?u=domhnallohanlon):

> Delete function is required in Data Viewer.
> The delete function is an important function, so please put it in as soon as possible.

**Comment by jonathanvalgar** [comment]
It would be also great to have a function (a block) that will update the Data Viewer.

**Comment by domhnallohanlon** [comment]
> It would be also great to have a function (a block) that will update the Data Viewer.

@jonathanvalgar if you're making a new feature request would you mind opening a separate issue for this?

This specific ticket relates to adding the ability to delete data.

Thanks

**Comment by jaredgib** [comment]
I second this. Currently, we are stuck creating and overwriting old rows. this means anytime we want to update the rows, there needs to be an equal number of new data or old data may show as it was not overwritten. this works for some ideas but not others. this also requires the rowID to be recorded on the first write and then referenced later. 

this is a basic part of CRUD services. Looking forward to seeing this added into the functionality at some point!

**Comment by josmas** [comment]
Delete block already exits. Thanks!
