### ISSUE TITLE
Data Viewer: "right swipe" does not work in "Data Viewer List"

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#505]
When using the new Data View I found, that the component "Data_Viewer_list" knows three events: "Item click", "Left swipe" and "Right swipe". The "Right swipe" dows not work, but the first two, so I think it should be no big thing to repair the "right swipe" - event?

**Comment by josmas** [comment]
hi @kezb765 thanks for your report. We have a fix for this and will be out in the next release early next week. Thanks!
