### ISSUE TITLE
Keep keyboard up when clicking button

### ISSUE THREAD

**Issue by sodart** [thunkable/thunkable-issues#506]
**Is your feature request related to a problem? Please describe.**
When keyboard is up you have to click the button once which closes the keyboard and then click it again so the button can do what it is supposed to do.

**Describe the solution you'd like**
Clicking on a button does what the button is set to do, keeping the keyboard up.

**Which platform are you asking for?**
Thunkable ✕

**Comment by Bellacopia** [comment]
I'm experiencing the same problem. MIT App Inventor 2 has a specific Screen block ("Screen.HideKeybord") which fixes it. 
Thunkable has a "dismiss keyboard" block (in the device drawer) but it doesn't work.

**Comment by domhnallohanlon** [comment]
Hi @sodart and @Bellacopia I wasn't aware that this wasn't working - apologies for the inconvenience. 

Do you know if this is happening on iOS, Android or both?

**Comment by jane-d-alt** [comment]
Hi all, it looks like this behavior has been resolved. In [this demo app](https://x.thunkable.com/projectPage/609e16de4a9c670012c9f4db/), I have multiple Text Inputs and 2 buttons. 

One Button will change color when clicked. This works first time, even when the keyboard is up.
The other button will dismiss the keyboard and change color. This also works first try, even when the keyboard is up.

Apologies for not following up when this behavior was originally resolved. Thanks for reporting!
