### ISSUE TITLE
Add Update function to Data Viewer block

### ISSUE THREAD

**Issue by jonathanvalgar** [thunkable/thunkable-issues#507]
**Is your feature request related to a problem? Please describe.**
The new data viewer can be updated by the user but not using the code (blocks). So, the it cannot be updated dinamically.

**Describe the solution you'd like**
Update function block. That allows the designer of the app updating the list every x seconds or when he/she wants.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
That function is already implemented for the user of the app, so he can update the tab swipping the screen, for that reason, it could be easy to implement as a block.

Thanks.

**Comment by josmas** [comment]
update is available now. Thanks!
