### ISSUE TITLE
Crear columna desde los bloques en el nuevo visor de datos. 

### ISSUE THREAD

**Issue by Francabral11** [thunkable/thunkable-issues#508]
En el visor de lista clásicos es posible crear una columna bajo una etiqueta,  en mi caso suelo hacerlo por ejemplo bajo la fecha actual,  asi cuando selecciono una fecha especifica en el selector de fecha puedo visualizar los items agregados ese día específico,  esto no puede hacerse en el nuevo visor de lista,   estaría genial que agreguen esta función,  porque así es imposible filtrar los datos...

**Comment by josmas** [comment]
This should be possible now. Closing. Thanks!
