### ISSUE TITLE
Project "Share Link" directs to "Project Detail Page" 

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#509]
**Is your feature request related to a problem? Please describe.**
Currently, the "Project Share Link" generated when a user clicks the share icon in a project (seen below) generates a link that copies the project to another person's account.
![image](https://user-images.githubusercontent.com/40954645/81479102-5192ae00-91ef-11ea-835b-d1d768f4439b.png)

What if you want to share the project without forcing the person to copy the project into their account. (I know the project's URL can be used to share a read only view, but most people do not).

**Describe the solution you'd like**
Instead have the share button generate a URL to the Project's "Project Detail Page"  where the person opening the share link can choose to test the project in the web app, test it on their companion device, or edit the project and create a copy on their account.

To me, this seems to be a better share option.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
In Thunkable's new Drag and Drop UI, you can access the project details page form inside the project UI. You can then share this URL with others.

We'll close this issue now; we hope that you enjoy checking out this and other features available in the Drag and Drop UI!
