### ISSUE TITLE
Add a "View Project" option to the "Project Detail Page"

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#510]
**Is your feature request related to a problem? Please describe.**
Currently, the "Project Detail Page" allows a user to test the app in web preview, test it on the companion device, and create a copy of the project on their account. 

What if a user wants to just look at the project without creating a copy on their account?

**Describe the solution you'd like**
Add an additional option to the "Project Detail Page" that allows a person to view the design and blocks of a project in the read-only format (without making a copy of the project).

Currently, if a user tries to open another user's project URL it shows a read-only view of the project.  Use that URL as what opens for the "View Project" option on the "Project Detail Page".

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by andykiang** [comment]
Does this `See Inside` button do what you're looking for?

<img width="1108" alt="Screen Shot 2020-05-11 at 3 38 12 PM" src="https://user-images.githubusercontent.com/36968048/81619110-ac6a0800-939d-11ea-8607-7c1575ab6a3d.png">

**Comment by MrMazzone** [comment]
Yes!  I thought that was there.  It wasn't showing for a project page I was looking at AND it doesn't show on your own project pages (which makes sense).

This feature already exists!  Thank you @andykiang !
