### ISSUE TITLE
Search box option on "My Projects" page 

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#511]
**Is your feature request related to a problem? Please describe.**
When you have a considerable number of projects, it is difficult to locate a project on the "My Projects" page.

**Describe the solution you'd like**
Have a search box at the top of the page where users can type in keywords/chars and show projects with names only containing those keywords/chars.

**Describe alternatives you've considered**
As an alternative, I do use `ctrl+f` to locate projects on the page, but I am sure a number of people do not think about this as a solution.

Sorting the order of projects in different ways (instead of just most recently opened) may be an alternative.  Sort by name (alphabetical), date created, date modified, etc.  These seems to be more complicated to implement and would be an additional request ticket. 

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by josmas** [comment]
thanks for the request @MrMazzone 
We are actually working on a re-design of my projects with basic filtering and more view options. We are planning some usability testing to figure our a few quirks, but it is definitely on the cards, hopefully in the next couple of weeks. We'll keep you posted.

**Comment by josmas** [comment]
We have a prototype for this and we are looking for a few people that have a large number of projects and can spare 30-40 minutes to run through a few usability tasks and answer some related questions. If interested do let us know!

**Comment by MrMazzone** [comment]
@josmas I am interested.

**Comment by josmas** [comment]
thanks a million @MrMazzone we'll be in touch shortly about it.

**Comment by MrMazzone** [comment]
Feature implemented!  Love the new "My Projects" page!  
https://community.thunkable.com/t/projects-page-redesign-list-view-search-and-filter/616561
