### ISSUE TITLE
PDF Reader trouble (#6313)

### ISSUE THREAD

**Issue by weihuali0509** [thunkable/thunkable-issues#513]
Platform: ✕ Android companion and ✕ iOS companion
Hi, today I tried to use the Pdf Reader component for the first time and it seems to work only in "Live test":

with ✕ Android companion appears this message: "Alert - Sorry, an error occurred"

while with ✕ iOS companion appears a white page.

cc @Bellacopia

**Comment by eoinparkinson** [comment]
I’ve seen this white screen appear a lot when the apps blocks don’t work. It happens mostly when you are testing the code and if the code breaks then it gives a white screen. 

I believe it broke when I accidentally carried the error block from firebase over to a function. It was supposed to be a variable and once this was changed the white screen didn’t appear anymore.

**Comment by weihuali0509** [comment]
We finished the fix and it will be out to x.thunkable.com soon.

**Comment by Bellacopia** [comment]
Now everything seems to be working perfectly. I really appreciated the option to link the PDF Reader to a remote URL. Grazie mille.
