### ISSUE TITLE
White screen when viewing data sources

### ISSUE THREAD

**Issue by jaredgib** [thunkable/thunkable-issues#516]
### Platform
Thunkable X

### Issue/Request Origin
Community

from user sr3

I still can’t use Google Sheets with the Data Viewer. I can get the desired sheet into the Data Source field, but from there, the binding fields tell me to select a data source. I try again and again, and I get the same results. I’ve deleted the data sources from the app in progress and put them back in with no different result. I can’t remove the data sources from the system because the data sources tab on my projects page gives me a blank browser screen. NEED HELP please!

after an update The My Data Sources tab on the Projects page still gives me a white screen. I get the same results in Chrome and Edge browsers.

### Steps to Reproduce
1. refresh and clear browser cache
2.  log out then log in
3. open my data sources

### Expected Behavior
see data sources, be able to bind to google sheet and produce data in the app with the data viewer

### Actual Behavior
white screens, 
```
  STACK TRACE AND/OR SCREENSHOTS
```

shortly after posting this, i saw a related post from steven on the forum. I will close this

**Comment by Rojroj101** [comment]
I am still having this same issue.  I cant connect google sheets source to my thunkable x. I just get a white screen... I don't know what to do !?
