### ISSUE TITLE
"Invalid Certificate" error message from Apple

### ISSUE THREAD

**Issue by Bellacopia** [thunkable/thunkable-issues#521]
Platform: Thunkable ✕

Hi,
today I started the "Publish to App Store" process and I managed to create the App Identifier.
But when I upload my CSR file I get an "Invalid Certificate" error message from Apple Developer website (see attached screenshot).
I await your instructions. Thanks

![AppleDevPrg](https://user-images.githubusercontent.com/63849566/82119465-11977200-977f-11ea-80fb-d72d34c3a588.png)

**Comment by weihuali0509** [comment]
I just checked this part and it was working fine for me. Can you try again? 

And please make sure you have selected *Apple Distribution* as the type.

**Comment by Bellacopia** [comment]
Problem solved, the cause was the browser (MS Edge). As soon as I tried with Google Chrome everything worked fine. Thank you.

Can you tell me something about issue #513 (PDF Reader trouble)?

**Comment by josmas** [comment]
the other issue is also closed, so closing this one now. Thanks @Bellacopia !

**Comment by josmas** [comment]
oh boy! I thought it was open... closing again! hahaha
