### ISSUE TITLE
multiline input

### ISSUE THREAD

**Issue by Raketten1963** [thunkable/thunkable-issues#524]
The input edit box does not support multi line input and we really need it

**Comment by MrMazzone** [comment]
Hi @Raketten1963 for the Text Input component, there is a "multiline" property in the advanced properties section.  That is what you are looking for, as well as some other properties that may be helpful to your multiline solution.
![image](https://user-images.githubusercontent.com/40954645/82152363-9e4d3900-982e-11ea-9749-31b989a685e4.png)

**Comment by Raketten1963** [comment]
Yes MrMazzone, and I have tried it, but every time I hit enter, the focus goes to next tab order, which makes the editing experience weird at best.

**Comment by MrMazzone** [comment]
OK, @Raketten1963.  After some testing, it seems that the Text Input component does support multiline text, but dismisses the keyboard/moves focus when enter/return key is clicked.

See example project:
https://x.thunkable.com/projects/5ec1af2273a853efa6c6513a/0d4c53e4-9044-4913-8744-409303940252/designer

Can you confirm this is what you are observing?

**Comment by jane-d-alt** [comment]
This is actually something we are working on at the moment. 
This should be taken care of within the week!

**Comment by josmas** [comment]
As @jane-d-alt mentioned, we are trying to make this a bit more intuitive as it is kinda messed up at the moment.

In the project @MrMazzone linked, if you add `number of lines` to anything over 1, you will see what you are expecting in the live preview. The designer text box will not change, but the live test and compiled app will show a multiline box.

'number of lines' is three properties above from 'multiline' in the advanced properties panel for the textbox, and it is a visual property in the sense that it will keep 3 lines visible, as long as the box has space for it in the screen. Note it does not hard limit the number of lines to 3, but shows 3 lines at a time.

**Comment by Raketten1963** [comment]
HI Jos,

thanks for your reply, I still see the same behaviour in my end.
Everytime I hit return, the focus moves on and the keyboard disappears...

RGds Henrik

**Comment by AlexITMan** [comment]
You can use Framework7. Sample on scrFramework7 in https://x.thunkable.com/projects/5d70f93f8a62b4079eedaff2/project/properties/designer/

**Comment by jane-d-alt** [comment]
Multiline input with a Text Input is now available when previewing apps on the web and when using apps on a device.
We'll close this issue now; apologies for not following up as soon as this feature was implemented.
