### ISSUE TITLE
Calling sleep changes the result

### ISSUE THREAD

**Issue by Raketten1963** [thunkable/thunkable-issues#527]
Thunkable/X

During onOpen call for my Screen I call functions with parameters. With the platform update 15/5 I realized that the value of these parameters depends on whether i put a leep on the code before calling function

![image](https://user-images.githubusercontent.com/62338118/82136621-fb85c200-980f-11ea-85c3-298c42400a58.png)

In above code I receive 50 in the function without the sleep/wait and 123 with the sleep.

This is quite unacceptable.
```

**Comment by jane-d-alt** [comment]
Hi there,

Apologies for not following up on this issue at the time. This behavior does appear to be resolved. We will close this issue now, but please do not hesitate to follow up with us if you observe this behavior again.
