### ISSUE TITLE
Webviewer Recieve message not working on webapps

### ISSUE THREAD

**Issue by ghost** [thunkable/thunkable-issues#528]
### Platform
published web apps
### Issue/Request Origin
my own issue

### Steps to Reproduce
send javascript message as is in the project linnk

### Project Link
https://x.thunkable.com/copy/66ae8ebc3051a15c32437a92baa89839

webapp link
https://thunk.app/web-build/index.html?webAppId=uTzj1SWVt

### Expected Behavior
when testing on the phone, i recieve a fixed date. the idea is to send a date. let javascript add days to it, then return that to the app. I dont want to create and repeat the function for each app so instead I am using this.

### Actual Behavior
on the web app, no dice. on the phone preview, this works perfectly. 

<img width="451" alt="Screen Shot 2020-05-17 at 11 08 16 PM" src="https://user-images.githubusercontent.com/58823942/82170739-544a6e80-9893-11ea-9764-fcf2f794de53.png">

![IMG_FEBE80B158E0-1](https://user-images.githubusercontent.com/58823942/82170787-75ab5a80-9893-11ea-8cfb-fead0d6570e2.jpeg)
<img width="790" alt="Screen Shot 2020-05-17 at 11 10 47 PM" src="https://user-images.githubusercontent.com/58823942/82170857-aab7ad00-9893-11ea-9973-f9cd62350ed8.png">

the code i am using also available [here](https://jaredgib.github.io/moment.html) 
```

<html>
	<head>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <script>
	  let ThunkableWebviewerExtension = {
		postMessage: function (message) {
		  if (window.ReactNativeWebView) {
			window.ReactNativeWebView.postMessage(message);
		  } else {
			window.parent.postMessage(message, '*');
		  }
		},
		receiveMessage: function(fxn) {
		  let callbackFunction = function(event) {
			if (typeof fxn === 'function') {
			  fxn(event.data)
			}
		  };
		  document.addEventListener('message', callbackFunction, false);
		  window.addEventListener('message', callbackFunction, false);
		}
	  }
	  </script>
	</head>
	<body id="idBody">
	</body>
	<script>
	  
	  ThunkableWebviewerExtension.receiveMessage(function(message) {
		  
		  if (message.indexOf('<script>')==-1){
		  
			  document.getElementById('idBody').innerHTML = message;	
			  
		  } else {
			  
			  let matches = message.match(/<script.*?>(.*?)<\/script>/);
			  eval(matches[1]);
		  }
	  });
	</script>
  </html>
```

**Comment by weihuali0509** [comment]
@JanhaviDahihande Can you take a look at this?

**Comment by AlexITMan** [comment]
@jaredgib check this way

https://x.thunkable.com/projects/5b5f50279fd789d8928fdf1e/project/properties/designer/

**Comment by jaredgib** [comment]
@AlexITMan looks like all you did was load the html into local assets?

**Comment by AlexITMan** [comment]
No. If I just loaded the html to the local assets, it would not have worked. And I made a function to load a local file until it loads normally. To do this, inside the html file, I just send the word "good"to the App. If this word is received in the App, it means that the script has been loaded successfully and you can then access it.

**Comment by JanhaviDahihande** [comment]
Closing the issue as the webviewer receive message works now as seen in the sample application
https://x.thunkable.com/projects/5f1f198807b2bae0d7bf6843/ec149e08-cf2d-4fe3-8ab6-e75cfab51b1c/designer

![image](https://user-images.githubusercontent.com/20217203/88600687-bf4abb00-d023-11ea-972d-ae3999382b6b.png)


Reopen in case the issue still persists.
