### ISSUE TITLE
Map component returns null coordinate values

### ISSUE THREAD

**Issue by ghost** [thunkable/thunkable-issues#532]
### Platform
iOS companion, android companion

### Issue/Request Origin
email

### Steps to Reproduce
1. on 1 screen place a map and label
2.  in the blcoks, create 1 variable. when click on map, save coordinate to variable
3. set label text as "get property nativeEvent of object variable"
4. click on the map

### Project Link
https://x.thunkable.com/copy/3842f11da3a6167a743fff06053dbfe9

### Expected Behavior
items from within the nativeEvent property should then be displayed or available for access

### Actual Behavior
the app crashes. the white screen of death!

![IMG_1755](https://user-images.githubusercontent.com/58823942/82482548-060cb980-9aa5-11ea-839b-8ab130654bd8.PNG)
![IMG_972C72237A41-1](https://user-images.githubusercontent.com/58823942/82482555-07d67d00-9aa5-11ea-8d92-34e09f60f213.jpeg)

**Comment by ggergely78** [comment]
Hello,

Same problem here. Such kind of events like press, long press, marker press on the map started to send back null values within the ‘nativeEvent’. When I try to read directly the ‘coordinate’ from the ‘nativeEvenet’ the apps are crashing.
It is crashing at the point when it tries to get the ‘coordinate’ from ‘nativeEvent’.
‘nativeEvent’ says ‘null’ when I text it to the label.

I created a simple app to demonstrate the issue:
https://x.thunkable.com/projects/5ec8eb5f36806d0ea1cc129f/ce0b201f-9145-4738-a4a7-bf46dea642db/blocks.

The old apps which were working in the past also crashing. So, the problem probably not in the blocks.

Android and IOS also tested, but same result.

**Comment by jonathanvalgar** [comment]
Good day,

Exactly as @jaredgib and @ggergely78 mentioned, the data received inside of "nativeEvent" are null values, so when i try to represent those coordinates in a map it crashes. I have to say that the app in which i tested it it was working perfectly till last week, but today it became impossible to make it work.

I also want to remind the devs, that there are some functionalities of maps component that there are not working and make impossible to develope propper apps using maps. I opened the post last year, i hope that those also could be fixed soon.

https://github.com/thunkable/thunkable-issues/issues/278

Regards.

**Comment by bymahoapp** [comment]
Hello;

This is a little bit urgent for me. Whole map component doesnt work. If it doesn't, whole app is nothing.

Wish you solve this quickly.

Best Regards.

**Comment by josmas** [comment]
Thanks for the report and for the nice and concise example. We'll look into it.

**Comment by kezb765** [comment]
Hello to the folks at Thunkable,

I also think this one is really urgent, because using Google Maps in an app is a valuable feature. I know no other way to detect a pressed marker (there is no block) than to analyze "nativeEvent". Is there any progress? Thanks...

**Comment by bymahoapp** [comment]
> Thanks for the report and for the nice and concise example. We'll look into it.

Is there any proggress? Or how can we contribute to solve this problem? It's a dishearting sitution. This makes me feel sitting in a black hole prison like Batman.

**Comment by josmas** [comment]
All, one question with regards to parsing nativeEvent, did you use to get any other information out of it or just `coordinates` and `position`? We want to provide blocks with direct access to those properties, but don't want to miss any other info that might be useful.

**Comment by ggergely78** [comment]
Hi @josmas,

I'm only using the coordinate --> nativeEvent --> coordinate --> latitude/longitude parsing like in the picture bellow:
(Or in case of Marker press: event --> nativeEvent --> coordinate --> latitude/longitude)
I don't use any other informations.
Thanks in advance!

![image](https://user-images.githubusercontent.com/65825280/84165913-87d47f00-aa74-11ea-8caf-821e9c6e5255.png)

**Comment by bymahoapp** [comment]
#335 #451

**Comment by kezb765** [comment]
Hi @josmas ,

you asked which values could be helpful when analyzing onMarkerPress. My short wishlist:
Essential:
- get latitude / longitude of the pressed marker
Great:
- get the index of the pressed marker in the total quantity of all markers. With the index I could get every other information out of my array of markers.

Unrelated: get the current value of map zoom.

**Comment by mehrsachal** [comment]
Many of my apps depend on this part, plz fix it ASAP its been 24 days already

**Comment by josmas** [comment]
All, we are waiting for an Apple review to deploy a first fix. Once this is out, the event returned will be `event.nativeEvent` directly, so you can access lat-long and posX-posY with one object operation each (instead of having to access nativeEvent first).

We also have two new blocks for onPress and onLongPress that directly return (lat, lng, posX, posY) but these are still being tested and have to be approved. I'll keep you posted on when the new Companion is out.

**Comment by jonathanvalgar** [comment]
Great @josmas 

If you have the chance it would be great also to fix the bug that restarts the map to it's original coordinates when an event occurs (pressinng a button, a timmer fires...). So it makes so difficult to work with the map.

Thanks!

**Comment by bymahoapp** [comment]
There is another important issue. While adding marker on map, we could add value for each marker.  This will increase the blocks number.

**Comment by gre4twh1te** [comment]
> event.nativeEvent

Hi, I tried this 

> All, we are waiting for an Apple review to deploy a first fix. Once this is out, the event returned will be `event.nativeEvent` directly, so you can access lat-long and posX-posY with one object operation each (instead of having to access nativeEvent first).
> 
> We also have two new blocks for onPress and onLongPress that directly return (lat, lng, posX, posY) but these are still being tested and have to be approved. I'll keep you posted on when the new Companion is out.

Hi,

I tried the following blocks but it will result in creating the marker somewhere totally off:
<img width="373" alt="Bildschirmfoto 2020-06-21 um 13 32 42" src="https://user-images.githubusercontent.com/37402054/85223471-cf87ce80-b3c3-11ea-80b0-64e82ca9f4c8.png">

![IMG_506977556CDD-1](https://user-images.githubusercontent.com/37402054/85223476-d6aedc80-b3c3-11ea-93dd-382f4c3f61a4.jpeg)

Best, Chris

**Comment by kezb765** [comment]
This position is well known as "Latitude=0, Longitude=0".

**Comment by josmas** [comment]
For now, you will still have to `unwrap` the object as:
<img width="475" alt="Screen Shot 2020-06-22 at 12 30 21 PM" src="https://user-images.githubusercontent.com/194925/85282742-2e148180-b484-11ea-9f93-dc3514e8f8aa.png">

Basically same as [before](https://github.com/thunkable/thunkable-issues/issues/532#issuecomment-641372071) but with one less nested object (nativeEvent is returned now directly).

This change is already live in last companion and works with blocks returning `coordinate` and `event`. We'll let you know when other changes are available.

**Comment by bymahoapp** [comment]
Any milestone?

**Comment by josmas** [comment]
The map should not reset anymore when using events, as long as the latest companion is used (or the app is downloaded). We are still working on upgrading the press blocks.

**Comment by kezb765** [comment]
@bymahoapp , I successfully used the onMarkerPress-event again and also the onMapPress.event. Still waiting for the onCallOutPress. I hope they build more information into the event, for example the title of the pressed marker. That way it should be much easier to analyse which marker has been pressed.

**Comment by bymahoapp** [comment]
> @bymahoapp , I successfully used the onMarkerPress-event again and also the onMapPress.event. Still waiting for the onCallOutPress. I hope they build more information into the event, for example the title of the pressed marker. That way it should be much easier to analyse which marker has been pressed.

nope. nothing is changed. still same.

**Comment by josmas** [comment]
@bymahoapp make sure you have the latest companion or you build the app. Basic events work now.

onCalloutPress is still not working, and before we can fix it, we need to do some fixes to markers. We do realise that the component is pretty broken and we apologise for it. We will keep on adding fixes with new releases.

**Comment by josmas** [comment]
We have released new onPress blocks as per image. Note that you can still use the, now deprecated, old versions of the blocks:
<img width="747" alt="Screen Shot 2020-07-09 at 10 41 56 PM" src="https://user-images.githubusercontent.com/194925/87093765-a1184900-c235-11ea-8901-8c483b72f93e.png">

**Comment by josmas** [comment]
I am going to close this issue as the main concern here has been fixed (alongside a few more). There are other open issues with feature requests for markers and so forth, so feel free to leave your comments in those threads. Thanks!
