### ISSUE TITLE
Error: After "Label set text" -> "Label get text" gives "undefined"

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#534]
Does not work on ThunkableX iOS or android. Tested on live view (actual app 189-1 / 18901). I think it is an error, if I made a mistake please tell me so.

Sample code:
![grafik](https://user-images.githubusercontent.com/7669660/82733299-30fc4500-9d13-11ea-8f58-8918bc438d4c.png)

Expected behaviour:
- Label1 should display two messages, separated by ".."
- Label2 should display the same text as Label1

Actual behaviour:
- Label1 displays only the second entry
- Label2 displays "undefined"

It looks like setting the text of a label changed to an asynchronous task?

BTW: please do not suggest to set the two messages with one statement. The code above is simplified and I have reasons to use two separated statements.

**Comment by MrMazzone** [comment]
I have observed this behavior also recently.  Some of the blocks are running asynchronously now.  I assume this is a byproduct of some of the speed improvement word the teams has been doing.

Thunkable Team, please take a look at this.

However, @kezb765 there is a workaround.  Add a `wait` block between each `Label set text` blocks.  You only need to wait for the smallest duration of time. I have been using 0.1 but I believe 0 even works.  It seems to force the code to preform sequentially. 
![image](https://user-images.githubusercontent.com/40954645/82736637-4ebcb080-9cf9-11ea-8743-28b546c8637e.png)

**Comment by kjbuttel** [comment]
Agreed. The wait block forces it to sequence. to avoid that, you can write a conditional IF surrounded by a forever block. Won't switch to the second one until the first one has been successfully rendered on screen.

**Comment by kezb765** [comment]
Hi @MrMazzone and @kjbuttel , thanks for the reply.

I think there should be a better solution to this, I hope that somebody from Thunkable looks into this weird behaviour. In my opinion this is similar to a cache mechanism (memory, harddrive):
- a program writes data to the disk
- instead of waiting for the write process to finish, the data is stored in a cache and the program can continue to work.
- the crucial part comes when another program reads data, before it was written to the disk: in this case the data must be fetched from the cache. The same should be the case with writing / reading text from a label (and maybe other components).

I have no insight into Thunkable's internal structures, this is a guess. I hope not to live with a "wait"-block before I can fetch text from a label...

**Comment by josmas** [comment]
This should be fixed now. Please re-open if that is not the case. Thanks!
