### ISSUE TITLE
In-App Purchase

### ISSUE THREAD

**Issue by kjbuttel** [thunkable/thunkable-issues#536]
**Is your feature request related to a problem? Please describe.**
All I can charge for my app on the app store is the single download purchase.

**Describe the solution you'd like**
In-app purchases such as a monthly subscription.

**Describe alternatives you've considered**
Considered outsourcing through REST API's, but I've heard a lot about Apple rejecting those apps due to the in-app purchase not being apple based.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by jane-d-alt** [comment]
We are working on an in-app purchases component. Since this request overlaps with #227 , we're going to close this issue. Thank you for making this request!
