### ISSUE TITLE
Data Viewer Grid/ List (beta) always leaves one behind.

### ISSUE THREAD

**Issue by easaw** [thunkable/thunkable-issues#539]
When I empty all rows, either via blocks or via the Design screen, there is still always one left 😕

I don't know if it's at position 0 (which I have still tried to remove), or there is some but, but I need the list to empty otherwise there are two of the first item.

_A note to all users, you must be part of the List Viewer Beta and a Pro user to view/ use this project - the APIs are example data from here: https://jsonplaceholder.typicode.com_

### Platform
X (Android Live App)

### Steps to Reproduce
1. populate local data source with WebAPI - button 1.
2. refresh list/ grid viewer
3. try to clear it using repeat and delete (see project) - button 2.
4. or try to clear it manually in the table editor (which shows as empty)

### Project Link
https://x.thunkable.com/copy/2d534d8253f3b157f8df1e4f5b54eec1

### Expected Behavior
List or Grid is emptied

### Actual Behavior
one item always remains 🤔

**Comment by easaw** [comment]
I hope there's a solution to this, but for now, I've found a temporary fix (it's active on screen 2 but not screen 1). 

I put **-1** in the count box. That seems to clear all data.

![clear_data_grid](https://user-images.githubusercontent.com/17411112/82744061-9845e380-9d6b-11ea-9e14-4f89e65ae923.png)

**Comment by josmas** [comment]
is this still an issue @easaw ? Thanks!

**Comment by jane-d-alt** [comment]
Hi there,

Since this behavior appears to be resolved, and there was no response to Jose's question, we are going to assume that this issue has been resolved on your end as well and close this issue.

Please reach out if you experience this issue in the future.

Thanks for reporting!
