### ISSUE TITLE
dynamically add components from blocks or  from functions

### ISSUE THREAD

**Issue by chinenyeegbe** [thunkable/thunkable-issues#54]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I have to create a component with the same settings multiple times especially when I have to do it 20+ times, it's exhausting and it takes way too much time

**Describe the solution you'd like**
Can the components be added to blocks such that we can dynamically create them and add their settings there and then simply use functions to manage duplication

**Describe alternatives you've considered**
Creating the layout on a website and then embedding it with a webview

**Which platform are you asking for?**
 Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by jane-d-alt** [comment]
This can now be done with the [any component blocks.](https://docs.thunkable.com/any-component-blocks)
