### ISSUE TITLE
White screen when choosing google sheets as data source

### ISSUE THREAD

**Issue by Rojroj101** [thunkable/thunkable-issues#543]
Platform
Thunkable X

Issue/Request Origin
Community

from user sr3

I still can’t use Google Sheets with the Data Viewer. I can get the desired sheet into the Data Source field, but from there, the binding fields tell me to select a data source. I try again and again, and I get the same results. I’ve deleted the data sources from the app in progress and put them back in with no different result. I can’t remove the data sources from the system because the data sources tab on my projects page gives me a blank browser screen. NEED HELP please!

after an update The My Data Sources tab on the Projects page still gives me a white screen. I get the same results in firefox, Chrome and Edge browsers.

Steps to Reproduce
refresh and clear browser cache
log out then log in
open my data sources
Project Link
Expected Behavior
see data sources, be able to bind to google sheet and produce data in the app with the data viewer

Actual Behavior
White screens. unable to  sync google sheets with thunkable x and using data viewer list or data viewer grid

**Comment by jonathanvalgar** [comment]
Hi,

Take a look

https://community.thunkable.com/t/clicking-on-the-data-sources-tab-causes-white-screen/565177/20

Regards.

**Comment by josmas** [comment]
closing for lack on activity; thanks!
