### ISSUE TITLE
Using Data Soigs can break the project

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#546]
1) Add multiple data sources-tables, AirTabel, and Google Table

2) Start deleting data sources

If you can't delete any data source, try switching to block mode and you will probably get a white list in the browser

https://x.thunkable.com/projects/5ed10733bdb0a60ccb6990dc/project/properties/designer/

**Comment by domhnallohanlon** [comment]
Hey @AlexITMan - apologies for the delay following up with this. 

Pretty sure this was fixed a while ago but just confirming this?

**Comment by jane-d-alt** [comment]
Hi there,

As there was no follow up here in response to Domhnall's comment, and this behavior appears to be resolved, we will close this issue for now. Thanks for reporting!
