### ISSUE TITLE
Download apk does not work

### ISSUE THREAD

**Issue by fastpipe** [thunkable/thunkable-issues#55]
Hi,
the download of an apk file for Android in Thunkable X does not work (or better: Only works very seldom)

**Comment by mark-friedman** [comment]
@fastpipe Could you please supply more details?  What, exactly, is the behavior that you are seeing when it doesn't work.  Are there any relevant screenshots that you can provide?

Thanks in advance.

**Comment by fastpipe** [comment]
see:

https://community.thunkable.com/t/download-assets/38110/14

**Comment by mark-friedman** [comment]
You can see the issue with this project: https://x.thunkable.com/projects/5b59e7fee0d050613da919a4/Web_Viewer1/designer.  Trying to copy or download it will fail.

**Comment by jane-d-alt** [comment]
This error message can now be resolved by contacting the creator success team.
