### ISSUE TITLE
iOS build number does not always increment

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#551]
Pretty self-explanatory:

![image](https://user-images.githubusercontent.com/7762893/83659530-5408dd80-a5cc-11ea-8724-7123462f0714.png)

I have encountered this issue quite a few times and while it is not a blocking point, it is an inconvenience as in many cases, new builds won't show as updates in Test Flight and the test user (if savvy enough) will need to go to "Previous Builds" and install it from there...

**Comment by jane-d-alt** [comment]
Hi there,

Are you still experiencing this behavior?
To me it looks like the visible number under Build is higher (202053834) in the newer build (looks like it was published a day ago) than the number under Build in the older (4 days old?) project, which is 2020431524. 

Is the filled in rectangle in this screenshot meant to be an outline that highlights some build numbers?

**Comment by AmigoDeluxe** [comment]
Hi Jane. Unless you did something on your side to fix it, it will most probably reoccur from time to time. But never mind, I am done with Thunkable so I am going ahead and closing this.
