### ISSUE TITLE
Data List Viewer loses images when style changes 

### ISSUE THREAD

**Issue by ifrew** [thunkable/thunkable-issues#553]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
Thunkable X, Android 9, Live view
 problem discovered testing the data list viewer

### Steps to Reproduce
1. Use the example Planet Express Data List Viewer from thunkable
2. Verify it run in live app and shows images in the list viewer
3. Change the style in directory screen from Image Title subtitile to Image title and rerun in live app
4. Images no longer shown in the list.
5/ Change style back to original and rerun. Images still not shown. 

### Project Link
https://x.thunkable.com/copy/5fb33657a0880fc40c1b0fc655049520

### Expected Behavior
Images are still shown when you change list style

### Actual Behavior
Images are lost

**Comment by josmas** [comment]
Thanks for your report. We've seen that behaviour in the live view but not on devices. We will have a look. Thanks!

**Comment by jane-d-alt** [comment]
HI ifrew,

This issue was resolved by Thunkable team members Jose and Steve shortly after reporting.

We'll close this issue now. Apologies for not following up when the fix was initially implemented!
