### ISSUE TITLE
Blocks not displaying after adding the audio recorder component

### ISSUE THREAD

**Issue by jonathanstringer** [thunkable/thunkable-issues#554]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
 ✕

### Issue/Request Origin
Community

### Steps to Reproduce

1. navigate to project called Random Test or bears
2. and click the blocks tab to edit blocks

(I figured out this issue is triggered by the new Audio Recorder component)
1. check blocks page of any project and it will work
2. add the Audio recorder component and link to googlesheet as datasource
3. Then the blocks page stops working.
4. Unfortunately even when you delete the Audio Recorder component the blocks page still does not display.
5. However when I make a copy which creates a read only copy the blocks start displaying again in the copy.
6. Please fix my 2 projects so I can start using them again. 

### Project Link
https://x.thunkable.com/projects/5b15825104c1f40001619d07/Screen1/blocks
or
https://x.thunkable.com/projects/5b3d19b691cd3d30516c4cbc/Screen1/blocks

### Expected Behavior
expect to see the blocks

### Actual Behavior
white screen
```

**Comment by josmas** [comment]
hi @jonathanstringer thanks for your report.
Are there any particular blocks you are using in either component? I am trying to reproduce with an audio recorder and a grid view with a Google Sheet and I cannot see any issues.

cc/ @StevenPurn

**Comment by Jonathan-Stringer** [comment]
Please see the gif file of the experience on a brand new project
![blank block page](https://user-images.githubusercontent.com/45999906/83952298-91a07d00-a7fd-11ea-8357-8b9bb5a1695e.gif)

**Comment by josmas** [comment]
Hi @Jonathan-Stringer there's somethine odd with your datasources. You mentioned adding a Google Sheet but the icon you click on is not a GSheet.

I can do the same steps with voice recorder and a google sheet without seeing any issues on blocks. Could you please have a look at your data sources dashboard? Click on thunkable logo and then choose the DS tab and check for any errors:

<img width="831" alt="Screen Shot 2020-06-08 at 12 04 16 PM" src="https://user-images.githubusercontent.com/194925/84023682-70b46500-a980-11ea-80b2-624b2782bd16.png">

**Comment by Jonathan-Stringer** [comment]
Perfect thanks you fixed it.
So this is what I saw. Once I deleted it  I could edit the blocks
[cid:image001.png@01D63D5C.A2F26B10]

For some reason the button to create a NEW sheet did not work. I had to go into google create the sheet and then select it and then it worked.
[cid:image002.png@01D63D5C.FBF06690]

Thanks for the support

**Comment by josmas** [comment]
Hi @Jonathan-Stringer I don't think your images uploaded properly, but in any case, I don't think we can create a new sheet for you, but a new connection (what we call a data source) to an existing sheet. So this may be a language issue, as in, not properly explained in our docs; I'll pass it along to our creator success team to try and revisit the language to avoid any more confusion. Thanks! Closing this now.
