### ISSUE TITLE
Time Input - title error

### ISSUE THREAD

**Issue by roroid** [thunkable/thunkable-issues#556]
### Platform
Thunkable X
iOS

### Issue/Request Origin
By building an app

### Steps to Reproduce
1.Add a time input to the screen
2.Go to live preview
3.When clicking a Time input you will get **Pick a date**.

### Project Link
None

### Expected Behavior
I was expecting here to write **Pick a time**. Or would be great if you could edit this title.

### Actual Behavior
![24851fe5957c701a15d6030c5ed50d158a01cb72](https://user-images.githubusercontent.com/1607400/84050989-2b5f5a00-a9b7-11ea-9a91-f8e804bbaf6d.jpeg)

**Comment by josmas** [comment]
This was fixed on Jan 19. Closing for now. Thanks!
