### ISSUE TITLE
Time input -PWA

### ISSUE THREAD

**Issue by roroid** [thunkable/thunkable-issues#557]
### Platform
Thunkable X-PWA

### Issue/Request Origin
By building an app

### Steps to Reproduce
1.Add a time input to the screen
2.Go to live preview, and select "Preview as a responsive web app"
3.When clicking a Time input you are not able to properly use it.

### Project Link
None

### Expected Behavior
Have the posibility to select the hour and minute, in a design similar to the app.
### Actual Behavior
<img width="999" alt="Captură de ecran din 2020-06-08 la 18 45 42" src="https://user-images.githubusercontent.com/1607400/84052728-9b6edf80-a9b9-11ea-9878-3bd5287a51ef.png">

**Comment by josmas** [comment]
thanks for the report @roroid We are looking into this and also the date picker. Thanks!

**Comment by jane-d-alt** [comment]
Time and Date Picker components now appear as expected on the web.

We'll close this issue now. Apologies for not following up when the fix was initially implemented!
