### ISSUE TITLE
Data_Viewer_List: too much space in displayed list on the right half

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#558]
In designer mode, I choose the 4th list layout for the data_list_viewer: 
![grafik](https://user-images.githubusercontent.com/7669660/84139897-ff90b280-aa50-11ea-8941-2d4110833f79.png)

When starting the app, the list contains too much space on the right side, so that the Title und Subtitle are unnecessarily shortened:
![grafik](https://user-images.githubusercontent.com/7669660/84140073-539b9700-aa51-11ea-8832-fec30a8412c5.png)

This happens in live preview (iOS, android) and also in the final app (tested on android). I think it is only a small formatting bug.

**Comment by josmas** [comment]
Thanks for the report @kezb765 We'll try and get a bit more space in before the names are truncated.

**Comment by jeff-net** [comment]
I, too, would like to see this issue addressed (widening/adding more text). At least twice as many characters would be great.

**Comment by kezb765** [comment]
This one is now over 3 months old. Could it be possible to optimize this layout thing?

**Comment by kezb765** [comment]
Seems like somebody has worked on it. Thanx! But now we have a gap between the title (above) and the subtitle (below). Or is it multilined now?

![grafik](https://user-images.githubusercontent.com/7669660/92388624-e367e480-f117-11ea-9d46-85c468bf0916.png)

**Comment by josmas** [comment]
This was fixed months ago. The gap does seem a bit large. No multiline intended.

**Comment by josmas** [comment]
This is how it looks like with 2 lines, but we need to go down in size for the font, so some people may complain:

<img width="471" alt="multiline" src="https://user-images.githubusercontent.com/194925/92390765-6e92ab80-f113-11ea-94be-14b51261968a.png">

**Comment by kezb765** [comment]
Oh cool, we have multiline text in the subtitle! Great, thanks! Does it wrap automatically?

**Comment by josmas** [comment]
@kezb765 note that that was a quick change on my part to see how it looks like, but it is not implemented.

I'll propose it as a change, but cannot guarantee it will be accepted.

**Comment by kezb765** [comment]
@josmas :  Ah, I tried it myself and didn't see multilines. I would support the request to have multilines in data viewer list.
