### ISSUE TITLE
Let users see app name in PWA links on FB and Twitter

### ISSUE THREAD

**Issue by ghost** [thunkable/thunkable-issues#561]
**Is your feature request related to a problem? Please describe.**
When I link to my published web apps on forums, the resulting url/image link is not super attractive  nor representative of my app. 

**Describe the solution you'd like**
The link should have the app name and the app icon. No mention of thunkable. 

**Describe alternatives you've considered**
Letting users know what I’m asking them to click on

**Which platform are you asking for?**
X

**Additional context**

![1531D46E-2A62-480B-B8A4-E9D361D16C5F](https://user-images.githubusercontent.com/58823942/84318929-2b896200-ab3d-11ea-9e5d-59cf2d8391a8.png)

**Comment by kezb765** [comment]
Hi @jaredgib ,

did you try domain redirection? You need a dedicated webspace and the ability to edit the settings for the subdomains. The goal is to set a permanent domain redirection (status 301) from your own subdomain (lets say "myapp1.jaredgib.com") to the thunkapp (lets say "https://thunk.app/blablabla"). That way you can publish a nicer looking web address.

**Comment by jaredgib** [comment]
I do this with bit.ly links

the link for the app mentioned above is bit.ly/ABATerms 

I want a better solution or am wondering if the staff will indicate that this is the only way it will be for now. 

Ideally, we can start to download and deploy our own apps on systems like Heroku or amazon AWS.

I am seeing this option on appgyver and it's, unfortunately, making me consider learning a second system. I want to be able to own the apps I create.

**Comment by jane-d-alt** [comment]
Closing as we have an open feature request from a live account for this feature at #701. Feature is in backlog and is recognized as being in demand.
