### ISSUE TITLE
Delete all rows block for DataSource

### ISSUE THREAD

**Issue by stanis14** [thunkable/thunkable-issues#563]
I have lots of problems trying to erase all rows and replacing them with new ones for a chat app.

Would be a lot more simple wit a block "delete all rows" 

I am asking for this on  Thunkable ✕

**Comment by jane-d-alt** [comment]
Hi there,

This block is available. See these docs for more details: https://docs.thunkable.com/data-sources#delete-all-rows
Apologies for not following up when this block was originally added.
