### ISSUE TITLE
Open Link in New Tab - Thunkable X Web App

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#566]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/40954645/84898600-89ee9d00-b075-11ea-9457-cf1bc73a3fad.png)
In the mobile app, the link opens in the default web browser, so the app runs separately. In the web app, the link opens in the tab the app is running. 

**Describe the solution you'd like**
An option on the "Open Link" block OR an additional block that open a link in a new tab.

**Describe alternatives you've considered**
Change the "Open Link" block to open addresses in a new tab as I believe it will function the same on mobile as it currently does.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by josmas** [comment]
Thanks for the request @MrMazzone 

@TingC any input on this?

**Comment by TingC** [comment]
There are already arguments around this topic on open link behave differently between react-native and react-native-web [here](https://github.com/necolas/react-native-web/pull/1432). As a tool platform, we could do the workaround mentioned in the discussion thread.

**Comment by MrMazzone** [comment]
Hi @TingC .  Hoping for a quick turnaround on this.  It is a stop point for my web app, especially with not having local storage availability.  Do you think you will be able to implement this quickly?

**Comment by TingC** [comment]
We'll think about it, and let you know once we decide. Thanks!

**Comment by TingC** [comment]
Hi @MrMazzone, we're going to enable open new tab on the web, thanks for waiting!

**Comment by MrMazzone** [comment]
@TingC  Awesome!  Your team is the best! 

I will test it out and report any issues.  Closing for now.

**Comment by MrMazzone** [comment]
I know it hasn't been a full 24 hours, but still not seeing links open in new tab for web apps.  I understand that it probably hasn't been released yet, but if it has I am just alerting you I am not seeing it.

I'll check on the feature again on Friday.

**Comment by josmas** [comment]
Hey @MrMazzone, this is planned work now, but it has not been yet implemented. Will reopen it and we'll keep you posted. Thanks!

**Comment by TingC** [comment]
Hi, @MrMazzone The opening link in a new tab on the web is now enabled. Please check and let us know if it is working for you, so we could close this issue. Thanks for waiting!

**Comment by MrMazzone** [comment]
Let me test it out!

**Comment by MrMazzone** [comment]
It works!!!  Thank you @TingC and Thunkable Team.  You guys are awesome!
