### ISSUE TITLE
Data Viewer List-Dynamic refresh

### ISSUE THREAD

**Issue by roroid** [thunkable/thunkable-issues#567]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm not able to refresh the data viewer list from code. In my opinion the solutions existing now(reopen screen/manual refresh by user) are just workarounds and data viewer list deserve a refresh proprerty.

**Describe the solution you'd like**
Would be great if the data viewer will automaticaly refresh when new data is added to the data source. If not possible than a function that when executed will generate a refresh.

**Describe alternatives you've considered**
Manual refresh
Reopen the screen

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by stanis14** [comment]
This would help me to a lot to add new data to the data source and display it on the data list viewer

**Comment by jane-d-alt** [comment]
The Data Viewer List now has a 'Refresh Data' block.

We'll close this issue now. Apologies for not following up when the block was initially implemented!
