### ISSUE TITLE
Help me please: I need to speed up firebase db searches

### ISSUE THREAD

**Issue by Bellacopia** [thunkable/thunkable-issues#569]
X Platform

Hi, my app searches on Firebase Realtime database by selecting the terms of a list based on a given criterion. The problem is that I am forced to insert a pause of at least 0.3 seconds between one cycle and another to obtain reliable results (see figure). 

![Screenshot (357)_LI](https://user-images.githubusercontent.com/63849566/85047056-9bc56280-b191-11ea-884c-4581e0e65437.jpg)

If the search is on a list of 500 terms, the wait is unacceptable: two and a half minutes!
Can anyone recommend a different way to proceed in order to avoid this delay.
(Do any of you speak Italian? This would simplify my job a lot.)
Thanks

**Comment by josmas** [comment]
Hi @Bellacopia I am not sure how you are thinking about this, but even without a 0.3 second wait, launching 500 requests to an external database is going to take too long. Think that each of those calls have to travel through the network, and that posibly takes longer than those 0.3 seconds.

Can you explain how the search works or what is supposed to happen?

Without any details, the only thing I can think of is that I would make one call to the database, download the 500 list items to the app, then do a local search on the list.

Doing `Realtime_DB.Get` inside a loop is always going to be problematic.

**Comment by jane-d-alt** [comment]
Closing this issue as Jose's suggestion is the correct way to address this behavior. Feel free to reach out to the team if you need guidance on implementation!
