### ISSUE TITLE
Thunkable LiveTest does not load button images

### ISSUE THREAD

**Issue by mtowfic** [thunkable/thunkable-issues#573]
For this project, the images on the buttons will not load when doing LiveTest feature but will load correctly if I were to test the app on my mobile device. https://x.thunkable.com/copy/0e15fab8bdd7274c1642b7830ad9c0ed

We purchased Thunkable licenses for classroom use and we usually use the LIveTest feature when teaching online, so hoping this new issue can be resolved very soon. 

My Thunkable account is : 
Username: msall00177n
Email: msall001@ucr.edu

**Comment by weihuali0509** [comment]
@mtowfic 

do you mean the following?
The image shows up in Android or iOS device.

but it doesn't work in the web preview? '
<img width="567" alt="Screen Shot 2020-06-23 at 2 50 08 PM" src="https://user-images.githubusercontent.com/1775235/85468103-def04e80-b560-11ea-9db4-3ce7fbcc6263.png">

**Comment by mtowfic** [comment]
Yes thats correct.

**Comment by weihuali0509** [comment]
Thanks for reporting this issue. Did this happen recently?

**Comment by bromanous** [comment]
It started happening with me and my students yesterday. We are both from the same university.

**Comment by TingC** [comment]
Good news! We fixed this issue. Could you try again and let us know if you still experiencing any issue? Thanks : D

**Comment by bromanous** [comment]
Yes I just tested it and the images are showing up! Thank you very much!
