### ISSUE TITLE
compnenet's property needs a wait of 0.2 seconds to be updated

### ISSUE THREAD

**Issue by bromanous** [thunkable/thunkable-issues#575]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
✕

### Issue/Request Origin
Myself

### Steps to Reproduce
1. Write a value to a property such as text change text color on a label.
2. Read that property's value.
3. You will get the old property value unless you add a 0.2 seconds wait between the write and read.

### Project Link
https://x.thunkable.com/copy/760c6a6a0a91c9d590d708675b01a021

### Expected Behavior
Today 06/24/2020

### Actual Behavior

on web live test:

1. Write a value to a property such as text change text color on a label.
2. Read that property's value.
3. You will get the old property value unless you add a 0.2 seconds wait between the write and read.

**Comment by josmas** [comment]
Hi @bromanous can you confirm if this is still an issue? I remove the wait blocks from your sample app and seem to be seeing the right valued. Thanks!

**Comment by bromanous** [comment]
Yes this solved the problem!
Thank you very much :)
