### ISSUE TITLE
More Fonts for Android

### ISSUE THREAD

**Issue by stanis14** [thunkable/thunkable-issues#579]
I would like to be able to have more choises of font when creating label.

Add more font for Android like for IOS.

No alternative solutions for now, just using the 10 fonts that are not very pretty.

For Thunkable C

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. As this covers the same topic as issue #181, we're going to close this issue. We are actually working on the ability to upload font files to Labels and Buttons right now!
