### ISSUE TITLE
Data viewer doesn't hide when empty

### ISSUE THREAD

**Issue by athornock84037** [thunkable/thunkable-issues#580]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

If I don't have data in my local table the data viewer displays a message that there's 'No data found' and cannot be hidden when the component isn't visible. It's okay that it says there's not data when that component is supposed to be showing, but not when the component is set to false visible.

### Steps to Reproduce
1. Set up a data viewer with an empty local table as the data source.
2. Set data viewer visibility to false. You'll quickly see the problem.

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

https://x.thunkable.com/copy/bf399a6c5b0a080590ba12b665f0f85b

### Expected Behavior
What did you expect to happen?

The component is fully hidden, even when there is no data in the table.

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
![image](https://user-images.githubusercontent.com/39869498/86259007-ba0b6500-bb78-11ea-97e1-d34d8e0469e8.png)

```

**Comment by josmas** [comment]
Thanks for the report @athornock84037 
This is a bug and we have a fix for it; it will be out in the next release some time next week.
