### ISSUE TITLE
List Viewer fonts

### ISSUE THREAD

**Issue by MrTwoCanes** [thunkable/thunkable-issues#583]
Please consider list viewer font color/size/bold/italic changes. Having only black letters makes it impossible to see characters on a black background; even just white font color would be a great help.  I have changed the background to a lighter color to see the items in my list viewer, but it just doesn't pop like light colored fonts on a black background.   I am a Thunkable X Pro user.

**Comment by AlexITMan** [comment]
See scrTableViewer in https://x.thunkable.com/projects/5d70f93f8a62b4079eedaff2/project/properties/designer/

**Comment by jane-d-alt** [comment]
Hi there,

Thunkable team member Jose is working on adding font size, font color, and background color properties to the List Viewer component. Expect to see these options in Thunkable very soon!

**Comment by jane-d-alt** [comment]
Hi there,

Just confirming that this update was published on April 13 2021. Apologies for not following up here at the time. Thanks for the request!
