### ISSUE TITLE
Web Viewer "Back" and "Forward" Blocks Not Visible in Drawer

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#586]
### Platform
Thunkable X

### Steps to Reproduce
1. Open Thunkable X
2. Add a Web Viewer
3. Look at blocks in Web Viewer drawer/section
![image](https://user-images.githubusercontent.com/40954645/86635674-61d1ca00-bfa1-11ea-8aa3-f84b8aafcdc2.png)

### Expected Behavior
You would expect to see all the blocks (events, methods, and property getters and setters) available for the selected component.  For the Web Viewer, you should see the "Back" and "Forward" purple method blocks.

### Actual Behavior
The only way to access the "Back" and "Forward" methods are to select a different method block and use the drop down.
![image](https://user-images.githubusercontent.com/40954645/86635999-cc830580-bfa1-11ea-9ee4-bfcf7ea8d8d5.png)

This is not intuitive, and defeats the purpose of blocks-based languages: discoverability of capabilities.  

_Side-note: There are a few more cases of this in Thunkable X.  I am reporting this one because they are newly added blocks.  If you feel it is valuable, I can locate the other missing blocks and report them.  Just say so in the comments._

**Comment by josmas** [comment]
Hey @MrMazzone we generally hide blocks until they are fully tested. These two particular ones should not have appeared in the dropdown either, but they will be released pretty soon. Thanks for letting us know though! :)

**Comment by MrMazzone** [comment]
@josmas OK.  That makes sense. 

The only reason I posted this was that the Thunkable documentation says the feature was released July 3: https://docs.thunkable.com/release-notes

It is also documented on the Web Viewer component page: https://docs.thunkable.com/web-viewer#go-back-forward

**Comment by josmas** [comment]
@MrMazzone Yeah, I believe this was an oversight on our side. We forgot to remove the flag to unlock this. It is an easy fix though, so should be out as soon as we release a new version. Thanks again for letting us know!

**Comment by jane-d-alt** [comment]
These blocks are now visible when you open the blocks drawer of a Web Viewer component.
We'll close this issue now. Thanks for bringing this behavior to our attention!
