### ISSUE TITLE
Unable to edit projects

### ISSUE THREAD

**Issue by Bellacopia** [thunkable/thunkable-issues#589]
Hi. In these days I am able to work on my projects: Thunkable Live (Android and iOS) works perfectly on the backup copies of a few days ago but as soon as I modify one of them it crashes to white screen. I tried to update it (v. 201) but the situation remains the same.
I use maps in my app. I read that the latest update was about the map component. What can I do to overcome the problem. I have been standing for at least three days. Thanks in advance

**Comment by josmas** [comment]
Hi @Bellacopia the changes to maps where mostly on how to get information (coordinates and position) out of the returned event, if you are using blocks such as onPress. The changes are [explained here](https://github.com/thunkable/thunkable-issues/issues/532#issuecomment-647459617).
If you are unwrapping objects, and the structure is not correct, it is possible that the companion goes blank. Let us know if that is the case. If not, please post a picture of your blocks.

**Comment by Bellacopia** [comment]
Hi Jos,
I'm happy to hear from you.

I try to better explain what happens.
If I use Thunkable live to open a project that I have saved a few days ago
everything works perfectly, including all maps.
Then I duplicate that project and modify it, then I launch Thunkable live
to check the effect of the changes (that have nothing to do with maps). The
effect is the desired one and everything seems ok. But, at this point, if
you open a screen that contains a map, the app crashes to white screen.
This had never happened to me before. Do you have any idea what the cause
may be?

Ugo

Il giorno gio 9 lug 2020 alle ore 12:38 Jos <notifications@github.com> ha
scritto:

**Comment by josmas** [comment]
hi @Bellacopia can you send a link to the particular project? there may be something wrong with the copy but we are not seeing any other similar issues, so it might be specific to your project. Feel free to send the link through support if it is a private project and do not want to have it on here. Thanks!

**Comment by Bellacopia** [comment]
Hi Jos, I would really like to send you the link because I think I have identified which component causes the block. The error is easily reproducible and I can send you the exact sequence of steps to take. 
But what do you mean by sending the link through support? And do I have to use the "Share" command to generate it?
(I'm asking you because I have never done it before...) 
Thank you so much.

**Comment by josmas** [comment]
hi @Bellacopia if it is a private project you can send the link and instructions either through intercom or as a private message in the community. If you send it through intercom, add a link to this issue so if someone else sees it first, they can forward to me.

**Comment by Bellacopia** [comment]
Hi Josmas, forgive me: could you be a little more specific. What to you mean with "intercom"? are you referring to this chat? 

![Screenshot (549)](https://user-images.githubusercontent.com/63849566/87594248-f7313480-c6ec-11ea-9475-d78d7e98bd78.png)

And how may I send you a "private message" in the community? The message windows looks like this:

![Screenshot (550)](https://user-images.githubusercontent.com/63849566/87594680-9eae6700-c6ed-11ea-9c67-685c4cbf861b.png)

and I wonder how to indicate you as recipient, and how to ask for the message to be private. 
Finally I ask you again how to generate the link to my project. Should I use the share command?
Thank you for your patience.

**Comment by Bellacopia** [comment]
Hi Jose, last Monday  I sent  links and instructions through intercom and Jane have passed all of that on to you. Did you received them?

**Comment by josmas** [comment]
Hi @Bellacopia I did get it and it's in my TODO list. Hoping to get to it sometime tomorrow. Thanks!

**Comment by jane-d-alt** [comment]
Closing as this issue was resolved in private conversations at the time of reporting.
