### ISSUE TITLE
How to use Thunkable Classic List format on Thunkable X?

### ISSUE THREAD

**Issue by pMertDogan** [thunkable/thunkable-issues#59]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
X and Classic
### Issue/Request Origin
Builder

### Steps to Reproduce
1.Make a some dummy list of list on Classsic version and store it on Firebase
2. Get stored list from firebase on Thunkable X
3.Try get list item 3 or another 
Its not work.You cant collect true value from list.Thunkable Classic list format not work with X.I cant move my list created wih Classic to Thunkable X platform.

### Expected Behavior
What did you expect to happen?
I want use my old list on Thunkable X  like Classic version

### Actual Behavior
What actually happens?
```
Thunkable X do   wrong list parsing .When ı try get 3. item ( dummyvalue ) 
Result = d or [  ...   Its wrong ı want get dummyvalue not d or somethink like this.There is parse error


  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
@GOTFire While we may eventually provide the capability to access lists from the Classic version of the Firebase component, it's not high on our priority list.  If you need this right away, there might be a way to parse the results coming back from the Thunkable ✕ component.  I would suggest asking for help on how to parse Thunkable Classic lists using Thunkable ✕ on the [Thunkable ✕ discussion forum](https://community.thunkable.com/c/thunkable-cross).

**Comment by tomer2526** [comment]
there are updates?  I need that too

**Comment by mark-friedman** [comment]
FWIW, I just posted this on the community which demonstrates a workaround for the problem: https://community.thunkable.com/t/firebase-scopevariableinfo-cloud-variable-error-notification/235341/4?u=mark

**Comment by tomer2526** [comment]
I also need to update the list (delete a certain index, change a certain index, look for a value and get its index, look for an index and get its value and everything that can be done with lists) Can it be done?

**Comment by mark-friedman** [comment]
@tomer2526 Yes.  If you use the workaround that actech and I suggest (i.e. of copying the list) you can then use any of the normal list operations on that copy.

**Comment by tomer2526** [comment]
But I have to return the updated list to the same list type that was (list as in the classic version)

**Comment by domhnallohanlon** [comment]
@pMertDogan @tomer2526 We've made a lot of great updates to the cloud variables recently (including the ability to access/manipulate objects) perhaps this would work with your Classic Firebase? 

https://docs.thunkable.com/variables#cloud-variables-and-data

Let me know what you think.

**Comment by jane-d-alt** [comment]
Hi there,

Since you didn't follow up on Domhnall's question, we will close this issue for now. You are welcome to follow up if Mark's workaround didn't work or if you have any follow-up questions after reading the docs. As Thunkable Classic has been deprecated, we recommend using the method explained in the docs Domhnall linked to save and retrieve lists from Firebase Realtime DB. Thanks!
