### ISSUE TITLE
Dark mode / dark theme for ThunkableX components

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#590]
Hi there,

I request the option to use components in ThunkableX with dark mode. It could be a simple flag that must be added in complex components like data list viewer, or the standard list viewer. For simpler components like buttons or labels it is sufficient to change the background / font colors, but for complex components it is maybe easier to have a simple swith in design mode like "dark mode on/off" and the component displays as dark or not. Or even better: a block "from data_live_viewer1 set darkmode = true"? That way I could implement settings that the app user could change.

btw: I am not talking about ThunkableX editor, that's another question.

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request.
This is a specific use case of other requests such as #565 - with more blocks to set the properties of components, creators will be able to implement dark modes in their app.
for that reason, we are going to close this issue, just to avoid having multiple versions of the same request open.
You are welcome to comment on the linked issue to show that it is a popular request!
