### ISSUE TITLE
Add Row ID to the "List of Values In" Data Source Block option list

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#591]
Although Thunkable X data source blocks are nice and can be used with the Data Viewer List, it is not possilble to programatically access the data without user interaction.  That is, the data source "Get Data From" block requires a Row ID, which cannot be obtained except in the click events of components like the Data List Viewer. This required user interaction cripples the useability of the Data Source blocks for anything more than the most rudamentary functions.

Could the "List of Values In" block be modified to include Row ID as well as the user defined columns? If so, programs could access the data without user interaction and programmers could perform a variety of sorting, filterings, and searching functions. 

Since the Row ID is used in the Get, Update, and Delete blocks, it seems like adding Row ID to the "List of Values In" block would have a small scope and a HUGE payoff.

Alternatives, other than completely abandoning the Data Source blocks and using another data storage option (e.g. Firebase Realtime DB) , are limited. AirTable data can be managed outside of Thunkable (an advantage). The AirTable blocks also have Get All Rows and Get Selected Rows. Unfortunately AirTable is limited in the amount of storage (1,200 rows) in their free accounts.  Google Sheets have the advantage of greater storage and can be managed outside of Thunkable, but cannot be accessed in Thunkable except by the Data Source.  A local table can be created, but is not accessible (manageable) outside of thunkable.

**Comment by tatiang** [comment]
I think I requested this recently, too. I also would like to see the rows selectable by numerical order. So "1" for the first row, "2" for the second, etc. I actually just tried this with a local data source and it worked. I'm not sure if that's a recent change...

**Comment by sysads** [comment]
Any luck with this as I need it for Airtable rows

**Comment by jane-d-alt** [comment]
Hi there,

It should now be possible to use integers (1, 2, 3...) as Row IDs for your Airtable and Google Sheets Data Sources with the Data Sources blocks. Thanks to all who requested!
