### ISSUE TITLE
Data Viewer List with Google Sheet Data Source Fails to display if there are empty rows

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#592]
### Platform
Thunkable X Responsive Web App (Windows 10 Chrome browser)

### Issue/Request Origin
Self Generated

### Steps to Reproduce
1. Create a Google Sheet with 1 column and 3 rows with each row containing some value
2. Create an empty thunkable project
3. Add the data viewer list control
4. set the data source to the Google Sheet
5. set the click event of the data list viewer to delete the selected row id and navigate to screen 1 (effectively refreshing the display)
6. Select the Live Test option from the Thunkable menu
7. Click Preview as responsive web app (the form should appear with the data viewr populated)
8. click the middle entry (which will then be deleted)
9. The Data Viewer list is no longer displayed.
10. Update the Google Sheet with a value in the middle row
11. Refresh the Response App Screen and the Data Viewer List reappears

### Project Link
Thunkable X Project
https://x.thunkable.com/copy/732eb9cad41a8f845312dfa52c111e27
Google Sheet
https://docs.google.com/spreadsheets/d/1xPg0XTUi1NeXWZj44XY_UWDkicEzOT3w9GekKxe93tA/edit?usp=sharing

### Expected Behavior
When a row is deleted, I would expect any rows BELOW to move upward. At the very least, at least a blank row should appear in the data viewer list .

### Actual Behavior
The data viewer list disappears.

![image](https://user-images.githubusercontent.com/66176281/87174808-989f2d00-c28c-11ea-8381-12a3de348137.png)

![image](https://user-images.githubusercontent.com/66176281/87174889-b40a3800-c28c-11ea-9d7c-af3e3bd2f720.png)
![image](https://user-images.githubusercontent.com/66176281/87174999-e025b900-c28c-11ea-992d-e30a07b0f475.png)

**Comment by josmas** [comment]
Thanks for the report, we will look into it.

**Comment by jane-d-alt** [comment]
This behavior appears to be resolved. We'll close this issue now. Apologies for not following up when this behavior was initally resolved. Thanks for reporting!

**Comment by DrTedGit** [comment]
I tested this out and the behavior is different.  But after deleted all of
the rows using thunakble and repopulating them in the google sheet, the
data viewer doesn't show any data... :-(
