### ISSUE TITLE
Getting map in a list and setting zoom crashes app and Thunkable live.

### ISSUE THREAD

**Issue by 22rdhall** [thunkable/thunkable-issues#595]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
✕ iOS companion

### Issue/Request Origin
Coding in thunkable

### Steps to Reproduce
1. Have a list of maps on one screen. (I tested with 5)
2. Use _From map, in list, of column #, to set zoom_
3. App crashes.
Link to test app [here](https://x.thunkable.com/copy/6500b11d44e1cea339931fc039d4fc06).

### Project Link
[https://x.thunkable.com/copy/6500b11d44e1cea339931fc039d4fc06](https://x.thunkable.com/copy/6500b11d44e1cea339931fc039d4fc06)

### Expected Behavior
Map should adjust zoom. This used to work before the last update where map components were updated.

Setting latitude and longitude with same type blocks works great.

### Actual Behavior
Thunkable live on iPhone 8 crashes. Screen turns white.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![Capture](https://user-images.githubusercontent.com/13912726/87323018-ce921a80-c4f3-11ea-8737-a6b71846ce35.JPG)

**Comment by josmas** [comment]
Thanks for your report; we have a fix for the Zoom property but we are waiting for approval to release the app. Should be out some time this week.

**Comment by 22rdhall** [comment]
Awesome thank you for the update.

**Comment by josmas** [comment]
The app as released some time last week. Closing this now. Please re-open if needed. Thanks!
