### ISSUE TITLE
Change data source of the data viewer with blocks.

### ISSUE THREAD

**Issue by stanis14** [thunkable/thunkable-issues#599]
I am doing a marketplace app and the users need to change multiple times the data source for a same data viewer grid to be able to see all the options or filters.

The solution would be to be able to change data source of the list viewer with blocks.

For now I have 10 data list viewer and I render visible the one I need. But to show all the filters ect .. I would need hundreds of them and it would make the app crash so I have a limited version of my marketplace.

Thunkable ✕ 

It could resemble at the airtable blocks for "Api key" "Base Id" "table name" and "View name"

**Comment by Freefeer** [comment]
It would be spectacular, as it is a component with few variants of personalization in data entry, the possibility of accessing the data source from the blocks becomes essential!

**Comment by stanis14** [comment]
Yes that would help me so much with my project !

**Comment by s-e-t-h** [comment]
+1 to this!

**Comment by Freefeer** [comment]
Hello everyone, has anyone found any news or solutions to this problem today? Greetings

**Comment by jane-d-alt** [comment]
Hi there,

This seems to overlap with #541, so we are going to close this issue. We are aware of community interest in this feature and hope to introduce it to the platform. Thanks!
