### ISSUE TITLE
Map: Zoom value does not update is user zooms in or out manually

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#604]
In Map component there is an event "when Map1 onUserLocationChange" which has a result named "coordinate". When I list all object properties of "coordinate" I get a long list: dispatchConfig,_targetInst,nativeEvent, ... but no latitude or longitude. The property "nativeEvent" reminds me of former solutions, but is this the way it's supposed to be?

Btw: the block "from Map1 get zoom" still does not delivers the **current** zoom level.

2nd btw: I am glad that "onCalloutPress" works now, and that the position stays the same after pressing or clicking on the map. Thanks a lot to the team, but Map still resets the orientation: when I rotate the map (with two fingers) and click on it, the rotation gets a reset.

**Comment by josmas** [comment]
Hi @kezb765 thanks for the report.

I don't think the location event is working at the moment, we'll have a look at that and also zoom's get block.

The rotation reset is a bit more complicated because the library does not provide a way to keep it. The library is a bit quirky, for instance I thought that ShowsCompass was not working either, but it turns out it only shows when your map is not pointing North (which is the default orientation; you only see it if it is active and you rotate the map). The more we work with it, the more quirks we find, so we can hopefully find more workarounds soon. Thanks!

**Comment by Baiar** [comment]
Map zoom don’t work

**Comment by Baiar** [comment]
Sorry, recognizing the work you do and the goodness of the software you are producing, and that I try to use, I would like to know if the missing zoom tracking feature in Google Map can be taken into consideration.
And if there is a possibility that the lack of functionality will be introduced.
Thank you

**Comment by josmas** [comment]
Hi @Baiar Zoom is working fine for me. Can you link to your project or show us your blocks? Please make sure you are following the instructions on range here: https://docs.thunkable.com/map#zoom-and-center-the-map

**Comment by Baiar** [comment]
Now I'll explain what "doesn't work" means, maybe I got the wrong word but ...

I'm sending you a video, [link](https://youtu.be/pL7YhSSDzE0),  explaining but I'll try to explain it.

https://x.thunkable.com/copy/877bb9cf7278f4ee6f3aa51517cb960b

Start MapZoom: 10. ok

I insert marcker and in a labelTest I put the value of mapZoom,

I zoom out of the map with my fingers.

I insert another mark and insert the zoom value (which should be changed and instead there is no control and the system does not change the zoom value. It always gives me 10. Which is a "wrong" value compared to the actual value of the zoom of the map.

ok, not an error but a lack.

Are you close to solving the problem?

Thank's,

Angelo Angius

**Comment by Bobbybase** [comment]
Does this issue also include times where the map flickers between two zoom levels and eventually crashes the app?  drted in the thunkable comminuty describes it better than I could and reports "I am having a similar problem on an iPhone 6 and ipad mini 4. If I reposition the map by touching the map BEFORE any blocks are activated, the Zoom BLOCKS work correctly. If a block changes the zoom BEFORE touching the map, the map flickers between 2 zoom/location points and the app locks up."  I am also seeing this issue on IOS devices.  So is this included or should I raise a separate issue?

**Comment by jane-d-alt** [comment]
Hi there,

The onUserLocationChange block now returns the following JSON object as the output coordinate:

target: Numeric ID for your app
coordinate:{
      latitude: latitude of point selected
      longitude: longitude of point selected 
}
position:{
      x: x-position of selected point on the Map component
      y: x-position of selected point on the Map component
}

You can read more about the Map blocks and their outputs [here](https://docs.thunkable.com/map#on-user-location-change).

Thanks for reporting! Apologies for not following up here when the new Map blocks were originally released.
