### ISSUE TITLE
Opening the keyboard squashes the screen

### ISSUE THREAD

**Issue by domhnallohanlon** [thunkable/thunkable-issues#605]
### Issue/Request Origin
Reported in the Community:
https://community.thunkable.com/t/keyboard-hides-textbox/681411?u=domhnallohanlon

### Steps to Reproduce
1. Add a Text Input to a screen
2. Open Thunkable Live
3. Click on the Text box to enter text

### Project Link
https://x.thunkable.com/copy/d54ea9b4e20a8194b50f61934b3d498c

### Expected Behavior
The keyboard should either overlay the contents underneath it, or push the contents of the screen up

### Actual Behavior

The entire screen gets squashed, with a large amount of padding between the screen and the keyboard:

**Closed:**
![keyboard_closed](https://user-images.githubusercontent.com/3117345/88056587-b73cd800-cb58-11ea-9969-48a46ccc4082.jpg)

**Opened:**
![keyboard_open](https://user-images.githubusercontent.com/3117345/88056633-c754b780-cb58-11ea-96c1-ca6f9b8e5539.jpg)

**Comment by josmas** [comment]
This seems to work fine in the latest companion version:

![Screenshot_20200731-120209](https://user-images.githubusercontent.com/194925/89029343-228b6480-d326-11ea-8736-e71a089a2e4b.jpg)

@domhnallohanlon can you please double check and reopen if needed? Thanks!

**Comment by SkulaMesterHU** [comment]
@jane-d-alt @domhnallohanlon It does the same to me. Any fix on the way?
