### ISSUE TITLE
The List of numbers from 1 to 1 block doesn't work

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#607]
![изображение](https://user-images.githubusercontent.com/20015046/88144269-587f6900-cc01-11ea-8c04-94b0c0cb7878.png)

**Comment by kezb765** [comment]
Have you tried:
from lsvTest set "text items" to **join** "list of..." ?

**Comment by AlexITMan** [comment]
Thank you for the other option of creating a list from a single element, but in this case we are talking about the fact that a novice user will try to use this block and will not be able to understand why it does not work. In this case, the "List of numbers from 1 1 1" block does not work"

**Comment by domhnallohanlon** [comment]
Hey @AlexITMan, 

Was that the default value for this block last year? 

Looking at it now it seems to be from 1 - 5.

![Screenshot 2021-03-12 at 14 20 53](https://user-images.githubusercontent.com/3117345/110952462-2b252e00-833e-11eb-8b77-261c4a8d4f18.png)

Does that address the issue you were trying to raise?
