### ISSUE TITLE
Loss of synchronization when executing blocks

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#608]
After the latest updates, there is a loss of synchronous block execution, which is expressed in the fact that you have to add a delay block to execute the previous blocks. Will this situation, which makes reliable application development impossible, be fixed?

The blocks below do not work in Live without a delay after the first block

![изображение](https://user-images.githubusercontent.com/20015046/88148462-4c96a580-cc07-11ea-8507-05ded3b41ef1.png)

In the example below the button block does not have time to assign a background color and for this reason buttons without a background color are created.

![изображение](https://user-images.githubusercontent.com/20015046/88154119-03e2ea80-cc0f-11ea-892f-1b91fb127386.png)

**Comment by jane-d-alt** [comment]
Hi there,

Since this seem to overlap with your other open issue relating to synchronicity, #552 , I'm going to close this issue. I have tagged the other issue as a bug and will ask the team to follow up on it. Thanks for reporting.
