### ISSUE TITLE
Setting the background color to 'none' results in a white button

### ISSUE THREAD

**Issue by 10MINT** [thunkable/thunkable-issues#61]
### Platform
Thunkable Classic on the latest version

### Issue/Request Origin
Discovered myself

### Steps to Reproduce
1. Add a button somewhere
2. Add material-icons.ttf and set the text of the button to some icon, e.g. `arrow_back`
3. Set the background of the button to `none`

### Expected Behavior
The background should be transparent and the icon should be visible

### Actual Behavior
The button turns completely white

![screenshot_2018-08-04-15-27-43 1](https://user-images.githubusercontent.com/10596945/43677025-aeb99160-97fb-11e8-95ac-a467ecc405c4.png)

**Comment by weihuali0509** [comment]
@10MINT are you talking about the icon or button? Can you send the sample aia to me?

**Comment by 10MINT** [comment]
To be clear, setting the background color of a button to `none` results in a white button. After some testing, I discovered that step 2 from above is not necessary, i.e. it does not matter whether you specify a font file or not. I tested it in Thunkable Live only. Any project with the update from Aug 4. will work
