### ISSUE TITLE
App Variables not updating as expected on Web App

### ISSUE THREAD

**Issue by amblemind** [thunkable/thunkable-issues#610]
### Platform
✕ Web App

### Steps to Reproduce
1. https://x.thunkable.com/copy/5342a5845580e4ba8b8c12f4b14b463b
2. Launch in Web Preview
3. Look at Label

### Expected Behavior
Should show `Changed Value`

### Actual Behavior
Shows `Initial Value`

![image](https://user-images.githubusercontent.com/45864164/88358267-de033600-cd33-11ea-9ce0-17ad014ae312.png)

**Comment by MrMazzone** [comment]
It seems app variable changes are not persisting between screens.  Maybe the variable is reinitializing on each screen?

This is not just on Web, this is on iOS and Android too.  Only started happening with most recent update (yesterday). 

Behavior I am observing: 
- Initialize a variable on Screen1
- Change variable on Screen1
- Observe change and it changes as expected
- Navigate to Screen2
- Use variable
- Variable is the initialized value, not the value you changed it to previously on the other screen.

Again, I am thinking it is initializing on each Screen, where before it used to initialize only on the screen you placed the initialize block.

**Comment by josmas** [comment]
Thanks for the report, guys. We'll look into it.
@pmwthunkable has there been any recent change to variables?

**Comment by josmas** [comment]
This should be fixed in the latest update. Thanks for the report.

**Comment by MrMazzone** [comment]
This does seem to be working as expected for me now.  @amblemind ?

**Comment by amblemind** [comment]
@josmas The app I originally discovered this on seems to be behaving as expected again, so I can say my issue was resolved.
