### ISSUE TITLE
"Number of rows" and "list of values" do not work in Live update 206 for Android 

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#611]
Data is displayed in the Data Viewer List, but the blocks below don't work and don't change anything in Label2.Text

![изображение](https://user-images.githubusercontent.com/20015046/88423223-1d915700-cdf4-11ea-8726-41d1e5a732a8.png)

**Comment by josmas** [comment]
Thanks for the report @AlexITMan I can reproduce.

@StevenPurn any recent changes that might have affected this? I can see a gql error in the console.

**Comment by StevenPurn** [comment]
I have an idea as to what might be happening but I'm not sure if there are additional issues. @AlexITMan, what type of data source are you using? Does it apply to all of your data sources or only a few?

**Comment by josmas** [comment]
Closing this for now; feel free to reopen if needed.
