### ISSUE TITLE
Request for: "delete all row in "Data Sources"

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#615]
Hi all,

I love the new components "data Viewer". But I would like to use them in filtered ways. The way it should be looks like (for me):
- get all rows from a data source
- filter them
- store the results in a local data base
- show a data list viewer with the results stored in that local data base.

Problem:
- you have to clear the local data base before filling it with new values

Solution (right now):
- before storing the results you have to to delete old entries. Therefore you have to iterate over all row IDs and delete them all.
- this is time consuming.

Better solution:
- ThunkableX provides a new block "delete all entries" in the Local Data Source.

**Comment by AlexITMan** [comment]
A workaround is not to delete data, but to update it if the current index is less than or equal to the number of rows in the Data Source. But due to an error in Data Source indexing, I noticed that Data List Viewer does not display an image in the first entry.

**Comment by kezb765** [comment]
This loop seems to work:
![grafik](https://user-images.githubusercontent.com/7669660/90262824-18ea1c80-de4f-11ea-9957-00fe2403fb42.png)

Thanks to thunkable user "actech".
