### ISSUE TITLE
The platform is not working.

### ISSUE THREAD

**Issue by RajShivlani** [thunkable/thunkable-issues#616]
My Thukable account is not working and whenever I do live test it is not working here is the link for the project I made https://x.thunkable.com/projectPage/5f2024cb2d1266dcd9420fda and this is my teacher made https://x.thunkable.com/projectPage/5f20258114bdb93bcba7415a  mine is not showing sprites and even the firebase stops working sometimes and I am having a lot of problem with my projects of whitehat jr. Please fix this bug or give me a solution my name in Thunkable is rajshivlani78y5rw.

**Comment by josmas** [comment]
Your project loads perfectly fine, if you are having issues with your code please ask for help in the [community](https://community.thunkable.com/). You are going to have to be more specific about what is not working if you open a thread in the community. Your teacher should be able to help you out debug the issues too. This is not a bug in the platform.

**Comment by RajShivlani** [comment]
> Your project loads perfectly fine, if you are having issues with your code please ask for help in the [community](https://community.thunkable.com/). You are going to have to be more specific about what is not working if you open a thread in the community. Your teacher should be able to help you out debug the issues too. This is not a bug in the platform.

Sorry, I hadn't been specific I was saying the sprites weren't loading.
