### ISSUE TITLE
Invalid indexing in the Delete Row block

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#618]
This block deletes the second position in the list and cannot delete the only position in the list.

![изображение](https://user-images.githubusercontent.com/20015046/88764575-dd2c3300-d17d-11ea-8253-65f054ed41ef.png)

Simply put, indexing starts with 0, but an attempt to delete a row with index 0 fails (or it happens randomly sometimes)

**Comment by josmas** [comment]
thanks for the report @AlexITMan 
We'll look into it!
