### ISSUE TITLE
Making a page scrollable makes the elemnts inside disappear

### ISSUE THREAD

**Issue by Alin63992** [thunkable/thunkable-issues#62]
### Platform
Thunkable ✕ for Android device

### Issue/Request Origin
In app editor, Thunable Live

### Steps to Reproduce
1. Put some items on any app screen.
2. Set `Scrollable` to `TRUE`

### Expected Behavior
Make the page scrollable and keep the items in place and visible.

### Actual Behavior
The items are not visible anymore, so I can't test if the page is indeed scrollable, unless I set `Scrollable` to `FALSE`

**Comment by mark-friedman** [comment]
@Alin63992 Are you observing the behavior on an Android device or an iOS device?  Also are you observing this during live testing (i.e., in the Thunkable Live app) or on a downloaded app?

**Comment by Alin63992** [comment]
I use an Android device, since I don't own an iOS device. And I saw this behavior during live testing, since I didn't download the app, because it's not finished. Sorry that I forgot to mention these.

**Comment by mark-friedman** [comment]
@Alin63992 Thanks for the additional info.

**Comment by mark-friedman** [comment]
@Alin63992 Are you still seeing this behavior?  I don't see it in the latest Thunkable Live app for Android that was released yesterday.

**Comment by jane-d-alt** [comment]
This behavior has been resolved.
