### ISSUE TITLE
Importing a saved screen and then deleting it, variables stay in project regardless if the screen is there or not. 

### ISSUE THREAD

**Issue by sogalanbat** [thunkable/thunkable-issues#620]
### Platform
Thunkable X 

### Issue/Request Origin
Personal project.

### Steps to Reproduce
1. Add a screen from your saved screens ( I saved the calendar screen you guys provided) 
2. Delete the screen you just added ( You might have made a mistake)
3. The variables are still there.
4. Clear the browser cache ( Chrome Versión 84.0.4147.89 (Build oficial) (64 bits))
5. The variables are still there.

### Project Link
https://x.thunkable.com/copy/98efa5f6ea2da20e8d501631c1c3aa24

### Expected Behavior
If the variables are not present anywhere in the projects, you should be able to delete them. 

### Actual Behavior
The variables stored are saved regardless if the blocks exist or not. 

```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/11952690/88813687-dc47d100-d17e-11ea-924d-e5dc5d4af454.png)

**Comment by jane-d-alt** [comment]
This behavior was resolved recently. We will close this issue now. Thank you for reporting it!
