### ISSUE TITLE
The image is not displayed in the first row of the Data List Grid on Android 9

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#623]
As you can see, in Live, the first line shows an image of a heart. On iOS 12.4, after the update swipe, it is also displayed, and on Android 9, the image is empty instead. I think this problem is related to the problem of incorrect data Source indexing.

![изображение](https://user-images.githubusercontent.com/20015046/88963904-36e14a00-d2b1-11ea-91e1-4a9f4a4fbf5c.png)

**Comment by jane-d-alt** [comment]
Hi there, it seems that this behavior has been resolved. We tested [this project](https://x.thunkable.com/projectPage/60a4d61b583ab400124d3499/) on Android 9 and the photo is visible in the first row of the Data Viewer List. We will close this issue now. We apologize for not following up here when this behavior was originally fixed. Thank you for the report!
