### ISSUE TITLE
Web app - Text Input triggers `Submit` event when enter key is pressed AND multiline == False

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#626]
### Platform
Thunkable X Web

### Issue/Request Origin
Trigger the `Submit` event when the enter key is pressed, text input is in focus, and multiline is set to false.

### Steps to Reproduce
1.  Create web app with text input.
2.  Add code to the `Submit` event handler
3.  Click enter while focused on the text input and code will not run.

### Expected Behavior
The `Submit` event's code should be triggered. 

### Actual Behavior
Nothing happens.

**Comment by josmas** [comment]
Thanks for the report @MrMazzone We'll look into it.

**Comment by jane-d-alt** [comment]
This behavior has been resolved: if you build an app with a Text Input as described in the Steps to Reproduce section, the code in the 'when Text Input Submit' block will be triggered when the enter key is hit on a web app.
We will close this issue now; apologies for not following up when this was originally resolved.

**Comment by MrMazzone** [comment]
I can confirm this is working for me now. Thank you @jane-d-alt !
