### ISSUE TITLE
In Live on Android 9 the app crashes after Map is added to the screen

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#629]
After adding the Map component to the screen, the application crashes: Error while updating property InitialRegion'. To fix the crash you need to fill the fields for Map on the image

![изображение](https://user-images.githubusercontent.com/20015046/89411090-80a4b700-d72d-11ea-86f1-123d743bce99.png)

**Comment by josmas** [comment]
Hey @AlexITMan is this specific to Android version 9?

We fixed this same issue a couple of weeks ago, but it might be specific for a particular device or version. It is working fine for me on a onePlus 6 with Android 10. Can you please send details about the device?

Also, can you check which version of the app you are running? If you go to the projects list and long click the Thunkable beaver it should pop up with a version like `The app Version is 21101` or similar.

**Comment by AlexITMan** [comment]
I'm using Live ver. 210 on Android 9 on a HUAWEI Y6s phone.

**Comment by josmas** [comment]
He @AlexITMan is this still happening with version 213? If that is the case, any change you can capture a log with Logcat?

**Comment by AlexITMan** [comment]
In the new version of Live the Map component works without this error

**Comment by josmas** [comment]
Thanks for confirming @AlexITMan 
Will close this now, feel free to reopen if needed. Thanks!
