### ISSUE TITLE
Labels overlap

### ISSUE THREAD

**Issue by Alin63992** [thunkable/thunkable-issues#63]
### Platform
Thunkable ✕ for Android device

### Issue/Request Origin
Editor and Thunkable Live

### Steps to Reproduce
1. Put 2 or more labels
2. Watch them place themselves one on top of another

### Expected Behavior
The labels were supposed to be placed one after another.

### Actual Behavior
The labels are placed on on top of the other.

**Comment by AlexITMan** [comment]
Do you need this function?

https://x.thunkable.com/projects/5b66a8321b0ca5aa4e1fe21c/project/properties/designer/

**Comment by mark-friedman** [comment]
That project had a couple of Advanced properties set (i.e. absolute position and non-zero margins), which accounted for the the labels being on top of each other.  Resetting those properties to the defaults brought the display back to the expected appearance.
