### ISSUE TITLE
Published Web App Not Accessible

### ISSUE THREAD

**Issue by amblemind** [thunkable/thunkable-issues#631]
Notes: 
- This worked this morning. 
- Published web apps aren't accessible. I tried republishing and publishing a new app. Same issue. 
- I can see the app in Web Preview, just not published. 
- Also not sure if this is related: https://community.thunkable.com/t/i-can-t-access-firebase-with-my-api-key/722349/2?u=darren It started occurring at the same time. 

### Platform
✕ Web App

### Steps to Reproduce
1. Click here: https://thunk.app/web-build/index.html?webAppId=FfTv4sJtJ&from=x
2. Or here: http://sendth.at/

### Expected Behavior
Should see app. 

### Actual Behavior
See blank white screen. 

![image](https://user-images.githubusercontent.com/45864164/89467082-9371b880-d73a-11ea-9fbe-e165b6cc0105.png)
![image](https://user-images.githubusercontent.com/45864164/89466986-6c1aeb80-d73a-11ea-86a5-036d5e3b7d68.png)

**Comment by MrMazzone** [comment]
I am having the same issue.

**Comment by TingC** [comment]
Thanks for reporting! We'll take a look and get back to you.

**Comment by Freefeer** [comment]
I have the same...

**Comment by weihuali0509** [comment]
It should be operational now.

**Comment by MrMazzone** [comment]
Maybe I just need to wait a bit longer, but I am still having the issue with one of my web apps: https://thunk.app/w/xBrUZzkmT

**Comment by StevenPurn** [comment]
@MrMazzone your link is working for me. It might be a caching issue so if you hard refresh I would guess your app will show up again.

Hard refresh in chrome by cmd + shift + r on mac or ctrl + shift + r on windows

**Comment by MrMazzone** [comment]
Thank you!  I thought I had tried that.
