### ISSUE TITLE
Installed Android apps crash on Samsung Galaxy S6 and S7 with Android 7.0

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#632]
### Platform
Installed Android app

### Steps to Reproduce
1. Create .apk for a Thunkable app
2. Install on Samsung Galaxy S6 or S7 with Android 7.0 (emulator or physical device)
3. App crashes immediately.

### Project Link
First reported from my app's users.  I was able to reproduce with an app that had a button and an alert, so it does not seem isolated to my app.

### Expected Behavior
App opens and does not crash

### Actual Behavior
App crashes immediately

**Comment by josmas** [comment]
Hi @MrMazzone is this happening with an app recently built? We fixed a bug affecting Samsung and Pixel devices last week (or the previous). If this happens with apps built with version 212+ any chance you can capture a log with logcat?

Also, could you please clarify, you mention s6 and s7 and also emulator; do you use a particular Samsung image for your emulator? not sure how to do that.

**Comment by MrMazzone** [comment]
Hi @josmas.  My build was older, so yesterday I rebuilt to see if there were any changes.  Then, I built a very simple app to see if it was just any Thunkable app and it was.

I setup a Genymotion emulator with Galaxy S6 and a Galaxy S7 with Android 7.0.  Crashes immediately on both.

Here is the logcat from the simple one button app I used to test if it was just Thunkable in general.  I just rebuilt it again also, just to make sure everything was up-to-date.
[Thunkable-S6-logcat.pdf](https://github.com/thunkable/thunkable-issues/files/5034272/Thunkable-S6-logcat.pdf)

**Comment by MrMazzone** [comment]
I just tested on multiple Pixel devices, they seem fine FYI.

**Comment by josmas** [comment]
Thanks for the log @MrMazzone that's very helpful. It seems to be the same issue we've already fixed:
```
8-06 06:35:02.664  2085  2085 W art     : Throwing OutOfMemoryError "Failed to allocate a 98304012 byte allocation with 6676874 free bytes and 86MB until OOM"
```
The device takes the splash screen and converts it to a bitmap so large that it cannot load it due to running out of memory. 
This was also affecting other models (specially lower end devices) and we made the splash smaller and fixed it for those, but for some reason it is now happening again on Samsung.

We'll try and optimise the image even further. And thanks also for the Genymotion tip. I haven't used it in a long time so it's time to install it again!

**Comment by MrMazzone** [comment]
Awesome.  Thanks @josmas!  Let me know when I can rebuild and test.

Yeah, I reinstalled Genymotion just for this purpose!  Glad I thought about it myself.

**Comment by weihuali0509** [comment]
@MrMazzone can you send us the apk to wei@thunkable.com and jose@thunkable.com?

**Comment by weihuali0509** [comment]
Btw, does the companion crash on the Samsung phone/emulator? @MrMazzone

**Comment by josmas** [comment]
@MrMazzone apologies for the multiple questions, but here's another one: is the app built with a PRO account? If so, it might actually be the icon you are using, that also gets used in the splash screen, that is creating the problem here.

**Comment by MrMazzone** [comment]
@weihuali0509  Sending apks in a minute.  I will also test companion. 

@josmas I did wonder if it was the icon I was user after you explained the issue, but the simple project I am sending to you and was the logcat I sen you does not have an icon image and displays made with Thunkable.

Also, yes PRO account.

**Comment by MrMazzone** [comment]
Fixed in the latest version of Thunkable.  Splash screen size was altered to work on Galaxy S6 and S7.  Tested on emulator and physical devices.  My two users with an S6 and S7 report the app is working properly.
