### ISSUE TITLE
Crash in Live on Android when adding a marker when Map.visible = false

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#634]
If you set for Map on property panel Visible to false, an error occurs when you try to execute the addMarker block

![изображение](https://user-images.githubusercontent.com/20015046/89502502-c5802a80-d7cd-11ea-9fdb-386ee5ac7bd0.png)

**Comment by domhnallohanlon** [comment]
@AlexITMan I just tried this on the latest version of Thunkable Live for Android and I can't replicate this issue. 

Can you confirm that this is working for you too?

**Comment by domhnallohanlon** [comment]
Hoping this is resolved now so @AlexITMan - please open another issue if this happens again.
