### ISSUE TITLE
High Click Count for New Preview Function

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#638]
**Is your feature request related to a problem? Please describe.**
The new preview function is very helpful. The downside is that there are an excessive number of clicks required to go from programming to preview back to programming.  Take the example of a 2 screen app. Screeen 1 is my authentication screen, screen 2 displays firebase data. Screen 1 has been completed and I am working on screen 2.  To preview the changes in my blocks for screen 2 I must:
1. Click Design
2. Click Preview
3. Actual testing of change
4. Click Edit
5. Click Screen 2 (since ending preview opens design of screen screen 1 )
6. Click Blocks 
7. resume working on blocks in screen 2 

**Describe the solution you'd like**
A smoother workflow would be
1. Click Preview (from blocks screen)
2. Actual testing of change
3. Click Edit
4. resume working on blocks in screen 2

This would seem to involve these changes:
1. Adding the edit button to the blocks screen
2. return to the original screen (vs. the first screen in the app
3. return to either blocks or design, depending on the original IDE state

**Describe alternatives you've considered**
Previously, in the live preview (or whatever it was called) an entirely new screen was spawned.  That was very convenient, because I could keep the preview screen open and simply click refresh after changing blocks or design elements. THat workflow was
1. Click on browser preview window
2. click refresh (sometimes it would refresh automatically)
3. acutal testing
4. click on IDE browser window
5. Resume editing

Having the option to open the preview in a second window would also be a great solution. That way I can see both the design (in preview) and blocks simultaneously. For more complex forms, this is much easier.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by MrMazzone** [comment]
Hi @DrTedGit 

You can click the "Live Test" button on any screen and see the same preview as the "Preview" button. 
![image](https://user-images.githubusercontent.com/40954645/89746299-f343c880-da86-11ea-912f-2c0f7ee93c98.png)

Alternatively, and this is what I do, you can click "Preview as responsive web app" in the Live Test menu and the app will open as a new tab.
![image](https://user-images.githubusercontent.com/40954645/89746346-20907680-da87-11ea-8cd4-8a19402d77e2.png)

**Comment by DrTedGit** [comment]
MrMazzone,

Thanks! I was so blinded by the new button I didn't even notice the live test button was still there!

Nonetheless, it would be nice after the preview that the IDE went back to the screen from which it was launched.
