### ISSUE TITLE
Data Source GetRow

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#639]
**Describe the solution you'd like**
Currently, to get a row from a datasource (e.g. Google Sheet) a GetValue block must be created for each column in the datasource. This requires a database/network call (super slow) for each column. This incurs a major performance it. It would be nice to be able to retrieve an entire row from the data source. Packaging the results as an object would be very convenient.

**Describe alternatives you've considered**
Described above (mulitple GetValue calls)

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

Addtional Information:
Because the DataSource performance is so slow, In almost every case, I have found it faster and easier to copy all of the data from the datasource into a firebase realtime database when running the program.

**Comment by kezb765** [comment]
Hi @DrTedGit , I also found that the data source performance is totally slow. Life could be so easy, just define a data source, display the data in a data list viewer and after clicking an entry get details from the block "get value from" in Data Sources. But the "get value block" is unusable because of lack in performance, see my issue #542

**Comment by DrTedGit** [comment]
I've developed a work-around with resonable performance, albiet block intensive.  The basic process is:

1. For each column in the data source, manually use the LIST OF VALUES block to copy the entire column into a local list
2. Use the LENGTH of one of the created lists for a COUNT WITH block and build a JSON object using the CREATE OBJECT and SET PROPERTY blocks
3. Insert the newly created object into an APP list as the last step in the loop

A few tip/hints/observations:
1. THE LIST OF VALUES block takes almost the same amount of time as the GET VALUE BLOCK regardless of the number of rows so the performance is MUCH better. I now retrieve thousands of rows in just a few second.
2. Combining more than 2 or three LIST OF VALUES blocks into a single CREATE OBJECT or SET PROERTY OF OBJECT block causes instability and crashes.
3. Building the JSON OBJECT and/or LIST in a CLOUD variable incurs a major peformance cost. If the list is more than a few rows long, it is faster to use an intermediate APP level variable, then copy it to a cloud variable when completed
4. Using the REALTIME_DB to create the CLOUD variable allows you to view the JSON in the firebase realtime db viewer, which is great for debugging.

Here is a screenshot of one example:
![blocks](https://user-images.githubusercontent.com/66176281/90761542-683dac00-e298-11ea-81a3-6593d0bca8c8.png)

**Comment by domhnallohanlon** [comment]
Hey @DrTedGit, 

Apologies for the delay following up to this - not sure if this block was available at the time, but would the `get row object` block work for your use case? 

![Screenshot 2021-03-12 at 14 06 56](https://user-images.githubusercontent.com/3117345/110950993-6f173380-833c-11eb-9b99-a018d18424c4.png)
