### ISSUE TITLE
Data Source GetValue retrieves incorrect value for second sheet in Google Sheets Document

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#640]
### Platform
IDE

### Issue/Request Origin
When using a Google Sheet with 2 sheets as a data source, GetValue block only works correctly for the first sheet. 

### Steps to Reproduce
1. Click the FIRST button and the contents of the first value in the FirstName column is populated in the textbox (A)
2. Click the LAST button and the contents of the first value in the FirstName column is populated in the text box (A). THe correct value would be (X).

The click events are identical, except the GetValue block references the second sheet in the workbook.

### Project Link
https://x.thunkable.com/copy/218120dc1055303f464ab05d223b8264 

### Data Source Link
https://docs.google.com/spreadsheets/d/1p9aikeUzYkuhGhIXRceIsWJ3mQIJg6tuBIa9XhadKp8/edit?usp=sharing

### Expected Behavior
The LAST button should retrieve the first value from the LastName column in the LAST Sheet (X)

### Actual Behavior
Execution halts with no results being displayed

**Comment by jane-d-alt** [comment]
Hi there,

This behavior appears to be resolved.

In these projects ([snap to place](https://x.thunkable.com/projects/6061f893020905001168d20a/abe49af2-7cd5-4edd-9899-41e441feca6c/designer), [drag and drop](https://x.thunkable.com/projects/6076b199e9c0ad0012188b86/148cb9ff-7730-4d59-ae2e-e6cfdde2dc99/designer)), you can view two Data Viewers, which display the first and second table respectively of a [Google Sheets Data Source](https://docs.google.com/spreadsheets/d/1fBXyjlXBhZRaJiNEf6bHzFTnPqOjsvtQN6xlwdyq1Gg/edit?usp=sharing). You can click the Button under each Data Viewer to get the first value from the first column of each table in the Data Source. These Buttons return the expected result.

We will close this issue for now. Apologies for not following up when this behavior was originally resolved. Thank you for reporting!
