### ISSUE TITLE
Slider does not rotate in web apps

### ISSUE THREAD

**Issue by Camelblack** [thunkable/thunkable-issues#643]
### Platform
Thunkable ✕

### Issue/Request Origin
Web apps

### Steps to Reproduce
1. Add slider
2. Transform
3. RotateZ, add value "1.57079632679"

### Project Link
https://thunk.app/w/bJ8W2rsOg
https://x.thunkable.com/copy/633a65ca87b03ef098f154d6db931ae1

### Expected Behavior
Slider to rotate in web apps

### Actual Behavior
Slider will now rotate in live previewer on phones, but not in web apps

**Comment by josmas** [comment]
Thanks for your report @Camelblack 

@TingC any idea if the advanced properties work on web? in the project above, look at `advanced --> Transform`. On devices the slider appears vertically with the transform. Thanks!

**Comment by TingC** [comment]
I'll take a look, thanks for reporting!
