### ISSUE TITLE
Severe Bugs appear when the app is built

### ISSUE THREAD

**Issue by Antoriccio9** [thunkable/thunkable-issues#644]
The same app Built or Live tested has different behaviors.

If I live-test the app it is able to read the database and works properly, even if the graphics are messy (this is another problem)

When I click on Menu, the orange tiles appear ( everything works)

LIVE TEST IMAGE BEFORE PRESSING THE BUTTON: 
<img width="352" alt="Screenshot 2020-08-04 at 19 36 11" src="https://user-images.githubusercontent.com/62944705/90889504-fca32e00-e3c0-11ea-864e-b7cdb555631d.png">

LIVE TEST IMAGE AFTER PRESSING THE BUTTON: 
<img width="317" alt="Screenshot 2020-08-04 at 19 36 21" src="https://user-images.githubusercontent.com/62944705/90888159-6110be00-e3be-11ea-981f-0ef88d3610e5.png">

if I do it on the Phone with the app built it seems unable to read the database to create the orange tiles.
BUILT APP IMAGE BEFORE PRESSING THE BUTTON: 
(The graphics are as they should be) 
<img width="267" alt="Screenshot 2020-08-21 at 15 15 37" src="https://user-images.githubusercontent.com/62944705/90889651-35430780-e3c1-11ea-861b-617cd32bc123.png">

 BUILT APP IMAGE AFTERPRESSING THE BUTTON: 
<img width="305" alt="Screenshot 2020-08-21 at 15 15 25" src="https://user-images.githubusercontent.com/62944705/90889675-40963300-e3c1-11ea-9a7f-83746f525604.png">

I ran different tests and I'm 100% sure that the app is able to read the database and that the variable that creates the tiles is filled up with the right values but the orange tiles still do not appear. 
PS The orange tiles are created using a clone function

Thank you

**Comment by domhnallohanlon** [comment]
Hey @Antoriccio9  - can you send us a project link so that we can try and reproduce this behaviour on our end? 

Thanks!
