### ISSUE TITLE
Data Viewer List crashes app

### ISSUE THREAD

**Issue by nbeerten** [thunkable/thunkable-issues#646]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Thunkable ✕, On companian and in app download

### Issue/Request Origin
I'm sorry, I dont understand this question.

### Steps to Reproduce
1. Use a Data Viewer List block.
2. Swipe to the left from the right side, no matter if "Left Swipe" is turned on, the app crashes.
3.

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

https://x.thunkable.com/projects/5f428035b8123f858aa33505/9c9a75d8-08b7-41e2-ad63-ae9fbeaad3b6/designer

(May find a alternative soon?
### Expected Behavior
To not crash (duh)

### Actual Behavior
The app crashes (as told above)

  STACK TRACE AND/OR SCREENSHOTS

![image](https://user-images.githubusercontent.com/59444993/91022287-41afa600-e5f5-11ea-86c0-7c703964cf4e.png)
![image](https://user-images.githubusercontent.com/59444993/91022316-4bd1a480-e5f5-11ea-8411-101b37cbc33c.png)

**Comment by josmas** [comment]
Hi @nbeerten thanks for your report. Can you reproduce with this simple project? https://x.thunkable.com/copy/665cf84d87dc800dfac672af9a2071b5

I am trying swiping left to right and nothing happens. If you can reproduce with the project above, can you please share more details about your setup (device platform, model , OS version and so forth)? Also please share more detailed instructions about how to reproduce. Thanks!

**Comment by nbeerten** [comment]
So, lets start. Im using a Nokia 5, with android pie. I do have a click action on the Data Viewer.

I did try to reproduce but i cant get it bugging again, so im slightly confused.
The screen has: 
- 2 Tabs
- Click actions on all of the Data List tiles (Click to open alert)
- Left And Right Swipe disabled, was enabled in the past.

The bug accured when im swiping FROM right TO left.

Here is a screenshot of the app: 

![image](https://user-images.githubusercontent.com/59444993/91035078-4f215c00-e606-11ea-8619-f4179a4762d2.png)

**Comment by nbeerten** [comment]
https://photos.app.goo.gl/4RZFEHdEmLovkFjWA

A video. I am swiping from the right to the left on the data viewer tile. Project: 
https://x.thunkable.com/projects/5f428035b8123f858aa33505/9c9a75d8-08b7-41e2-ad63-ae9fbeaad3b6/

**Comment by josmas** [comment]
hi @nbeerten but is the bug happening with the data viewer or the Tabs? what kind of navigator are you using?

**Comment by nbeerten** [comment]
> hi @nbeerten but is the bug happening with the data viewer or the Tabs? what kind of navigator are you using?

Guess its happening by the combination of them. I cant tell and dont have the time to test either. 

I am using "Top Bar Navigator". As seen in the video. Just watch it.

**Comment by jane-d-alt** [comment]
This behavior could not be replicated when testing a Data Viewer List in a Top Tab Navigator. We will close this issue now.
