### ISSUE TITLE
Bug when using emojis in Label

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#649]
When start a project using a link on my Android 9, an empty field is formed after the cyclist char instead of cells. This bug is not present if the cyclist character is set closer to the beginning of the string.

https://x.thunkable.com/projects/5f4bea11abec44ccde589500/project/properties/designer/

**Comment by domhnallohanlon** [comment]
Hey @AlexITMan - this is what it looks like in web preview for me. 

![Screenshot 2021-03-19 at 14 11 24](https://user-images.githubusercontent.com/3117345/111793261-ff192800-88bc-11eb-8167-e969e39dc756.png)

What is it supposed to look like?

**Comment by domhnallohanlon** [comment]
@AlexITMan going to close this one now as I think it's working correctly. 

Let me know if there are any issues on your end. 

Thanks!
