### ISSUE TITLE
In Drag&Drop mode, the canvas is not displayed and the components are not set to the specified X and Y coordinates on Android Live

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#653]

**Comment by domhnallohanlon** [comment]
Hey @AlexITMan we shipped a huge update for DnD yesterday - can you take a look and let me know if this is still an issue for you?

**Comment by domhnallohanlon** [comment]
@AlexITMan - going to close this one out too. The canvas component works fine and the issue with how positioning works (https://github.com/thunkable/thunkable-issues/issues/880) (i.e. centre or top left corner) is being worked on.
