### ISSUE TITLE
Duplicating Project does not copy AirTables

### ISSUE THREAD

**Issue by MrTwoCanes** [thunkable/thunkable-issues#655]
Thunkable X

Duplicating Project does not copy AirTables

### Steps to Reproduce
1.  Duplicate Project that has AirTables
2.  Duplicate Copy has no AirTables
3.  A few Tables leak thru as Data Source Thunkable Tables
4.  All cells of those tables say "Thunkable"

### Project Link
https://x.thunkable.com/projects/5f4967f43313e4debddcb87e/3eba1be8-e3d4-4e65-950f-1d48144656f6/designer
https://x.thunkable.com/projects/5f51defcf21990e5364928a4/3eba1be8-e3d4-4e65-950f-1d48144656f6/designer

Exact copies of my AirTable tables.

### Actual Behavior
Only half the tables come across with dummy data.

![Screenshot from 2020-09-03 23-34-49](https://user-images.githubusercontent.com/67872003/92207577-533b4e00-ee3e-11ea-8f62-e61e5b7b8082.png)

![Screenshot from 2020-09-03 23-34-04](https://user-images.githubusercontent.com/67872003/92207572-4d456d00-ee3e-11ea-83e4-eb984d380f71.png)

**Comment by josmas** [comment]
closing this as it is being discussed in https://github.com/thunkable/thunkable-issues/issues/654

**Comment by MrTwoCanes** [comment]
You closed 655 cuz of 654.  Then you closed 654 as well.  Now I have no recourse but to open another ticket?

**Comment by josmas** [comment]
@MrTwoCanes as far as I can see #654 is not closed.
