### ISSUE TITLE
Slider properties are giving different results in web app and android device

### ISSUE THREAD

**Issue by hskit** [thunkable/thunkable-issues#659]
I have added MaximumTrackTintColor and Visible properties in the app, they are perfectly working in web app, but in the android device none of those properties are working. 

MaximumTrackTintColor, never changes, it stays the default color and when I tried to hide slider it leaves the thumb circle on the top left corner in android device test. 

Note: I have also tried to put slider in row/column and changed visibility to false on click, but that hack doesn't work either. 

### Platform
Thunkable ✕ (issue found only in android device so far)

### Steps to Reproduce
Please mirror your android device using live test in thunkable X, and then re-run the same test in web app. 

### Project Link
https://x.thunkable.com/copy/6fd4f2b29467198c506609bb5a0e52cb

### Expected Behavior
Must be similar or at least close enough.

**Comment by domhnallohanlon** [comment]
@hskit sorry for the delay getting back to you - I tried to open your link there but unfortunately it has expired. 

Would you mind sending a new one? 

Thanks!
