### ISSUE TITLE
Images fail to be deleted and also impossible to upload an image that existed earlier

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#663]
In one of my apps I suddenly can neither delete images (well at least most of them) nor can I upload an image, that was uploaded before but renamed. I will always just get error messages. It's no fun working with Thunkable at all at the moment... Slow, unresponsive and running into failures all the time...

![Thunkable_image_fail](https://user-images.githubusercontent.com/37402054/93889143-236ac200-fce9-11ea-843d-687557b076bf.gif)

**Comment by gre4twh1te** [comment]
Update: I cannot even upload completely new images/files... really bad!

**Comment by TingC** [comment]
Thanks for providing the project link. Issues of uploading and deleting assets in that project should be fixed now. If you're still experiencing issues, please let me know.

**Comment by jane-d-alt** [comment]
Given lack of follow-up here, we will assume that Ting's fix resolved this behavior in this project. Please follow up with a member of the team if you see this behavior in other apps. Please re-open this GitHub issue if this behavior persists in this app.
