### ISSUE TITLE
Extremely slow and unresponsive

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#664]
I don't know what has changed but recently Thunkable is extremely bad to use... It is really annoyingly slow, often becomes unresponsive, items cannot be dragged properly a lot of the times (specially in Chrome) and the companion barely updates... Really no fun to work on projects that way... I also paused my Pro plan because I am barely able to seriously work on any project this way...

**Comment by josmas** [comment]
Hi @gre4twh1te is this happening on a particularly large project or just for anything, even brand new ones?

**Comment by stanis14** [comment]
For me it is on a large project

**Comment by MrMazzone** [comment]
Yesterday, I have a handful of students experience this.  It was a new project, so not large at all.

**Comment by josmas** [comment]
All, apologies for this; we have now increased our server capacity by 50% and we'll be keeping and eye on it.
We have also started separating our backend infra into smaller, more manageable pieces, which might make a bigger impact than increasing capacity, but these changes are still a few weeks away from hitting production. We'll keep you posted.

**Comment by jane-d-alt** [comment]
As this issue was addressed directly at the time, and measures are consistently being made to made using Thunkable a faster, smoother experience, we will close this issue for now. Thanks to all who contributed. Please reach out if you have any other questions or feedback for us regarding this issue.
