### ISSUE TITLE
Blank screen whenever companion runs into an issue with non-existing object

### ISSUE THREAD

**Issue by gre4twh1te** [thunkable/thunkable-issues#665]
Whenever I change something related to objects, the companion will always crash in a blank screen when it updates while you stick certain blocks together. I guess it is e.g. because it might run into a non-existing object when not all blocks are yet connected properly... However I think there must be a better way to handle/catch these kind of errors than a total blank screen with no other way to exit/continue than completely restarting the companion?

**Comment by josmas** [comment]
Thanks for the report, @gre4twh1te 
We'll look into ways to better handle object issues.

**Comment by jane-d-alt** [comment]
Hi again,
We have not been able to reproduce this behavior, so we currently believe it to be resolved. We will close this issue for now.
If you encounter this behavior again, feel free to re-open this issue or create a new issue. Thanks!
