### ISSUE TITLE
Data Source crashes the app

### ISSUE THREAD

**Issue by A01750170** [thunkable/thunkable-issues#667]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Thunkable X

### Issue/Request Origin
Community

### Steps to Reproduce
 I’ve written a simple app to test creating, viewing and deleting rows and found out:

everything works as expected now. I am able to create some rows, I can delete a single row or I can delete all rows.
then I switch to screen2 where a data viewer list resides. It uses the local data source and it displays the local datasource correctly (green button “View Data”)
but when I go back to the first screen, every operation on the local datasource (create, delete) crashes the app
I can reproduce this behaviour on preview, iOS live companion and Android live companion.

I looks like the data viewer list takes a grip on the local datasource on first view and then prevents further changes to it. Here is my sample project:

### Project Link
https://x.thunkable.com/projects/5f59e082c22d07967782afad/project/properties/designer/

### Expected Behavior
I expect the app not to crash and to update the table succesfully.

### Actual Behavior
A blank screen appears and the app crashes.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by StevenPurn** [comment]
Hi @A01750170, thanks for letting us know about this issue. I _believe_ this might be fixed with an update we pushed recently. Can you please verify that you are on Thunkable Live app version 222 or higher? If not, can you please update, try again, and let us know if you're still seeing the issue?

**Comment by jane-d-alt** [comment]
This behavior seems to have been resolved in September, as observed by Steve at the time. Please re-open this issue if this behavior persists.
