### ISSUE TITLE
Published Web Apps Are Down

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#668]
@josmas Published web apps are not loading for all of my projects.  HELP!

**Comment by josmas** [comment]
hey @MrMazzone we are looking into it. Seems like a number of our servers all restarted at once and some parts are unavailable. We'll keep you posted.

**Comment by josmas** [comment]
@MrMazzone web apps should be back; might need a hard refresh. Let us know if you can see any issues still. Thanks!

**Comment by MrMazzone** [comment]
@josmas They are back!  Thank you!
