### ISSUE TITLE
Important Features request

### ISSUE THREAD

**Issue by khalidalmannai** [thunkable/thunkable-issues#669]
Hi,

It would be nice to add the most important packages that are available in most app builders like react native and other such as:

1. Contacts to read user contacts
2. Client Side Audio & video call support such as WebRTC
3. Bluetooth 
4. Push notifications
5. Facebook, GitHub, Google etc.. login page associated with firebase or such provider 
6. Payment feature such as pay pall 
7.  Social Integration such as Twitter post etc..

Most of these features -if not all- are available in android and iOS..

Regards,

**Comment by jane-d-alt** [comment]
Please make separate feature requests for each feature you would like to see in Thunkable.
Please note that Thunkable does have Bluetooth and Push Notifications components.
