### ISSUE TITLE
Web app a lot faster then android or IOS app

### ISSUE THREAD

**Issue by stanis14** [thunkable/thunkable-issues#670]
I'm always frustrated when I load my project on web app everything load and react so fast and when I download the app on my phone or use the companion it is 10 times slower to load pages execute code react when I press buttons ect..

Is it possible to make android app and IOS app as fast as the web app or faster then it is now ?

A lot of time is spent thinking about workarounds in how to make things faster 

Talking about Thunkable ✕ 

To execute the code at the beginning of my big project I need 1 or 2 sec on the web app and 10 to 15sec on the phone with companion ; IOS app or Android App.

**Comment by jane-d-alt** [comment]
Hi there,

We are constantly working on making apps as fast as possible on all devices.
However, it is worth noting that your computer is almost certainly more powerful than your mobile device(s), and will therefore execute an identical program such as a Thunkable app more quickly.

There's not a lot we can act on here, so I'm going to close this issue. If you have a specific app which you think has a longer load time than it should, then you are encouraged to contact support or post in the Community about it. Thanks!
