### ISSUE TITLE
Add the Ability to change the datasource and the table name through the use of code blocks.

### ISSUE THREAD

**Issue by SupermanBritt** [thunkable/thunkable-issues#671]
Currently I have to create a new data list for each table and spreadsheet which cause lag in my app as well as it to crash. The ability to change the datasource and the data table would give me the ability to make my app work again. I have looked at the available blocks that concern the data lists and the datasources and there are no blocks currently that let me change the datasource and table name through blocks. I am asking for this to be added to Thunkable X to allow for my app to work without lag and to be able to easily change what data I am setting a data list to without having to create a new data list for every datasource and every different table.

**Comment by pippawilder** [comment]
I want a data viewer list to e dynamic to change sources seems like blocks could be used to make this possible, but nope. Datasource is hard coded in the gui of the data viewer list. Please make it changeable in blocks.

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. We will close this issue as it overlaps with #541 and #599. We are aware of community interest in this feature and hope to start working on it soon.
