### ISSUE TITLE
Custom Data Viewer create row doesn't update local db

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#672]
# Platform
Thunkable X

### Steps to Reproduce
See sections below and screenshot.

### Project Link
https://x.thunkable.com/copy/f2f902c52340fca51d840f3512b25932

### Expected Behavior
I expect that when I create a new row, the local database will display that row if I edit the database. The initial database "temp" has four rows of data.

### Actual Behavior
A new row gets added in the preview (e.g. if I click the +/add sensor button 5 times, I see 5 new columns with "Las Vegas," etc. displayed). But when I click "Click to edit data table" it just shows the original database content. So instead of 9 rows, it shows 4, none of which contain "Las Vegas" as a city.
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="490" alt="Screen Shot 2020-09-26 at 5 47 35 PM" src="https://user-images.githubusercontent.com/10355498/94352963-a9a44280-0020-11eb-8dc0-a8f465cf70f7.png">

<img width="261" alt="Screen Shot 2020-09-26 at 5 53 20 PM" src="https://user-images.githubusercontent.com/10355498/94353022-3818c400-0021-11eb-8c7d-077f480c07ea.png">

<img width="368" alt="Screen Shot 2020-09-26 at 5 53 28 PM" src="https://user-images.githubusercontent.com/10355498/94353023-3a7b1e00-0021-11eb-99c4-b89da9e2c919.png">

**Comment by jane-d-alt** [comment]
Hi there,
As a Local Data Source is stored locally, changes made to this Data Source during app runtime will not be reflected in your Thunkable project.
Changes made to your Data Source will persist, ie. any changes you make to the Data Source will still be visible after you close and re-open the app on your device.
If you would like changes you make to the Data Source to be reflected in your original Thunkable project, please use an online Data Source such as Google Sheets or Airtable.
We will close this issue for now. Please feel free to reach out if you have any further questions or feedback on this issue.
