### ISSUE TITLE
"Local Data Source" should have an option to create new tables

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#675]
When creating a new data source you have the choice of "Create your own table" / "Airtable" / "Google Sheets".

Selecting "Create your own table" creates a local data base, and when you click on it there is one "Table1" inside:

![grafik](https://user-images.githubusercontent.com/7669660/94434370-fb240d00-0199-11eb-835a-b81de7111267.png)

I request a way (button? block?) to create **more tables** inside a local data base. And maybe an option to rename them.

**Comment by tatiang** [comment]
Yes, we need to be able to rename tables and create/delete them.

**Comment by tatiang** [comment]
Glad this is being considered... it's a shame we can't easily add a new table.
