### ISSUE TITLE
Live Test / Web App Calendar appears behind controls 

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#683]
### Platform
Thunkable X Web App / Live TEst

### Issue/Request Origin
Self Generated

### Steps to Reproduce
1.Open example app (https://x.thunkable.com/copy/8da73281448ab51b73a98c6a11d2fda7)
2. Click on second date box 
3.Resize the browser window (figure 1, calendar appears behind the shaded rows)
4. Click on the first date box (Figure 2, calendar appears behind the second date input and the swith controls)
![image](https://user-images.githubusercontent.com/66176281/95016831-5e82c480-060a-11eb-8d61-65ba10bb2f22.png)
![image](https://user-images.githubusercontent.com/66176281/95016992-7575e680-060b-11eb-9f1c-8715b7125f7e.png)

### Project Link
https://x.thunkable.com/copy/8da73281448ab51b73a98c6a11d2fda7

### Expected Behavior
Calendar appear over the cloned row
### Actual Behavior
alendar appears under the cloned row
```
  STACK TRACE AND/OR SCREENSHOTS
![image](https://user-images.githubusercontent.com/66176281/95016831-5e82c480-060a-11eb-8d61-65ba10bb2f22.png)
![image](https://user-images.githubusercontent.com/66176281/95016993-773faa00-060b-11eb-980b-776de88930e0.png)

**Comment by josmas** [comment]
Hi @DrTedGit thanks for the report.

Hey @TingC did we have this issue before? it sounds familiar but I might be wrong; any idea what is going on?

**Comment by josmas** [comment]
This should be fixed now; please let us know if that is not the case. Thanks!

**Comment by MrMazzone** [comment]
Working!  Thank you!
