### ISSUE TITLE
Publish Web App does not show changes

### ISSUE THREAD

**Issue by StefanSladdenEng** [thunkable/thunkable-issues#691]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. I made several updates to the size of buttons on screen. Including changed from PX to % in sizes 
2. When looking in Live Preview i can see changes 
3. But When publish to Web App i cannot get the updates there. 
The URL just show the same app and display of it - as it was before started to change things   

### Project Link
https://thunkable.site/web-build/index.html?webAppId=EdabfVM6 

### Expected Behavior
Updates made to the app should vi visible / displayed in webb App

### Actual Behavior
Screen remains the same as before
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/60143626/95457680-84dd9280-0971-11eb-8b7a-297ab6459189.png)

**Comment by josmas** [comment]
Hi @StefanSladdenEng did you publish your current version? Changes are not published automatically so developers can have their current production version and still work on the project.
The publish dialog has an option to publish the most current version.

**Comment by StefanSladdenEng** [comment]
Hi - Yes in fact i did several times... (as i have tried various different settings to "provoke" something to happen. No resuklt though...(i even made save as and tried in a new app project...

**Comment by josmas** [comment]
I just tried with a brand new project, adding one button first, publish, then another button and publish, and I can see the two buttons. I did have to hard refresh the browser though (ctrl + R or cmd + R). If you look at the link from an incognito browser window, do you still see the old one?

**Comment by StefanSladdenEng** [comment]
Nope did not work either way... Still problems...

**Comment by josmas** [comment]
Hey @StefanSladdenEng we've no other reports of this. If this is still happening, it might be a particular issue with your project. Can you send the link to it? If it is a private project feel free to send the link through intercom. Thanks!

**Comment by jane-d-alt** [comment]
Hi Stefan,

Were you able to resolve this behavior through email or Intercom messages?

**Comment by jane-d-alt** [comment]
Hi Stefan,

As we haven't heard from you on this topic in a few weeks, we will close this issue for now. If you have further questions regarding updating your web apps, please re-open a new issue or contact us via Intercom or the Thunkable Community. Thank you!
