### ISSUE TITLE
\n does not create newline in web apps

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#693]
### Platform
Thunkable X Web App

### Steps to Reproduce
1. Add a label component.
2. Include a ```\n``` in the label's text property
3. ```\n``` will not create a new line

### Expected Behavior
```\n``` should create a newline.  This works properly for on Android and iOS and the design preview.

### Actual Behavior
No newline is created.

**Comment by josmas** [comment]
Thanks for the report @MrMazzone 
Hey @TingC you think we could escape that sequence somehow for web? or are we doing it already?

**Comment by josmas** [comment]
This should be fixed now; please let us know if that is not the case. Thanks!

**Comment by MrMazzone** [comment]
Working!  Thank you!
