### ISSUE TITLE
Video Library & Audio Library Components

### ISSUE THREAD

**Issue by MaadhavKrishna** [thunkable/thunkable-issues#698]
Hi I Am Madhav I want To Upload all types of files into my app like we already have an image library I want video, audio, document, and other types of libraries to upload.

I want to have components that can upload all types of files and I want to specify that he should only upload an image or only video or only audio or only document for that you can add a dropdown for the type of file to be uploaded in the blocks of that component.

I Want all the components inside thunkable x that were in thunkable classic.

Thank You

**Comment by josmas** [comment]
Hi there, you can currently use [Media DB (Cloudinary)](https://docs.thunkable.com/media-db) to manage assets.
We will be adding some more components to X but prioritising things that cannot currently be done in some other way, like it's the case for this. Thanks for your request!

**Comment by MaadhavKrishna** [comment]
but I want to upload files like videos, docs, and audios from the phone's storage like the [Photo Library](https://docs.thunkable.com/photo-library) component in which we can upload photos from storage I want a video library, audio library, and documents library

**Comment by MaadhavKrishna** [comment]
> Hi there, you can currently use [Media DB (Cloudinary)](https://docs.thunkable.com/media-db) to manage assets.
> We will be adding some more components to X but prioritising things that cannot currently be done in some other way, like it's the case for this. Thanks for your request!

but I want to upload files like videos, docs, and audios from the phone's storage like the [Photo Library](https://docs.thunkable.com/photo-library) component in which we can upload photos from storage I want a video library, audio library, and documents library
