### ISSUE TITLE
Suspected error: switching in a bottom tab navigator to a map slows down extremely the second time.

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#702]
My app has a bottom tab navigator and 5 screens. One of them contains a map component, and the screen.open triggers a loop to display approx. 20 markers. Switching from the home-screen to the "map"-screen displays the markers in a fraction of a second, but only at the first time. Switching back to "home" is also fast, but when switching to the "map" for the second time it slows down to approx 30 seconds before dispalying the screen.

This can be found in all environments: live test app iOS / Android, downloaded app on iOS and Android. I checked with a simple system monitor: during switching from "home" to "map" all CPUs go up to their maximum speed, so there must be something going on during the 30 seconds, but what and why, and how could this be solved? Maybe I've done something wrong but I don't know what. At the beginning of creating the app everything worked fine.

I wrote a new test-app with a bottom tab nav and 4 screens, here it works always as fast as expected.

I suspect an internal error, could some thunkable expert have a look into my app? Here is the link (it is not a public app because of API key):
https://x.thunkable.com/projects/5f5e760a33142a592fcc5321/project/properties/designer/

**Comment by DrTedGit** [comment]
I have found the TOPT tab causes all screens to load simultaneously.  That could account for the tremedous lag you are experiencing.  https://community.thunkable.com/t/start-event-timing-for-tab-and-drawer-navigators/953880?u=drted
