### ISSUE TITLE
How to set up a Listener for a FireBase node protected by rules

### ISSUE THREAD

**Issue by MartinHerraizH** [thunkable/thunkable-issues#705]
How can I set up a Listener for a FireBase node with access restricted by read rules?
Kind of adding "?auth=<ID_TOKEN>"" like in authenticating a REST request?

If so, How can I fetch the IdToken given by auth when signin in?

**Comment by josmas** [comment]
Hi @MartinHerraizH this kind of questions will get more attention in the [community](https://community.thunkable.com/). Please include more information about what you are trying to do, though. Are you using the Web API component to talk to Firebase? How the restricted access was setup is also important to know.

**Comment by jane-d-alt** [comment]
We hope you got the information you were looking for in the Community! We will close this issue now as it is neither a bug report nor a feature request.
