### ISSUE TITLE
Manage "My Projects" list in Thunkable Live

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#707]
**Is your feature request related to a problem? Please describe.**
I have a long list of projects in Thunkable Live. And because I save multiple versions of projects while testing them, about 50 of them are named the same thing (since the project name is longer than the list viewer width).

**Describe the solution you'd like**
There should be a way to delete individual projects from the list. There should also be a way to clear the entire list of projects.

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable Live app, iOS

**Additional context**

![IMG_0568](https://user-images.githubusercontent.com/10355498/96346689-05774f80-1052-11eb-8640-9a94fa13f5bc.PNG)

**Comment by josmas** [comment]
Hi @tatiang I completely agree with you on this one.
I would also like to make the tutorials list collapsible, as it is taking center stage and it's rarely used by medium/advanced users. I'll add it to the list, but cannot give it much of a priority at the moment. Thanks!

**Comment by kezb765** [comment]
Hi everybody,

this is a feature I adore for a long time now. I just discovered that the sorting of my projects changed (I didn't do anything) so my most recent projects are at the top at the list. This is very nice!

Next enhancement would be to have an option to disable/hide the tutorials. In my >3 years of thunking I never used them.

**Comment by josmas** [comment]
We fixed the sorting last week and we have a chage in testing to collapse the tutorials.

The original request here is a bit more complex though, because the app basically shows the same list that exists on web.
We cannot `delete` projects as such, as they would also get deleted on web, so we need to figure out a way to `hide` them instead. This means we need to come up with a way to revert that hidden state. So anyway, this needs a bit of though.

**Comment by StevenPurn** [comment]
Quick question on the use case here. What is the criteria you use to determine that you want to keep the project in your account but don't want it to show in the list on the companion app? I guess I'm wondering what the logic is simply to help us figure out the best way to implement the change. I know I personally just initiate live testing via my browser 95+% of the time so I don't have a good perspective on this.

**Comment by tatiang** [comment]
I find it useful to "carry around" a few demos to share with people. It's only on my single device but it's nice to whip out my phone and say -- "hey, here are a couple of apps I'm working on." I realize I could do that by publishing as web apps but there are differences and Thunkable Live is useful apart from web apps. 

Mainly, though, I tend to save multiple versions of each project as I work. So I'll have MyGreatApp1, MyGreatApp2, ... MyGreatApp12 and by the time I've made those saves in one day and tested them, I've cluttered Thunkable live so badly that I can't even find the version I want to check again. That's assuming that I work on multiple apps, which I do. So if I have 4 apps times 12 versions (or whatever), ... hopefully you can see why hiding/deleting some might be useful to me.

**Comment by kezb765** [comment]
Hi all,

big thanks to the Thunkable team: in live companion 243-05 (iOS and Android) the "Tutorials" section is now collapsed, and the "Projects" section sorts the most recently used to the top. Fabulous!

**Comment by tatiang** [comment]
This is SO much better! Thank you, Thunkable staff!

**Comment by weihuali0509** [comment]
kudos to @josmas !

**Comment by jane-d-alt** [comment]
Thanks for contributing to this discussion, everyone! Since Tatian and kezb765 seem happy with the changes made to the Thunkable Live app at the time, we'll close this issue for now.

**Comment by tatiang** [comment]
It's better... yes... but I still would like to be able to:

> There should be a way to delete individual projects from the list. There should also be a way to clear the entire list of projects.
