### ISSUE TITLE
(Thunkable Live X) Shaking (repainting) of images during timer operation or slider motion

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#71]
Shaking (repainting) of images on iOS and Android during timer operation or slider motion

https://x.thunkable.com/projects/5b712d5880721d04a944e9db/project/properties/designer/

**Comment by fishish1** [comment]
I'm having this issue too. Trying to fight it with better layouts (using relative sizing) but it's a struggle.

**Comment by AlexITMan** [comment]
The workaround is to use other components that can display an image instead of Image - сolumn, row, button.

**Comment by jane-d-alt** [comment]
This behavior was resolved shortly after reporting. We'll close this issue; apologies for not following up when this was originally resolved.
