### ISSUE TITLE
Control photo quality

### ISSUE THREAD

**Issue by jaredgibb** [thunkable/thunkable-issues#710]
**Is your feature request related to a problem? Please describe.**
I am frustrated that each image I send to cloudinary is <4mb often. this is due to the phone i am using. this results in a lot of bandwith usage with cloudinary and having to resize images to compress them for network transfer

**Describe the solution you'd like**
I would like to be able to control resolution/image quality when uploading/taking photos. this is possible when sending a photo from the iphone but not while taking the photo. 

**Describe alternatives you've considered**
Currently i resize all photos using the cloudinary api. this results in compression from 4mb to 50kb

**Which platform are you asking for?**
ThunkableX

**Comment by AmigoDeluxe** [comment]
Duplicate request? https://github.com/thunkable/thunkable-issues/issues/224

**Comment by jaredgibb** [comment]
Hey @josmas. I wonder if your team has had a chance to talk about this one? I’d ao, any news?

**Comment by josmas** [comment]
this is indeed a Duplicate of #224
There's more info there so closing down this one. Please follow discussion there.
