### ISSUE TITLE
When I Delete Canvas Its White Screen

### ISSUE THREAD

**Issue by SonicFreddyGT** [thunkable/thunkable-issues#712]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
When I want to delete the sprite in canvas its glitch out turn my sreen in to white and I can't even do anything I have to exit only.

The more info, the faster we will be able to address it!

### Platform
On site while programming

### Issue/Request Origin
My self

### Project Link
https://x.thunkable.com/copy/973864ec7f6edfd38aae0e1402c3b2f5

### Expected Behavior
Fix this glitch

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
``` 

[White Screen Glitch.zip](https://github.com/thunkable/thunkable-issues/files/5409369/White.Screen.Glitch.zip)

**Comment by josmas** [comment]
Thanks for the report @SonicFreddyGT 
we will look into it

**Comment by josmas** [comment]
This should be fixed in out next release in a couple of days. thanks!
