### ISSUE TITLE
Airtable access works, but needs a delay-time to avoid crash

### ISSUE THREAD

**Issue by migo4Huuub** [thunkable/thunkable-issues#713]
### Platform
Thunkable-X

### Issue/Request Origin
At several passages in my app I read data from airtable tables. I have noticed several times that I have to pause after reading the data in order to keep the app running correctly. Up to now I have created workarounds by adding wait seconds. But I think it is a bug.
To demonstrate it I created a separate mini app that does nothing else than reading the airtable table and checking if a certain email address is in it. If so, a boolean variable is set to true and the three values (default email, airtable email and the boolean variable) are displayed on the screen.

### Steps to Reproduce

This is my test-screen, very simple:

![grafik](https://user-images.githubusercontent.com/72560309/96603614-7a69b400-12f4-11eb-8270-c762dd1543b4.png)

**Example 1:** Original-Code, will reproduce crash:
![grafik](https://user-images.githubusercontent.com/72560309/96603730-94a39200-12f4-11eb-8fed-30455f1d42ca.png)

**Result of test: White, blank screen, nothing on it, app obviously crashed.**

##########################################

**Example 2:** Same code **with a 1-second-wait**:
![grafik](https://user-images.githubusercontent.com/72560309/96604022-e9470d00-12f4-11eb-811b-4759c269fef3.png)

Result of test:
![grafik](https://user-images.githubusercontent.com/72560309/96604213-214e5000-12f5-11eb-8b36-164dea41a0d7.png)

### Expected Behavior
App should display the results without the waiting workaround.

**Comment by josmas** [comment]
Hi @migo4Huuub you need to put your labels that use the values read inside the `then do` block for airtable.

The call to get rows is asynchronous, so you have to wait for the values to be back if you want to use them.
What is happening in your code is that the call to rows will take a while to complete, and the label blocks will execute before your have your values back. That is why if you give it time to complete (with a wait) you will get the values.
Move your label blocks right after your `for each` and that should solve your issue with not wait blocks needed.

**Comment by josmas** [comment]
closing for now; let us know if that solves the issue.

**Comment by migo4Huuub** [comment]
Yep, that helped me a lot! I did not realize that the process was asynchronous. I have now adjusted my reading routines accordingly and my problem is solved. Many thanks!
