### ISSUE TITLE
Live Test (Web) calls to API are encrypted even if the API_URL is http://

### ISSUE THREAD

**Issue by gnoshme** [thunkable/thunkable-issues#714]
### Platform
X - Specifically the Live View (Web) version

### Issue/Request Origin
Discovered as I develop.  I'm building an app and api at the same time so poking a hole through my firewall for to get to my dev box which is running puma.  

### Steps to Reproduce
1. Create an app to call any API on http (not https) 
2. Click Live Test
3. It won't work (generates Invalid HTTP format error)
4. Click Live Test, link phone
5. It will work on the phone

### Project Link
App is private. 

### Expected Behavior
It works fine with Live Test using the phone which correctly interprets how to communicate with an http uri.

### Actual Behavior
If you have access to the server logs you'll see some message about Invalid HTTP Format.  I did with attempts for both puma and thin.  Here is the puma error:

2020-10-22 10:14:52 -0600: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>

**Comment by josmas** [comment]
Have you considered using a tool like https://ngrok.com/ so you don't have to mess with your firewall and you can get both http and https while developing?

**Comment by jane-d-alt** [comment]
Hi there,

An update was made to the platform on April 13, 2021 to allow HTTP traffic over API on Android. Apologies for not following up when this behavior was originally resolved. Thanks for reporting!

**Comment by tatiang** [comment]
It seems like this issue persists. When previewed in a browser, API calls appear to use https:// regardless of the URL. When previewed on an iPhone, API calls use http:// or https:// depending on the url.

See https://community.thunkable.com/t/api-json-tutorial-video/1140575/31 and the comments that follow it.
