### ISSUE TITLE
Feature Request: Allow upload of custom OTF/TTF fonts 

### ISSUE THREAD

**Issue by youshau** [thunkable/thunkable-issues#716]
**Is your feature request related to a problem? Please describe.**
I am looking to create an app using a language for which both android/iOS system does not yet support any native font. Therefore, I need to upload a custom .otf/.ttf font file in order to set that font to work properly. 

**Describe the solution you'd like**
I have done this in numerous occasions on web and you can see this font being implemented on this website (https://voice.mv) 

**Describe alternatives you've considered**
I could think of any alternatives to get the font to work without the proper font file being uploaded. 

**Which platform are you asking for?**
I am using Thunkable X. I want it to adpot this feature previously possible under thunkable classic

**Comment by Oreldad** [comment]
upvoting

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. As this covers the same topic as issue #181, we're going to close this issue. We are actually working on the ability to upload font files to Labels and Buttons right now!
