### ISSUE TITLE
Column with Height Fit Contents Displays switch controls on  top of each other 

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#723]
### Platform
Android companion

### Issue/Request Origin
self

### Steps to Reproduce
IF the column height is set to fit contents, the controls all stack on top of each other.  If the column height is set to Fill container, the controls display correctly
![image](https://user-images.githubusercontent.com/66176281/97289119-ffc4fb00-1803-11eb-9155-b4c20c021829.png)

### Project Link
https://x.thunkable.com/copy/d2ecac319eab19e663c8bf20b32a8f60
go to the HELP screen and use dialog buttons to get to the third screen.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
![image](https://user-images.githubusercontent.com/66176281/97288876-b1176100-1803-11eb-8934-9c6117878641.png)

**Comment by jane-d-alt** [comment]
Hi there,

This behavior was resolved shortly after reporting. Apologies for not following up at the time. Thank you for your report!
