### ISSUE TITLE
The app load two time

### ISSUE THREAD

**Issue by stanis14** [thunkable/thunkable-issues#724]
Platform : ✕ 

Issue Origin : The issue appear when starting de the app once downloaded and installed on the phone , when refreshing the companion with "live test"

Steps to Reproduce :
1. Start the app

Project Link : 

https://x.thunkable.com/projects/5f74b250b1ddb477a2793ecb/d6e54a48-d95c-4cb6-a083-8903fe1fe08c/designer

Also other people are talking about it on Thunable community :

https://community.thunkable.com/t/splash-page-opens-twice-on-downloaded-app-on-ios/833717

Expected Behavior : Not double loading the app

Actual Behavior : The app load two time

**Comment by kezb765** [comment]
Yes, I also discovered this behaviour. 

My workaround is: initialise an app variable to zero and count up by one in the block "when screen1 starts". Only do your init-stuff when the variable is zero otherwise you know that you are in the second "startup" and skip it. Not nice but right now the only way I found to prevent this error.

**Comment by AmigoDeluxe** [comment]
Nice. Now we need a proper fix.

**Comment by tatiang** [comment]
We really need a fix for this. It would be great to know what the timeline is for a resolution.

It's hard to trust your own coding when the screen opens twice instead of once. It can create all sorts of unpredictable variable and conditional states within a project.

**Comment by camtez** [comment]
I'm having the same issue with my downloaded apps, sometimes the first screen loads three times, which is a really embarrassing glitch for any new user. It also seems to be crashing my app in other ways (as none of this happens in the Live app).

**Comment by rogergrajalesg** [comment]
Same here, i use a timer for start the actions on my app, but still is a bad experience for the final users.

**Comment by jane-d-alt** [comment]
Hi there,

This behavior has been resolved. Apologies for not following up here when this fix was originally implemented. Please reach out if you have any other projects which still demonstrate this behavior. Thanks for reporting!
