### ISSUE TITLE
Paying down technical debt

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#729]
Thunakble appears to be  a [perpetual beta application](https://en.wikipedia.org/wiki/Perpetual_beta), as evidenced by the plethora of unresolved bug report in GitHub as well as the notes in the documentation that some features only work on some platforms.

I would REALLY like to see a concerted effor to pay down the [technical debt](https://www.bmc.com/blogs/technical-debt-explained-the-complete-guide-to-understanding-and-dealing-with-technical-debt/). It is incredibly discouraging to step away from thunkable for a week and discover that my apps no longer work due to some undocumented refactoring. Stability is essential for a commercial product.

As I have said many times.  I think Thunkable has the potential to be an industry changing applications.  But until is is a stable platform, it is hard to justify making it a mission critical system.

**Comment by rem708** [comment]
I too have to agree completely here. I saw the potential in this product but have been very disappointed in missing basic features and the constant bug fixes that breaks modules. The fees for the pro version is three times higher than that of Microsoft Office 365 so I would expect a premium product. I expect the churn on people using this product is huge.
Lets get the basics addressed first before adding 'limited' new features.
In the real world the way bugs are fixed is just not acceptable. I've spent the last 40+ years in the industry, coding and largely bug fixing. Writing code that is cross platform compatible is always going to be at task especially when the platforms keep changing goal posts.

**Comment by amblemind** [comment]
@DrTedGit 100% agree.

**Comment by realmisterfish** [comment]
1000% agree. There's been an unresolved video element bug for 10+ months that I wasn't able to get resolved even as a Pro user.

**Comment by camtez** [comment]
Thunkable, would love your input on this. I have run into too many bugs to count. How you think anyone could publish an acceptably functioning app on an App Store with your platform is beyond me.

**Comment by realmisterfish** [comment]
Posting so other people know that emailing support doesn't get you anywhere either. It's been nearly a year now and I regret choosing Thunkable for this project. Unfortunate because they have a ton of potential as a platform

**Comment by andykiang** [comment]
Over the past six months, we've been focused more on addressing bugs and technical debt as well as improving stability and performance on the platform. This will continue to be a focus going forward. Please let us know if there are any specific issues that are still a concern. Thanks for your patience and continued support.
