### ISSUE TITLE
to change the background image of stage

### ISSUE THREAD

**Issue by dariocappello** [thunkable/thunkable-issues#734]
Hi. I need to change the background image of the stage from an image loaded in the project or from a photo in the gallery of the mobile phone or from a photo taken also using the same app to be dynamically changed. Right now thunkable doesn't. Can it be implemented?

I wish we could change it the same way you change the image in a picture.

**Describe alternatives you've considered**
I do not know

**Which platform are you asking for?**
 Thunkable ✕ (x.thunkable.com)

**Additional context**
I think the problem is clear

**Comment by jane-d-alt** [comment]
Hi Dario,

Thanks for this feature request. As this request overlaps with #704, we will close this request. You are welcome to comment on request #704 to indicate community interest in such a block.
