### ISSUE TITLE
The "find first occurrence of item" list block only works on strings

### ISSUE THREAD

**Issue by bromanous** [thunkable/thunkable-issues#736]
We noticed that the "find first occurrence of item" list block only works on strings and cannot search through numbers. It would be great it could work on numbers as well.

**Comment by tatiang** [comment]
It does work for numbers but you have to put a math block in for the search term. If you simply type in a number such as 15, it will be the string "15" by default.

<img width="704" alt="Screen Shot 2020-11-12 at 8 12 39 PM" src="https://user-images.githubusercontent.com/10355498/99027985-7ad82200-2523-11eb-8fa7-19f0d0c08603.png">

**Comment by bromanous** [comment]
Thank you so much. The value that we are searching for is entered by the user through the text property of the text input component. is there a way to convert a text block to a math block?

**Comment by tatiang** [comment]
Yes. Just add zero to the string value using the addition math block.

**Comment by bromanous** [comment]
Great! thank you so much!
