### ISSUE TITLE
All my webapps are down. Thunkable Outage? Status page available?

### ISSUE THREAD

**Issue by cesomaggio** [thunkable/thunkable-issues#741]
Tunkable user caminostudio.

Thunkable X is a amazing platform. I am using Thunkable to create webapps (4 at the moment). These webapps have permanent users. Since yesterday (16h ago) all my apps aren't working. Outhers Thunkable users are reporting the same. PLEASE, give me some feedback to help me restore my websapps or say something to my users. Users of my webapps are complaining a lot.

I need information when the apps are not working to find out if the problem is with the Thunkable platform or my "code". Thunkable platform have status page? I could have access to it?

Thanks

Carlos Eduardo Somaggio (caminostudio)

**Comment by MrMazzone** [comment]
My web apps seem to be up and working fine.

**Comment by josmas** [comment]
Hi @cesomaggio we are not seeing any outages on our side. A status page would be good to have, I'll add it as an enhancement for future consideration. Thanks!

**Comment by amblemind** [comment]
https://community.thunkable.com/t/thunkable-outage-any-system-changes-in-the-past-6-hours

@josmas Something is up. My app was working fine yesterday morning and then was not functional when I returned yesterday evening. Trying to isolate now.

**Comment by josmas** [comment]
We are testing cloud vars at the moment, it seems like that might be the issue. I'll report back once I know anything.

**Comment by cesomaggio** [comment]
I debugged a lot. I am having problems with app variables. I inicialize in first screen, and can´t in others.

**Comment by cesomaggio** [comment]
All my webapps crashed. All my users trying to kill me. :(

**Comment by MrMazzone** [comment]
Just as an update.  My web apps are still fully functional.  I do not use cloud variables, FYI.

**Comment by cesomaggio** [comment]
I don´t use cloud variables.

**Comment by josmas** [comment]
So cloud vars seem to be a bit slow, but they are working fine. We'll look into why, but they should not be making the app crash. @cesomaggio can you contact support with project details if you haven't done so yet?

**Comment by weihuali0509** [comment]
@cesomaggio do you still have active subscription?

**Comment by cesomaggio** [comment]
Yes. I still have active PRO subscription. A create a demo project to show the bug. https://x.thunkable.com/projectPage/5fae92e99a39fa00114ed898. 

PLEASE, roll back.

**Comment by cesomaggio** [comment]
@weihuali0509 . Guys, I really love Thunkable. With Thunkable I creating amazing webapps (learning games) to me and sharing with others my games. The unique Thunkable problem is lack of reliability, tests, more stables deploys. I'm betting on Thunkable. Thanks.

**Comment by amblemind** [comment]
Here is a demo of my example: https://x.thunkable.com/projectPage/5fae9567d779e30012990271

I stripped out as much as I could from the project. 

On my loading screen i added a wait 5 seconds after showing JSON. 
![image](https://user-images.githubusercontent.com/45864164/99084620-cf63b780-258c-11eb-8c8a-46fcfae1d829.png)
![image](https://user-images.githubusercontent.com/45864164/99084511-a8a58100-258c-11eb-89f7-3a0dbfb3b81c.png)

The it goes to the next screen and I try to show the same data but nothing...
![image](https://user-images.githubusercontent.com/45864164/99084664-dd193d00-258c-11eb-8890-6d21098ef8c3.png)
![image](https://user-images.githubusercontent.com/45864164/99084580-c1ae3200-258c-11eb-8c4c-4a3912217167.png)

**Comment by cesomaggio** [comment]
I have a 3 hour meeting to demonstrate my game (Thunkable webapp). Any chance the system is fixed by then?

**Comment by cesomaggio** [comment]
I have a meeting in 3 hours to demonstrate my game (Thunkable webapp). Any chance the system is fixed by then?

**Comment by weihuali0509** [comment]
@cesomaggio please us an email pro-support@thunkable.com with your web app id.

**Comment by cesomaggio** [comment]
Thanks

**Comment by weihuali0509** [comment]
@cesomaggio It should be fix by now. Can you confirm?

**Comment by amblemind** [comment]
My web previews are back in action. Thanks!

What's the ETA on pushing the updates to the Thunkable Live app?

**Comment by weihuali0509** [comment]
The Android one will be out shortly, while the iOS one need to wait for approval.

@amblemind can you send me an email wei@thunkable.com?

**Comment by cesomaggio** [comment]
Confirm! Working again. Thanks @weihuali0509!

**Comment by amblemind** [comment]
@weihuali0509 Any updates on iOS? I've been checking all weekend for the new version to come out. 

Can you guys make a standard practice to provide a TestFlight option when critical bugs like this happen?

**Comment by jane-d-alt** [comment]
Hi there,

As an update to the request for a status page in the original issue, Thunkable now has a status page at https://status.thunkable.com/

Since the issues with web apps were resolved at the time, we will now consider this issue resolved and close it out.
