### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by Oreldad** [thunkable/thunkable-issues#745]
Hello,

I would love to have the option to add my own fonts to my project.
(otf files). 

thunkable x

thank you

**Comment by Muaazt** [comment]
Hey @Oreldad,

Checkout this article by the Tunkable Team Regarding Fonts: https://docs.thunkable.com/fonts

Hope this helps!
-Muaaz Teladia

**Comment by Oreldad** [comment]
hey, thanks! 
I am familiar with those. 
I would love the option to upload my own fonts for languages other than English.

נest,

**Comment by kezb765** [comment]
Hi @Oreldad , did you try unicode? There are thousands of special characters, I am pretty sure that your language will be covered by unicode characters. For a starting point look here: https://en.wikipedia.org/wiki/List_of_Unicode_characters

**Comment by Oreldad** [comment]
The language is covers , but not in a nice to watch kind of way. I would prefer to have the option to add my unique own fonts if possible.

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. As this covers the same topic as issue #181, we're going to close this issue. We are actually working on the ability to upload font files to Labels and Buttons right now!
