### ISSUE TITLE
Null Variables from one screen to others 

### ISSUE THREAD

**Issue by aiasp** [thunkable/thunkable-issues#746]
Hello since 48 hours all App variables values are not passed to other screens. 

It happens on mobile versions. Not in web app and not I preview. Only in mobile Thunkable app.

It's happening also in apps that are working since September. Another user reported this problem too. I think it's a bug !

my user is info@aiasp.org

thanks for your help and your answers

Guido

**Comment by aiasp** [comment]
I've tried to use iPhone 11 and iPad but nothing . Null variable passed from one screen to one other.

**Comment by josmas** [comment]
Hi there, this is a current known bug; it has fixed in all platforms but we are waiting for Apple to approve the live test app. As soon as they do, this should work again in the released version. Thanks!

**Comment by aiasp** [comment]
Thanks to u for quick answer!

Inviato da iPhone

**Comment by tatiang** [comment]
Also mentioned in this forum thread: https://community.thunkable.com/t/global-variable-values-issues/980900/25
