### ISSUE TITLE
Datasource - create row with Airtable computed column not working

### ISSUE THREAD

**Issue by vaskarni** [thunkable/thunkable-issues#749]
When using Datasource/Dataviewer/Airtable - creating a row with Datasource block does not work when computed column is involved.

Ex. Items table has a 'boxName' which is computed from 'boxID'. The boxID is the rowid of the Box table which has boxName.
When using **create row** block from Datasource - it fails. But when an Airtable block : **in Airtable call create row** is used, it works as expected. Images attached. In the example itemURL field is a regular non-computed column and it accepts 'blank' or 'null'.

### Platform
Thunkable X

### Steps to Reproduce
1. Create Airtable tables Box (implicit rowid, boxName); Items (implicit rowid, boxID (references rowid of Box), itemName).
2. Use Datasource block create row for Box,, it works fine. Use Datasource block create row for **Items** with boxID and itemName with boxName blank (because it is computed by Airtable) - it fails. There is no error output to see what the message from Airtable is. 
3. Use Airtable block to create the row in **Items** using **in Airtable create row** with row object, it works. In this case, Airtable1 is configured with API Key, Base ID, Table name as Items, View Name as Grid view.

### Project Link
Easy to reproduce. Can provide link if needed.

### Expected Behavior
Expected a row in Items table to be created with Datasource block.

### Actual Behavior
Row creation fails. 
![DSfail](https://user-images.githubusercontent.com/60406446/99720688-f0cc1400-2a62-11eb-922d-b4387dc2761e.JPG)
![ATsuccess](https://user-images.githubusercontent.com/60406446/99720694-f4f83180-2a62-11eb-8f55-8f14ea585534.JPG)

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by tatiang** [comment]
Are your functions inside of loops?

What happens if you assign values to boxName and itemURL?

**Comment by vaskarni** [comment]
It is not inside loops.
When I assign boxName and itemURL, the row is not created in the table. No error message.

**Comment by vaskarni** [comment]
In the second case (Airtable block) when I assign the boxName it gives an error message - cannot insert because boxName is computed value. When I take it out it (as shown in image) it works. The table row is created correctly with boxName automatically populated.

**Comment by tatiang** [comment]
It should work to add a row ID that was already generated into a text field in a local data source. Row IDs are just text strings.

Can you post a screenshot of the error you're seeing?

And also the RowID value you're getting (e.g. displayed in a label)? Are you initializing the RowID variable with a value or is it just blank?

**Comment by vaskarni** [comment]
Your comment: It should work to add a row ID that was already generated into a text field in a local data source. Row IDs are just text strings.
Response: Not sure what you mean. The rowid is a text string generated by Airtable when a row is created : in this case I am using the rowid of the Box record(parent) and using it as "boxId" field in Items table (child) to establish the link with the parent. 

Your comment: Can you post a screenshot of the error you're seeing?
Response: When I use the Datasource block "create row in BoxItems" - the first screenshot - you can see there is no "error" output (that green block) to use. So I can't tell what the error is.

Your comment: And also the RowID value you're getting (e.g. displayed in a label)? Are you initializing the RowID variable with a value or is it just blank?
Response: I am not initializing it, it is generated by Airtable. (See details in first response above). 

Appreciate a deeper analysis of the issue - resolving it would certainly help keep the codeblocks clean.

**Comment by jane-d-alt** [comment]
Hi there,

Were any of these fields not Text, eg numbers or dates? If so, we believe that this issue should now be resolved. Can you test your project again and confirm?

**Comment by jane-d-alt** [comment]
Hi there, we're going to close this issue as we believe this behavior has been resolved. Thanks for reporting!
