### ISSUE TITLE
Block desappeared

### ISSUE THREAD

**Issue by aiasp** [thunkable/thunkable-issues#750]
i don't find this block after upgrading to new version.

i need this block "get value" and "update or insert block" in airtable db

can u help me please ? 
thanks

<img width="306" alt="Schermata 2020-11-19 alle 17 27 33" src="https://user-images.githubusercontent.com/66922345/99730260-6d3f1100-2abc-11eb-9f7c-89c2c57ef50a.png">

**Comment by tatiang** [comment]
Do you have a "Data Sources" drawer? Have you added an Airtable component?

**Comment by jane-d-alt** [comment]
Hi there,
If you connect a Data Source to your project, you can find this block in the Data Sources drawer of blocks. Read more about Data Sources blocks here: https://docs.thunkable.com/v/drag-and-drop/data-sources#read
