### ISSUE TITLE
Automatically scroll/start at bottom of column

### ISSUE THREAD

**Issue by LuEllaBella** [thunkable/thunkable-issues#752]
**Is your feature request related to a problem? Please describe.**
I’m not sure if I missed it, but I can't figure out how to have the the column start at the most recent message on the bottom of the column, so you don’t have to scroll down to the most recent message

**Describe the solution you'd like**
A block to insert, for example, in When Screen Starts - Scroll to bottom of Column 1.

**Describe alternatives you've considered**
Or in the design side when editing position info for a column that there be an option to select to have the starting view at the bottom.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
This comes into play when trying to create a messaging app and the most recent messages are displayed at the bottom of the screen. We don't want the user to have to scroll all the way down to the most recent message.

**Comment by jane-d-alt** [comment]
Hi there,

Thanks for this request. Since this request overlaps with #342 , we're going to close this issue. We are considering adding this feature at some point, though right now there is no planned delivery date for such a feature.
