### ISSUE TITLE
Critical ERROR while updating property ‘fontSize’ in shadow node of type:RCTTextat

### ISSUE THREAD

**Issue by kushadapt** [thunkable/thunkable-issues#754]
### Platform
Thunkable X on Android Only. I have teste with IOS and webview is working

Tested with :

Huawei Honor X9 Build 9.1.0.210(C432E2R1P5patch03)
EMUI 9.1.0
Node version 4.9.148

Huawei p20Lite0
Build 9.1.0.355(C109E6R1P3)
EMUI 9.1.0
Node version 4.9.148

### Issue/Request Origin
Changing the font size, or changing the alignment of a column, row or object with Data viewer LIST and google shee

### Steps to Reproduce
1.Create Data viewer list
2. Create google sheet or own table or Airtable
3.Create a Label
4.Insert a Fontsize colum
5.Bind the FontSize or Align with one column on Google Sheet
6.Enter value 20 on Column
7.Test on Android

### Project Link
https://x.thunkable.com/projects/5fc20463145be60012bc05d6/0e0285da-e6d5-438e-acfe-efe9835e4a68/designer
### Expected Behavior
Change font size

### Actual Behavior
Critical error while updating property ‘fontSize’ in shadow node of type:RCTTextat
```
  STACK TRACE AND/OR SCREENSHOTS
```
![WhatsApp Image 2020-11-28 at 04 39 48](https://user-images.githubusercontent.com/65672472/100497218-1ee3df00-315a-11eb-8572-6a0f37ad78ff.jpeg)

**Comment by kushadapt** [comment]
Update 04/12/2020 :
I have added the information of the phones with which I got the error.

**Comment by kushadapt** [comment]
Tested with Android im not sure, but in IOS There is no problem.
to check

Tested:

Button
Label
TextInput
ListViewer
Switch
Slider
Loading icon
Rating
Row
Column
Rating icon
Column
:x:AlignItems Error while updating property’AlignItems’ in shadow node of type:RCTview at
:x:JustifyContent Error while updating property’JustifyContent’ in shadow node of type:RCTview at
The rest works

Row
:x:AlignItems Error while updating property’AlignItems’ in shadow node of type:RCTview at
:x:JustifyContent Error while updating property’JustifyContent’ in shadow node of type:RCTview at
The rest works

Button
:x:Fontsize Error while updating property’Fontsize’ in shadow node of type:RCTText at
:x:Width and Height Blank screen with thunkable logo
:x:Disabled Error while updating property’disabled’ of a view managed by:RCTText at
The rest works

TextInput
:x:Width and Height Blank screen with thunkable logo
:x:Borderwidth Error while updating property’borderWidth’ in shadow node of type:AndroidTextInput
The rest works

ListViewer
:x:Width and Height Blank screen with thunkable logo
The rest works

Image
✓resizeMode
:x:Width and Height Blank screen with thunkable logo
The rest works

Rating
✓Value
✓Count
:x:Icon Blank screen with thunkable logo tested with (image url,text,number)
✓Visible
:x:Direction Error while updating property’FlexDirection’ in shadow node of type:RCTview at
✓ReadOnly
:x:FontSize Error while updating property’Fontsize’ in shadow node of type:RCTText at
✓IconMargin
✓Rating color
✓Background color

Loading Icon
✓color
:x:Size Error while updating property’Width’ in shadow node of type:RCTview at
:x:Width and Height Blank screen with thunkable logo
✓Visible

Slider
:x: Maximum value Error while updating property’maximumvalue’ of a view managed by :RCTSlider at
:x: Minimum value Error while updating property’minimumvalue’ of a view managed by :RCTSlider at
:x: Step value Error while updating property’step’ of a view managed by :RCTSlider at
:x: Value Error while updating property’value’ of a view managed by :RCTSlider at
:x: Width and Height Blank screen with thunkable logo
✓ MinimumTrackTintColor
✓ MaximumTerackTintcolor
✓ Disabled
✓ ThumbTintColor

Label
:x:FontSize Error while updating property’FontSize’ in shadow node of type:RCTText at
:x:NumberofLines Error while updating property’numberofLines’ in shadow node of type:RCTText att
:x:TextAlign Error while updating property’TextAlign’ in shadow node of type:RCTText att
:x: Width and Height Blank screen with thunkable logo
The rest works

Switch
All work

**Comment by jane-d-alt** [comment]
Hi there,

It looks like this behavior was resolved in a release that was published in December 2020. I'm going to close this issue now. Apologies for not following up when this update was originally published!
