### ISSUE TITLE
SecureTextEntry does not hide value of text_input component

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#756]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Thunkable X Web App and Web Live Test

### Issue/Request Origin
Community https://community.thunkable.com/t/solved-hide-password-in-thunkable/61319/17

### Steps to Reproduce
1. Create a screen
2. Add a text_input
3.Change SecureTExtEntry to true
4. Preview on Live test
5. Enter text in box

### Project Link
https://x.thunkable.com/copy/64bc4ec7847f870caa748fb053ff9ad1

### Expected Behavior
Text should be obfuscated like in android and iOS apps

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/66176281/100517315-a885b380-313e-11eb-9920-181ef825ed8e.png)

**Comment by GMShack11** [comment]
Even I get it, I live tested in my sign-in screen and it showed the password

**Comment by kkadouhtcc** [comment]
@mjgallag Is there an update on this issue? It's been a while since it's been reported and SecureTextEntry is a necessity when creating a webapp

**Comment by kkadouhtcc** [comment]
Why was this closed? The issue is ongoing @StevenPurn

**Comment by StevenPurn** [comment]
It has been fixed. The fix isn't released yet but it is in our code base and should be getting released sometime early next week.

**Comment by kkadouhtcc** [comment]
Ah, ok glad to hear! Thank you for the help! @StevenPurn
