### ISSUE TITLE
Can't scroll in the blocks sectiom

### ISSUE THREAD

**Issue by GMShack11** [thunkable/thunkable-issues#757]
I can't scroll in the blocks section on any of my apps, 
I can only Drag the scrollbar to scroll,
```I hope you can fix this issue soon

 Thank you

**Comment by domhnallohanlon** [comment]
Hi @GMShack11 - I'm not able to reproduce this behaviour on my end. 

Are you trying to use Thunkable from a mobile device?

**Comment by jane-d-alt** [comment]
Hi there,

Is your desired behavior that you can pan-to-scroll or use a scroll wheel to navigate in the Blocks tab?

**Comment by GMShack11** [comment]
I can't use the scroll wheel to navigate in the blacks tab @jane-d-alt

**Comment by jane-d-alt** [comment]
This issue overlaps with #706, so we will close this as a duplicate. Thanks for the request!
