### ISSUE TITLE
From Airtable Set Base Id block doesn't work

### ISSUE THREAD

**Issue by BoBKoF** [thunkable/thunkable-issues#758]
I tried a lot of time, i tried to delay with timer but nothig.

The block doesn't change the Base Id, only if i put it manually with a textbox

**Comment by domhnallohanlon** [comment]
@BoBKoF - could you use multiple tables in your base rather than trying to use multiple bases?

**Comment by jane-d-alt** [comment]
Hi there,

We believe this behavior has been resolved since you originally reported it. Can you test your projects to confirm?

**Comment by jane-d-alt** [comment]
Hi there, we're going to close this issue as we believe this behavior has been resolved. Thanks for reporting!
