### ISSUE TITLE
Sounds plays without previewing project & does not stop when closing preview

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#765]
### Platform
Thunkable X

### Steps to Reproduce
1. Open https://x.thunkable.com/copy/4d20e68a037d7f0bc5312410ad9e389d, change "stop" block to "play." 
2. Song will begin playing immediately.
3. Change "play" block to "stop."
4. Click Live Test.
5. Close preview. 
6. The song now stops because of the "stop" block. But previewing a song that is playing and then closing the preview does not stop the song. It continues playing in the browser.

Could this be related to this issue? https://community.thunkable.com/t/sound-function-buggy/1021944/2

### Project Link
https://x.thunkable.com/copy/4d20e68a037d7f0bc5312410ad9e389d

### Expected Behavior
Not this!

### Actual Behavior
See above
```
  STACK TRACE AND/OR SCREENSHOTS
```
Here's a screencast of the issue: https://drive.google.com/file/d/1cxK3Un_43Bmn8HpS9csvIjCUDbNsYvIK/view

**Comment by josmas** [comment]
This has been currently fixed and merged; it might not be out till after the break though. Thanks for the report!

**Comment by jane-d-alt** [comment]
Hey all,

Just following up to say that this fix was released. Thanks for reporting!
