### ISSUE TITLE
Is it possible to add an image to a button in a drag-and-drop project?

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#769]
### Platform
Thunkable X

### Issue/Request Origin
I can't import a jpg or png into a button component without getting an error message. If I import the same file(s) into an image component, they work fine.

### Steps to Reproduce
1. Drag a button component onto a screen.
2. Click in the Picture field and click Upload files. 
3. Select a jpg or png and click Open.

### Project Link
https://x.thunkable.com/projects/5f640dd2745a27afedece52d/b90c5f9b-b5d9-4d45-977c-2bc062482e4a/designer

### Expected Behavior
The button takes on the image I imported.

### Actual Behavior
See error message below.
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="406" alt="Screen Shot 2020-12-09 at 11 30 22 PM" src="https://user-images.githubusercontent.com/10355498/101735409-b8729100-3a76-11eb-997d-a347bd872baf.png">

**Comment by josmas** [comment]
this should be fixed now. Thanks @tatiang and let us know if you still having issues.
