### ISSUE TITLE
(Thunkable X) Text floating too high in Text Box (Android only)

### ISSUE THREAD

**Issue by KaneoheKid** [thunkable/thunkable-issues#77]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
This is for x, in the Android companion and compiled apps
#76 
identified during app building.  

### Steps to Reproduce
1. Open this link:  https://x.thunkable.com/copy/8fb8b662e37b4651aca6528307c466e2
2. View in iOS and then Android device companion
3.  That's it.  I don't see any way to remove the underline or lower/center the text.

### Expected Behavior
What did you expect to happen?
Expect the text in a text box to display close to the bottom of the box, or be centered vertically.  
### Actual Behavior
What actually happens?
Text floats high above the bottom in Android while it is centered in iOS.  Text box must be abnormally tall in order to see text when using Android.
  STACK TRACE AND/OR SCREENSHOTS
```
![android4](https://user-images.githubusercontent.com/42430475/44191632-05711300-a0c8-11e8-9b9e-527d7aaaab02.png)
![ipad](https://user-images.githubusercontent.com/42430475/44191639-115cd500-a0c8-11e8-8867-6c5c5382c8a2.PNG)

**Comment by AlexITMan** [comment]
On the Advanced tab of the input fields set the underlineColorAndroid property to a transparent color.

**Comment by KaneoheKid** [comment]
Seems to have taken care of the issue.  Thanks.
