### ISSUE TITLE
Getting substring from current year crashes project

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#786]
### Platform
Thunkable X, legacy interface

### Issue/Request Origin
I mentioned it here: https://community.thunkable.com/t/cant-get-substring-of-current-year/1040701

### Steps to Reproduce
1. Create the blocks in either screenshot below
2. Click Live Test button to preview in browser
3. (Blank white screen appears)

### Project Link
https://x.thunkable.com/projects/5fdee9f8fe45820012bdda19/ddf200bc-b146-41ba-bc9a-424763a1f0ec/blocks

I may try some workarounds so I can't promise I'll still have that configuration of blocks in that project.

### Expected Behavior
I expected to see "20" for the label value.

### Actual Behavior
Project crashes
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="781" alt="Screen Shot 2020-12-21 at 9 05 27 AM" src="https://user-images.githubusercontent.com/10355498/102803420-105da180-436d-11eb-9af6-364351f1fc29.png">

<img width="426" alt="Screen Shot 2020-12-21 at 9 19 00 AM" src="https://user-images.githubusercontent.com/10355498/102803770-a396d700-436d-11eb-8008-0835385eac5e.png">

**Comment by domhnallohanlon** [comment]
@tatiang - just followed up on your Community posts with explanation/work-around. 

https://community.thunkable.com/t/cant-get-substring-of-current-year/1040701/2?u=domhnallohanlon

Let us know whether or now that works for you!

**Comment by tatiang** [comment]
I was able to get it working by following this example:

https://community.thunkable.com/t/cant-get-substring-of-current-year/1040701/4

**Comment by jane-d-alt** [comment]
Hi Tatian,
The first block in your Community post won't work because date type != String type. You seem to be aware of/satisfied with this explanation.
The second block not working was an issue, but that appears to be resolved now. I can set a Label's text to **[current year] + ""** with no issue. 
We're going to close this issue for now. Let us know if you have any follow-up questions about this!

**Comment by tatiang** [comment]
Thanks, @jane-d-alt. I'm not sure why I didn't realize the type conflict back in December but that makes a lot of sense.
