### ISSUE TITLE
Backpack type feature is very much needed

### ISSUE THREAD

**Issue by ndrorian** [thunkable/thunkable-issues#790]
I miss the Backpack feature in MIT AI2 it is very useful.

**Comment by jane-d-alt** [comment]
Hi there,
Thanks for this request. We will close this issue as it overlaps with #51 . We are considering adding this feature to the platform, but there is no delivery date at this time.

**Comment by ndrorian** [comment]
binary to octal, hexadecimal
bitwise or, and , xor
min, floor, ceiling
log
modulo, remainder, quotient
radians to degrees, degrees to radians
hex to base 10, base 10 to binary, binary to base 10
