### ISSUE TITLE
Open Event does not occur on Android Live Test if Loading Icon Present

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#799]
### Platform
✕ Android companion

### Issue/Request Origin
https://community.thunkable.com/t/list-viewer-not-set-on-screen-open/1042157

### Project Link
https://x.thunkable.com/copy/8511e2e52bbc35dcf8a85f991bd86f16

### Expected Behavior
The open event should occur

### Actual Behavior
OPen Event does not occur
```

**Comment by jane-d-alt** [comment]
Is this issue only seen on Live Test on Android, or on both Live Test and downloaded apps?

**Comment by DrTedGit** [comment]
I did not test the effect on APKs

**Comment by alex-jinhyuk** [comment]
i'm having the same symptom. my apps were just fine but suddenly they (all the versions including past ones) stoped at the beginning. and its iOS and android both.

**Comment by josmas** [comment]
@alex-jinhyuk if you start a new project, place a label and a button that changes the text in the label, and open in the Companion... that also does not work?

**Comment by jane-d-alt** [comment]
Thunkable team member Janhavi is working on this issue.

**Comment by alex-jinhyuk** [comment]
> @alex-jinhyuk if you start a new project, place a label and a button that changes the text in the label, and open in the Companion... that also does not work?

it is solved now. thanx

**Comment by Oreldad** [comment]
this is happening in ios also - live and downloaded versions

**Comment by gobassky** [comment]
It happened on published web-apps also. Whatever blocks in the Open blocks did not execute. (the screens that "open' don't work screens are within top navigators)

**Comment by jane-d-alt** [comment]
Hi there,

This behavior has been resolved on devices and on the web. Apologies for not following up when this behavior was originally resolved. Thanks for reporting!
