### ISSUE TITLE
Feature Request: event that fires when "Go" (or other button) is pressed on keyboard (ThunkableX)

### ISSUE THREAD

**Issue by rschoem** [thunkable/thunkable-issues#8]
Hi,

I am building an app that contains a logon screen. What I am missing is an event that fires when a user "presses" the "Go" or "Done" or "Next" or equivalent buttons on the keyboard.

Now these "Done" buttons merely acts as a "close keyboard" button, and the user has to press another button on the screen to actualy perform the action.

It would be nice if there was a block that could respond to the fact that the "Done" button on the keyboard is pressed (similar to the blocks that are available for normal buttons). Something like "when keyboardbutton click ...."

Thanks

**Comment by rschoem** [comment]
Also, it would be nice if it was possible to move the cursor to a specified input field when the "Next" button is pressed

**Comment by nicbyron** [comment]
+1 for this! Not a great UX to make the user hit done and then done again on the screen.

**Comment by jane-d-alt** [comment]
Hi there,

We now have a 'when Text Inout Submit' block: https://docs.thunkable.com/text-input#submit
This should cover your use case.

Thanks for the request!
