### ISSUE TITLE
Code not running on start

### ISSUE THREAD

**Issue by alex-jinhyuk** [thunkable/thunkable-issues#800]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
thunkable X

### Issue/Request Origin
actual app ( iOS and android same )

### Steps to Reproduce
1. start app
2. then nothing
3.

### Project Link
solved

### Expected Behavior
it has to be navigated to another screen and do the rest thing

### Actual Behavior
nothing. just first screen i made and stop
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by domhnallohanlon** [comment]
@alex-jinhyuk just linking this to your Community post too
https://community.thunkable.com/t/code-not-running-on-start/1042328?u=domhnallohanlon

**Comment by domhnallohanlon** [comment]
@alex-jinhyuk  can you share your project link with us as well as the copy link provided above so that we can see the more up-to-date version of your project. 

Thanks!

**Comment by alex-jinhyuk** [comment]
@domhnallohanlon you mean this? https://x.thunkable.com/projects/5fcdcca2e5bde500119b54b9/1bd95e2a-1959-4c95-83c3-cb34638e872b/designer

**Comment by josmas** [comment]
hi @alex-jinhyuk this is running for me. Is it something particular you do that it stops working? is it on download?

**Comment by alex-jinhyuk** [comment]
> hi @alex-jinhyuk this is running for me. Is it something particular you do that it stops working? is it on download?

hi. sorry i solved this problem. firebase rules causes problem. but still i sense problem exists but i'll let you guys know when i organized it. solved issue for now anyway

**Comment by josmas** [comment]
ok, thanks @alex-jinhyuk . Will close this for now, if you find any other issues, do let us know (feel free to reopen).
