### ISSUE TITLE
Networ Request Failed

### ISSUE THREAD

**Issue by AmanChaudharyy** [thunkable/thunkable-issues#802]
Hello Thunkable,
I am connecting web api to my app. it works fine in livetest window but it throw me a error NETWORK REQUEST FAILED while test/install app on my android phone. Api URl:  https://youngmanbeta.com/testAndroid
pls reply asap …

**Comment by josmas** [comment]
Please ask for programming help in the [community forum](https://community.thunkable.com/). Thanks!
