### ISSUE TITLE
Barcode reader does not work in new drag & drop interface

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#803]
### Platform
Thunkable X - new drag & drop interface

### Issue/Request Origin
Also posted at https://community.thunkable.com/t/does-the-barcode-reader-work-in-the-new-interface/1044945

### Steps to Reproduce
1. Add a barcode block to an event block
2. Live Test on a device
3. There is no camera view and no result is passed to the "value" or "error" blocks.

### Actual Behavior
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
thanks for the report @tatiang 
I believe we have a fix for this, @JanhaviDahihande could you please confirm?

**Comment by domhnallohanlon** [comment]
@josmas I think this is it? 
https://github.com/thunkable/thunkable-for-ios/pull/7373

**Comment by JanhaviDahihande** [comment]
Yes @josmas Fix is under review now. Thanks :)
