### ISSUE TITLE
Data viewer bug

### ISSUE THREAD

**Issue by Irwin2004** [thunkable/thunkable-issues#805]
### Platform
Thunkable Live, version 254

### Issue/Request Origin
I have four tab navigator screen, I put every screen a tab navigator. But when I change to the next screen, it begin with loading icon then a few second it shows data viewer. I go back to the previous screen, then it shows loading icon again. Why it shows loading icon again when i press on evey screen?

### Steps to Reproduce
1. Open Thunkabke Live
2. Go to the next screen of tab navigator

### Expected Behavior
The data viewer don't shows loading icon when I press on every screen of tab navigator.

### Actual Behavior
Every time I go to the next screen, it always show loading icon.

**Comment by josmas** [comment]
hi @Irwin2004 can you clarify what do you mean by `I put every screen a tab navigator`?
If what you have is the data viewer in each of the tabs, it will always reload when you change screen. This is in case the data has changed, you don't want to show stale data to your users (say that you modify the data in screen 1, you need to reload in screen 2, right?).

**Comment by Irwin2004** [comment]
Hi @josmas 
In this case, I don't modify the data. Example I'm in screen 1 than I go to screen 2, in the beginning the data viewer shows loading icon then it show the data. Then I go back to screen 1 and I go back again to screen 2 again. But the loading icon is visible again.

Previously, the loading icon is not visible. When I press screen 2, it automaticly show the data. The loading icon is not visible.

**Comment by josmas** [comment]
Not sure that is the case. Hey @StevenPurn, do we always refresh the data when changing screens? In this case we are talking about a navigator, so it is a new Screen.

**Comment by StevenPurn** [comment]
Sorry for the delayed response. I don't believe we should but I also just heard of a similar issue where the scroll position isn't persisted when navigating to/from a screen with a DV. Going to take a look at it now.
