### ISSUE TITLE
I have an issue in iOS status bar color.

### ISSUE THREAD

**Issue by boomdaba** [thunkable/thunkable-issues#808]
[IMG_0567](https://community.thunkable.com/uploads/default/original/3X/a/3/a39bd4bf7e3ed8316200bd94e8f35b1bb9fc10da.jpeg)

I'm in iOS and I have an issue about status bar.
Could you please resolve this issue. I need to publish my app as soon as possible.

following this topic
https://community.thunkable.com/t/status-bar-color-blending-issue/426070

**Comment by jane-d-alt** [comment]
Hi there,

This issue has been resolved. You can find more details in Wei's comment on the Community post linked above: https://community.thunkable.com/t/solved-status-bar-color-blending-issue/426070/118 

Thanks for reporting!
