### ISSUE TITLE
ThunkableX global variables

### ISSUE THREAD

**Issue by tomhendric** [thunkable/thunkable-issues#81]
Hello

How do you create a global variable in ThunkableX ?

Kind regards

**Comment by mark-friedman** [comment]
This issues list is for reporting bugs and requesting features.  Questions like this are better asked in the [community forum](https://community.thunkable.com/c/thunkable-cross).  That said, please take a look in [our documentation section on variables](https://docs.thunkable.com/thunkable-cross-platform/create/blocks/variables).
