### ISSUE TITLE
List Viewer issue beginning 1/27/21

### ISSUE THREAD

**Issue by KaneoheKid** [thunkable/thunkable-issues#812]
### Issue/Request Origin
Issue began suddenly ~ midnight PDT on 1/27.  Listviewer stopped working on all screens of a 5 screen app, so it was not due to one of my typical blunders.  Upgrading to companion V255 did not resolve the issue.  Adding a new listviewer component to a screen did not resolve it.  Copying the whole project did not resolve it.  Simply saving the screen to "my screens" did resolve it for that screen.

### Steps to Reproduce
1.  project link:

go to any screen and then tap on a button which makes the listviewer visible.  None of the listviewers work, the webviewer disappears but is not replaced by a visible list from the listviewer:
https://x.thunkable.com/copy/9f04459c271683dfa8e02d23502a8353

2. The following link is for a new project created by "Save Screen to My Screens" from one of the Screens in the above link.  It functions normally.
https://x.thunkable.com/copy/748dbbbac965880d022115f6f9f2ccdb

### Expected Behavior
When tapping a button, webviewer should disappear and be replaced by a list.

### Actual Behavior
Blank screen, no list.  However, it does not happen with all of my projects, most continue to be normal.
```

**Comment by josmas** [comment]
hi @KaneoheKid so I added a list viewer on your first screen and that shows just fine.
I see this error in console when I click on one of your images: `SyntaxError: missing ) after argument list` which seems to suggest that at least one of the lists that you are using has some type of error.
I am guessing you are using a list for your list view elements? Could you temporarily substitute one of those that you see failing for a list with just a couple of elements and see if that renders properly?

**Comment by KaneoheKid** [comment]
Just to be clear, the project "BadSatListview" listview actually functions properly.  The Sat screen in "RestlessWorld1", which has the same variables does not.  Replacing the list elements in the variable with a new different list of elements did not resolve the issue.  If no one else is reporting a similar issue, then it isn't significant.  Perhaps the project was corrupted somehow.  I am able to save copies of all of the screens and reassemble them in a new project, so my work is not lost.
