### ISSUE TITLE
Add Font, font color, and background color/pic to list viewer.

### ISSUE THREAD

**Issue by Swish205** [thunkable/thunkable-issues#813]
I have a project and I have a very dark background. The gray font is not visible on the list viewer. Can Thunkable please and an option where you can change the font/color, background color/pic to list viewer? Thank you!

**Comment by boomdaba** [comment]
I have this issue too and want it to be changed soon
![IMG_0838](https://user-images.githubusercontent.com/77819558/107012032-0aac0600-67cb-11eb-8649-489952c07eea.PNG)

**Comment by jane-d-alt** [comment]
As of April 13, 2021, you can change List Viewer's Font Size, Font Color and Font Background Color: https://docs.thunkable.com/release-notes#april-13-2021
You can place a List Viewer in a Row, Column or Group that has a background picture, and make the List Viewer's background color transparent, to show an image behind your List Viewer's text items:

<img width="508" alt="Screen Shot 2021-06-03 at 9 09 27 AM" src="https://user-images.githubusercontent.com/51848939/120610749-6752c100-c44b-11eb-9275-4f0876173cfd.png">

Thanks for the request!
