### ISSUE TITLE
Web App Not Working

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/thunkable-issues#815]
@josmas My web app stopped working this morning.  No updates to it or anything on my end.  Something update on Thunkable's end to make this happen?

https://thunkable.site/web-build/index.html?webAppId=lCcCqQ3ts

Please let me know what we can do resolve this issue ASAP.  Thank you in advance. 

Joe

**Comment by josmas** [comment]
Hi @MrMazzone thanks for the report and apologies for the issues; we'll have a look.
Is it just the one app that is failing? do you happen to have more that one published?

**Comment by MrMazzone** [comment]
@josmas Looks like just web apps that have loading icon and Airtable only.  Not sure which one is causing issue.  I can investigate later today, but would very much appreciate if you guys could discover the issue.

**Comment by MrMazzone** [comment]
![image](https://user-images.githubusercontent.com/40954645/106756907-c0295e80-65fd-11eb-9b0a-a3225647a0e6.png)

**Comment by josmas** [comment]
Is that screenshot from the same app? My error points to `Screen.js:987` when I open your app.

**Comment by MrMazzone** [comment]
Hmmm... Yes.  Same app from the URL above.

**Comment by josmas** [comment]
Do you happen to use `Device` blocks such as `device is online`?

**Comment by MrMazzone** [comment]
Yes. I believe it does use that block.

**Comment by josmas** [comment]
I can see the issue locally if I use that particular block. Let me check what is going on and get back to you. Thanks!

**Comment by josmas** [comment]
@MrMazzone we have a fix but I am not sure when we can push to production as it affects the apps. We'll keep you posted.

**Comment by MrMazzone** [comment]
@josmas Thank you.  Please let me know.  I am hoping soon.

**Comment by josmas** [comment]
hey @MrMazzone I can see the sign in for your app now. Can you please verify all is back to normal? Thanks!

**Comment by MrMazzone** [comment]
It is operational again!  Thank you so much for the quick work @josmas

**Comment by josmas** [comment]
Thanks and apologies again for the downtime!
