### ISSUE TITLE
Buttom tab navigator bug

### ISSUE THREAD

**Issue by Irwin2004** [thunkable/thunkable-issues#817]
### Platform
Thunkable Live v257, Android

### Issue/Request Origin
I have 5 screen of buttom tab navigator. I am in screen 1, then I want to go to screen 2, so I press the icon of screen 2. But there is a delay when I press the icon of screen 2. It delay about 1 second then it will go to screen 2.

### Steps to Reproduce
1. Open Thunkable Live
2. Press the icon of buttom tab navigator 

### Expected Behavior
Don't have delay when I press every buttom tab navigator's icon

### Actual Behavior
Have delay about 1 second when I press every buttom tab navigator's icon

**Comment by tommy10088** [comment]
Yes, I have experienced the same issue. For the buttom tab navigator, everything seems really slow following the update of Thunkable live to v255. Please fix this.

**Comment by jane-d-alt** [comment]
Hi there,

This behavior appears to have been resolved with subsequent updates to the Thunkable Live app. If you experience this issue in the future, please reach out and provide an app that demonstrates this behavior when you test it.

Thanks for reporting!
