### ISSUE TITLE
"image from photo library" block does nothing

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#823]
### Platform
Thunkable X, drag-and-drop interface

### Steps to Reproduce
1. "Attempt to use an image from photo" library block.
2. Nothing happens.
3.

### Actual Behavior
```
  STACK TRACE AND/OR SCREENSHOTS
```
These blocks do nothing. There's no response, no result, no label value, no image.

<img width="480" alt="Screen Shot 2021-02-07 at 10 57 56 AM" src="https://user-images.githubusercontent.com/10355498/107156477-68f3f880-6933-11eb-9e8c-8b3c0988a412.png">

**Comment by josmas** [comment]
thanks for the report @tatiang 
Seems to only affect new DnD UI, I can see the same; we'll look in to it.

**Comment by josmas** [comment]
We have a fix for this; should be out in next release. Thanks!
