### ISSUE TITLE
Visible block not working

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#826]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Thunkable X Drag and Drop interface

### Steps to Reproduce
1. Use visible block and set to false
2. Live test on android or Companion

### Expected Behavior
Text input to be not visible

### Actual Behavior
What actually happens?
Text input its position changes

**Comment by josmas** [comment]
hi @lukeplays33 is the label is still visible in the same place it was? as in, it does not hide at all? or does it appear somewhere else?

**Comment by lukeplays33** [comment]
IT is still visible.
And moves to X: 0 and Y: 0 position.
Whitout turning invisible.
And when i make IT visible IT turns back to normal.

**Comment by josmas** [comment]
thanks for confirming; we'll have a look.

**Comment by lukeplays33** [comment]
Hey @josmas is there any news about this?
Bacause it is still not working

**Comment by josmas** [comment]
Hi @lukeplays33 we have a fix for this now. Should be out in the next (or maybe one after, depending on if we release today or not) release. Thanks!

**Comment by lukeplays33** [comment]
Thank you @josmas

**Comment by lukeplays33** [comment]
Hey @josmas and the Thunkable team Thank You!
The issue is now fixed on my android phone.
