### ISSUE TITLE
Thunkable Live on iOS freezes when date picker is launched

### ISSUE THREAD

**Issue by hazhalim** [thunkable/thunkable-issues#828]
### Platform

Thunkable Live companion for iOS

### Issue/Request Origin

iOS/iPadOS 14.4, Thunkable Live version 258-2 for iOS/iPadOS. I tested my apps again after one week to discover the date input does not work and freezes the app upon launching the date picker. This issues happens across projects so I don't think my blocks are the issue. Reinstalling Thunkable Live does not resolve the issue.

### Steps to Reproduce

1. Create a new project
2. Insert label, button and date input components into a screen
3. Program project to launch date picker when button is tapped, and label set to date after date is picked
4. Live Test project on an iOS/iPadOS device

### Project Link

https://x.thunkable.com/projectPage/600a4bc78e80a500129d1db2

### Expected Behavior

Date picker opens, user confirms date, date picker closes and label is set to picked date.

### Actual Behavior

Button shows that it was tapped but Thunkable Live freezes, user needs to reopen Thunkable Live again or press "Live Test" from computer to unfreeze Thunkable Live.

### Screenshot

<img width="810" alt="dateinputbug" src="https://user-images.githubusercontent.com/63937254/107844721-f42c2d00-6e10-11eb-94e6-0fab6430a642.png">
The screenshot of the project appears normal but Thunkable Live is frozen after pressing the blue "Choose Date" button, I'm unable to press the Back nor the View Code button at the top of the screen.

**Comment by josmas** [comment]
Hi there @hazhalim I am testing your project on an iPhone with ios 14 and it works fine; can you confirm this is still an issue or not?

**Comment by hazhalim** [comment]
Yes, but I just noticed that my "choose date" button doesn't freeze anymore if I leave the Date Input component visible. If I keep it hidden, my "choose date" button will freeze the app again. So far, my only workaround is setting the Date Input's opacity to 0.

**Comment by josmas** [comment]
hi @hazhalim I see what you mean. We've added a check to call open on the picker only if it is visible, so the app does not hang. Will be out in next release (some time next week). Thanks!

**Comment by jane-d-alt** [comment]
Hi @hazhalim ,

Just confirming that this fix has been released. Thanks again for reporting!
