### ISSUE TITLE
Speech recognizer - please add support for Khmer language

### ISSUE THREAD

**Issue by kmsato** [thunkable/thunkable-issues#829]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by josmas** [comment]
Hi there, we use Google's speech recognizer and we cannot add language support to it. If you request this to the Android team and they add it, it will automatically work on Thunkable. Thanks!

**Comment by kmsato** [comment]
Then it should be working, since this updated list includes Khmer

[image: image.png]
Can you help me set this up?

**Comment by josmas** [comment]
Hi @kmsato did you mean to include an image? I can only see the following text:

> [image: image.png]

**Comment by kmsato** [comment]
excuse me Jos, the image I've captured is from the list of supported
languages of Google in the speech-to-text
 function. This list includes Khmer.

Then why Thunkable doesn't have Khmer in the speech recognizer settings?

**Comment by MrMazzone** [comment]
It does seem to be on the list here: https://cloud.google.com/speech-to-text/docs/languages

![image](https://user-images.githubusercontent.com/40954645/108211539-c853c480-70fa-11eb-98ce-23ddfc4b7dfe.png)

**Comment by MrMazzone** [comment]
@josmas Does something like this work for @kmsato ? 

![image](https://user-images.githubusercontent.com/40954645/108211800-27193e00-70fb-11eb-93c9-1a66c862ee36.png)

**Comment by josmas** [comment]
hey @MrMazzone, note that the list you link to is for Google's cloud speech-to-text service, which is not the same as they provide within their mobile SDKs. Having said that, @kmsato you should try @MrMazzone's suggestion, either with a text block like in the screenshot above, or with simply a `km` value.

If any of those works for you, I'd be happy to add it to our list so you can select from the dropdown, but we need to make sure that it works first.

**Comment by kmsato** [comment]
I've tested it with both km-KH and km, but it didn't work. D
@MrMazzone <https://github.com/MrMazzone>, any other suggestion?

Thank you!

**Comment by MrMazzone** [comment]
@kmsato I was unable to find a list of languages supported by Google's mobile SDK that @josmas mentioned.  Sorry, I do not have any other ideas.
