### ISSUE TITLE
Ads Issue and solution !

### ISSUE THREAD

**Issue by AcrobatEpee** [thunkable/thunkable-issues#83]
In Thunkable X we have no possibility of adding ads on our apps.

And as I make apps on thunkable and as every other developer I want my job to get rewarded and I do want to add ads on my different apps, for this reason I’m here to propose you something to add (as fast as possible if you can because many members of the community are asking for it :) ) As I was making researches on how to integrate ads I found a website called Enhance which proposes to integrate an SDK in your app which then allows you to put any ad provider on your app. I’d like to suggest for you to develop the same sort of sdk or why not make a partnership with them as they are charging nothing to integrate it.

Hoping to see this added soon ! A old thunkable user, looking forward !

**Comment by jane-d-alt** [comment]
Thunkable X now supports [AdMob](https://docs.thunkable.com/admob) ads.
