### ISSUE TITLE
Local html files will not load in Webviewer on Android

### ISSUE THREAD

**Issue by NathanaelGW** [thunkable/thunkable-issues#834]
### Platform
Thunkable X, Android App

### Steps to Reproduce
Set webviewer to display local html. Download app for Android and run.

### Expected Behavior
Webviewer displays local html file.

### Actual Behavior
The html file doesn't load and the webviewer crashes or becomes not visible. Cannot see any error messages.

### Comments
I repackaged an app for Android that worked correctly in January 2021 and any webviewers loading local html files would not appear. Unlike broken links or ssl permission issues which would at least show an error message, the webviewers just crash or become not visible. Webviewer loading local html files works on iOS or in Live Preview but not installed on an Android device.

**Comment by josmas** [comment]
Hi @NathanaelGW thanks for the report. Are we talking plain html files or do you also have javascript files?
Could you please share a small project that shows the issue? I've just uploaded a plain html file and the webviewer shows it as usual.

**Comment by NathanaelGW** [comment]
Hi @josmas, thanks for the quick reply. Here is a quick example of a webviewer displaying a plain, local html file: https://x.thunkable.com/copy/158c3bb96b330bd9fda958e8da205afb.

For me, it works fine in Live Preview but when I download and install it on Android the screen is just blank. I've tested it on three different Android phones with the same result.

Rather than failing to load the html and displaying and error, it seems like the webviewer just changes to not visible. Strange that it's working fine on your device, let me know if this project is any different.

**Comment by josmas** [comment]
Hi @NathanaelGW thanks for the reproducible example. It might have something to do with the new system not showing base64 enconded images, as that is something I have not tried. I'll give it a go locally and let you know what I can find.

**Comment by josmas** [comment]
We are patching up the build server in the next couple of hours. It should be good to go after that. Leaving the issue open for now in any case. Thanks!

**Comment by josmas** [comment]
This has now been deployed. As a heads up, I've built your test app again and the first time I tried it I had a `'net::ERR_ACCESS_DENIED'` error that turned out to be an issue with caching in the device. Opening the app after clearing out the cache worked fine.

**Comment by NathanaelGW** [comment]
I just tested the webviewer on my end and it's working again! I appreciate the quick resolution to this problem.

Thank you,

Nathanael
