### ISSUE TITLE
Allow thunkable web app in Iframe 

### ISSUE THREAD

**Issue by stanis14** [thunkable/thunkable-issues#835]
I would like to put my web app on a WIX website with Iframe fonction to have a personalize URL  
For now there is a message saying that thunkable dont accepte Iframe when I trie to do it 

It would be great if I could put the URL of the thunkable project and see it in a Iframe

I dont have alternative solution to put a personalize url

**Comment by MrMazzone** [comment]
Hi @stanis14.  We have been discussing this in #486

**Comment by stanis14** [comment]
Ok sorry thanks !
