### ISSUE TITLE
Push Notifications GetUserId failing!!!

### ISSUE THREAD

**Issue by camtez** [thunkable/thunkable-issues#837]
### Platform
✕

### Issue/Request Origin
Through testing my app on Testpilot and downloaded Android (for some reason it worked in the Live Test app).

### Steps to Reproduce
1. Set up a Push notifications account
2. Call GetUserId
3. It will return undefined for at least 10 seconds (I haven't tried longer)

### Project Link
I have a big project so probably best to look at this thread I made explaining it in more detail. https://community.thunkable.com/t/push-notifications-not-working/1127935/2 

### Expected Behavior
It would return the actual Id

### Actual Behavior
It returns undefined

```
  STACK TRACE AND/OR SCREENSHOTS
```
https://community.thunkable.com/t/push-notifications-not-working/1127935/2

@josmas this is super urgent for me, unfortunately there is no work around -  have tried to use the REST API and that returns the id, however it does not 'subscribe' the device to the OneSignal app and therefore I cannot send notifications. This is critical as I have a timer app which relies on notifying users when their timers are over. I could theoretically do without this fix if it was possible to connect to the Apple APN to get a push token. Please let me know if you have any questions.

**Comment by josmas** [comment]
Hi @camtez I just tested this in a brand new app with nothing but these blocks and it works both on Live App and Android built/downloaded app. Is it possible that something else is wrong in your blocks?

<img width="630" alt="getuiserid" src="https://user-images.githubusercontent.com/194925/109436166-40cd5600-7a16-11eb-970b-70bd05e839bd.png">

**Comment by camtez** [comment]
Hey @josmas thanks for checking. I don't think so as the push notifications SDK seems to be working fine in my project - just not the call GetUserId. Do you have any suggestions for what might be causing it? If not, is it possible for me to generate my own Apple or Google Push Tokens?

**Comment by camtez** [comment]
Ok it turns out I think the problem was I had 2 different Push_Notification components within the app (one for iOS and one for Android), and as soon as I removed these it started working.

**Comment by josmas** [comment]
Oh, I see. You should be able to use just the one for both platforms. Thanks for letting us know.  Will close this one now.
