### ISSUE TITLE
'JSON to object' is not working

### ISSUE THREAD

**Issue by CFOLD** [thunkable/thunkable-issues#839]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
X

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/80024133/109916116-639d8a00-7cf6-11eb-8258-184a42b21387.png)

### Project Link
https://x.thunkable.com/projectPage/60406c9f8dd34d0012a3e9bc

### Expected Behavior
'JSON to object' is working well. 

### Actual Behavior
'JSON to object' is not working. At this time, the result is "undefined".

### STACK TRACE AND/OR SCREENSHOTS

![image](https://user-images.githubusercontent.com/80024133/109916312-bbd48c00-7cf6-11eb-95c8-6c7132cfbd62.png)

**Comment by josmas** [comment]
Thanks for the report @CFOLD 
We'll have a look.

**Comment by josmas** [comment]
We have found the problem; we will try and get this out on main server in the next few hours. Thanks!

**Comment by josmas** [comment]
This will be out in the next hour. Make sure you visit your blocks page so that the code underneath gets regenerated. Thanks for the report!

**Comment by CFOLD** [comment]
@josmas Thank you for the fast feedback.
