### ISSUE TITLE
Thunkable X iOS, Stack Navigator back arrow is missing on downloaded apps

### ISSUE THREAD

**Issue by thesuigeneris** [thunkable/thunkable-issues#84]
The arrow shows while live testing, but not after downloading the app.

### Platform
✕

### Issue/Request Origin
In the stack navigator, the back arrow is missing once the app is downloaded, but works fine in the live version.

  STACK TRACE AND/OR SCREENSHOTS
![f014c4aab20126eec65d372aea576a51f9d32212](https://user-images.githubusercontent.com/2738525/44887169-caaad580-ac98-11e8-9e0e-a151d466c808.jpeg)
![d1387dd78d9c22b95c8b2dd825e0a1237e936f3f](https://user-images.githubusercontent.com/2738525/44887170-caaad580-ac98-11e8-8197-895c03dc3655.jpeg)

**Comment by thesuigeneris** [comment]
I discovered that swiping left to go back to the previous screen also no longer works.

**Comment by MrSco** [comment]
this is still happening... 6 months later. any updates?

**Comment by mark-friedman** [comment]
Sorry. This is still on our queue, though.

**Comment by ritvik0611** [comment]
This is a big issue and seems very unprofessional for the app. Please resolve it as soon as possible.

**Comment by MrSco** [comment]
i think this is fixed....

https://github.com/thunkable/thunkable-issues/issues/90#issuecomment-473742814

**Comment by jane-d-alt** [comment]
This behavior has been resolved.
