### ISSUE TITLE
Warning when deleting another user's project

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#840]
### Platform
Thunkable X

### Steps to Reproduce
1. Another user shared a link to their project.
2. When I tried to delete the project from my list of projects, I got the warning message in the screenshot below.

### Project Link
I can provide it privately if needed.

### Expected Behavior
It shouldn't warn me about deleting an app that's been published if I wasn't the user who published it.

### Actual Behavior
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="421" alt="Screen Shot 2021-03-04 at 9 52 18 AM" src="https://user-images.githubusercontent.com/10355498/110007259-57520680-7ccf-11eb-9564-74577c48cc57.png">

**Comment by josmas** [comment]
Hi @tatiang we have added add to all projects. Once you made a copy, it becomes yours and we decided to warn users about the implications of deleting projects.

We've had so many cases in which a user deletes an app they have previously uploaded and then they need the keys to update their app on the store, and at times we won't have a copy ourselves either.

**Comment by josmas** [comment]
Just to clarify, this will come up on any project, published or not.

**Comment by tatiang** [comment]
Ah, okay. I was thinking it was suggesting that I had published that project but I see now it says "If..."

Thanks.
