### ISSUE TITLE
Allow us to store items to the device its storage

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#843]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to store files to the device its Storage

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jaredgibb** [comment]
This is already possible using the local storage blocks.

**Comment by lukeplays33** [comment]
Hello could you tell me where i can find those blocks?
Thank you

**Comment by MrMazzone** [comment]
@lukeplays33 Local storage is a component you can add to your app. 
![image](https://user-images.githubusercontent.com/40954645/111605075-609da180-87ac-11eb-806c-cf9b5a595710.png)

Once the component is added, you have access to the blocks. 
![image](https://user-images.githubusercontent.com/40954645/111605256-86c34180-87ac-11eb-8dc9-414c8c97e552.png)

**Comment by lukeplays33** [comment]
Oh this is in the legacy UI

**Comment by lukeplays33** [comment]
Still one question does this write to internal storage?

**Comment by MrMazzone** [comment]
Hmm... Yeah @lukeplays33 , seems this is not in the new drag and drop UI.  @josmas is this component coming soon to new UI?

@lukeplays33 What do you mean "write to internal storage"?  This will let you save, get, and remove data from the local device storage (internal storage).

**Comment by lukeplays33** [comment]
internal storage is a public storage on android devices.
where you can store maps and retrive data even if the app is deleted.

**Comment by lukeplays33** [comment]
> Hmm... Yeah @lukeplays33 , seems this is not in the new drag and drop UI. @josmas is this component coming soon to new UI?
by the way the new UI uses variables instead of local storage

**Comment by MrMazzone** [comment]
That's right!  They are just using the `stored` variables now. 
![image](https://user-images.githubusercontent.com/40954645/111627630-a155e480-87c5-11eb-9eef-6b23e8629c2d.png)

@lukeplays33 I don't think the current features will do what you want.  I think you want more control to save in the phone file system.  The issue Thunkable X faces with this is what is available on iOS.  I am not sure what type of access iOS grants for this.

**Comment by lukeplays33** [comment]
oh

> I think you want more control to save in the phone file system
Yes that's right

**Comment by jane-d-alt** [comment]
Hi there,

MrMazzone's comment is correct: instead of the Local Storage component, you can use stored variables in your Thunkable project. You can read more about stored variables here: https://docs.thunkable.com/v/drag-and-drop/variables#stored-variables-1

We'll close this issue now. Thank you!
