### ISSUE TITLE
Dark mode editor

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#846]
**Describe the solution you'd like**
I would like to have the app project editor to have a dark theme so it wouldn't hurt my eyes when working at my projet at late days.
Or at dark places.

**Describe alternatives you've considered**
Chrome exstension but these messed up the editor.
As shown in the picture below.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
![Screenshot 2021-03-18 3 20 33 PM](https://user-images.githubusercontent.com/54947833/111641646-a46cc700-87fd-11eb-9d2f-ef00e4a3762f.png)

**Comment by jane-d-alt** [comment]
Hi there,

Thanks for this request. We are going to close this issue as your request overlaps with #69 
We are working on designs for a Dark Mode Thunkable editor. Thanks!

**Comment by lukeplays33** [comment]
Thank you
