### ISSUE TITLE
Label text sizing problems

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#849]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
✕ Android companion, or ✕ iOS companion? and download app

### Issue/Request Origin
Community and my own 

### Steps to Reproduce
1. aadd a label to project
2. compile project
3. run app on biger screen sizes

### Expected Behavior
Text to be displayed normal

### Actual Behavior
text gets strechteched
```
  STACK TRACE AND/OR SCREENSHOTS
https://community.thunkable.com/t/label-text-sizing-problems/1088570?u=lukehoogenboom0i

**Comment by jane-d-alt** [comment]
Hi there,

This behavior has been resolved: Labels are no longer stretched when viewed on larger screens. Apologies for not following up when this behavior was originally resolved.

Thanks for reporting!

**Comment by lukeplays33** [comment]
Thanks but now IT doesn't size to the right screens sizes.
Example if is set the width/height to the whole screen on my Chromebook the size doesn't change as described here:
https://community.thunkable.com/t/current-bugs-ive-found-in-the-dnd-ui/1275487?u=lukehoogenboom0i
