### ISSUE TITLE
Newline (\n) in label text is broken

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#852]
### Platform
Thunkable X, legacy interface

### Steps to Reproduce
1. Add \n to a label's text (e.g. "Privacy\nPolicy")
2. Live Test or Download the project
3. The label displays the newline character instead of adding a newline

### Expected Behavior
Yesterday, the newline character would be hidden and a line would be added when displaying the label.

### Actual Behavior
See screenshots below.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/10355498/111819617-c9b11200-889d-11eb-8cf9-40c52ea2b654.png)

![image](https://user-images.githubusercontent.com/10355498/111819659-d59cd400-889d-11eb-83a5-018e39e8cbc3.png)

**Comment by lukeplays33** [comment]
You have to Use the block.
Else it Will be seen as a String

**Comment by tatiang** [comment]
It worked fine yesterday. This is a new change and I’m hoping it can be reversed.

**Comment by lukeplays33** [comment]
Hmm i always tought it only worked with blocks.

**Comment by tatiang** [comment]
For now, I have a workaround:

![image](https://user-images.githubusercontent.com/10355498/111839184-a1cea800-88b7-11eb-9aa0-9ac3dd373319.png)

**Comment by MrMazzone** [comment]
This was fixed a few months back when I reported it.  This is a new break as @tatiang is reporting.  The team probably just needs to patch this again.

**Comment by domhnallohanlon** [comment]
@lukeplays33 this is a new issue (but same symptoms as @MrMazzone experienced previously)

We're working on a fix right now and also tracking it in the Community here:
https://community.thunkable.com/t/in-progress-issue-with-component-text-852/1176425?u=domhnallohanlon

Thanks again for reporting this.

**Comment by jane-d-alt** [comment]
Hi there,

The fix for this behavior was released shortly after reporting. Thanks to all who contributed! We will close this issue now. Apologies for not following up when the fix was initially released.

**Comment by tatiang** [comment]
This is again not working in the drag and drop interface. If I enter a newline (\n) within a string for a button name either on the Design tab properties or by using a set label's text block on the Blocks tab, it doesn't add a newline and instead displays "\n" within the button name.
