### ISSUE TITLE
Extreamly thick shadow around text input

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#853]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
✕ Android companion, or ✕ iOS companion? And installing

### Issue/Request Origin
My own 
### Steps to Reproduce
1. Add text input
2. Compile project
3. See a shadow around it

### Expected Behavior
Too look normal

### Actual Behavior
Has a thick shadow
```
  STACK TRACE AND/OR SCREENSHOTS
https://community.thunkable.com/t/problems-with-text-input/1110070?u=lukehoogenboom0i

**Comment by jane-d-alt** [comment]
Hi there,

We will follow up with this issue in the Community Post.
