### ISSUE TITLE
Allow us to scroll trough the block editor

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#857]
**Is your feature request related to a problem? Please describe.**
It is quite anoying when i am having a lot of blocks.
And not Boeing able to scroll trough tgen

**Describe the solution you'd like**
To be able to scroll trough the block editor.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
Hi there, thanks for this request. I am going to close this issue as it overlaps with #757. We are working on adding scrollability to the Design tab, and will hopefully be able to do so in the Blocks tab soon.
