### ISSUE TITLE
Web API component cant call not https api on android

### ISSUE THREAD

**Issue by XinWu-Naz** [thunkable/thunkable-issues#859]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?
✕ Android companion

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
from me

### Steps to Reproduce
1. Create an app to call any API on http (not https)
2. Live test on android
3. Observe the app did not make any call to the server

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.
https://x.thunkable.com/copy/8050a1a7c258ba9cbe6200c6c53c1633

### Expected Behavior
What did you expect to happen?
expecting the app to talk to the server

### Actual Behavior
What actually happens?

got error saying "Network request failed"
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/76924320/112246605-ee3a2f00-8c8d-11eb-9466-164032fe31fa.png)

**Comment by XinWu-Naz** [comment]
workaround for now is ngrok

**Comment by josmas** [comment]
Hi @XinWu-Naz thanks for the report. We changed access a while ago but we'll be setting it back to allow http connections (should be ready for release early next week, all going well).

We would still recommend that you get a certificate. If you are using ngrok, I am guessing you are hosting the API yourself. If you have a domain name you can use let's encrypt for free (not sure you can use let's encrypt on a subdomain for a domain you don't own such as duckdns, but it is worth having a look).

**Comment by josmas** [comment]
Change are reverted; should be out in next release.

**Comment by jane-d-alt** [comment]
This release has been published, so we will close this issue. Feel free to follow up if you experience this behavior again. Thanks!
