### ISSUE TITLE
Canvas not showing Sprites/Labels

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#861]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Installing APK.

### Issue/Request Origin
Community
And My own
### Steps to Reproduce
1. Create project
2. Add canvas with Sprite OR label
3. Compile project

### Expected Behavior
To show sprites OR labels

### Actual Behavior
Nothing apears

  STACK TRACE AND/OR SCREENSHOTS
https://community.thunkable.com/t/canvas-label-sprites-not-showing/1186953?u=lukehoogenboom0i

**Comment by jane-d-alt** [comment]
Hi there,

I have followed up with this issue on the Community Post. I will close this issue so that the conversation is kept in one place. Thanks!
