### ISSUE TITLE
Datasource - "number of rows" block doesn't work properly with airtable

### ISSUE THREAD

**Issue by isaiasanchez** [thunkable/thunkable-issues#863]
### Platform
Thunkable X - BETA Drag and Drop

### Issue/Request Origin
I'm using Community version.

### Steps to Reproduce
1. Create and airtable datasource.
2. Create a simple block filling the table.
3. Display the result of "number of rows block"

### Project Link
https://x.thunkable.com/copy/31ae7d465195774dbba920b23f1d5cc7

You need to create an airtable datasource.

### Expected Behavior
I expect that every time I call the number of rows, it goes to airtable to get the correct value, even if it changes during execution.

### Actual Behavior
The number of rows remain unchanged with the value when the screen starts.

![Screenshot_20210403_184312](https://user-images.githubusercontent.com/8542819/113486031-0f322980-94b1-11eb-8222-9d6990352f58.png)
![Screenshot_20210403_184107](https://user-images.githubusercontent.com/8542819/113486033-0fcac000-94b1-11eb-9c85-8880c1c71bfb.png)

**Comment by jane-d-alt** [comment]
Hi there,

Thanks for reporting this behavior. This issue has since been resolved. Apologies for not following up here when the fix was released; we will close this issue now.
