### ISSUE TITLE
List Viewer background

### ISSUE THREAD

**Issue by aiasp** [thunkable/thunkable-issues#868]
Hello, 

in the night, my List Viewer-background became white (1) instead that Transparent (2)
without doing anything on my app...

do u have a solution ? 

Thanks

Guido 

<img width="481" alt="2" src="https://user-images.githubusercontent.com/66922345/114272532-d9dc8d00-9a16-11eb-8c42-d39da55651b6.png">

![1](https://user-images.githubusercontent.com/66922345/114272513-c9c4ad80-9a16-11eb-8d76-c66d50558049.PNG)

**Comment by josmas** [comment]
Hi @aiasp do you see the same thing on web preview?

I believe what is happening is that we have updated the apps but not the server.
We have added properties to change the font size and background color for the items in List Viewer, but it won't be out until the next release (probably on Monday afternoon PST).

**Comment by aiasp** [comment]
Yes, I see that happening only on mobile not on Web preview

So I’ll wait for Monday realease. 

Thanks for your answer, always appreciate

Guido

**Comment by josmas** [comment]
Closing this one as it seems to be resolved; feel free to open if that is not the case. Thanks!
