### ISSUE TITLE
Cannot make a switch invisible

### ISSUE THREAD

**Issue by royrosemarin** [thunkable/thunkable-issues#869]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Android (Galaxy Note 10+ device)

### Steps to Reproduce
(I am not sure if steps 1-3 are necessary)
1. Create a column
2.  Inside a column create a row
3. Inside a column create another row
4. Inside the last row crate a switch

### Project Link
https://x.thunkable.com/copy/3d86367cf074d6fee8963e38c83e38ed

### Expected Behavior
In the Sign_in_or_up screen when the user clicks "Forgot password" the row of the switch next to the text "show password" should turn invisible.

### Actual Behavior
In the Sign_in_or_up screen when the user clicks "Forgot password" the row of the switch next to the text "show password" and the switch itself turn into invisible. However, then, the switch just turns up at the top left of the screen (of the external column?). It is impossible to press it, but still, it is there on the screen.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
Thanks for the report @royrosemarin 
We are about to deploy a couple of fixes for `switch`. We'll circle back to this report when we finish up testing. Thanks!

**Comment by jane-d-alt** [comment]
Hi there,
Thanks again for reporting. This behavior has been resolved. [See this demo app](https://x.thunkable.com/projectPage/609d3222731ded0011def059/). We'll close this issue for now.
