### ISSUE TITLE
Duplicate tool

### ISSUE THREAD

**Issue by visjble** [thunkable/thunkable-issues#87]
I was working on a game app that required several buttons/labels. Once I customized a button the way I liked I was looking for a copy-and-paste solution or a paint style solution that would have allowed me to apply the same style to all the other buttons to no avail. 
This would be a nice feature to have, thanks.

**Comment by jane-d-alt** [comment]
It is now possible to duplicate components on a screen in Thunkable X, both in the Design tab and with blocks.
