### ISSUE TITLE
The title of the web app in the browser should be App Name (not Project Name)

### ISSUE THREAD

**Issue by caminostudio** [thunkable/thunkable-issues#873]
I am using Thunkable X to create Web apps. We can use the Thunkable interface to define the App Name (attribute in Application Settings), but the title of the web app in the browser (title of the HTML tag) is the name of the project. It is a problem because we use this project name to control / indicate the different versions of the application. And this “internal” name is shown to the user through the browser.

My demand is to use the App Name (attribute in the application settings) to define the HTML tag title for Thunkable web applications.

Is it possible to change that?

Thanks!

**Comment by josmas** [comment]
Thanks for the request @caminostudio 

hey @TingC do you think this is something that can be done?

**Comment by caminostudio** [comment]
I created different web apps Thunkable that can be considered just one system. Each app is a "module". Each “module” has a different name. Each "module" has different versions. But I would like users to see just one name / title in the browser. And changing these names is more work in the “deploy process”.

**Comment by TingC** [comment]
Yup, that's possible. We'll take a look at it and keep you updated here, thanks!

**Comment by caminostudio** [comment]
Thanks @TingC @josmas !

**Comment by caminostudio** [comment]
Nice! Thanks a lot!

**Comment by MrMazzone** [comment]
This seems to be working now. Correct?

I had to republish each of my web apps because they now say "thunkablecompanion" in the tab title.  Which is no big deal.

**Comment by josmas** [comment]
It is, sorry about that @MrMazzone 
It's all for the greater good! :D

Thanks!
