### ISSUE TITLE
Crash When Label's Font Size is Blank

### ISSUE THREAD

**Issue by justinscottleonard** [thunkable/thunkable-issues#881]
### Platform
X

### Issue/Request Origin
When working with students, I have noticed that they delete the font size before typing in the new size. This causes the website to go white and force a reload.

### Steps to Reproduce
1. Add a Label to your screen
2. Edit the Label's font size by deleting the default and not replacing it.

### Project Link
https://x.thunkable.com/copy/610c89bab4978cc6ba59ab4163a5d59e

### Expected Behavior
My expectation would be that I would be allowed to type in the font size before it updates.

### Actual Behavior
The website crashes and needs to be reloaded. It seems to be the website trying to render the font size as NaN which throws an error. Would there be a way to not update until enter is clicked or until the field is left? Or to default to 0?

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
thanks for the report @justinscottleonard 
We have a fix for a similar case; we'll check if it also fixes this one. It is expected to be out in the next couple of days. Thanks!

**Comment by jane-d-alt** [comment]
Hi @justinscottleonard ,

Just following up here to confirm that this behavior has been resolved in a recent release. Thanks again for reporting!
