### ISSUE TITLE
Add Hex to color block.

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#882]
I would like to be able to paarse a Hex color code to RGB and vice versa.
This would make IT easier to create colors(atleast for me)

Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
Hi there,

If you're looking to [set the color property of a component with a hex value](https://docs.thunkable.com/v/drag-and-drop/color#set-hex-color), you can do this with a Text block that contains the hex value.

If you are looking to convert hex values to rgb values, you can use an API such as the [color API.](https://www.thecolorapi.com/)

Thanks,
Jane
