### ISSUE TITLE
Add add block to Amy Components section

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#886]
Hi i would like to have a add block to the Amy Component section.
IT works like the Opposite of the remove block.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
Hi there,

The Any Component drawer has a create block which lets you add components to your project.
Read more here: https://docs.thunkable.com/any-component-blocks#what-is-the-create-block

Thanks!

**Comment by lukeplays33** [comment]
That block does not exist in the DnD UI
