### ISSUE TITLE
Data Viewer List/Grid "Subtitle" Text block value is incorrect

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#887]
### Platform
Thunkable X, Drag & Drop interface

### Issue/Request Origin
https://community.thunkable.com/t/cant-get-data-sources-subtitle-text/1256483

### Steps to Reproduce
1. Setting a label or other component to a Data Viewer List (or Grid)'s "Subtitle" text block results in the value "Subtitle" appearing rather than the actual value in the Data Source.
2. It doesn't matter what the value of the mapped "Subtitle" cell is in the local data source. It always returns the text string "Subtitle."

### Project Link
It's from a private project but I provided the link using the Chat support icon from within the project.

### Actual Behavior

```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/10355498/116776646-5d8a0800-aa1e-11eb-8ace-f045537f9e7e.png)

**Comment by jane-d-alt** [comment]
Hi Tatian,

It looks like this issue has been resolved, going by [this demo project](https://x.thunkable.com/projectPage/605b644ab9e6510012367f82/) I built to replicate this behavior.

This is connected to an Airtable Data Source. Please let me know if this behavior is resolved for you, or if you see this behavior with another Data Source. Thanks!

**Comment by tatiang** [comment]
Yes, it does look like this has been resolved. Thank you, @jane-d-alt!

**Comment by jane-d-alt** [comment]
That is great to hear! I'll close out this issue in that case. Thanks for reporting :)
