### ISSUE TITLE
Missing Back Arrows (ios & android), Tall Element Screen Height (android), system Back button quits (android)

### ISSUE THREAD

**Issue by MrSco** [thunkable/thunkable-issues#90]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
✕, X Live, Downloaded

### Issue/Request Origin
Community/Myself...
https://github.com/thunkable/thunkable-issues/issues/84
https://community.thunkable.com/t/recent-changes-and-their-effects/45028/2?u=mrsco

### Steps to Reproduce
1. Test app with stack navigator on Android Live X (element screen height too tall) or downloaded apk (missing back buttons, element screen height too tall, system back quits app)
2.  Test app with stack navigator on iOS downloaded (missing back arrows)

### Expected Behavior
system Back arrow should go back instead of quit app and the app back arrow should appear in top left header instead of being hidden

### Actual Behavior
system back arrow quits app and app back arrow is not displayed but still clickable and still goes back.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![bluestacks_2018-09-12_12-44-02](https://user-images.githubusercontent.com/11297411/45440740-198a3f00-b68b-11e8-8014-20b232a5a840.png)

**Comment by James-Livesey** [comment]
Thumbs up. Need physical/Android back key functionality so much!

**Comment by MrSco** [comment]
STill having this issue in latest thunkable pro. how are we expected to pay for something that produces such a broken result?!

**Comment by James-Livesey** [comment]
Yeah I agree seeing that Thunkable is now turning into more of a commercialised platform!

**Comment by scandling1** [comment]
please help missing back arrow on stack navigator after download

**Comment by James-Livesey** [comment]
Hmm that's strange, however I think that's a tiny bit unrelated (we're talking about the physical Android back button not doing its job, not the one at the top of the phone), feel free to make a new issue to get it resolved ASAP!

**Comment by MrSco** [comment]
There is way more then just back button issues. iOS has missing back button icons. Android’s physical back button closes the app. Androids vertical element spacing is all whacked out. All these issues started happening after you guys did your Android api update a couple months ago. It’s been busted ever since. I can’t believe you guys are charging money now and it’s more broken then ever. Please investigate and fix it. I can provide you my project as an example if you’d like. But please see the screenshots above and you can see the screen spacing issues on android. 

-Rocco

**Comment by James-Livesey** [comment]
I agree greatly.

**Comment by James-Livesey** [comment]
Ugh how annoying!

**Comment by MrSco** [comment]
I think the back button has been fixed in the last update on the 12th. Can anyone else confirm?

**Comment by MrSco** [comment]
this was fixed earlier this year in one of Thunkable X's updates they did. 

https://community.thunkable.com/t/issues-with-spacing-on-android-devices/65867/5

make sure padding is 0 on screens and columns for android to display properly
