### ISSUE TITLE
GIF plays twice as a Column’s Background Picture on iOS

### ISSUE THREAD

**Issue by SkulaMesterHU** [thunkable/thunkable-issues#902]
### Platform
Using Thunkable Legacy UI. The bug is only on iOS devices and in the iOS companion app as well.

### Issue/Request Origin
If I set a Column's Background Picture to a GIF, it plays two times instead of playing one time only on iOS.

### Steps to Reproduce
[See the Thunkable Community](https://community.thunkable.com/t/gif-as-a-columns-background-picture/1276484)

### Project Link
[The project link](https://x.thunkable.com/copy/52917c50f450e83ca5253239e8922339)

### Expected Behavior
Background Picture only plays once.

### Actual Behavior
Background Picture plays twice.

**Comment by jane-d-alt** [comment]
The GIF seems to display for the desired period of time. As the original Community Post seems to be resolved, we will close this issue. Thanks!
