### ISSUE TITLE
Tapping textboxes one after another is limited

### ISSUE THREAD

**Issue by lisztomania1** [thunkable/thunkable-issues#92]
### Platform
Thunkable ✕

### Steps to Reproduce
1. If you have three textboxes on one screen, you might want to tap with your finger on the first, write text and then tap on the second to write text and then tap on the third... and so on

### Expected Behavior
If you tap on the textbox, the keyboard should come up. Or the keyboard should stay up and the focus should be on the textbox that was tapped

### Actual Behavior
The third tapping is not functioning (no keyboard shows up and no focus on the tapped textbox)

**Comment by DLM-thunkable** [comment]
Desperately need this function to work (GetFocus). Can't find a suitable workaround which works for numeric fields.

**Comment by jane-d-alt** [comment]
The keyboard now stays open when the user switches between Text Inputs in Thunkable X.
