### ISSUE TITLE
putting 2 loops after each other doesn't fire the second one

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#924]
when ever i put two loops like a repeat 110 times and forever the first loops only fires.
wich is in this case repeat 10 times.
and when i make the repeat 10 times the forever block only fires.
### Platform
Thunkable X

### Issue/Request Origin
My self

### Steps to Reproduce
1. add a loop with some code
2. add a second loop with some code
3. and download apk file or live test in web preview

### Expected Behavior
to start fireing both loops

### Actual Behavior
only fires first loop

**Comment by lukeplays33** [comment]
Its not only the forever block its for all loops.

**Comment by cathysarisky** [comment]
"After the FOREVER block, the blocks don't run." After a forever block, you wouldn't expect the blocks after it to run.  The code is going to sit there and do whatever you told it to do "forever".

**Comment by cathysarisky** [comment]
Can you link a project with the behavior @lukeplays33 ?  I have lots of loops and I haven't seen the problem.

**Comment by lukeplays33** [comment]
Hi there @cathysarisky i've fixed the problem for the loops in My project.
But stil i think it would be beter to be able to put multiple loops behind each other.

**Comment by jane-d-alt** [comment]
Hi there,

Can you link to a project that demonstrates this behavior so that we can troubleshoot it?

**Comment by lukeplays33** [comment]
Hi there @jane-d-alt 
I've created an example where i have 3 loops.
the first one loops 10 times.
then a forever loop
and then the first loop again.
i want all 3 of the mto fire at the same time.
https://x.thunkable.com/copy/b9001ed8699322c97fbff57c1955e2f3

**Comment by tatiang** [comment]
If you want the three loops to fire at the same time, put each one in a separate`When Screen Opens` block.

Because as @cathysarisky said, anything below a `Forever` block will never run.

**Comment by lukeplays33** [comment]
Thanks @tatiang and @cathysarisky 
Think i Just misunderstood it.
I'll close it for now
