### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by AcrobatEpee** [thunkable/thunkable-issues#94]
Hello, I would like to suggest a simple feature request. The optionto color or change the aspect of a single text line in the list_viewer by using blocks. It can be very useful to signal the user which info to look to etc.

Thanks !

**Comment by jane-d-alt** [comment]
Format of lists can now be personalized with Custom Data Viewer Layouts: https://docs.thunkable.com/custom-data-viewer-layout
We'll close this issue; apologies for not following up when this feature was originally released.
