### ISSUE TITLE
Component name with question mark causes views to improperly load

### ISSUE THREAD

**Issue by Hrist0S** [thunkable/thunkable-issues#96]
### Platform
Thunkable X

### Issue/Request Origin
User submitted an issue on Intercom that they were not able to see their blocks drawer. 

### Steps to Reproduce
1. Create a new Thunkable X project.
2. Add a component and add a question mark anywhere in its name.
3. Click on the component and attempt to open Designer or Blocks view.

### Expected Behavior
The selected view to load correctly.

### Actual Behavior
The selected view does not load properly. I believe this is because the question mark in the component name causes the current view to be passed as a URL parameter.

  STACK TRACE AND/OR SCREENSHOTS

<img width="843" alt="screen shot 2018-09-29 at 22 34 06" src="https://user-images.githubusercontent.com/41082935/46250720-741bed00-c438-11e8-983d-d4f902534ee5.png">
<img width="691" alt="screen shot 2018-09-29 at 22 39 16" src="https://user-images.githubusercontent.com/41082935/46250724-8a29ad80-c438-11e8-98d4-1d74b75a6969.png">

**Comment by jane-d-alt** [comment]
This has been resolved by changing how components are referred to in project URLs.
