### ISSUE TITLE
Thunkable button sizes aren't right

### ISSUE THREAD

**Issue by Danieljsmith1011** [thunkable/thunkable-issues#961]
### Platform
Using thunkable so both android and IOS

### Issue/Request Origin
This issue shows up when I put buttons on my app in rows. I make it "Fit Contents" but when I do that the buttons aren't the original size anymore. The png pictures don't stay the same size when I open the preview of the app. 

### Project Link
https://x.thunkable.com/copy/35013adbb1d541f230e2e6d988c2d8f1

### Expected Behavior
The buttons were supposed to stay the size that they are meant to be. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/85645847/121421003-54e8f380-c933-11eb-9b72-347d6ef55230.png)

![image](https://user-images.githubusercontent.com/85645847/121421059-6205e280-c933-11eb-80e0-b7e208dbae00.png)

**Comment by jane-d-alt** [comment]
Hi there,

I'm not sure what happened here, but I changed your Buttons' Heights to any other size, then back to 'fit contents'. This seemed to resolve this behavior.

You can access a version of your project with the Buttons' Heights fixed here: https://x.thunkable.com/copy/df09ef811080d1a5840fe410c850d6b9
