### ISSUE TITLE
Incrementing ads

### ISSUE THREAD

**Issue by AcrobatEpee** [thunkable/thunkable-issues#97]
I already submited a suggestion for the ads issue but here I am with another idea.

Programmers make their apps on Xcode and / or Android Studio, and they integrate the sdk’s of their ad platform directly in their apps on these tools, so why not able us thunkable creators to download our apps, insert them in these programs, and allow us to increment ourselves the ad services.

However, the main reason why people use thunkable is because it requires no coding, so a video made by a professionnal or a member of the thunkable team or even a member of the community explaining to the fellow thunkers how to increment those ads by these tools would be required.

Have a nice day :)

**Comment by mark-friedman** [comment]
Most, if not all, of these ad platform SDK require some code to be inserted in your app, so there's no real way for Thunkable creators to do this, unless we create components for those ad platforms.  When we do provide a component for any ad platform we will certainly provide documentation/videos showing people how to integrate them.

**Comment by AcrobatEpee** [comment]
I am not talking about doing this in Thunkable but to make this available on thunkable apps after they’re done. Because at the moment we’re not able to insert ads on our apps unless if we know how to code. My idea was just to find someone able to make a complete tutorial (video) to help us integrate ads to our apps

**Comment by jane-d-alt** [comment]
Thunkable X now allows creators to [display ads](https://docs.thunkable.com/admob) in their app.
