### ISSUE TITLE
Custom Drawer Navigator

### ISSUE THREAD

**Issue by Advaitt** [thunkable/thunkable-issues#971]
**Describe the solution you'd like**
I would to add a custom drawer navigator with the user info. But Having an option to add a image to the navigator ould also be really haelpful

*

**Comment by domhnallohanlon** [comment]
Thanks @Advaitt - this has already been requested in #612 by @bymahoapp

I've made a note of your request!

**Comment by jane-d-alt** [comment]
Hi @Advaitt,
Since there is an outstanding request for this feature, we are going to close this issue to avoid having duplicate issues open. We appreciate your feedback and the team is aware of renewed interest in this feature!
