### ISSUE TITLE
Copied/duplicated projects should have current date applied

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#977]
**Is your feature request related to a problem? Please describe.**
When I copy or duplicate an existing project, the Date Modified value for the newly-copied project is the original creation date of the existing project.

This makes it hard to find the copy when my project list is sorted by Date Modified. It used to be that newly-copied projects would be at the top of this list.

**Describe the solution you'd like**
Newly-copied projects should have a Date Modified value matching the current date and time.

**Describe alternatives you've considered**

**Which platform are you asking for?**
Thunkable X

**Additional context**

**Comment by jane-d-alt** [comment]
Thanks for reporting! I have filed an internal report to address this behavior.

**Comment by jane-d-alt** [comment]
Hey Tatian,It looks like this behavior has been resolved. The 'Copy Made!' pop-up appears for me, and the correct date is applied to duplicated projects.

Can you confirm that this behavior is resolved for you as well?

**Comment by jane-d-alt** [comment]
Hi Tatian,

Since this behavior seems resolved on our end, and you haven't followed up to say you still experience this behavior, we will close this issue.

Thanks for reporting!
