### ISSUE TITLE
horizontal and vertical

### ISSUE THREAD

**Issue by YCY-Tony** [thunkable/thunkable-issues#978]
The horizontal and vertical sizes are wrong, and the content disappears.

**Comment by jane-d-alt** [comment]
Hi there,

Can you provide more detail on this topic?
What horizontal sizes?
What vertical sizes?
What content?
What component(s) are you referring to?

**Comment by jane-d-alt** [comment]
As there was no follow up detail, we are going to close this issue for now. You are welcome to re-open the issue and provide answers to the questions in my previous comment.

Thanks,
Jane
