### ISSUE TITLE
Thunkable как сохранить действие кнопки ?

### ISSUE THREAD

**Issue by maxim9788** [thunkable/thunkable-issues#980]
Как в thunkable сделать так чтобы при в входе в приложение пользователю в первый раз предлагалось допустим 2 кнопки он нажмёт на любую из них и перейдёт на другую страницу. Вопрос как сделать чтоб при следующем входе в приложение это нажатие на кнопку которое сделал пользователь в первый раз сохранилось и автоматически переходило на другую страницу не выдавая опять страница с этими двумя кнопками если до этого пользователь уже нажимал на них .

**Comment by Advaitt** [comment]
Для этого установите для сохраненной переменной A Начало приложения значение False. Когда пользователь нажимает на любую из этих кнопок, установите для нее значение true. В следующий раз, когда приложение откроется, проверьте, установлено ли для сохраненной переменной значение true, если это так, перейдите на другую страницу.
Спасибо
Также, пожалуйста, опубликуйте подобные вопросы в сообществе.
https://community.thunkable.com/

**Comment by josmas** [comment]
This seems to be a programming question so, as suggested above, please use the community instead. Thanks!
