### ISSUE TITLE
Transferring code from MIT App Inventor to Thunkable 

### ISSUE THREAD

**Issue by Danieljsmith1011** [thunkable/thunkable-issues#981]
**Is your feature request related to a problem? Please describe.**
Thunkable is missing some Blocks functions that MIT App Inventor has. For example some of the functions that are missing are .initialize .PermissionGranted .PermissionDenied. I have pictures of what it looks like. 

**Describe the solution you'd like**
I want to know if there's any way to make this work. I want to convert it to thunkable but am confused on what to use. Please let me know if there's a way to convert them well. 

**Which platform are you asking for?**
Thunkable Classic (app.thunkable.com) or Thunkable ✕ (x.thunkable.com)

**Additional context**
![image](https://user-images.githubusercontent.com/85645847/123819869-b7446c80-d8bf-11eb-8bce-167cd2d3355e.png)
(MIT App Inventor)

**Comment by josmas** [comment]
Hi @Danieljsmith1011 
In Thunkable you don't have to worry about permissions at the same level. If you use a component that needs a permission, it will be asked for automatically. If the user denies your request, you will probably see the error in the error handler for the particular block you want to use, so you can do something similar to what you do in `PermissionDenied`. It might be a little less flexible, but it is much easier if you don't have to think about permissions that much.

**Comment by Danieljsmith1011** [comment]
Thank you!!
