### ISSUE TITLE
Spinner on thunkable 

### ISSUE THREAD

**Issue by Danieljsmith1011** [thunkable/thunkable-issues#983]
**Is your feature request related to a problem? Please describe.**
I am wondering what would be the best way to make a spinner like this on thunkable. Since there isn't a spinner component on thunkable I am wondering how to do it. I am re making my app from MIT App Inventor over to thunkable. 

**Describe the solution you'd like**
I want it just like how the picture looks. Have the spinner button have a pop up screen that allows you to choose from the options listed. 

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**
![MITSpinner](https://user-images.githubusercontent.com/85645847/123986814-428b3400-d98c-11eb-87ea-06a125f04516.jpg)

![IMG-9779 (2)](https://user-images.githubusercontent.com/85645847/123986822-45862480-d98c-11eb-8d6d-4bf30991715a.jpg)

**Comment by josmas** [comment]
Hi there, please ask programming questions in the [community](https://community.thunkable.com/). Thanks!
