### ISSUE TITLE
Add left/right swipe to listviewer

### ISSUE THREAD

**Issue by lukeplays33** [thunkable/thunkable-issues#984]
I would like to be able to have left/right swipe for the listviewer.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by jane-d-alt** [comment]
Hi there,

If you want to display a list of items, and allow the user to left and right swipe this list of items, you can use the [Data Viewer List. ](https://docs.thunkable.com/data-viewer-list) You can display a single text item in each row of the Data Viewer List.
