### ISSUE TITLE
Joystick or self-centering slider?

### ISSUE THREAD

**Issue by MiloMindbender** [thunkable/thunkable-issues#99]
**Is your feature request related to a problem? Please describe.**
I would like to use this to control a simple robot but need proportional (variable) control for steering and forward/back throttle.

**Describe the solution you'd like**
Would like to have a way to put up one or more analog joysticks in the app.  Alternately, if there could be an option on the "slider" control for it to automatically return to center when you lifted your finger off the screen.

**Describe alternatives you've considered**
Alternately, the robot could host a web server with a web-page based control

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Additional context**

**Comment by jane-d-alt** [comment]
The slider 'on sliding complete' block can be used to reset the slider, which facilitates this functionality. We'll close this issue; apologies for not following up when this block was originally added.
