### ISSUE TITLE
Remove letter ____

### ISSUE THREAD

**Issue by Advaitt** [thunkable/thunkable-issues#990]
Hi , what i wanted is that a block with remove letter 6 or remove letter 7 from word instead of replace all a with b. Even a block which says that replace 1st letter with j would be helpful

**Comment by cathysarisky** [comment]
The workaround is this:
![image](https://user-images.githubusercontent.com/42299862/125321964-38155680-e30b-11eb-9310-c7abe3b9caea.png)

**Comment by Advaitt** [comment]
Thanks , though that block would've been more helpful
