### ISSUE TITLE
Create Row hangs - affects DOWNLOADED iOS and Android and Web app and web preview, also Thunkable live.

### ISSUE THREAD

**Issue by cathysarisky** [thunkable/thunkable-issues#995]
### Platform
Web app and web preview.  Downloaded Android (7.0) and iOS (14.something) apps are also broken.  Android and iOS Live both worked fine prior to the 276-1 update, but now the same broken behavior happens for 276-1 on iOS (14.5).
Local data source AND Airtable AND Google Sheets all impacted.

### Issue/Request Origin
Forum discussion: https://community.thunkable.com/t/create-row-block-not-moving-to-next-step/1394796/12

### Steps to Reproduce
Sample project below - connect a Google Sheet (or just use the local table) and then do a "create row".  The create row will happen (can be seen in the sheet), but neither the code in the "do" area nor any blocks after it ever execute.

### Project Link
https://x.thunkable.com/copy/80fb37dbfe7146f197692bfc2a27c927

### Expected Behavior
Both labels should change

### Actual Behavior
Neither label changes.

### Other testing
Tried linking a different Google sheet.  No change in behavior.

Tried downloading an APK and doing the testing install on iOS.  Both download formats have the same problem.  I tested on Android 7.0 and iOS 14.something.  

NOTE: Rows are created (confirmed in Google Sheets and Airtable), but failure to continue on to subsequent blocks is going to be a major source of breakage for lots of apps!

**Comment by cathysarisky** [comment]
UPDATE:  Using a local data source also causes the same behavior.

**Comment by cathysarisky** [comment]
Additional information on timing, courtesy of Thunkable user bnice:
![image](https://user-images.githubusercontent.com/42299862/125554956-75f53ed3-0353-41a0-bf09-e335b0c7da5a.png)
I also realized there was a gap in my timeline. at 12:21 PM [PST] yesterday afternoon, it stopped working, but then started working again at 3:41PM (as shown). Then stopped working at 10:59[pm] (apparently that was my last okay run).

**Comment by cathysarisky** [comment]
This is probably the same bug as #996 . I thought they were different because of different behavior in Live, but I think it was a Live version difference.

**Comment by jane-d-alt** [comment]
Hi there, since this is the same issue as #996 , and there is more active discussion there, we will close this issue. Thanks for reporting this behavior is resoled in most cases now. Of course, we will leave 996 open until it is resolved in 100% of the cases.
